add(userprofile): add user profile modal AP-489
Satellite-im/Core-PWA pull request #1006
Opened 2022-01-13 10:20 UTC by davidchan1219

**What this PR does** 📖

Added user profile modal, and added close button in quickprofile

**Which issue(s) this PR fixes** 🔨

AP-489

2022-01-13 14:52 UTC, Jekrimo requested changes

2022-01-13 14:52 UTC, Jekrimo commented on components/views/user/User.vue
> +        { text: 'Profile', func: this.handleShowProfile },
Hey David! Will you make an Enum for these? I feel like we are going to definitely need them in other places.

2022-01-13 17:31 UTC, stavares843 requested changes
<img width="1457" alt="Captura de ecrã 2022-01-13, às 17 27 31" src="https://user-images.githubusercontent.com/29093946/149379198-614dc44b-198f-43c7-b043-fa2c9a773bac.png">

The first time closing the user profile appears like this

and clicking on the close icon wasn't working, only disappeared after refreshed


video

https://user-images.githubusercontent.com/29093946/149379708-aa0651e3-6afe-4cb9-a776-fa16ff6ab77f.mov

browser - Chrome

no relevant info on the console log

2022-01-13 19:35 UTC, davidchan1219 commented
> <img alt="Captura de ecrã 2022-01-13, às 17 27 31" width="1457" src="https://user-images.githubusercontent.com/29093946/149379198-614dc44b-198f-43c7-b043-fa2c9a773bac.png">
> 
> The first time closing the user profile appears like this
> 
> and clicking on the close icon wasn't working, only disappeared after refreshed
> 
> video
> 
>  Gravacao.do.ecra.2022-01-13.as.17.30.02.mov 
> browser - Chrome
> 
> no relevant info on the console log

2022-01-13 19:39 UTC, davidchan1219 commented
@stavares843 I just fixed the issue. Please test with the new update again.

2022-01-13 19:41 UTC, stavares843 commented
thanks! checking 🔨

2022-01-13 19:44 UTC, stavares843 commented
fixed ✅

2022-01-13 19:44 UTC, stavares843 commented
added changes requested label regarding @Jekrimo comment's

cc @davidchan1219

2022-01-14 03:36 UTC, davidchan1219 commented on components/views/user/User.vue
> +        { text: 'Profile', func: this.handleShowProfile },
I think enum is not suitable for these. Because every text is associated with the function. And those function get the values in the self component. And with the introduction of enum, we have to change the data structure of some components.

2022-01-14 14:05 UTC, Jekrimo approved these changes

2022-01-18 13:01 UTC, WanderingHogan approved these changes

2022-01-18 16:54 UTC, stavares843 approved these changes

2022-01-18 16:54 UTC, merged