fix(theme): fixed bugs related to buttons flair and text, moved all the color style in a unique file
Satellite-im/Core-PWA pull request #1016
Opened 2022-01-14 14:40 UTC by ThomBos

**What this PR does** 📖
Fixes theme issues with the buttons and reorders the code, every color-related thing is now in a unique style file

**Which issue(s) this PR fixes** 🔨
AP-414 and AP-428 

**Special notes for reviewers** 🗒️
Created a new "satellite" flair and set it as default, so is no longer necessary locking the flair select

**Additional comments** 🎤

2022-01-14 16:18 UTC, phillsatellite approved these changes

2022-01-15 14:13 UTC, Jekrimo requested changes

2022-01-15 14:13 UTC, Jekrimo commented on components/views/settings/pages/personalize/Personalize.html
> +      <!-- :disabled="theme===ThemeNames.DEFAULT" -->
Can we trash this comment?

2022-01-17 16:48 UTC, Jekrimo approved these changes

2022-01-19 10:45 UTC, molimauro commented on assets/styles/themes/moonless_night.less
> -  .flair {
@ThomBos all the items in this file have been moved to `base.less`?

2022-01-19 13:18 UTC, ThomBos commented on assets/styles/themes/moonless_night.less
> -  .flair {
no, just the things in common between the default and the "moonless night" theme

2022-01-19 13:44 UTC, molimauro commented on assets/styles/themes/moonless_night.less
> -  .flair {
good

2022-01-19 19:37 UTC, stavares843 requested changes
dev.satellite.one

<img width="697" alt="Captura de ecrã 2022-01-19, às 19 36 08" src="https://user-images.githubusercontent.com/29093946/150201515-fc0dba71-641d-4338-a8e9-849b3204e0d8.png">


vs this branch
<img width="741" alt="Captura de ecrã 2022-01-19, às 19 35 08" src="https://user-images.githubusercontent.com/29093946/150201549-f5b0ffaa-d09d-48f8-a173-38b4fec26214.png">
<img width="680" alt="Captura de ecrã 2022-01-19, às 19 35 11" src="https://user-images.githubusercontent.com/29093946/150201562-21541836-da9f-4d2c-9180-591ea854e019.png">

it has some blue bar on the username/status sections

also the ''set photo'' copy only appears when hovering

the expected change on that screen would only be the ''set photo'' copy to be white instead of pink

you can find this screen when creating a new account

2022-01-20 09:46 UTC, ThomBos commented
Those things are now fixed, thanks for spotting them! 🔧👀 

I've checked around the application if anything else is broken, but couldn't find any more bugs. 
Tell me whenever you find something like that! 😄

2022-01-20 18:12 UTC, stavares843 commented
those are fixed 🎉 


i noticed the blue shade on the toggles when creating a account is different compared to dev

<img width="1330" alt="Captura de ecrã 2022-01-20, às 18 10 45" src="https://user-images.githubusercontent.com/29093946/150397031-2100c283-b94e-4b63-87b4-f51f7dd6d09a.png">

left side is this branch, right side is dev

2022-01-20 18:24 UTC, WanderingHogan approved these changes

2022-01-20 19:40 UTC, ThomBos commented
> those are fixed 🎉
> 
> i noticed the blue shade on the toggles when creating a account is different compared to dev
> 
> <img alt="Captura de ecrã 2022-01-20, às 18 10 45" width="1330" src="https://user-images.githubusercontent.com/29093946/150397031-2100c283-b94e-4b63-87b4-f51f7dd6d09a.png">
> 
> left side is this branch, right side is dev

The left blue should be the new primary color we are already using through the entire app 😅

2022-01-20 19:57 UTC, stavares843 approved these changes

2022-01-20 19:57 UTC, stavares843 commented
confirmed with design as well, thanks for updating 🎉 only missing fixing the conflict

2022-01-20 20:50 UTC, ThomBos commented
Fixed conflict, should work now! 👍

2022-01-20 20:50 UTC, stavares843 commented on assets/styles/base.less
> +  border: 1px solid var(--flair-color); */
commented out code 🔨

2022-01-20 20:50 UTC, stavares843 commented on assets/styles/base.less
> +    } */
commented out code 🔨

2022-01-20 20:50 UTC, stavares843 commented on assets/styles/base.less
> + */
commented out code 🔨

2022-01-20 20:55 UTC, stavares843 commented
something happened with the font color meanwhile

this branch

<img width="1023" alt="Captura de ecrã 2022-01-20, às 20 53 54" src="https://user-images.githubusercontent.com/29093946/150420749-4fda1835-c221-471a-8fe8-3f91acfb6d44.png">


dev

<img width="1023" alt="Captura de ecrã 2022-01-20, às 20 53 59" src="https://user-images.githubusercontent.com/29093946/150420718-fc6505f4-c067-417e-995f-83b2ce765f34.png">

2022-01-20 21:04 UTC, ThomBos commented
> something happened with the font color meanwhile

if i well remember there was a ticket for this, i had to align all text colors and that white is the new one

2022-01-20 21:30 UTC, WanderingHogan commented
@ThomBos I think you are referencing this ticket: https://satellite-im.atlassian.net/browse/AP-428 and unfortunately I think I made a mistake here.

I created that ticket to address some of the text being odd color - a bug where some of the text was pink/red had popped up.

Unfortunately, something in this branch is causing the light text color to be harder to read. Is there something you can do to address that here?
<img width="594" alt="Screen Shot 2022-01-20 at 4 29 48 PM" src="https://user-images.githubusercontent.com/2993032/150425153-2e5b5093-6260-4b51-a0d3-9da5db87ace4.png">

2022-01-20 21:38 UTC, ThomBos commented
> Unfortunately, something in this branch is causing the light text color to be harder to read. Is there something you can do to > address that here?

Sure, i can try to turn that greyer white to full white!

2022-01-21 11:08 UTC, ThomBos commented
Should be better now, button's text are now white and more visible.
Also Liz noticed that the switches weren't aligned to the figma, so i added blur on them💥

2022-01-21 13:16 UTC, WanderingHogan commented
Sweet, it looks really clean!

2022-01-21 14:20 UTC, stavares843 commented
neat! 🎨

2022-01-21 14:20 UTC, stavares843 approved these changes

2022-01-21 14:20 UTC, merged