add(filesystem): add import/export features for file system
Satellite-im/Core-PWA pull request #1018
Opened 2022-01-17 09:33 UTC by davidchan1219

**What this PR does** 📖

added import/export functions for filesystem

**Which issue(s) this PR fixes** 🔨

AP-467

2022-01-17 13:59 UTC, RetroPronghorn requested changes

2022-01-17 13:59 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +    newObj.id = obj._id
can we use newObj = { ...newObj, id: something, name: something, etc }

2022-01-17 13:59 UTC, RetroPronghorn commented on libraries/Files/test/FileSystem.test.ts
> +// describe('Test FileSystem', () => {
please uncomment test and make sure it works

2022-01-17 13:59 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +      newContent.push({ ...itemRes })
let's just use ...this.getChildrenItems(item)

2022-01-17 13:59 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +  getChildrenItems(obj: any): any {
let's change to `exportChildren`

2022-01-17 13:59 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +    let newObj: any = {}
Let's rename to children: any = {}

also let's make a type instead of `any`

2022-01-17 13:59 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +        cItem.forEach((element: any) => {
let's use a strict type instead of any

2022-01-17 13:59 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +      item.children.map((cItem: any) => {
add type, not any

2022-01-17 16:12 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +    let rTestData = JSON.parse(testData)
This is the second requirement of AP-467 ticket.
`Create a method on libraries/Files/FileSystem.ts called import which accepts the json from export in order to recreate the filesystem given some bit of data.`
importAll function is to solve this requirement.

2022-01-17 17:16 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +      child.forEach((cItem: any) => {
For cItem, it's difficult to set the type. So I remained only this as any

2022-01-17 17:18 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +      item.children.map((cItem: any) => {
Solve. please check with above cases again

2022-01-17 21:43 UTC, RetroPronghorn requested changes

2022-01-18 09:23 UTC, RetroPronghorn requested changes

2022-01-18 09:23 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +        console.log('cItem: ', cItem)
remove

2022-01-18 09:23 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +              ...mockFileData,
why are we importing the mock file data directly inside the method? This should be real data only.

2022-01-18 09:23 UTC, RetroPronghorn commented on libraries/Files/test/FSImport.test.ts
> +  console.log(JSON.stringify(filesystem.exportAll))
remove log

2022-01-18 09:23 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +  exportChildren(obj: FSCItem): any {
Have you tried the Item type here? This should work since it returns the same items you're looking for in FSC item, please try obj: Item

2022-01-18 13:13 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +  exportChildren(obj: FSCItem): any {
@RetroPronghorn Please test again

2022-01-18 14:31 UTC, WanderingHogan commented on libraries/Files/FileSystem.ts
> +  exportChildren(obj: Item): any {
this can return FSCItem instead of any, right?

2022-01-18 14:33 UTC, WanderingHogan commented on libraries/Files/FileSystem.ts
> +  importAll(filesystem: FileSystem, testData: string): any {
since nothing gets returned you can either leave off any, or make it void

2022-01-18 16:37 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +  importAll(filesystem: FileSystem, testData: string): any {
@WanderingHogan Please check now

2022-01-19 12:57 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +    newObj.id = obj._id
of course. I fixed the code.

2022-01-19 13:00 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +      newContent.push({ ...itemRes })
okay, implemented

2022-01-19 13:01 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +  getChildrenItems(obj: any): any {
changed the function name

2022-01-19 13:01 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +    let newObj: any = {}
renamed

2022-01-19 13:02 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +        cItem.forEach((element: any) => {
made new type and used that instead of any

2022-01-19 13:03 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +        console.log('cItem: ', cItem)
removed console log

2022-01-19 13:04 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +              ...mockFileData,
removed mock file and used real data

2022-01-19 13:05 UTC, davidchan1219 commented on libraries/Files/test/FSImport.test.ts
> +  console.log(JSON.stringify(filesystem.exportAll))
removed

2022-01-19 15:59 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +      id: obj._id,
solved

2022-01-20 13:50 UTC, RetroPronghorn commented on libraries/Files/FileSystem.ts
> +  exportChildren(obj: Item): FSCItem {
change return type to item

2022-01-20 13:51 UTC, RetroPronghorn commented on libraries/Files/types/filesystem.ts
> +export type FSCItem = {
once we change the return type we can delete this type..

2022-01-20 18:30 UTC, davidchan1219 commented on libraries/Files/FileSystem.ts
> +  exportChildren(obj: Item): FSCItem {
changed

2022-01-21 16:15 UTC, merged