WIP feat(profile): basic functionality for profile pictures AP-476
Satellite-im/Core-PWA pull request #1026
Opened 2022-01-18 03:50 UTC by josephmcg

**What this PR does** 📖
- upload picture to textile on account creation, set hash in Solana and state
- render picture in various places

**Which issue(s) this PR fixes** 🔨
AP-476

**Special notes for reviewers** 🗒️
- not done yet. I want to clean up the types a bit. Also want to refactor picture src data

**Additional comments** 🎤

2022-01-18 19:11 UTC, WanderingHogan commented on components/interactables/QuickProfile/QuickProfile.vue
> +    text: string
💪 fewer typescript red squiggles is nice

2022-01-18 20:15 UTC, WanderingHogan commented on components/views/navigation/sidebar/status/Status.html
> +      :text="accounts.details.status || 'No status set.'"
how will the translation service handle this

2022-01-19 00:51 UTC, josephmcg commented on components/views/navigation/sidebar/status/Status.html
> +      :text="accounts.details.status || 'No status set.'"
idk if it should be translated. Seems like that may encroach on the user's self expression. people can always google if theyre curious

2022-01-19 00:53 UTC, josephmcg commented on components/interactables/QuickProfile/QuickProfile.vue
> +    text: string
🦕

2022-01-19 18:58 UTC, WanderingHogan commented on components/views/navigation/sidebar/status/Status.html
> +      :text="accounts.details.status || 'No status set.'"
i specifically mean `No status set.`

2022-01-20 00:47 UTC, stavares843 requested changes
seems the photo is rendered on
- chat
- quick profile
- adding friend
- friends list
- status

<img width="889" alt="Captura de ecrã 2022-01-20, às 00 44 34" src="https://user-images.githubusercontent.com/29093946/150241947-e7c464cc-46be-4649-b2fd-34944cea82eb.png">
<img width="1401" alt="Captura de ecrã 2022-01-20, às 00 45 15" src="https://user-images.githubusercontent.com/29093946/150241951-faa15333-8bb1-49b0-8193-f4bfb2ad95cb.png">
<img width="452" alt="Captura de ecrã 2022-01-20, às 00 45 22" src="https://user-images.githubusercontent.com/29093946/150241957-e8081cc3-e40b-4f32-a3dd-9d6d1f1e9406.png">
<img width="354" alt="Captura de ecrã 2022-01-20, às 00 45 32" src="https://user-images.githubusercontent.com/29093946/150241962-599a2a1b-9797-4506-93fe-7c91b793510a.png">

but not on the profile

<img width="1394" alt="Captura de ecrã 2022-01-20, às 00 45 47" src="https://user-images.githubusercontent.com/29093946/150241920-604ff291-c828-440d-8091-6eddfeddc52c.png">

flow
- create account
- add photo
- go to profile

is that expected?

2022-01-20 00:49 UTC, josephmcg commented on components/views/navigation/sidebar/status/Status.html
> +      :text="accounts.details.status || 'No status set.'"
ah gotcha, I'll fix that

2022-01-20 01:23 UTC, phillsatellite commented
<img width="1728" alt="Screen Shot 2022-01-18 at 10 08 15 PM" src="https://user-images.githubusercontent.com/93608357/150245065-fd42cab5-3d20-4895-b695-3ce71c9467df.png">

I got this bug one time and couldn't replicate it again after clearing data once but I thought I should comment it still just in case we wanted to add an error message if an image doesn't properly load in for some reason

2022-01-20 01:29 UTC, josephmcg commented
Thanks Sara, I thought I was missing one. should be fixed now.

I've seen that bug too Phil, thought I fixed it by adjusting the data being passed around. Let me know if you're able to recreate it after pulling these latest changes

2022-01-20 19:12 UTC, WanderingHogan approved these changes

2022-01-20 19:41 UTC, stavares843 approved these changes

2022-01-20 19:41 UTC, merged