feat(chatbar): **markdown** in chatbar
Satellite-im/Core-PWA pull request #1040
Opened 2022-01-19 14:06 UTC by molimauro

**What this PR does** 📖
Chatbar markdown, chatbar rework, css bugfix, integrating old features, emoji fix. Focus input on reply, recipient switch, emoji selection.

**Which issue(s) this PR fixes** 🔨
AP-2
AP-196
AP-474

**Special notes for reviewers** 🗒️
Available markdown:
italics with * and _ 
bold **
underscore __
escape command
code with single `
combined bold/italics ***
strikethrough ~~
autolinks \<https://satellite.im>
url parsing
spoilers ||

**Additional comments** 🎤
Related to the chatbar, I’m going to open the following tickets:
* keep track of last cursor position for different purposes (example: emoji are always inserted at the end of the string);
* remove marked (when you send a message it will be converted in the chat to html by marked, must be refactored and removed);
* undo/redo manager (cmd + z, shift + cmd + z);
* integrate highlightjs;
* integrate mentions ui (\@user1, \@here, \@channel..).

2022-01-19 19:32 UTC, phillsatellite commented
https://user-images.githubusercontent.com/93608357/150200830-c43c51e0-cf98-4811-8159-5c59631a5f4f.mov

Only issue I noticed going through was Emoji is showing up tiny in the chatbar and when you select an emoji the menu will move to the opposite side of the screen otherwise all good

2022-01-20 07:48 UTC, molimauro commented
> emoji.mov 
>  spoilers.mov 
> Only 2 issue I noticed going through was Emoji is showing up tiny in the chatbar and when you select an emoji the menu will move to the opposite side of the screen and spoilers was not working correctly for me either (verified this problem only happens on my local and not dev) otherwise all good

For the emoji i'll check. I see the spoilers are working correctly in the chatbar, they do not work correctly once you send the message because that part is still a WIP

2022-01-20 16:43 UTC, phillsatellite commented
> > emoji.mov
> > spoilers.mov
> > Only 2 issue I noticed going through was Emoji is showing up tiny in the chatbar and when you select an emoji the menu will move to the opposite side of the screen and spoilers was not working correctly for me either (verified this problem only happens on my local and not dev) otherwise all good
> 
> For the emoji i'll check. What do you mean by "tiny"? How should they appear?
> 
> I see the spoilers are working correctly in the chatbar, they do not work correctly once you send the message because that part is still a WIP.

I think the emojis looking too small was just me so you can just scratch that lol and noted about the spoilers 👍

2022-01-20 17:17 UTC, stavares843 commented
thanks for testing @phillsatellite 🔨 

@molimauro thanks for clarifying, is there anything else that is a WIP?

2022-01-20 17:19 UTC, molimauro commented
> > > emoji.mov
> > > spoilers.mov
> > > Only 2 issue I noticed going through was Emoji is showing up tiny in the chatbar and when you select an emoji the menu will move to the opposite side of the screen and spoilers was not working correctly for me either (verified this problem only happens on my local and not dev) otherwise all good
> > 
> > 
> > For the emoji i'll check. What do you mean by "tiny"? How should they appear?
> > I see the spoilers are working correctly in the chatbar, they do not work correctly once you send the message because that part is still a WIP.
> 
> I think the emojis looking too small was just me so you can just scratch that lol and noted about the spoilers 👍

Great!! Thanks :)

2022-01-20 17:24 UTC, stavares843 commented
@molimauro yes, both Phil and I checked the additional comments, but there was nothing there regarding the spoilers being a WIP, thats why im asking to double check 😂

2022-01-20 17:32 UTC, molimauro commented
@stavares843 yeah sorry, i should have been more specific. Spoilers and underlines are "special" md rules i have added. They are parsed correctly only in the chatbar and not when sent :)

2022-01-21 08:02 UTC, molimauro commented
@phillsatellite i should've fixed the enhancer problem :)

2022-01-21 23:30 UTC, stavares843 commented on test/Markdown.test.ts
> +import { toHTML, htmlTag } from '../libraries/ui/Markdown'
thanks for adding the test 🔨 

can you move this to ../libraries/ui/Markdown to be near the markdown file instead of the test folder?

2022-01-24 14:35 UTC, phillsatellite approved these changes

2022-01-25 16:11 UTC, WanderingHogan commented on store/ui/types.ts
> +  chatbarFocus: Boolean
should we make these all primitives instead of objects since you're touching this file anyays

2022-01-25 16:12 UTC, WanderingHogan commented on components/views/chat/chatbar/Editable.vue
> +      } else {
guard here

2022-01-25 16:12 UTC, WanderingHogan approved these changes
It looks great, there are a couple minor things you could change if you wanted, but up to you

2022-01-25 17:54 UTC, stavares843 commented
<img width="1110" alt="Captura de ecrã 2022-01-25, às 17 53 21" src="https://user-images.githubusercontent.com/29093946/151032036-299454b7-4aa5-4962-939d-bdf37e27a15c.png">
<img width="1101" alt="Captura de ecrã 2022-01-25, às 17 53 32" src="https://user-images.githubusercontent.com/29093946/151032042-a9190de4-a3fa-4313-8b16-9af7d3449102.png">

first is this branch, second is dev branch

the chat bar has a bigger height compared with dev, is that modification in purpose?

2022-01-25 18:28 UTC, stavares843 commented
neat, thanks for checking, just confirming 🎨

2022-01-25 18:37 UTC, stavares843 commented
I checked with the design team and there was an error within Figma

it should be 48px high. with a 16px padding all around the inside

<img width="1003" alt="Screen_Shot_2022-01-25_at_12 32 20_PM" src="https://user-images.githubusercontent.com/29093946/151038038-baa5f207-0080-4795-8769-515fec68113e.png">

2022-01-26 07:59 UTC, molimauro commented
great job @stavares843, thanks 🎉

2022-01-26 10:35 UTC, molimauro commented on components/views/chat/chatbar/Editable.vue
> +      } else {
Can remove if-else but should duplicate line 119

2022-01-26 13:09 UTC, molimauro commented on store/ui/types.ts
> +  chatbarFocus: Boolean
yes, i'll do it for sure

2022-01-27 15:21 UTC, stavares843 commented
are you gonna address that layout change? 🔨 let me know if you need more details

also, conflict 🔨

2022-01-27 15:26 UTC, molimauro commented
> are you gonna address that layout change? 🔨 let me know if you need more details
> 
> also, conflict 🔨

yes, i'm doing it! I asked to Liz because i had to reduce the padding but kept the 48px height. I'll resolve also other minor fixes i discovered (like adding a max-height on the chat, otherwise if you keep adding a lot of paragraphs it's not very good) and then i rebase and push. Thanks!!

2022-01-28 13:53 UTC, molimauro commented
@stavares843 in file `store/ui/mutations.ts` line 151 i inserted a TODO, probably a bug that needs to be investigated. Could you add please a ticket for it 🔨 ? thanks a lot

2022-01-28 14:24 UTC, iltumio commented
can you do a check on the file upload?
![Schermata 2022-01-28 alle 15 23 09](https://user-images.githubusercontent.com/36959970/151563476-6ffa8c70-831d-4562-8f6a-d43d55089452.png)

2022-01-28 15:09 UTC, stavares843 commented
will do, thanks!

2022-01-28 15:09 UTC, stavares843 commented
changes requested due to manuel's comment

2022-01-28 16:31 UTC, molimauro commented
Done!

2022-01-28 16:52 UTC, phillsatellite commented
Files bug is fixed on my side! Only issue I still see is the chat bar text is grey and still looks like its a little big/offset a little. Lemme know whatcha think

https://user-images.githubusercontent.com/93608357/151588193-913bb10e-cd5c-4960-9cfe-d785299175ba.mov

2022-01-28 16:59 UTC, molimauro commented
The height should now be 48px as per Figma (checked with the ui/ux team and with @stavares843 )! I think on the current version is around 40px

2022-01-28 17:00 UTC, phillsatellite commented
> The height should now be 48px as per Figma (checked with the ui/ux team and with @stavares843 )! I think on the current version is around 40px

Sounds good! Thanks for letting me know!

2022-01-28 17:19 UTC, molimauro commented
Ok @phillsatellite, Liz confirmed the color!

2022-01-28 17:32 UTC, phillsatellite commented
> Ok @phillsatellite, Liz confirmed the color!

Awesome! We going with the white? 💥

2022-01-28 17:33 UTC, phillsatellite commented
> Ok @phillsatellite, Liz confirmed the color!

Just saw in the Ui chat! SOunds good!

2022-01-28 22:49 UTC, WanderingHogan approved these changes

2022-01-28 23:13 UTC, stavares843 commented
<img width="662" alt="Captura de ecrã 2022-01-28, às 23 10 26" src="https://user-images.githubusercontent.com/29093946/151634234-e36979b3-fc08-4a45-8e61-96b4d1446e55.png">
<img width="639" alt="Captura de ecrã 2022-01-28, às 23 10 31" src="https://user-images.githubusercontent.com/29093946/151634237-0ef5aeca-ca41-4d88-9db9-4d343a7969aa.png">

this PR is adding 2 duplicate tests, you can remove the test folder 🔨

2022-01-28 23:14 UTC, stavares843 commented
<img width="345" alt="Captura de ecrã 2022-01-28, às 23 13 23" src="https://user-images.githubusercontent.com/29093946/151634286-146c91c6-dfbe-4383-a856-784fa0a04e11.png">

also, the spoilers are not working here, is that part still a WIP?

2022-01-28 23:18 UTC, stavares843 commented on libraries/ui/Cursor.ts
> +   * @param element Elemeet to set cursor position
Elemeet 🔨

2022-01-28 23:18 UTC, stavares843 commented on libraries/ui/Cursor.ts
> +   * @param parentElement Elemeet to get cursor position
Elemeet 🔨

2022-01-29 04:23 UTC, drepram commented on libraries/ui/Markdown.ts
> +  for (let attr in attributes) {
attr is never re-assigned, use const here instead of let!

2022-01-29 04:24 UTC, drepram commented on libraries/ui/Markdown.ts
> +  let unclosedTag = `${openDec}<${tagName}${attributeString}>`
unclosedTag is never re-assigned, use const here instead of let!

2022-01-29 04:26 UTC, drepram reviewed
hi! all the tests returned green but there's just some linting you've got to do :)

2022-01-29 04:26 UTC, drepram commented on libraries/ui/Markdown.ts
> +      /^[\s\S]+?(?=[^0-9A-Za-z\s\u00c0-\uffff-]|\n\n|\n|\w+:\S|$)/.exec(source),
In light of ESLint, you're gonna need to `use uppercase characters for the value of the escape sequence.` (https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v39.0.0/docs/rules/escape-case.md)

2022-01-30 18:25 UTC, iltumio requested changes
there are some little changes requested. Once we address those we can merge it

2022-01-30 18:25 UTC, iltumio commented on libraries/ui/Cursor.ts
> +      let range = Cursor._createRange(element, chars)
`range` is never reassigned. Use `const` instead of `let` (suggested by eslint, `prefer-const` rule)

2022-01-30 18:25 UTC, iltumio commented on libraries/ui/Cursor.ts
> +    let rows = node.innerText.split('\n\n')
rows never reassigned, use const

2022-01-30 18:25 UTC, iltumio commented on libraries/ui/Cursor.ts
> +    for (let [row, el] of rows.entries()) {
`[row, el]` never reassigned, use const instead

2022-01-30 18:25 UTC, iltumio commented on package.json
> +    "marked": "^4.0.7",
we should remove 'marked' since it is not used anymore

2022-01-30 18:25 UTC, iltumio commented on store/ui/mutations.ts
> +    state.settingReaction = status // TODO: check this mutation, probably a bug
can you open a ticket for that?

2022-01-30 18:25 UTC, iltumio commented on test/Markdown.test.ts
> +import { toHTML, htmlTag } from '../libraries/ui/Markdown'
I can still see the one in `test` folder. Can we remove it and just keep the one in `libraries/ui/Markdown` ?

2022-01-30 19:38 UTC, iltumio commented
Seems that we have an overlap with the right icons

![Schermata 2022-01-30 alle 20 35 27](https://user-images.githubusercontent.com/36959970/151714743-b398a3dd-58e5-47f6-9039-8340d959ff56.png)

2022-01-31 08:51 UTC, molimauro commented on package.json
> +    "marked": "^4.0.7",
it is, it'll be removed in another branch

2022-01-31 08:51 UTC, molimauro commented on store/ui/mutations.ts
> +    state.settingReaction = status // TODO: check this mutation, probably a bug
Sara already opened

2022-01-31 08:52 UTC, molimauro commented on libraries/ui/Markdown.ts
> +      /^[\s\S]+?(?=[^0-9A-Za-z\s\u00c0-\uffff-]|\n\n|\n|\w+:\S|$)/.exec(source),
thanks! :)

2022-01-31 08:53 UTC, molimauro commented
> <img alt="Captura de ecrã 2022-01-28, às 23 13 23" width="345" src="https://user-images.githubusercontent.com/29093946/151634286-146c91c6-dfbe-4383-a856-784fa0a04e11.png">
> 
> also, the spoilers are not working here, is that part still a WIP?

In this branch spoilers and underlines are managed only in the chatbar, they're not parsed when the msg is sent

2022-01-31 09:13 UTC, molimauro commented
Done, thanks guys!!

2022-01-31 11:48 UTC, iltumio approved these changes

2022-01-31 14:25 UTC, phillsatellite approved these changes

2022-01-31 16:48 UTC, merged