feat(ui): clicking on the user image shows profile modal
Satellite-im/Core-PWA pull request #1045
Opened 2022-01-19 22:01 UTC by vimercati-samir

2022-01-20 00:38 UTC, stavares843 commented
@vimercati-samir please fill out our pretty template 🎨

2022-01-20 03:21 UTC, josephmcg requested changes
Overall good, mostly cleanup old code from the same files you were updating.

One functionality question though.. Should clicking this open the profile modal?
It sets the active chat as well as opening the profile modal

![image](https://user-images.githubusercontent.com/33670767/150266266-164df999-6310-481c-9c3b-99d8ea2099f3.png)

2022-01-20 03:21 UTC, josephmcg commented on components/views/navigation/mobile/nav/Nav.html
> +</div>
I guess this is more of a preference, but I try to use the shorthand @click whenever I can. I think you can also remove the arrow functions in the click attributes

2022-01-20 10:11 UTC, vimercati-samir commented on components/views/settings/modal/Modal.vue
> +        allowTouchMove: !!this.$device.isMobile,
modified accordingly

2022-01-20 10:11 UTC, vimercati-samir commented on components/views/navigation/mobile/nav/Nav.html
> +</div>
modified accordingly

2022-01-20 10:13 UTC, vimercati-samir commented on store/ui/actions.ts
>  // @ts-ignore
activateKeybinds and clearKeybinds depend on it, are you sure Mousetrap should be removed?

2022-01-20 10:39 UTC, josephmcg commented on store/ui/actions.ts
>  // @ts-ignore
I highlighted the wrong line by accident. I meant the ts-ignore can be removed. my bad lol
Thanks for confirming

2022-01-20 10:50 UTC, vimercati-samir commented
> Overall good, mostly cleanup old code from the same files you were updating.
> 
> One functionality question though.. Should clicking this open the profile modal? It sets the active chat as well as opening the profile modal
> 
> ![image](https://user-images.githubusercontent.com/33670767/150266266-164df999-6310-481c-9c3b-99d8ea2099f3.png)

Maybe instead of opening the profile modal when clicking on the user photo (user item in messages sidebar) the correct behaviour would be to open the chat
<img width="357" alt="Screenshot 2022-01-20 at 11 39 39" src="https://user-images.githubusercontent.com/52865716/150323898-11a9408a-66dd-48e6-b2e6-976917043822.png">

Then clicking on the user photo in the chat header would open the profile modal
<img width="1325" alt="Screenshot 2022-01-20 at 11 43 11" src="https://user-images.githubusercontent.com/52865716/150323904-e8d36caf-5111-4863-be85-94caed3b9469.png">

What do you think about this flow?

2022-01-20 11:28 UTC, josephmcg commented
I like that much better from a UX perspective

2022-01-24 23:02 UTC, stavares843 commented
thanks for adding the PR template info 💥

2022-01-27 03:12 UTC, WanderingHogan commented
So we want to get to the profile when the user clicks the user image in the quick profile, not the list on the left. Sorry for the delay

2022-01-27 03:21 UTC, WanderingHogan commented
![image](https://user-images.githubusercontent.com/2993032/151286297-9aa9d021-a70c-411a-81f0-2a3b0f85fa64.png)

2022-01-27 03:22 UTC, WanderingHogan commented
1. clicking doesnt do anything
2. clicking opens quick profile
3. clicking opens full profile

2022-01-31 17:02 UTC, stavares843 commented
cc @vimercati-samir

2022-02-01 16:21 UTC, WanderingHogan commented
@vimercati-samir closing this, please re-open when ready

2022-02-01 16:21 UTC, closed without merging