feat(timezone): add timezone picker to profile setting
Satellite-im/Core-PWA pull request #1065
Opened 2022-01-21 17:55 UTC by genie-magic

**What this PR does** 📖
add timezone picker to profile setting

**Which issue(s) this PR fixes** 🔨

AP-518

2022-01-21 23:13 UTC, stavares843 requested changes
I think it's somewhat strange for UI/UX regarding we can click but doesn't work, the user is obligated to use the enter in order to save the selection

https://user-images.githubusercontent.com/29093946/150611882-4508f99b-5451-463b-a65b-22298f7a2d15.mov

2022-01-21 23:15 UTC, stavares843 requested changes
<img width="294" alt="Captura de ecrã 2022-01-21, às 23 10 37" src="https://user-images.githubusercontent.com/29093946/150611934-6867e7a7-7e18-42f7-9495-98c49d2ce027.png">

also, this all says location, but what the user is really selecting is the timezone, and timezone and location are different things, I can be anywhere in Portugal but selecting Lisbon as the timezone

2022-01-21 23:15 UTC, stavares843 requested changes
<img width="267" alt="Captura de ecrã 2022-01-21, às 23 11 09" src="https://user-images.githubusercontent.com/29093946/150612018-48762b65-cad8-45c6-9c15-a1758964af96.png">

after selecting a timezone, the text inside is not vertically aligned

2022-01-21 23:16 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/150611882-4508f99b-5451-463b-a65b-22298f7a2d15.mov


when typing, the font color is dark but then after selecting a timezone is white

2022-01-21 23:20 UTC, stavares843 commented on mock/profile.ts
> +  'America/Port_of_Spain',
can we edit the ones with an underscore in order to avoid showing Port_of_Spain on the user side?

2022-01-21 23:21 UTC, stavares843 commented on mock/profile.ts
> +  'Antarctica/DumontDUrville',
seems the correct name is Dumont-d'Urville

2022-01-21 23:22 UTC, stavares843 commented on mock/profile.ts
> +  'America/Scoresbysund',
seems the correct name is Scoresby Sund

2022-01-24 10:59 UTC, genie-magic commented
> I think it's somewhat strange for UI/UX regarding we can click but doesn't work, the user is obligated to use the enter in order to save the selection
> 
>  Gravacao.do.ecra.2022-01-21.as.23.11.45.mov 
> also asked the design team if they have any ideas
> 
> design team replied it shouldn't be like that, typically both the user clicking the option or hitting 'enter' key will work just fine.

@stavares843  Problem is that multiselect package we are using for select does not support click option... cc: @WanderingHogan

2022-01-27 03:37 UTC, WanderingHogan commented
@genie-magic can you switch these to the normal dropdowns, the user has no reason to select more than one anyways, and also make the other updates Sara found

2022-01-27 03:42 UTC, WanderingHogan commented
can you store the offset, too, and provide a way to access it

2022-01-27 03:43 UTC, WanderingHogan requested changes
please make sara's changes, switch to a dropdown, and create that way to get the offset

2022-01-31 17:45 UTC, stavares843 commented
cc @genie-magic

2022-01-31 17:47 UTC, genie-magic commented
Sorry for late response, @WanderingHogan , @stavares843 .
I will do it after finishing current tasks.

2022-02-04 11:44 UTC, genie-magic commented
@stavares843  , @WanderingHogan  I will create new PR with rebased code.

2022-02-04 11:44 UTC, closed without merging