add(jest): unit tests for Hounddog and Logger
Satellite-im/Core-PWA pull request #1073
Opened 2022-01-24 07:41 UTC by drepram

**What this PR does** 📖

Add unit tests (100% coverage) for the Hounddog and Logger utilities.

**Which issue(s) this PR fixes** 🔨

AP-531

**Special notes for reviewers** 🗒️

I've added a comment on JIRA at this ticket regarding how we can bump up the branches coverage of Hounddog.test.ts.

**Additional comments** 🎤

-

2022-01-24 12:49 UTC, stavares843 commented on utilities/Hounddog.test.ts
> +      //     },
please remove the commented out 🔨

2022-01-24 12:49 UTC, stavares843 commented on utilities/Hounddog.test.ts
> +        // textilePubkey: "", this have been written above. cannot have redundancies.
please remove the commented out 🔨

2022-01-24 15:42 UTC, drepram commented on utilities/Hounddog.test.ts
> +      //     },
Updated. Please check!

2022-01-24 15:42 UTC, drepram commented on utilities/Hounddog.test.ts
> +        // textilePubkey: "", this have been written above. cannot have redundancies.
Updated. Please check!

2022-01-24 16:22 UTC, stavares843 commented on utilities/Hounddog.test.ts
> +    // WebRTC.default.setActiveCall(state.webrtc, '0xdf9eb223bafbe5c5271415c75aecd68c21fe3d7e')
commented out code 🔨

2022-01-24 16:22 UTC, stavares843 commented on utilities/Hounddog.test.ts
> +})
missing empty line before describe

2022-01-24 18:50 UTC, drepram commented on utilities/Hounddog.test.ts
> +    // WebRTC.default.setActiveCall(state.webrtc, '0xdf9eb223bafbe5c5271415c75aecd68c21fe3d7e')
Removed. Please check again, thanks!

2022-01-24 18:50 UTC, drepram commented on utilities/Hounddog.test.ts
> +})
Added. Please check again, thanks!

2022-01-26 03:12 UTC, drepram commented
Hi, `git submodule update` wasn't reverting the changes so I went into the directory and checkout into the base commit for it (https://github.com/Satellite-im/locales/compare/53d940e23eb9ccfad2834aeab60fd19e399f36d6...1bd50dfae3a32cb15b6adb3884cd1d77921f3311#diff-663ade211b3a1552162de21c4031fcd16be99407aae5ceecbb491a2efc43d5d2); and that seemed to work, let me know if I am doing it wrong!

2022-01-27 03:46 UTC, WanderingHogan commented on utilities/Hounddog.ts
> -  findFriendByAddress(
please put this back

2022-01-27 03:47 UTC, WanderingHogan commented on utilities/Hounddog.ts
> +import { FriendStatus } from '~/libraries/Solana/FriendsProgram/FriendsProgram.types'
why did you add this? it doesn't look like it gets called?

2022-01-27 03:48 UTC, WanderingHogan requested changes
couple changes in the hounddog file

2022-01-27 13:52 UTC, drepram commented on utilities/Hounddog.ts
> +import { FriendStatus } from '~/libraries/Solana/FriendsProgram/FriendsProgram.types'
Removed!

2022-01-27 13:52 UTC, drepram commented on utilities/Hounddog.ts
> -  findFriendByAddress(
I've put it back in and wrote an additional unit test for it. Please check!

2022-01-28 16:51 UTC, WanderingHogan commented on utilities/Hounddog.ts
> -  findFriendByAddress(
sweet, thank you

2022-01-28 16:51 UTC, WanderingHogan approved these changes

2022-01-28 18:38 UTC, merged