add(jest): 100% coverage for SoundManager unit test
Satellite-im/Core-PWA pull request #1082
Opened 2022-01-24 18:46 UTC by drepram

**What this PR does** 📖

Add unit tests (100% coverage) for the SoundManager unit test.

**Which issue(s) this PR fixes** 🔨

AP-139

**Special notes for reviewers** 🗒️

The `this.sounds[sound].play()` returns two weird `console.error`:

![image](https://user-images.githubusercontent.com/34530026/150844410-bf732163-626c-4a74-bb25-83ea320ea340.png)

I did some googling and came across [this](https://stackoverflow.com/questions/51829319/how-to-mock-video-pause-function-using-jest/51831366), to which I tried to add to the code but it didn't work so I just commented it out for further debugging!

![image](https://user-images.githubusercontent.com/34530026/150844497-95539333-b447-4a5b-b7fe-84af2d06ee6b.png)

I think it's a particular problem to` .play()` because other units in the test suite are written identically and yet only `.play()` have those two console errors:

![image](https://user-images.githubusercontent.com/34530026/150844627-c1198f75-c536-4af1-9a86-af9ecdbe5f88.png)

**Additional comments** 🎤

2022-01-25 08:12 UTC, josephmcg commented
I don't think I know enough about Jest to give meaningful feedback here

2022-01-25 17:06 UTC, WanderingHogan commented
Jest uses jsdom, which doesn't have HTMLMediaElement, so you will have to fake it:
https://bharat-tiwari.gitbook.io/our-tech-journal/react/jest-setup-file

We had to do something similar for canvas. In this case you should be able to get away with the first little 4 line snippet from that link. For canvas we loaded something to mock it in dev dependencies, but I don't see it anymore

2022-01-25 17:07 UTC, WanderingHogan requested changes
check out the comment to mock htmlaudio

2022-01-29 00:22 UTC, WanderingHogan approved these changes

2022-01-29 00:29 UTC, stavares843 approved these changes

2022-01-29 00:29 UTC, merged