add(live): add active and close chat for live component items AP-538
Satellite-im/Core-PWA pull request #1141
Opened 2022-01-25 04:02 UTC by davidchan1219

**What this PR does** 📖

added chat active and close function in live component

**Which issue(s) this PR fixes** 🔨

AP-538

2022-01-25 08:28 UTC, josephmcg requested changes

2022-01-25 08:28 UTC, josephmcg commented on components/views/navigation/sidebar/live/Live.html
> +  <div class="name-and-icon" v-on:click="() => activeChat()">
@click, also don't think you need the arrow function

2022-01-25 08:28 UTC, josephmcg commented on components/views/navigation/sidebar/live/Live.html
> +    v-if="this.$store.state.friends.all.find((friend) => friend.address === this.$store.state.webrtc.activeCall)"
same extra arrow function here.
the v-if maybe be better off in a computed. You shouldn't include `this` if you keep it here

2022-01-25 08:28 UTC, josephmcg commented on components/views/navigation/sidebar/live/Live.vue
> +      }
confused by the guard clause on 28 if the same condition is being checked on 35 to dispatch the connection, could you explain?

2022-01-25 08:28 UTC, josephmcg commented on store/ui/mutations.ts
> +  },
declare this as User, let's be kind to our future selves

2022-01-25 08:28 UTC, josephmcg commented on store/ui/types.ts
> +  senderInfo: Object
same ^

2022-01-25 09:33 UTC, davidchan1219 commented on components/views/navigation/sidebar/live/Live.vue
> +      }
This function was made by other developer a few months ago. I think line 25 is not necessary.

2022-01-25 09:35 UTC, davidchan1219 commented on store/ui/mutations.ts
> +  },
I changed function name and object variable name. like setSelectedUserInfo, selectedUserInfo

2022-01-25 09:35 UTC, davidchan1219 commented on components/views/navigation/sidebar/live/Live.html
> +  <div class="name-and-icon" v-on:click="() => activeChat()">
changed

2022-01-25 09:35 UTC, davidchan1219 commented on components/views/navigation/sidebar/live/Live.html
> +    v-if="this.$store.state.friends.all.find((friend) => friend.address === this.$store.state.webrtc.activeCall)"
changed

2022-01-25 09:38 UTC, davidchan1219 commented on store/ui/types.ts
> +  senderInfo: Object
changed the variable name

2022-01-25 10:03 UTC, josephmcg commented on store/ui/mutations.ts
> +  },
Hey David, thanks for the quick fixes. I wasn't concerned with the variable name, more so the declaration as type Object. Since we know it will be a User, we should declare it as such. Sorry if my comment wasn't clear.

2022-01-25 11:21 UTC, davidchan1219 commented on store/ui/mutations.ts
> +  },
@josephmcg I just fixed the type

2022-01-26 01:51 UTC, josephmcg approved these changes

2022-01-26 02:58 UTC, phillsatellite approved these changes

2022-01-27 03:57 UTC, WanderingHogan approved these changes

2022-01-27 04:00 UTC, WanderingHogan requested changes
I think the UI is a little off

2022-01-27 04:01 UTC, WanderingHogan commented
<img width="658" alt="Screen Shot 2022-01-26 at 11 01 10 PM" src="https://user-images.githubusercontent.com/2993032/151289773-99977a43-60b6-4356-97fd-a54c22a470fd.png">
I think that green icon should not be visible when not in a call

2022-01-27 14:42 UTC, davidchan1219 commented
> I think the UI is a little off

Fixed. Please check again

2022-01-31 20:35 UTC, WanderingHogan commented
![image](https://user-images.githubusercontent.com/2993032/151868634-2a204197-9e84-463b-8727-61b7915c740c.png)
If you look close, the live component still shows this horizontal rule. It makes it the container too tall.

If you can hide the entire live component it looks way more balanced
![image](https://user-images.githubusercontent.com/2993032/151868912-50fedb31-41c6-49b1-9875-50986bd462d4.png)


When you make this change, if you have to fix conflicts, please rebase and not merge

2022-01-31 20:35 UTC, WanderingHogan requested changes
see comments

2022-02-02 01:07 UTC, stavares843 commented
/rebase

2022-02-02 09:53 UTC, closed without merging