fix(user): fix timestamp for user list AP-118
Satellite-im/Core-PWA pull request #1143
Opened 2022-01-25 05:21 UTC by davidchan1219

**What this PR does** 📖

added correct timestamp for last message

**Which issue(s) this PR fixes** 🔨

AP-118

2022-01-25 08:11 UTC, josephmcg requested changes

2022-01-25 08:11 UTC, josephmcg commented on components/views/user/User.vue
> +    },
Is `curUserMInfo && curUserMInfo.lastInbound` necessary? why not just `curUserMInfo.lastInbound`

I believe this should be fromNow(). from() expects arguments
https://day.js.org/docs/en/display/from-now

I'll fix the dayjs type errors soon so this will be more apparent

2022-01-25 08:56 UTC, davidchan1219 commented on components/views/user/User.vue
>      user: {
moved computed after data

2022-01-25 08:56 UTC, davidchan1219 commented on components/views/user/User.vue
> +    },
changed from() to fromNow()

2022-01-26 01:26 UTC, josephmcg approved these changes
thanks David

2022-01-26 02:30 UTC, phillsatellite approved these changes

2022-01-27 04:08 UTC, WanderingHogan approved these changes

2022-01-27 15:18 UTC, stavares843 commented
@davidchan1219 only missing conflict 🔨

2022-01-27 16:00 UTC, davidchan1219 commented
> @davidchan1219 only missing conflict 🔨

@stavares843 fixed the conflict.

2022-01-27 20:43 UTC, stavares843 commented
thanks! 🔨

2022-01-27 20:44 UTC, stavares843 commented
<img width="1439" alt="Captura de ecrã 2022-01-27, às 20 43 42" src="https://user-images.githubusercontent.com/29093946/151440623-4b00e7a3-5a85-456f-a09c-667fdfa52778.png">

my account doesn't have a timestamp

those messages are older than 24h ago

2022-01-27 21:01 UTC, davidchan1219 commented
> <img alt="Captura de ecrã 2022-01-27, às 20 43 42" width="1439" src="https://user-images.githubusercontent.com/29093946/151440623-4b00e7a3-5a85-456f-a09c-667fdfa52778.png">
> 
> my account doesn't have a timestamp
> 
> those messages are older than 24h ago

Are there messages from the friends of the sidebar?
If there is no any message from the friend, can't display the timestamp.

2022-01-27 22:00 UTC, stavares843 commented
checking 🔨

2022-01-27 22:17 UTC, stavares843 commented
the previous screenshot was my own messages, which I thought would appear when it was the messages from the current user as well

couple questions

<img width="349" alt="Captura de ecrã 2022-01-27, às 22 11 27" src="https://user-images.githubusercontent.com/29093946/151452331-4e2dd2cf-1682-4db4-b685-056f424178a4.png">

should that say ''a few moments ago'' when the other user sent a message? the ticket says

''Once #AP-125 goes in, you will want to make the time in components/tailored/core/user/User.vue/html use the same timestamp transformation from the message box, but using the time data from the textile state object, lastInboundkey for the appropriate user'' - so seems it would be somewhat on the format of 12:00 or similar right? cc @WanderingHogan let me know if I misunderstood 

<img width="951" alt="Captura de ecrã 2022-01-27, às 22 11 35" src="https://user-images.githubusercontent.com/29093946/151452380-72bd91cc-d03e-4bc1-a372-a570680090d7.png">


also, when the ''a few moments ago'' updated on the chat itself saying ''a minute ago'', but not on the sidebar so this is lacking a real-time update here

<img width="869" alt="Captura de ecrã 2022-01-27, às 22 13 57" src="https://user-images.githubusercontent.com/29093946/151452502-27458591-6392-4013-a3f5-4f74091e9094.png">


after switching chats, then updated properly, but I thought this was expected to say the exact timestamp such as 11:28 instead of 3 minutes ago

2022-01-29 14:39 UTC, davidchan1219 commented
@stavares843 I fixed the timestamp issue you mentioned above. I made to load the message's last update time.

2022-01-29 20:15 UTC, stavares843 commented on components/views/user/User.vue
> +      const curUserMInfo =
maybe currentUserInfo would be easier to understand compared to curUserMInfo

2022-01-30 13:37 UTC, davidchan1219 commented on components/views/user/User.vue
> +      const curUserMInfo =
@stavares843 renamed that

2022-01-31 00:05 UTC, stavares843 commented
<img width="815" alt="Captura de ecrã 2022-01-31, às 00 04 25" src="https://user-images.githubusercontent.com/29093946/151723579-29951fb8-973b-4491-8f6f-46ebbaa36457.png">

neat 💥

2022-01-31 18:03 UTC, davidchan1219 commented
@stavares843 fixed the videoscreenshot's issue

2022-02-01 16:20 UTC, WanderingHogan requested changes
with lastInbound added to indexeddb, is it possible to use that instead of what's going on in the getLastBoundary method?

2022-02-02 01:07 UTC, stavares843 commented
/rebase

2022-02-02 10:03 UTC, closed without merging