feat(profileModal): make reusable social account component
Satellite-im/Core-PWA pull request #1144
Opened 2022-01-25 06:47 UTC by nickjjang

**What this PR does** 📖
Reusable social account component in profile modal->accounts
**Which issue(s) this PR fixes** 🔨

AP-525
**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-01-25 07:33 UTC, josephmcg requested changes

2022-01-25 07:33 UTC, josephmcg commented on components/views/user/profile/SocialAccount/SocialAccount.html
> +  <a v-if="profileUrl" class="account-link" :href="profileUrl">
target="_blank" rel="noopener noreferrer" would be nice on the link

2022-01-25 07:33 UTC, josephmcg commented on components/views/user/profile/Profile.html
> +      </div>
maybe just 
`<UserProfileAccounts v-if="route==='accounts'" />`

2022-01-25 07:33 UTC, josephmcg commented on components/views/user/profile/SocialAccount/SocialAccount.less
> +  }
These are off-center and increasing the height of the box due to 1.5 line-height. This helps a bit
`.account-link`
`line-height:1`

2022-01-25 07:33 UTC, josephmcg commented on types/social/social.ts
> +}
If it's just enum, maybe this should live in the enums folder. I noticed we also tend to use CAPS since they're constants. I know there's lots of linter errors, I fixed these in another PR. You can add 
`export {...
...
SocialMediaEnum}`

`libraries/Enums/types`

2022-01-25 07:33 UTC, josephmcg commented on components/views/user/profile/Accounts.vue
> +</style>
rather than overriding bulma template classes, I would probably just write some new css.
flex with a gap, flex-wrap. max width on the account

2022-01-25 07:35 UTC, josephmcg commented
oh 1 more.. we already have line-height: 1.5 coming from generic.sass. can remove line 10

![image](https://user-images.githubusercontent.com/33670767/150931877-f3ac5361-b4b8-402b-931d-0086796ae6f4.png)

![image](https://user-images.githubusercontent.com/33670767/150931941-3c4c2fb0-b529-4d90-a7e7-0a3bfe12f246.png)

2022-01-26 01:03 UTC, nickjjang commented
@josephmcg I've fixed changes requested.

2022-01-26 01:23 UTC, josephmcg approved these changes
looks great, thanks Nick

2022-01-26 05:14 UTC, phillsatellite commented
<img width="1021" alt="profilemodal" src="https://user-images.githubusercontent.com/93608357/151107645-98df3393-1948-44fd-a16f-1dfe384ef112.png">
Is the link for users Youtube supposed to be missing?

2022-01-26 16:55 UTC, nickjjang commented
> <img alt="profilemodal" width="1021" src="https://user-images.githubusercontent.com/93608357/151107645-98df3393-1948-44fd-a16f-1dfe384ef112.png">
> 
> Is the link for users Youtube supposed to be missing?
@phillsatellite it is just mockup. you can check design from https://www.figma.com/file/FfmiRxikUeCO2AGHryXeNc/User-Profile-Modal?node-id=39%3A5907

2022-01-27 04:11 UTC, WanderingHogan approved these changes

2022-01-27 15:04 UTC, stavares843 approved these changes

2022-01-27 15:04 UTC, merged