add(jest): 100% coverage for store/webrtc/mutations.ts unit test
Satellite-im/Core-PWA pull request #1152
Opened 2022-01-25 14:56 UTC by drepram

**What this PR does** 📖

Add unit tests (100% coverage) for the store/webrtc/mutations.ts unit test, while also updating the mutations.ts module in accordance with #1149 

**Which issue(s) this PR fixes** 🔨

AP-588

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-01-25 15:08 UTC, stavares843 approved these changes

2022-01-25 16:21 UTC, WanderingHogan requested changes
Can you add setConnectedTime back in, and do a `git submodules update`

2022-01-26 12:56 UTC, drepram commented
Hi Hogan, I added the changes you requested. Though I think it's relevant that I tell you that Manuel told me that Eric and Jason both worked on the **same fix** in which they came up with the same solution but with a different name for the mutation, hence my removal of it (as per #1149); let me know if I need to omit the redundant `setConnectedTime` function or if there are more changes to be made!

2022-01-27 04:22 UTC, WanderingHogan approved these changes

2022-01-27 04:26 UTC, WanderingHogan commented
oh cool, thank you for that explanation.

If you want to remove it again, can you also update where that removed function was getting called in other files, otherwise we can create a ticket for it and a put it in a cleanup epic or something

2022-01-27 10:22 UTC, merged