feat(textile): add lastInbound to indexeddb records AP-598
Satellite-im/Core-PWA pull request #1156
Opened 2022-01-25 22:29 UTC by davidchan1219

**What this PR does** 📖

added lastInbound to indexeddb records

**Which issue(s) this PR fixes** 🔨

AP-598

2022-01-26 01:14 UTC, josephmcg requested changes

2022-01-26 01:14 UTC, josephmcg commented on store/textile/actions.ts
> +      })
This method is for outbound messages. you should not update lastInbound based on an outbound message

2022-01-26 01:14 UTC, josephmcg commented on store/textile/actions.ts
> +        : 0,
This has the potential to set lastInbound based on an outboundMessage. I would suggest the lastInbound in textile store. you can move the scope up one level outside of the else.

![image](https://user-images.githubusercontent.com/33670767/151086503-d11714e0-5245-410b-ac9d-09091a83d257.png)

2022-01-26 04:12 UTC, phillsatellite approved these changes

2022-01-26 05:27 UTC, davidchan1219 commented on store/textile/actions.ts
> +      })
updated

2022-01-26 05:28 UTC, davidchan1219 commented on store/textile/actions.ts
> +        : 0,
removed that part

2022-01-26 05:34 UTC, josephmcg commented on store/textile/actions.ts
> +      })
David, please read this method documentation, understand what it is doing, and where it is called. It is only called when sending messages, you should not be adjusting lastInbound at all here.

2022-01-26 05:37 UTC, josephmcg commented on store/textile/actions.ts
> +        : 0,
Rather than juggling two variables, you should just declare that const lastInbound outside of the else

2022-01-26 10:06 UTC, davidchan1219 commented on store/textile/actions.ts
> +      })
StoreMessage is called when the user sends and receives the messages.
And I made to register incoming message's lastbound.

2022-01-26 10:09 UTC, davidchan1219 commented on store/textile/actions.ts
> +        : 0,
I updated the code with your suggestion.

2022-01-26 10:32 UTC, josephmcg commented on store/textile/actions.ts
> +      })
I see, thank you for helping me understand. It is being called for incoming messages inside of the subscribeToMailbox function.

2022-01-26 11:21 UTC, davidchan1219 commented on store/textile/actions.ts
> +      })
fixed

2022-01-27 00:52 UTC, josephmcg requested changes
1 more bug, then I think it's good to go

2022-01-27 00:52 UTC, josephmcg commented on store/textile/actions.ts
> +
this is always evaluating false because conversations is an object
If there are no inbound messages, it will be 0 anyway. I believe you can take advantage of ts optional chaining
`rootState.textile.conversations[address]?.lastInbound ?? 0`

![image](https://user-images.githubusercontent.com/33670767/151270612-19e04239-fddb-4863-b85b-f789a8de3a21.png)

2022-01-27 05:03 UTC, davidchan1219 commented on store/textile/actions.ts
> +
fixed

2022-01-27 19:02 UTC, Jekrimo approved these changes

2022-01-28 01:02 UTC, josephmcg approved these changes

2022-01-31 16:03 UTC, WanderingHogan approved these changes

2022-01-31 16:45 UTC, merged