feat(ui): implementation of layout for locked toggle
Satellite-im/Core-PWA pull request #1167
Opened 2022-01-26 16:05 UTC by vimercati-samir

What this PR does 📖
Implementation of layout for locked toggle

Which issue(s) this PR fixes 🔨
AP-530

Special notes for reviewers 🗒️

Additional comments 🎤

2022-01-27 03:26 UTC, josephmcg requested changes
functionality is good, minor refactor requests to make things more readable

2022-01-27 03:26 UTC, josephmcg commented on components/views/settings/pages/privacy/Privacy.html
> +        <InteractablesSwitch :isLocked="true" />
rather than `:isLocked="true"`, you could also just provide `<InteractablesSwitch isLocked />`

2022-01-27 03:26 UTC, josephmcg commented on components/interactables/Switch/Switch.less
>        }
we can improve the readability of this file, taking advantage of less. I'll DM you a newly formatted version

2022-01-27 03:27 UTC, josephmcg commented on components/interactables/Switch/Switch.vue
> +    isLocked: Boolean,
also good to specify more details like required & default

2022-01-27 10:29 UTC, vimercati-samir commented on components/views/settings/pages/privacy/Privacy.html
> +        <InteractablesSwitch :isLocked="true" />
modified accordingly in commit https://github.com/Satellite-im/Core-PWA/pull/1167/commits/92cd73802d99ee21bec2f91a0abfc0faabda5d60

2022-01-27 10:29 UTC, vimercati-samir commented on components/interactables/Switch/Switch.vue
> +    isLocked: Boolean,
modified accordingly in commit https://github.com/Satellite-im/Core-PWA/pull/1167/commits/92cd73802d99ee21bec2f91a0abfc0faabda5d60

2022-01-27 10:29 UTC, vimercati-samir commented on components/interactables/Switch/Switch.less
>        }
modified accordingly in commit https://github.com/Satellite-im/Core-PWA/pull/1167/commits/92cd73802d99ee21bec2f91a0abfc0faabda5d60

2022-01-27 17:31 UTC, phillsatellite approved these changes

2022-01-27 18:58 UTC, Jekrimo approved these changes

2022-01-28 00:58 UTC, josephmcg approved these changes

2022-01-28 19:23 UTC, stavares843 commented
<img width="716" alt="Captura de ecrã 2022-01-28, às 19 20 48" src="https://user-images.githubusercontent.com/29093946/151608365-4de8a0af-a6b5-418a-9443-93df16814d99.png">

this is the design from liz

vs branch

<img width="531" alt="Captura de ecrã 2022-01-28, às 19 21 26" src="https://user-images.githubusercontent.com/29093946/151608463-510e5e50-864d-4cc7-a23c-1b954e161bf5.png">

it should have a space between the border and the rest of the toggle

2022-01-31 16:58 UTC, stavares843 commented
cc @vimercati-samir

2022-02-01 17:02 UTC, WanderingHogan approved these changes

2022-02-02 01:07 UTC, stavares843 commented
/rebase

2022-02-02 16:56 UTC, vimercati-samir commented
changed accordingly and rebased
<img width="671" alt="Screenshot 2022-02-02 at 17 44 09" src="https://user-images.githubusercontent.com/52865716/152200267-2779799f-a293-4eac-a3e4-764008793718.png">

2022-02-02 17:05 UTC, WanderingHogan commented
/rebase

2022-02-02 19:36 UTC, WanderingHogan commented
Samir and I talked about how to rebase this and open a new pull request or update this one with a force push, so we need to hold off merging it

2022-02-02 19:39 UTC, closed without merging