fix(Theme): deactivate flair dropdown until selects moonless night
Satellite-im/Core-PWA pull request #1181
Opened 2022-01-27 18:06 UTC by nickjjang

**What this PR does** 📖
Themes - the flair dropdown be deactivated until the user selects the moonlight theme

**Which issue(s) this PR fixes** 🔨
deactivate flair dropdown until selects moonless night and set the satellite as default.

AP-424
**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-01-27 18:55 UTC, Jekrimo approved these changes

2022-01-27 19:23 UTC, phillsatellite approved these changes

2022-01-28 01:06 UTC, josephmcg approved these changes
great from a functionality perspective. I wonder if the disabled select needs more of a visual indication though. Seems a bit bright for a disabled state

2022-01-28 19:18 UTC, stavares843 commented
good point

im gonna ask design about it 🎨

2022-01-28 19:27 UTC, stavares843 commented
![image](https://user-images.githubusercontent.com/29093946/151609274-c5bb272c-ddfc-474c-82f5-041a6bbfcb46.png)

so when is deactivated, should be grey

color - #576574

2022-01-31 16:57 UTC, stavares843 commented
cc @nickjjang

2022-02-01 23:47 UTC, nickjjang commented
> 

Hey @stavares843, I've fixed it

2022-02-02 00:57 UTC, stavares843 commented
/rebase

2022-02-02 01:03 UTC, stavares843 commented
<img width="863" alt="Captura de ecrã 2022-02-02, às 01 03 01" src="https://user-images.githubusercontent.com/29093946/152076961-fc2af6c4-81d1-4a9c-ba4d-a7e7c513de8b.png">
<img width="855" alt="Captura de ecrã 2022-02-02, às 01 03 06" src="https://user-images.githubusercontent.com/29093946/152076966-f1574082-07ff-4a0a-91a1-188af3173c9d.png">


neat 💥

2022-02-02 13:05 UTC, iltumio requested changes

2022-02-02 13:05 UTC, iltumio commented on components/views/settings/pages/personalize/Personalize.html
> +        :disabled="theme===ThemeNames.DEFAULT"
add spaces between the === symbol for better readability ("theme === ThemesNames.DEFAULT)

2022-02-02 13:05 UTC, iltumio commented on components/views/settings/pages/personalize/index.vue
> +        if (activeTheme.name === ThemeNames.DEFAULT) {
`activeTheme` is possibly undefined. Use the optional chaining operator. (`activeTheme?.name`) since it's the result of a `.find()` call

2022-02-02 13:05 UTC, iltumio commented on components/views/settings/pages/personalize/index.vue
> +            Flairs.find((flair) => flair.value === FlairColors.SATELLITE),
the result of the `find()` is possibly undefined. Extract the value first, then commit the state only if the value is really found

2022-02-03 17:36 UTC, WanderingHogan commented on components/interactables/Select/Select.less
> +      box-shadow: 0 5px 14px -5px @gray !important;
there's no quick way to fix this without potentially affecting a lot of other places. The base less file uses important for the backgroundf color, so nick used important in the component to override it. I made a note here: https://satellite-im.atlassian.net/browse/AP-670 for post alpha because it will be a bigger problem than just here and can be addressed all at once

2022-02-03 17:50 UTC, WanderingHogan approved these changes

2022-02-04 00:17 UTC, stavares843 approved these changes

2022-02-04 00:18 UTC, merged