fix(actions): remove more option button AP-419
Satellite-im/Core-PWA pull request #1234
Opened 2022-01-31 03:51 UTC by davidchan1219

**What this PR does** 📖

Removed more option button

**Which issue(s) this PR fixes** 🔨

AP-419

2022-01-31 14:19 UTC, Jekrimo requested changes

2022-01-31 14:19 UTC, Jekrimo commented on components/views/chat/message/actions/Actions.html
> +  </div> -->
Can we just delete this whole commented code? Or are we planning to uncomment for later use?

2022-01-31 14:21 UTC, davidchan1219 commented on components/views/chat/message/actions/Actions.html
> +  </div> -->
@Jekrimo I removed that code.

2022-01-31 15:09 UTC, stavares843 commented
i don't think the idea was to remove the button

i think the idea was something more

if there are options show the button

if not, hide the button

cc @WanderingHogan thoughts?

2022-01-31 15:47 UTC, WanderingHogan commented
@davidchan1219 like @stavares843 said - this isn't meant to remove the ellipses, just hide them if there are not things to show in the ellipses, more likely a v-if

2022-01-31 15:48 UTC, WanderingHogan requested changes
hide if nothing in it, show if something in it, not remove code

2022-01-31 16:08 UTC, davidchan1219 commented
@WanderingHogan There is no any item in the settings, so I made to hide the more icon.

2022-01-31 16:53 UTC, stavares843 commented
@davidchan1219 feel free to remove changes requested label and add missing code review label when you address the feedback

2022-01-31 16:53 UTC, stavares843 commented
and thanks for updating 🔨

2022-02-01 14:32 UTC, phillsatellite approved these changes

2022-02-01 23:34 UTC, WanderingHogan approved these changes

2022-02-02 01:06 UTC, merged