feat(groupChatManager): create a groupChat manager to create seperate collections on a thread
Satellite-im/Core-PWA pull request #1291
Opened 2022-02-02 21:03 UTC by Jekrimo

**What this PR does** 📖
create a groupChat manager to create separate collections on a thread, allow sending messages, listening to the collection for changes, eventEmitters for testing I presume

**Which issue(s) this PR fixes** 🔨

AP-660

**Special notes for reviewers** 🗒️
This has no way to test as it currently is. Missing some front end integrations and a way to save collectionUUID's for users

2022-02-03 12:35 UTC, iltumio requested changes

2022-02-03 12:35 UTC, iltumio commented on libraries/Textile/GroupChatManager.ts
> +    this.eventEmitter.emit(newCollectionUUID)
EventEmitter should extend the class, then you should be able to use the `this.emit()` method

2022-02-03 12:35 UTC, iltumio commented on libraries/Textile/GroupChatManager.ts
> +import { EventEmitter } from 'events'
Use the custome EventEmitter class we built for WebRTC that is strongly typed

2022-02-03 19:22 UTC, phillsatellite commented
Tested: I'm not 100% sure if its caused by the PR but can't seem to get past the Linking Satellites page when creating a new account. I switched back to Dev branch, created new account and got in fine, switched back to this branch and created new account and still got blocked at Linking Satellites
![Screen Shot 2022-02-03 at 2 20 40 PM (2)](https://user-images.githubusercontent.com/93608357/152413965-8abd6727-01f1-4fed-8012-650a0a0aa9ae.png)

2022-02-08 21:44 UTC, stavares843 commented
/rebase

2022-02-08 22:03 UTC, phillsatellite approved these changes

2022-02-09 20:53 UTC, stavares843 commented
tickets that jeff added

[AP-732](https://satellite-im.atlassian.net/browse/AP-732)
[AP-733](https://satellite-im.atlassian.net/browse/AP-733)
[AP-734](https://satellite-im.atlassian.net/browse/AP-734)
[AP-735](https://satellite-im.atlassian.net/browse/AP-735)
[AP-736](https://satellite-im.atlassian.net/browse/AP-736)
[AP-737](https://satellite-im.atlassian.net/browse/AP-737)
[AP-738](https://satellite-im.atlassian.net/browse/AP-738)
[AP-739](https://satellite-im.atlassian.net/browse/AP-739)
[AP-740](https://satellite-im.atlassian.net/browse/AP-740)
[AP-741](https://satellite-im.atlassian.net/browse/AP-741)
[AP-742](https://satellite-im.atlassian.net/browse/AP-742)
[AP-743](https://satellite-im.atlassian.net/browse/AP-743)
[AP-744](https://satellite-im.atlassian.net/browse/AP-744)

thanks for adding @Jekrimo 🔨

2022-02-09 21:51 UTC, phillsatellite commented
Tested: Only issues I've found that I don't think weren't already addressed was the error in terminal (switched to branch, yarn, yarn dev to get that error) and the other error in Console "Error: errors.textile.friend_not_found"
<img width="1728" alt="Screen Shot 2022-02-09 at 4 49 06 PM" src="https://user-images.githubusercontent.com/93608357/153296206-9c0167b1-938a-4941-b6c9-1ce9b1ab69ce.png">

<img width="1415" alt="Screen Shot 2022-02-09 at 4 41 09 PM" src="https://user-images.githubusercontent.com/93608357/153296214-7c2f3782-a7c8-4ad3-bdfb-25397816e9df.png">

2022-02-09 23:02 UTC, Jekrimo commented
> Tested: Only issues I've found that I don't think weren't already addressed was the error in terminal (switched to branch, yarn, yarn dev to get that error) and the other error in Console "Error: errors.textile.friend_not_found" <img alt="Screen Shot 2022-02-09 at 4 49 06 PM" width="1728" src="https://user-images.githubusercontent.com/93608357/153296206-9c0167b1-938a-4941-b6c9-1ce9b1ab69ce.png">
> 
> <img alt="Screen Shot 2022-02-09 at 4 41 09 PM" width="1415" src="https://user-images.githubusercontent.com/93608357/153296214-7c2f3782-a7c8-4ad3-bdfb-25397816e9df.png">

I think this has to do with us tricking it currently to allow multi users. I say we leave it and open a bug for it. But Idk what everyone else thinks

2022-02-09 23:39 UTC, stavares843 commented
do we know why appears the errors.textile.friend_not_found from Phil's screenshot? I see that added here
https://github.com/Satellite-im/locales/blob/main/en-US.js#L469


can we fix the warning when it finishes compiling locally? atm we have zero compiling warnings after compiling

2022-02-10 15:55 UTC, stavares843 commented
is possible to get the textile error that phil mentioned above fixed as well? 🔨

2022-02-10 16:05 UTC, Jekrimo commented
I'm tryin to recreate it and can't get the error, is it showing for anyone else?

2022-02-10 18:12 UTC, phillsatellite commented
> I'm tryin to recreate it and can't get the error, is it showing for anyone else?

Hey Jeff! Sorry didn't notice earlier I got that error from trying to react to a message, which you said above isnt working yet 👍

2022-02-10 18:12 UTC, stavares843 commented
thanks for testing @phillsatellite

2022-02-10 18:22 UTC, Jekrimo commented
Awesome! That's great news, perfect!

2022-02-10 21:02 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
> +          this.$store.dispatch('textile/sendGroupMessage', {
what do you think about dumping the if/else and doing something like 

```
        // Check if the message is a group or a direct message
        const messageType = RegExp(this.$Config.regex.uuidv4).test(
          this.recipient.textilePubkey,
        )
          ? 'sendGroupMessage'
          : 'sendTextMessage'

        this.$store.dispatch(`textile/${messageType}`, {
          to: this.recipient.textilePubkey,
          text: value,
        })
        ```

2022-02-10 21:12 UTC, WanderingHogan commented on components/views/chat/conversation/Conversation.vue
> +import { Message } from '~/types/textile/mailbox'
is this getting ready for something in the future, or leftover

2022-02-10 21:22 UTC, WanderingHogan commented on layouts/chat.vue
> +        : isMe
How is this meant to work?

2022-02-10 21:30 UTC, WanderingHogan commented on layouts/chat.vue
> +        : isMe
is it missing something to wrap that first ternary, or does it not need it?

2022-02-10 21:33 UTC, WanderingHogan commented on layouts/chat.vue
> +        : isMe
TIL: conditional chains in ternary operators

2022-02-10 21:38 UTC, WanderingHogan approved these changes

2022-02-10 21:58 UTC, merged