fix(imageUpload): able to have pending upload images stay in specific…
Satellite-im/Core-PWA pull request #1328
Opened 2022-02-04 02:56 UTC by KemoPaw

… chat

**What this PR does** 📖
https://satellite-im.atlassian.net/browse/AP-113

**Which issue(s) this PR fixes** 🔨

Upload modal updates when you switch chats. 

**Special notes for reviewers** 🗒️
**In the Index.vue file there is a `resetAllUploadedFiles`, not sure if this is the best practice. Other attempted methods did not work such as adding it in mutationsBlacklist in `persist.ts`**

**Additional comments** 🎤

2022-02-05 04:39 UTC, WanderingHogan commented on components/views/files/upload/Upload.vue
> +      this.$store.commit(
move these up, above methods. If you have ESLint installed in your IDE you should be able to 'quickfix' it
<img width="809" alt="Screen Shot 2022-02-04 at 9 36 46 PM" src="https://user-images.githubusercontent.com/2993032/152628829-c662e880-59dd-4f7f-b319-e874755fb3c5.png">

2022-02-05 04:44 UTC, WanderingHogan commented on pages/index.vue
> +   destroyed(){
good idea

2022-02-05 04:47 UTC, WanderingHogan commented on types/chat/chat.ts
> +export interface UploadedFiles extends UploadDropItemType {}
Why did you extend this instead of just importing the type directly in store/chat/types.ts?

2022-02-05 04:48 UTC, WanderingHogan requested changes
Minor eslint update and a question. 

Great job Kat

2022-02-07 01:04 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +        tempFiles.every(async (uploadFile: UploadDropItemType) => {
this should probably be a forEach since the boolean returned by every isn't being used

2022-02-07 01:20 UTC, josephmcg requested changes
Good job, let me know if you want to work through these changes together

2022-02-07 01:20 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +        tempFiles.every(async (uploadFile: UploadDropItemType) => {
this should probably be a forEach since the boolean returned by every isn't being used

2022-02-07 01:20 UTC, josephmcg commented on pages/index.vue
> +    this.$store.commit('chat/resetAllUploadedFiles')
I think we typically set this inside `plugins/thirdparty/persist.ts`

2022-02-07 01:20 UTC, josephmcg commented on store/chat/mutations.ts
> +  },
I think it would be better to just delete uploadedFiles[address]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete

2022-02-07 01:20 UTC, josephmcg commented on store/chat/mutations.ts
> +  },
After configuring the anti-persist stuff, can delete

2022-02-07 01:20 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +  },
Could you explain your thought process for setting the empty array in `initUploadedFiles`? I feel like this could be avoided by using optional chaining when you're accessing the properties

2022-02-07 01:20 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +        return this.chat.uploadedFiles[this.$props.recipient?.address]
try this instead: 
`return this.chat.uploadedFiles[this.$props.recipient?.address] ?? []`

If there's an object, it returns it. If not, return whatever is after the `??`

2022-02-07 06:12 UTC, josephmcg commented on types/chat/chat.ts
> +export interface UploadedFiles extends UploadDropItemType {}
That's my fault, I thought it would be good to have the state related interface in that file to keep things consistent

2022-02-07 06:12 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +        tempFiles.every(async (uploadFile: UploadDropItemType) => {
also can you explain why you created the tempFiles variable?

2022-02-07 21:38 UTC, cmckelvy42 commented on store/chat/mutations.ts
> +  },
We tried that initially but reassigning to a new pointer was causing all kinds of headaches. This was done to maintain the same reference across the app, as creating a new empty array prevents the modal from clearing properly after a successful send

2022-02-07 21:39 UTC, cmckelvy42 commented on store/chat/mutations.ts
> +  },
> I think it would be better to just delete uploadedFiles[address], or just set to []. With some of my other feedback below though, I think delete is better https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete

We tried that initially but reassigning to a new pointer was causing all kinds of headaches. This was done to maintain the same reference across the app, as creating a new empty array prevents the modal from clearing properly after a successful send

2022-02-07 21:42 UTC, cmckelvy42 commented on components/views/files/upload/Upload.vue
> +        tempFiles.every(async (uploadFile: UploadDropItemType) => {
> also can you explain why you created the tempFiles variable?

Initially it used this.$data.files, but since that now functions solely as a reference to an array in the store, it can never be directly assigned, as that will cause an error due to modifying the store outside of a mutation. the tempFiles array exists only to be passed to loadPicture where the files are put into the array in the store

2022-02-07 21:44 UTC, cmckelvy42 commented on components/views/files/upload/Upload.vue
> +  },
In the Upload.html, it references files.length
If there isn't already an instanced array, it will throw an error as soon as it tries to render because you're referring .length on an object that doesn't exist

2022-02-07 21:48 UTC, cmckelvy42 commented on pages/index.vue
> +    this.$store.commit('chat/resetAllUploadedFiles')
We tried that, but it seems, at least as far as I can tell, that doing that simply prevents the store from persisting _when the listed mutations are made_ it does NOT stop the results of those mutations from being stored when a subsequent, non blacklisted mutation occurs. May be wrong on the reasoning, but at the very least, using the blacklist did not serve to actually wipe the files from the store on page refresh like we needed.

2022-02-08 01:29 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +  },
Reference the comment below

2022-02-08 01:54 UTC, cmckelvy42 commented on components/views/files/upload/Upload.vue
> +        return this.chat.uploadedFiles[this.$props.recipient?.address]
> try this instead: `return this.chat.uploadedFiles[this.$props.recipient?.address] ?? []`
> 
> If there's an object, it returns it. If not, return whatever is after the `??`

this doesn't work as it creates a new array outside of the store

2022-02-08 02:17 UTC, josephmcg commented on pages/index.vue
> +    this.$store.commit('chat/resetAllUploadedFiles')
I don't believe it would clear anything that was added before the non-persist config. I had to manually clear first, then it was working for me

2022-02-08 02:20 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +        return this.chat.uploadedFiles[this.$props.recipient?.address]
ah I see, you could try returning a deep copy of the array in the getter rather than the files array itself.
https://lodash.com/docs/4.17.15#cloneDeep

2022-02-08 02:23 UTC, KemoPaw commented on types/chat/chat.ts
> +export interface UploadedFiles extends UploadDropItemType {}
> Why did you extend this instead of just importing the type directly in store/chat/types.ts?

Should I still do these changes?

2022-02-08 02:55 UTC, WanderingHogan commented on types/chat/chat.ts
> +export interface UploadedFiles extends UploadDropItemType {}
no, i was just curious

2022-02-08 02:57 UTC, WanderingHogan approved these changes

2022-02-08 02:59 UTC, josephmcg approved these changes
Going to refactor later

2022-02-08 03:06 UTC, WanderingHogan commented
thank you all for sharing your thought process and putting this together

2022-02-08 04:13 UTC, stavares843 requested changes
<img width="1467" alt="Captura de ecrã 2022-02-08, às 04 11 29" src="https://user-images.githubusercontent.com/29093946/152916898-e80268df-d5ea-4f25-8cf8-e10c48140e17.png">

- go to a chat
- copy paste/drag 1 image
- change chats
- works

if you do the following
- go to a chat
- copy paste/drag 4 images
- change chat
- always crashes

doesn't happen on dev

2022-02-08 21:18 UTC, WanderingHogan commented
Good work, but we will come back to this after alpha. Closing for now, but please keep the branch

2022-02-08 21:18 UTC, closed without merging