fix(chat): increase drop field for image upload
Satellite-im/Core-PWA pull request #1382
Opened 2022-02-08 14:29 UTC by AlexZakablukov

**What this PR does** 📖
increase the available field for uploading an image to the chat, add hover effect while user drags an image over this field

**Which issue(s) this PR fixes** 🔨
[AP-315](https://satellite-im.atlassian.net/browse/AP-315)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-02-08 14:58 UTC, phillsatellite approved these changes

2022-02-08 16:48 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
> +import { bus } from '../../../../layouts/chat';
Can you change this to `import { bus } from '~/layouts/chat'` we don't use semi colons and have alias'ed `~` to the root of the project

2022-02-09 06:58 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
> +import { bus } from '../../../../layouts/chat';
Remove the EventBus

2022-02-09 06:58 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
> +  created() {
Get rid of this created block

2022-02-09 07:00 UTC, WanderingHogan commented on layouts/chat.vue
> +            <Chatbar :recipient="recipient" />
add a ref attribute to the Chatbar component, eg: `ref="chatbar"`

2022-02-09 07:01 UTC, WanderingHogan commented on layouts/chat.vue
> +        bus.$emit('dropFiles', {
instead of emitting on this global bus, you can pass directly into the child like this:

```this.$refs.chatbar?.handleUpload(e.dataTransfer?.items, e)```

where chatbar above is the ref name you chose

2022-02-09 07:02 UTC, WanderingHogan requested changes
Awesome first start! Really interesting way you went about solving this.

We aren't using an event bus and don't need to introduce that here, though. Can you check into passing the data through a ref (see comments below).

2022-02-09 09:12 UTC, AlexZakablukov commented on components/views/chat/chatbar/Chatbar.vue
> +import { bus } from '../../../../layouts/chat';
done

2022-02-09 09:12 UTC, AlexZakablukov commented on components/views/chat/chatbar/Chatbar.vue
> +  created() {
done

2022-02-09 09:12 UTC, AlexZakablukov commented on layouts/chat.vue
> +            <Chatbar :recipient="recipient" />
done

2022-02-09 09:13 UTC, AlexZakablukov commented on layouts/chat.vue
> +export const bus = new Vue()
done

2022-02-09 09:13 UTC, AlexZakablukov commented on layouts/chat.vue
> +        bus.$emit('dropFiles', {
done

2022-02-09 10:28 UTC, molimauro commented on layouts/chat.vue
> +          <DroppableWrapper :handle-drop-prop="handleDrop">
change this to `@handle-drop-prop="handleDrop"`

2022-02-09 10:28 UTC, molimauro commented on layouts/droppableWrapper.vue
> +  },
get rid of this props block

2022-02-09 10:30 UTC, molimauro commented on layouts/droppableWrapper.vue
> +      this.handleDropProp(e)
substitute this function call with `this.$emit('handle-drop-prop', e)`. In vue you can invoke parent methods with `$emit` without passing the parent method as prop :)

2022-02-09 10:32 UTC, molimauro commented on layouts/droppableWrapper.vue
> +<template>
i would move this file out of the layouts folder and put the code in `components/ui`

2022-02-09 10:33 UTC, molimauro commented
Overall i agree with Hogan, really good (and interesting) start! 💣

2022-02-09 11:43 UTC, AlexZakablukov commented on layouts/chat.vue
> +          <DroppableWrapper :handle-drop-prop="handleDrop">
done

2022-02-09 11:43 UTC, AlexZakablukov commented on layouts/droppableWrapper.vue
> +  },
done

2022-02-09 11:43 UTC, AlexZakablukov commented on layouts/droppableWrapper.vue
> +      this.handleDropProp(e)
done

2022-02-09 11:43 UTC, AlexZakablukov commented on layouts/droppableWrapper.vue
> +<template>
done

2022-02-09 13:32 UTC, molimauro approved these changes

2022-02-09 17:07 UTC, phillsatellite approved these changes

2022-02-09 17:42 UTC, WanderingHogan approved these changes

2022-02-09 18:19 UTC, stavares843 requested changes
dev
<img width="1443" alt="Captura de ecrã 2022-02-09, às 18 17 09" src="https://user-images.githubusercontent.com/29093946/153264580-7303bb48-4392-43a2-97b8-f01c7b9a93fc.png">

this branch
<img width="1467" alt="Captura de ecrã 2022-02-09, às 18 17 17" src="https://user-images.githubusercontent.com/29093946/153264590-73327516-fe3e-4d43-85f0-4022456b03e2.png">

those modals available on the chat bar are going to the middle of the screen instead of the same place where they are on dev branch

browser - Chrome

2022-02-10 09:12 UTC, AlexZakablukov commented
modals position is fixed

2022-02-10 16:49 UTC, WanderingHogan approved these changes

2022-02-10 18:04 UTC, merged