fix(nav): change the bottom nav in the mobile
Satellite-im/Core-PWA pull request #1492
Opened 2022-02-14 21:46 UTC by davidchan1219

**What this PR does** 📖

changed the bottom menu in the mobile

**Which issue(s) this PR fixes** 🔨

AP-675

2022-02-15 01:25 UTC, KemoPaw commented
<img width="368" alt="Screen Shot 2022-02-14 at 5 23 28 PM" src="https://user-images.githubusercontent.com/53127481/153974769-db63f8f6-bf89-4ed1-8c29-1d8677c7002f.png">
<img width="368" alt="Screen Shot 2022-02-14 at 5 23 28 PM" src="https://user-images.githubusercontent.com/53127481/153974816-498b8526-a9c5-4157-9088-3b627e3f8ffe.png">


Functions well, noticed that on the UI/UX example the gradient for the colors is from top --> bottom, but on this ticket it shows top left --> bottom right.

2022-02-15 05:56 UTC, KemoPaw commented on components/views/navigation/mobile/nav/Nav.less
> +      163.91deg,
Make line 5 --> '180deg'

2022-02-15 06:00 UTC, KemoPaw reviewed
Let me know if these may help!

2022-02-15 10:06 UTC, davidchan1219 commented on components/views/navigation/mobile/nav/Nav.less
> +      163.91deg,
changed

2022-02-15 10:07 UTC, davidchan1219 commented on components/views/navigation/mobile/nav/Nav.less
> +      359.95deg,
changed

2022-02-15 10:07 UTC, davidchan1219 commented on components/views/navigation/mobile/nav/Nav.less
> +      163.91deg,
changed

2022-02-15 19:56 UTC, stavares843 commented
@davidchan1219 

from liz

the bottom bar should always be active, the only time it's not is when in chat or in video calling mode. So basically if the user is chatting in any way like through dm's or group chat, or in a video call, etc. it's not displayed (cause normally the chat bar is there, or in the video, the buttons are more center of the screen or hidden)


let me know if you have any questions about it


atm the bar gets dismissed when you click on any of the icons

2022-02-15 19:58 UTC, stavares843 requested changes
added comment

2022-02-21 21:02 UTC, davidchan1219 commented
@stavares843 Just fixed the above issue.

2022-02-22 01:59 UTC, stavares843 commented
@davidchan1219 

the design was good how it was before the last commit

![image](https://user-images.githubusercontent.com/29093946/155049263-272d4dae-b5d9-4f98-961a-b4fd641061ee.png)


the only thing that needed modification was this

''the bottom bar should always be active, the only time it's not is when in chat or in video calling mode. So basically if the user is chatting in any way like through dm's or group chat, or in a video call, etc. it's not displayed (cause normally the chat bar is there, or in the video, the buttons are more center of the screen or hidden)''

2022-02-22 02:34 UTC, davidchan1219 commented
@stavares843 Now the nav bar always exists except chat page. I am not sure what is wrong. Could you tell me that in details?

2022-02-22 04:04 UTC, stavares843 commented
is possible to have the same design that had here

![image](https://user-images.githubusercontent.com/29093946/155061147-cf90839e-3c8e-4a0b-a19e-b8ca7a4b483e.png)


and having the nav bar always appearing except the chat page?

2022-02-22 19:40 UTC, phillsatellite commented
While testing I found something I don't think Sara mentioned yet, but the bottom nav has some transparency to it, verified with Liz that the Nav bar should not have any transparency 
![IMG_4654](https://user-images.githubusercontent.com/93608357/155206510-dd7e6350-be86-4dbe-958e-3940f52eec49.jpeg)

2022-02-22 20:14 UTC, davidchan1219 commented
@phillsatellite fixed the nav opacity problem

2022-02-22 21:44 UTC, stavares843 commented
i agree with @phillsatellite

2022-02-22 21:51 UTC, phillsatellite approved these changes

2022-02-23 17:34 UTC, genie-magic approved these changes

2022-02-24 15:07 UTC, Jekrimo approved these changes

2022-02-24 15:51 UTC, stavares843 commented
/rebase

2022-02-24 16:07 UTC, stavares843 approved these changes

2022-02-24 16:11 UTC, merged