feat(user program): updated the app to use the new user program
Satellite-im/Core-PWA pull request #1511
Opened 2022-02-16 07:04 UTC by iltumio

**What this PR does** 📖
Replace the previous User registration mechanism on Solana with the new User program implementation. Using a Program Derived Account for the user information, brings a lot of advantages like an easier integration with existing Solana wallets

**Which issue(s) this PR fixes** 🔨
AP-724

**Special notes for reviewers** 🗒️
🚨 BREAKING CHANGE 🚨 you have to delete and recreate your account in order to make it work.

To properly test this PR you should at least:
- register a new account
- send a new friend request to someone
- accept/deny the friend request
- remove a friend
- check around the app if the user information are properly shown (name, status message, profile picture)

**Additional comments** 🎤
I am satoshi, but don't tell anyone

2022-02-16 13:57 UTC, molimauro commented on config.ts
> +    groupchatsPrograId: 'bJhvwTYCkQceANgeShZ4xaxUqEBPsV8e1NgRnLRymxs',
just typos here `usersPrograId` -> `usersProgramId` and `groupchatsPrograId` -> `groupchatsProgramId`

2022-02-16 14:07 UTC, Jekrimo approved these changes

2022-02-16 14:10 UTC, molimauro commented
Just 2 typos, ok other than that 💥

2022-02-16 16:40 UTC, WanderingHogan approved these changes

2022-02-17 14:00 UTC, stavares843 commented
/rebase

2022-02-17 18:53 UTC, stavares843 requested changes
![image](https://user-images.githubusercontent.com/29093946/154550702-2b8dc803-1312-4c1a-aa1f-916d54435bb1.png)

your branch after sign up with the new account

![image](https://user-images.githubusercontent.com/29093946/154550721-d68704ea-5c4e-43c8-a372-11f521205256.png)

same flow on dev branch locally works fine

2022-02-17 23:10 UTC, phillsatellite commented
Tested: Crash is gone but after starting on 2 new accounts seems when you try to send a friend request you get "hmm, we couldn't find that address" verified issue does not happen on local dev 

https://user-images.githubusercontent.com/93608357/154586991-872b47d8-4a0e-4fb7-aa88-78cffc107664.mov

2022-02-18 16:11 UTC, phillsatellite approved these changes

2022-02-18 17:59 UTC, stavares843 requested changes
made 2 accounts new on chrome
user A is non private browser
user B is private browser
user A was able to add user B
user A when inviting user B, user B appears on the outgoing requests on user A
<img width="623" alt="Captura de ecrã 2022-02-18, às 17 57 35" src="https://user-images.githubusercontent.com/29093946/154736779-2c1de1e3-f697-495c-8595-d02725c1f672.png">

but invite from User A doesn't appear on user B side
<img width="1394" alt="Captura de ecrã 2022-02-18, às 17 57 56" src="https://user-images.githubusercontent.com/29093946/154736837-e0d24c80-84d4-4e55-a05a-b68845b58c0e.png">

also, if user B tries to add anyone says ''your account is not ready''

![image](https://user-images.githubusercontent.com/29093946/154736882-29701a22-3121-4806-bd23-500cc75ee741.png)

I have a .har file of the request returning 200 from solana, let me know if you want that

2022-02-24 15:02 UTC, iltumio commented
made a lot of changes. It looks like the issues disappeared after refactoring the flow a little bit. I removed the prerequisites Vuex module since there were redundant information about the readiness of different features of the app

2022-02-24 15:05 UTC, Jekrimo approved these changes

2022-02-24 16:43 UTC, phillsatellite commented
Hi Manuel I'm sorry to come with another issue ☹️  I tested, started from 2 new profiles, added each other and got "errors.friends.textile_not_initialized" attaching a photo of console as well 
<img width="1728" alt="Screen Shot 2022-02-24 at 11 41 16 AM" src="https://user-images.githubusercontent.com/93608357/155568536-12177e96-c973-4836-a9b2-bf0f37fa2c6a.png">
<img width="1728" alt="Screen Shot 2022-02-24 at 11 41 20 AM" src="https://user-images.githubusercontent.com/93608357/155568553-b887df81-15ec-48bf-8466-b1201a617860.png">

2022-02-25 15:10 UTC, phillsatellite approved these changes

2022-02-25 16:14 UTC, WanderingHogan commented on components/views/friends/add/Add.vue
>  import ServerProgram from '~/libraries/Solana/ServerProgram/ServerProgram'
i don't think we use this anymore

2022-02-25 17:34 UTC, stavares843 approved these changes

2022-02-25 17:35 UTC, merged