feat(groupchatsProgram): create a class to interact with the group chat program
Satellite-im/Core-PWA pull request #1535
Opened 2022-02-17 15:20 UTC by nickjjang

**What this PR does** 📖
Create a class to interact with the Group Chat program

**Which issue(s) this PR fixes** 🔨
AP-658

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-02-17 17:08 UTC, iltumio requested changes

2022-02-17 17:08 UTC, iltumio commented on config.ts
> +    groupchatsPrograId: 'bJhvwTYCkQceANgeShZ4xaxUqEBPsV8e1NgRnLRymxs',
typo: groupchatsPrograId -> groupchatsProgra**m**Id

2022-02-17 17:08 UTC, iltumio commented on libraries/Solana/SolanaWallet.ts
> +import { Keypair, PublicKey, Transaction } from '@solana/web3.js'
this file is no longer needed

2022-02-19 01:09 UTC, phillsatellite commented
Tested: Seems the mockup for the groupchats in the sidebar is missing so user cant navigate into the group chat
![Screen Shot 2022-02-18 at 8 00 56 PM (2)](https://user-images.githubusercontent.com/93608357/154779826-a38fc0c7-c2f6-4903-bea8-751014b5226b.png)

2022-02-21 18:28 UTC, stavares843 commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +   * @param recipient: receipient address
typo - receipient

2022-02-21 18:43 UTC, WanderingHogan commented
@nickjjang can you check why this PR breaks being able to see the hard coded group chats? It doesn't look like you altered anything in the ui at all.

2022-02-21 18:53 UTC, WanderingHogan commented
/rebase

2022-02-21 19:46 UTC, phillsatellite approved these changes

2022-02-21 22:16 UTC, merged