fix(webrtc): hangs up call when accepting a new call
Satellite-im/Core-PWA pull request #1682
Opened 2022-02-24 00:11 UTC by jpanay

**What this PR does** 📖
Stops users from being able to be in 2 calls by hanging up current call when accepting a new call
**Which issue(s) this PR fixes** 🔨
AP-750

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-02-24 17:39 UTC, phillsatellite commented
Tested: Tested a couple times and tried starting from a new account but was still able to be in 2 calls at once 

https://user-images.githubusercontent.com/93608357/155577737-87998717-75be-4169-909e-91510d888aa3.mov

2022-02-24 18:12 UTC, jpanay commented
> Tested: Tested a couple times and tried starting from a new account but was still able to be in 2 calls at once 
> 
> 
> 
> https://user-images.githubusercontent.com/93608357/155577737-87998717-75be-4169-909e-91510d888aa3.mov
> 
> 
> 
> 
> 
> 

Hmm, I'll do some investigating

2022-03-02 00:11 UTC, stavares843 commented
@jpanay any news? 💥

2022-03-02 14:04 UTC, stavares843 commented
thanks 🎉

2022-03-04 20:57 UTC, stavares843 commented
/rebase

2022-03-07 16:24 UTC, WanderingHogan commented on components/views/media/Media.vue
> +          friend.activeChat && friend.address === this.webrtc.activeCall,
Can you move the 'friend.activeChat' outside of the find method, no sense in running the find if activeChat is already ''

2022-03-07 16:26 UTC, WanderingHogan requested changes
please check the comments and let me know

2022-03-08 16:28 UTC, jpanay commented on components/views/media/Media.vue
> +          friend.activeChat && friend.address === this.webrtc.activeCall,
We could do if activechat === activecall but it's necessary to have both

2022-03-10 16:15 UTC, phillsatellite commented
/rebase

2022-03-10 16:49 UTC, phillsatellite approved these changes

2022-03-10 19:50 UTC, WanderingHogan approved these changes

2022-03-10 20:04 UTC, stavares843 approved these changes

2022-03-10 20:04 UTC, merged