fix(chatbar): fixed is typing but
Satellite-im/Core-PWA pull request #1724
Opened 2022-02-25 15:50 UTC by ThomBos

**What this PR does** 📖
Fixes persistent "is typing" bug
**Which issue(s) this PR fixes** 🔨
AP-830

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-02-25 21:58 UTC, stavares843 commented on components/views/chat/chatbar/Chatbar.vue
> +     * @description Clears typing event immediatly
immediately

2022-02-28 12:23 UTC, ThomBos commented on components/views/chat/chatbar/Chatbar.vue
> +     * @description Clears typing event immediatly
> immediately

i go correct immediatly, sorry 🤣

2022-03-01 01:42 UTC, stavares843 commented on components/views/chat/chatbar/Chatbar.vue
> +     * @description Clears typing event immediatly
🤣

2022-03-01 05:40 UTC, WanderingHogan requested changes
This is very clean and a great attempt, but i dont think it solves the issue. I think we need to look at where this.debounceTypingStop(this) should go, so on the receiving side it tries to end the typing message if it doesn't hear anything back because the person you are chatting with closed the chat in the middle of typing

2022-03-01 09:01 UTC, ThomBos commented
> This is very clean and a great attempt, but i dont think it solves the issue. I think we need to look at where this.debounceTypingStop(this) should go, so on the receiving side it tries to end the typing message if it doesn't hear anything back because the person you are chatting with closed the chat in the middle of typing
Trying doing it this way! 👍 
By the way the main problem is when CTRL or META key are pressed... seems like the tab get detached and it doesn't receive any state update. Since we emit the chat event from the one who texts, we don't get the update and it stays "is typing".

2022-03-01 09:22 UTC, ThomBos commented
> This is very clean and a great attempt, but i dont think it solves the issue. I think we need to look at where this.debounceTypingStop(this) should go, so on the receiving side it tries to end the typing message if it doesn't hear anything back because the person you are chatting with closed the chat in the middle of typing

What if i add a setTimeout (which calls the debounce function) to the typing function?

2022-03-04 14:22 UTC, iltumio commented
we should reset the typing state even when we receive a disconnection event. On the recipient side we should automatically remove the typing notification if we do not receive a typing event within a certain amount of time

2022-03-04 14:49 UTC, ThomBos commented
> we should reset the typing state even when we receive a disconnection event. On the recipient side we should automatically remove the typing notification if we do not receive a typing event within a certain amount of time

that's exactly what this modification does (after 3s the typing state is cleared), but it can't be done from the recipient since we manage the typing state from the sender

2022-03-04 20:37 UTC, WanderingHogan commented
/rebase

2022-03-04 20:55 UTC, stavares843 commented
/rebase

2022-03-07 21:14 UTC, phillsatellite approved these changes

2022-03-07 21:17 UTC, stavares843 commented
/rebase

2022-03-09 17:47 UTC, ThomBos commented
Need to wait for Hogan's update for the peer connections to merge this PR

2022-03-10 14:40 UTC, stavares843 commented
thanks for the update @ThomBos 🔨

2022-03-11 15:07 UTC, ThomBos commented
@stavares843 can you please check if there're still conflict with cypress? 
By the way, i started back from dev and applied new update following the Hogan's one

2022-03-11 17:49 UTC, WanderingHogan approved these changes

2022-03-11 18:56 UTC, phillsatellite commented
Tested again after rebase and it seems like if the user types very fast, it'll stop recognizing that they are typing and will just say connected until the user sends message and starts typing a new one 

https://user-images.githubusercontent.com/93608357/157933802-9daa3b1b-a083-43a1-90e3-6d419303c3aa.mov

2022-03-11 19:17 UTC, ThomBos commented
> Tested again after rebase and it seems like if the user types very fast, it'll stop recognizing that they are typing and will just say connected until the user sends message and starts typing a new one
> 
>  fast.typing.mov

i don't think that is't possible to have the perfect solution for this with the webrtc state we're currently using... 
The only thing i can do, is increasing the timer that turns off the typing state and decreasing the debounce function that sets off the typing state from sender's side (for updating more times the state while typing and having a more precise state).

Actual settings are:

sender                  receiver
0.5s                       5s   (inactivity.... or too much activity, like this case)

The main problem is that the sender doesn't update his state when is typing too fast and the receiver starts the inactivity timer if doesn't detect state changes (this is because refreshing page and disconnections are slow to detect... about 1 minute).

If you have any suggestion, i'd like to read that!! Anything that can improve this code! 💥

2022-03-15 07:47 UTC, molimauro commented on components/views/chat/chatbar/Chatbar.vue
> +    }, 2000),
I'd put this `2000` in config

2022-03-15 07:48 UTC, molimauro commented on store/webrtc/actions.ts
> +      }, 2000)
And then multiply here the config const * 3. Normally triple time is a good sign that connection dropped

2022-03-15 16:25 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/158424764-86533ba4-5936-4a64-a5ec-8b3020d56af9.mov

user A writes to user B
user A stops writing
still shows on user B for couple seconds that user A is typing but it isn't

2022-03-15 16:30 UTC, molimauro commented
@stavares843 we send a "is_typing" event once every 2 seconds and if within triple this time (so 6 seconds of course) we did not receive another event we assume the communication stopped, thats why is not immediate. We can lower the 6 seconds threshold its just a matter of preference. Sorry for not having specified this before

2022-03-15 17:45 UTC, stavares843 commented
thanks for clarifying @molimauro 🔨

2022-03-16 10:02 UTC, ThomBos commented
what should i change here?

2022-03-16 14:09 UTC, stavares843 approved these changes

2022-03-16 14:09 UTC, merged