feat(files): file type support for common image and archive types
Satellite-im/Core-PWA pull request #1742
Opened 2022-02-28 04:03 UTC by josephmcg

**What this PR does** 📖
- type support for common file types
- switch type check on import to support more dynamic enums
- add basic file types to enum

**Which issue(s) this PR fixes** 🔨
AP-906

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-02-28 20:24 UTC, stavares843 commented
/rebase

2022-03-01 09:45 UTC, molimauro approved these changes

2022-03-02 00:48 UTC, stavares843 requested changes
this branch

![image](https://user-images.githubusercontent.com/29093946/156273386-bcdb89c0-2e11-49b3-a7b6-a5ced7c71134.png)

dev.satellite.one

![image](https://user-images.githubusercontent.com/29093946/156273392-809e25dc-b18e-4ea6-8966-4a341eacc308.png)

preview is not showing for .PNG images but works on dev

2022-03-02 01:41 UTC, stavares843 approved these changes

2022-03-02 01:42 UTC, merged