fix(chat): scroll through glyphs/emoji
Satellite-im/Core-PWA pull request #1766
Opened 2022-03-02 10:11 UTC by vimercati-samir

What this PR does 📖
Fix scroll through glyphs/emoji

Which issue(s) this PR fixes 🔨
AP-889

Special notes for reviewers 🗒️

Additional comments 🎤

2022-03-02 17:42 UTC, Jekrimo approved these changes

2022-03-02 19:30 UTC, vimercati-samir commented on components/views/chat/enhancers/glyphs/Glyphs.less
> +    } */
removed it in commit a60d46b8d74545807866836d6f658d9003cbea66

2022-03-03 01:25 UTC, josephmcg requested changes
This breaks the virtual list. change the value of :keeps to something lower. I believe it needs a fixed height in order to work, that's why I added a css scrollbar instead
https://github.com/tangbc/vue-virtual-scroll-list

2022-03-03 15:26 UTC, vimercati-samir commented
> This breaks the virtual list. change the value of :keeps to something lower. I believe it needs a fixed height in order to work, that's why I added a css scrollbar instead https://github.com/tangbc/vue-virtual-scroll-list


https://user-images.githubusercontent.com/52865716/156594654-f92f1424-3248-4777-9099-d9cc3b0f5233.mp4

I think it's working properly, I manually added more sticker packs (38 to be precise) and I left the "keeps" parameter to 15 and as you can see in the DOM on the right side of the video the list items are always 15 and on scroll they update, is this behavior correct and perhaps it didn't seem to work because the "keeps" threshold was higher than the number of sticker packs or is still wrong?

2022-03-03 19:21 UTC, phillsatellite approved these changes

2022-03-04 01:13 UTC, josephmcg approved these changes
I only tested changing :keeps to 4 with the usual number of packs. It breaks in that instance.
However, that's not a realistic use case for our app. We would likely keep it higher, more similar to your example. I guess it's alright then.

Please confirm that it's loading every pack that you added

2022-03-04 01:32 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/156681976-fff9c7ee-a91d-46e2-903b-2844b6fe62b7.mov


the scroll is more fluid on dev compared with this branch

2022-03-14 08:51 UTC, vimercati-samir commented
> any news? 🔨

fixing and closing it now

2022-03-14 10:56 UTC, vimercati-samir commented
> Gravacao.do.ecra.2022-03-04.as.01.30.44.mov 
> the scroll is more fluid on dev compared with this branch
> 
> Chrome, macOS

Should be resolved in commit db62e22bf598bb2d1d11529671fc75561eacc076

2022-03-15 08:49 UTC, josephmcg approved these changes

2022-03-15 16:31 UTC, stavares843 approved these changes

2022-03-15 16:32 UTC, merged