fix(profile): fix close button issue on ios device
Satellite-im/Core-PWA pull request #1795
Opened 2022-03-04 11:52 UTC by genie-magic

**What this PR does** 📖
Close icon in profile is sitting in mobile status bar and causes user from not being able to close profile modal
**Which issue(s) this PR fixes** 🔨

AP-991

2022-03-04 13:56 UTC, Jekrimo approved these changes

2022-03-04 14:34 UTC, iltumio requested changes

2022-03-04 14:34 UTC, iltumio commented on components/views/user/profile/Profile.less
> +      top: 2.5rem !important;
is there a way to avoid the use of `!important` directive?

2022-03-04 14:34 UTC, iltumio commented on components/views/user/profile/Profile.less
> +      top: 2.5rem !important;
is there a way to avoid the use of `!important` directive?

2022-03-09 09:01 UTC, genie-magic commented on components/views/user/profile/Profile.less
> +      top: 2.5rem !important;
@iltumio  I removed it.

2022-03-09 09:01 UTC, genie-magic commented on components/views/user/profile/Profile.less
> +      top: 2.5rem !important;
@iltumio  I removed it.

2022-03-09 22:52 UTC, phillsatellite commented
/rebase

2022-03-09 23:22 UTC, phillsatellite approved these changes

2022-03-09 23:23 UTC, stavares843 approved these changes

2022-03-09 23:27 UTC, merged