feat(privacy): change the title of the privacy page and add some components
Satellite-im/Core-PWA pull request #1815
Opened 2022-03-08 15:08 UTC by davidchan1219

**What this PR does** 📖

change the title of the privacy page and add some components

**Which issue(s) this PR fixes** 🔨

AP-1014

2022-03-08 15:34 UTC, stavares843 commented on locales/en-US.js
> +      newTitle1: 'Signaling Servers',
instead of newTitle 1 and newTitle2 we should update the current locales instead of adding new ones if we are not gonna use the old ones

2022-03-08 15:38 UTC, stavares843 requested changes
added comment

2022-03-08 15:38 UTC, stavares843 commented on locales/en-US.js
> +        'Enter your http, udp, or websocket URL for your signaling server here’, show a warning if the input is not a valid http, udp, ws url (ip or domain name).',
the '', show a warning if the input is not a valid http, udp, ws url (ip or domain name).','' is not a locale
are just instructions from hogan

what hogan meant was
- how a warning if the input is not a valid http, udp, ws url (ip or domain name)

like red copy as the warning if the input on the input text field is not valid

2022-03-08 15:39 UTC, stavares843 requested changes
<img width="1357" alt="Captura de ecrã 2022-03-08, às 15 35 40" src="https://user-images.githubusercontent.com/29093946/157271768-fc6f0449-7d39-415c-bb7c-f55a5302e1e4.png">


the dropdown is small before user selects any option

also is not aligned on the left side

2022-03-08 15:39 UTC, stavares843 requested changes
<img width="1249" alt="Captura de ecrã 2022-03-08, às 15 35 54" src="https://user-images.githubusercontent.com/29093946/157271869-c6e04169-de11-4775-a37b-6807d3ec4ad5.png">

can you add a locale for the placeholder?

2022-03-08 15:42 UTC, stavares843 requested changes
<img width="1335" alt="Captura de ecrã 2022-03-08, às 15 41 32" src="https://user-images.githubusercontent.com/29093946/157272213-e51aaa94-5078-4c48-b341-91bbe734a5fa.png">

it gets cut off when we add a huge name

also, there's no limit on that field on the privacy page on sign up

2022-03-08 17:36 UTC, davidchan1219 commented
@stavares843 I've just fixed the above issues.

2022-03-08 17:38 UTC, stavares843 commented
thanks 🔨 

will check

2022-03-08 17:54 UTC, stavares843 requested changes
<img width="714" alt="Captura de ecrã 2022-03-08, às 17 53 25" src="https://user-images.githubusercontent.com/29093946/157296901-6971c8de-3003-4448-95c0-3e5edd381676.png">

when i add wss://www.example.com/socketserver it always say its invalid

2022-03-08 17:54 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/157296950-5de199e0-d07a-4bdc-98e3-123a00062fb5.mov

the invalid input error message only clears out after changing tabs

2022-03-08 18:00 UTC, stavares843 requested changes
<img width="945" alt="Captura de ecrã 2022-03-08, às 17 59 32" src="https://user-images.githubusercontent.com/29093946/157297909-29d4e1a8-7595-4869-a7e1-a103a2a49d14.png">

can we remove the caps lock on the error message here?

2022-03-09 10:03 UTC, davidchan1219 commented
@stavares843 Could you please check the update again?

2022-03-09 14:30 UTC, stavares843 commented
will check 🔨

2022-03-09 17:56 UTC, phillsatellite commented
Tested: Found a few other issues so far if i come across anymore will comment 

if I type "eee" the error message will appear but add onto it the error message goes away. So when I have "eee.efefesoijgs" no error message appears. It should appear the entire time since eee is a invalid source. 

https://user-images.githubusercontent.com/93608357/157501815-c98c850b-b0b0-4bdd-90d2-3719c7c06c62.mov

Another issue I found is, if a users URL is longer than the text box given it should have "..." at the end of it

https://user-images.githubusercontent.com/93608357/157502029-4c94e759-c8fa-4519-aecf-f5afb6273c1c.mov

2022-03-09 19:52 UTC, stavares843 commented
yes please address those as well @davidchan1219 thanks 🎉

2022-03-10 14:06 UTC, davidchan1219 commented
@phillsatellite I tried to make the better url validation function. but the current function is good.
And fixed the second issue.

2022-03-10 14:31 UTC, stavares843 commented
@davidchan1219 can we fix the first issue as well? the validation is not working properly on Phil's video

2022-03-10 16:34 UTC, stavares843 commented
![image](https://user-images.githubusercontent.com/29093946/157710284-273bffaf-10b9-4f5e-a95f-cf47dbd75c39.png)


atm doesn't seem there's any validation on the field 


example I added a emojin and no warning appears


could you take a look pls? thanks! 🎉

2022-03-10 16:41 UTC, davidchan1219 commented
@stavares843 Sorry, When I change the validation function, I lost one problem. Just fixed. 
Please check again now.

2022-03-10 16:56 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/157714653-0878573a-8df7-4b1d-b0b7-427c2a9ed146.mov

https://user-images.githubusercontent.com/29093946/157714676-7c4b6d58-4828-4f9c-bb99-050d55deb3e2.mov

user is still writing but is already returning invalid error, is there a way to improve that behavior? @davidchan1219

2022-03-10 17:07 UTC, davidchan1219 commented
@stavares843 We implement the validation function when change function runs. So the current status is not bad. 
But I will reference your review and find the better solution.

2022-03-10 17:11 UTC, davidchan1219 commented
@WanderingHogan Could you check the current validation feature and give me the innovative idea?

2022-03-10 17:17 UTC, stavares843 commented on libraries/ui/Common.ts
> +      '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,63}|' +
can you edit from ''2'' to ''3''? to allow the ''ws'' one as well, thanks 🎉

2022-03-10 17:58 UTC, WanderingHogan commented
Sorry I am getting to this so late

![image](https://user-images.githubusercontent.com/2993032/157724975-c8c15748-892a-484f-9e96-3fe84d15146c.png)

From the ticket, I meant that I wanted you to add a section to the pages, I should have clarified underneath the section with the toggles, something more similar to this:
![image](https://user-images.githubusercontent.com/2993032/157725696-e071b26b-c3cd-40b4-a379-df7d682ec52b.png)

2022-03-11 01:01 UTC, stavares843 requested changes
@davidchan1219 please revert the submodule changes


this is deleting both android and electron submodules from the repo

2022-03-11 01:21 UTC, stavares843 commented
<img width="1341" alt="Captura de ecrã 2022-03-11, às 01 20 45" src="https://user-images.githubusercontent.com/29093946/157783408-2a33cae7-666d-4b97-b2a4-59fa86967351.png">

the error is hidden, this view has no scroll when the user adds a invalid format on the input field

2022-03-11 01:22 UTC, stavares843 commented
<img width="1303" alt="Captura de ecrã 2022-03-11, às 01 21 52" src="https://user-images.githubusercontent.com/29093946/157783499-9ab3884d-d412-4fbf-aa7d-8f7d0b86cddd.png">

when you add a server and change tabs, the server is there

if you add a server and refresh the page, the server you added manually disappears

2022-03-11 13:27 UTC, davidchan1219 commented
@stavares843 I found the first one. but I made to not save the url, if that is not valid. Am I wrong?

2022-03-11 20:36 UTC, stavares843 requested changes
@davidchan1219 please revert the submodule changes

this is deleting both android and electron submodules from the repo

2022-03-11 21:18 UTC, stavares843 commented
<img width="502" alt="Captura de ecrã 2022-03-11, às 21 17 26" src="https://user-images.githubusercontent.com/29093946/157967901-26d49f01-efdb-4ed8-b990-222f6a1e91a1.png">
<img width="498" alt="Captura de ecrã 2022-03-11, às 21 17 32" src="https://user-images.githubusercontent.com/29093946/157967907-a129be62-87e4-476c-bdb1-a60224553cb2.png">

on the privacy page on sign up now has a scroll but its above the copy when scrolling and also the button saying continue on the bottom lacks padding

on dev is fine

2022-03-11 21:21 UTC, stavares843 commented
if you add 2049 chats says invalid format
<img width="1347" alt="Captura de ecrã 2022-03-11, às 21 20 02" src="https://user-images.githubusercontent.com/29093946/157968735-54049367-7e74-48c6-9b1c-fd61b073e344.png">

but if you add 2048 no errors appear


and is not a format issue so that error shouldn't appear

2022-03-11 22:24 UTC, WanderingHogan commented
closing for https://github.com/Satellite-im/Core-PWA/pull/2308

2022-03-11 22:24 UTC, closed without merging