feat(searchIndex): index conversation messages, implement basic search
Satellite-im/Core-PWA pull request #1817
Opened 2022-03-08 18:35 UTC by aewing

**What this PR does** 📖
- Adds separate indexeddb index for conversationMessages
- Adds searchConversations action in textile store
- Updates Search to leverage searchConversations
- Temporarily disables advanced search filters
**Which issue(s) this PR fixes** 🔨
[AP-978](https://satellite-im.atlassian.net/browse/AP-978)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-03-08 19:58 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/157314998-0476cc2b-d79d-4032-98a3-bca2796ad9a7.mov

2022-03-08 20:11 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/157316967-144cd807-9279-4764-a67c-9ece6890325e.mov

if you send a message saying test001

and then you search the message

you have the users dropdown on the search filters

if you erase the user, it no longer appears on that dropdown

2022-03-08 20:14 UTC, stavares843 requested changes
sometimes searching by the message - test001 returns results

<img width="815" alt="Captura de ecrã 2022-03-08, às 20 09 52" src="https://user-images.githubusercontent.com/29093946/157317397-8203bbd5-c161-4431-aaea-d16b82b610fa.png">

sometimes when refreshing the browser and searching again, no results appear

<img width="1407" alt="Captura de ecrã 2022-03-08, às 20 13 22" src="https://user-images.githubusercontent.com/29093946/157317463-35cb6455-b630-4b1b-b36f-498854985845.png">



same keyword, same chat, same browser

no useful info on browser log

2022-03-08 20:16 UTC, stavares843 requested changes
<img width="813" alt="Captura de ecrã 2022-03-08, às 20 15 43" src="https://user-images.githubusercontent.com/29093946/157317696-520678f8-7112-4dc0-9367-16467e02de32.png">

you mentioned on the PR description ''Temporarily disables advanced search filters''

would that include the more filters button? clicking on it doesn't do anything, so if thats not gonna be implemented should probably be hidden

2022-03-08 20:19 UTC, stavares843 requested changes
<img width="804" alt="Captura de ecrã 2022-03-08, às 20 17 31" src="https://user-images.githubusercontent.com/29093946/157317937-682128ba-7794-4f02-aa57-4c72072f685e.png">

it says on the top of the modal - 5 results

but then says 1 Results - and only displays one

is this expected to be working? considering the basic search would include the needed data to display those counts on the top

2022-03-08 20:25 UTC, stavares843 requested changes
this is not fetching the messages properly

https://user-images.githubusercontent.com/29093946/157318916-ed2f1db8-77ea-4b61-8c41-8cb8fdd3652e.mov


send a message saying test008
search
no results
search for one thats already there
results appear
search again for the test008
results appear

2022-03-08 20:27 UTC, stavares843 requested changes
<img width="1398" alt="Captura de ecrã 2022-03-08, às 20 27 07" src="https://user-images.githubusercontent.com/29093946/157319269-3c37f844-6bb9-41aa-943b-5ea6533ced93.png">

do we allow emoji search? i tried a couple different flows to see if would fetch the emoji, but never shows the emoji message on the search result

2022-03-08 20:33 UTC, stavares843 requested changes
<img width="819" alt="Captura de ecrã 2022-03-08, às 20 32 44" src="https://user-images.githubusercontent.com/29093946/157320095-26d54b64-2b55-4e97-b31c-5569453972df.png">

if you search for a bigger keyword such as 

8WThokDUkWXvh5FpGUfUvJCfPMXzw5PcxHN7NQ7RNjm18WThokDUkWXvh5FpGUfUvJCfPMXzw5PcxHN7NQ7RNjm18WThokDUkWXvh5FpGUfUvJCfPMXzw5PcxHN7NQ7RNjm18WThokDUkWXvh5FpGUfUvJCfPMXzw5PcxHN7NQ7RNjm18WThokDUkWXvh5FpGUfUvJCfPMXzw5PcxHN7NQ7RNjm18WThokDUkWXvh5FpGUfUvJCfPMXzw5PcxHN7NQ7RNjm18WThokDUkWXvh5FpGUfUvJCfPMXzw5PcxHN7NQ7RNjm1

the layout breaks, do we want to address front end fixes on a different PR?

2022-03-08 20:35 UTC, stavares843 requested changes
<img width="1062" alt="Captura de ecrã 2022-03-08, às 20 34 48" src="https://user-images.githubusercontent.com/29093946/157320372-22ce0ecf-cb07-48a6-8979-736d15a3ada9.png">

any other different alphabets such as telugu - తెలుగు are those expected to be searchable? 

so far numbers and letters appears, but not chars from other alphabets such as తెలుగు

2022-03-08 20:37 UTC, stavares843 requested changes
<img width="806" alt="Captura de ecrã 2022-03-08, às 20 37 02" src="https://user-images.githubusercontent.com/29093946/157320672-1403568e-b9ca-4355-a0d3-89fdf2fcb505.png">

if you send ''test__01'' and then search for that keyword, appears 1 results but no results are displayed

2022-03-08 20:39 UTC, stavares843 requested changes
<img width="1410" alt="Captura de ecrã 2022-03-08, às 20 38 17" src="https://user-images.githubusercontent.com/29093946/157320877-fa2e3085-1287-4373-b973-13f645c357f4.png">

crash if you search by "url" including the " as well - only crashed once, not reproducible

2022-03-08 20:44 UTC, stavares843 requested changes
<img width="1404" alt="Captura de ecrã 2022-03-08, às 20 43 13" src="https://user-images.githubusercontent.com/29093946/157321755-4b1ef001-b3ee-4bdd-a248-ded332489f1a.png">


crash when searching by a hyphen - 

always reproducible

2022-03-08 20:46 UTC, stavares843 requested changes
<img width="790" alt="Captura de ecrã 2022-03-08, às 20 45 41" src="https://user-images.githubusercontent.com/29093946/157322048-f98ac5ad-2a2f-4dd6-b208-96ecf2cf7e67.png">

if you search by * just displays every message the user sent even if any of that has a *

2022-03-08 20:48 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/157322278-a5d49818-3eca-4716-8e2e-022bdaba5247.mov


if you send a video you notice that on the search results appears as 

{
  "url": "https://hub.textile.io/ipfs/bafybeidjxlrsxoj7qs5wr2pysz5ltxrpblowx3burpl5tzsg3bv7bx3nd4/156241927-5e422647-dc30-45bd-9586-eef13ceb3430.mov",
  "name": "156241927-5e422647-dc30-45bd-9586-eef13ceb3430.mov",
  "size": 66177558,
  "type": "video/quicktime"
}

2022-03-08 20:52 UTC, stavares843 requested changes
if you send test001 and test001漢語

and then search

test001

he finds both
<img width="808" alt="Captura de ecrã 2022-03-08, às 20 51 25" src="https://user-images.githubusercontent.com/29093946/157322936-b87d4cea-4e75-457d-bf12-3659368d1395.png">

search test001漢語

no results
<img width="804" alt="Captura de ecrã 2022-03-08, às 20 51 32" src="https://user-images.githubusercontent.com/29093946/157322967-da19b01c-135d-4a39-9861-8fb80d66c208.png">

even if the result was already fetched on the previous search

2022-03-08 20:58 UTC, stavares843 requested changes
<img width="1033" alt="Captura de ecrã 2022-03-08, às 20 57 46" src="https://user-images.githubusercontent.com/29093946/157323823-4942a1d8-6d73-4131-9db5-698c69ddbecc.png">

<img width="1043" alt="Captura de ecrã 2022-03-08, às 20 57 53" src="https://user-images.githubusercontent.com/29093946/157323832-c12da2bc-8500-4bc7-a697-1ab9564a171c.png">

a@a.com works but @a.com no results are displayed

2022-03-08 21:03 UTC, stavares843 requested changes
<img width="1412" alt="Captura de ecrã 2022-03-08, às 21 03 22" src="https://user-images.githubusercontent.com/29093946/157324649-a54f0053-3417-45dc-be41-0c811216661c.png">

crash when searching by ?search !Func^tionality} 

always reproducible

2022-03-08 21:05 UTC, stavares843 requested changes
<img width="1404" alt="Captura de ecrã 2022-03-08, às 21 04 59" src="https://user-images.githubusercontent.com/29093946/157324872-6d743db6-2c02-43a8-90d8-f537efd6f599.png">

crash when you search for more than the allowed chars number

2022-03-08 21:06 UTC, stavares843 commented
thanks for adding the log, will let you know if triggers something 🔨

2022-03-08 21:10 UTC, aewing commented
ok there is a lot of feedback on this. 
I have pushed up a change to also temporarily disable the from and mentions filter.
I have also added a catch for unexpected search syntax that will retry without punctuation.

To clarify the intent of this ticket, we're just setting up the indexeddb indexes and search index here, there is a followup ticket to clean up the UI, where I will address the filters and search results - https://satellite-im.atlassian.net/browse/AP-983

2022-03-08 21:15 UTC, stavares843 commented
yes, thats why i ignored most of the UI things and focused the feedback mostly on the search itself

is there anything search related (except UI fixes), that's not expected to be addressed within this PR?

2022-03-08 21:39 UTC, stavares843 commented
I can add tickets for whatever we don't want to address here including improving the search itself

at least the crashes should be addressed

2022-03-08 21:50 UTC, aewing commented
> Gravacao.do.ecra.2022-03-08.as.19.56.46.mov
> 
> crash when performing the above flow
> 
> also, can we ditch the tauro nix stuff that appears there? or do you want to address that separately? tauro nix is from the mock

crashes should be addressed, filters should be hidden

2022-03-08 21:51 UTC, aewing commented
> Gravacao.do.ecra.2022-03-08.as.20.10.10.mov
> 
> if you send a message saying test001
> 
> and then you search the message
> 
> you have the users dropdown on the search filters
> 
> if you erase the user, it no longer appears on that dropdown
> 
> and you need to refresh the page and search again in order to have the search results again after the previous action - erasing the user from the users dropdown

ui issue, will be addressed in a future ticket

2022-03-08 21:52 UTC, aewing commented
> sometimes searching by the message - test001 returns results
> 
> <img alt="Captura de ecrã 2022-03-08, às 20 09 52" width="815" src="https://user-images.githubusercontent.com/29093946/157317397-8203bbd5-c161-4431-aaea-d16b82b610fa.png">
> 
> sometimes when refreshing the browser and searching again, no results appear
> 
> <img alt="Captura de ecrã 2022-03-08, às 20 13 22" width="1407" src="https://user-images.githubusercontent.com/29093946/157317463-35cb6455-b630-4b1b-b36f-498854985845.png">
> 
> same keyword, same chat, same browser
> 
> no useful info on browser log

this is an issue somewhere in the UI layer and will be addressed in a followup

2022-03-08 21:54 UTC, aewing commented
> <img alt="Captura de ecrã 2022-03-08, às 20 45 41" width="790" src="https://user-images.githubusercontent.com/29093946/157322048-f98ac5ad-2a2f-4dd6-b208-96ecf2cf7e67.png">
> 
> if you search by * just displays every message the user sent even if any of that has a *

the current implementation of search introduces lunr which uses the asterisk to match wildcards and some other punctuation for searching. I'm not sure how we want to address this, perhaps we won't use the `search` function in the future.

2022-03-08 21:55 UTC, stavares843 commented
sounds good

added all the rest into other tickets

2022-03-08 22:05 UTC, stavares843 commented
are you gonna address this crash as well? 🔨 

https://github.com/Satellite-im/Core-PWA/pull/1817#pullrequestreview-903582904

2022-03-09 16:42 UTC, WanderingHogan commented
lets hit pause on these changes until I have a chance to look at it.

2022-03-09 21:17 UTC, WanderingHogan commented on components/interactables/Search/Input/Input.html
> +  <div :class="{'search-box': true, focus: isFocus}">
can you add 'class="disabled"' here after the :class

2022-03-09 21:18 UTC, WanderingHogan commented on components/interactables/Search/Input/Input.html
> +      @mousedown="setFocus"
can you comment out the mousedown setFocus function, something like `@mousedown="/* setFocus disable-temporariliy until search re-work */"

2022-03-09 21:19 UTC, WanderingHogan commented on components/interactables/Search/Input/Input.html
> +      @mousedown="setFocus"
to elaborate - we want to prevent search from being tested until a future pull request where we re-work this component to be what we want it to be

2022-03-09 21:20 UTC, WanderingHogan commented on libraries/SearchIndex/index.ts
> +
can you add some basic jsdoc documentation to these methods

2022-03-09 21:21 UTC, WanderingHogan commented on package.json
> +    "vue-template-compiler": "^2.x",
I think we can remove core-js, vue-template-compiler, babel-core, and fake-indexeddb, what do you think?

2022-03-09 21:27 UTC, WanderingHogan commented on plugins/thirdparty/dexie.ts
> +    this.version(2)
can you just combine this with version1?

2022-03-09 21:28 UTC, WanderingHogan commented on plugins/thirdparty/dexie.ts
> +    this.version(2)
do we even still need the conversations table?

2022-03-09 21:37 UTC, WanderingHogan commented on store/textile/actions.ts
> +    db.conversations
can we do away with this creation of the lastInbound, and instead have a method that pulls the most recent message from conversationMessages from the search class/indexeddb class?

2022-03-09 21:47 UTC, WanderingHogan commented on store/textile/actions.ts
> +  async searchConversations(
this is okay for now, but in the future i think this should be moved to the indexeddb/search class. Send an object to the library, get the response object back kind of thing

2022-03-09 21:48 UTC, WanderingHogan commented on store/textile/mutations.ts
> +    state.activeConversation = address
what does activeConversation give us? just storing in state so we can filter down on the one user when they choose to search?

2022-03-09 22:05 UTC, aewing commented on store/textile/mutations.ts
> +    state.activeConversation = address
Currently nothing, but we had discussed filtering on the active conversation, and the idea was with this knowledge we have that option, and when we get to the UI step I was thinking maybe we make that a default in the UI.

2022-03-10 11:59 UTC, aewing commented on plugins/thirdparty/dexie.ts
> +    this.version(2)
> do we even still need the conversations table?

need? I guess not, but I think it matches the data structure in textile and can easily see it being useful in the future. 
I also assumed there would be some (albeit minor) performance benefit to syncing conversations based on lastInbound without the messages attached. I can drop this table and rewrite the textile sync (which is currently based on lastInbound) if desired, but I didn't see any benefit to rewriting that and personally like that it mirrors textile.

2022-03-10 12:06 UTC, aewing commented on store/textile/actions.ts
> +    db.conversations
I can definitely get rid of this if we want. My thinking was that I could see the conversation table being useful to store things like background color or other preferences specific to the conversation or tab, etc... and it seemed convenient. I will go ahead and work on the alternative, but just wanted to note that I kind of like the separate table.

2022-03-10 12:10 UTC, aewing commented on store/textile/actions.ts
> +  async searchConversations(
Yea, I can see that. I may have mentioned you about this already, but I feel like there is a lot of logic in TextileManager and wanted to ask about perhaps breaking some of it up into a ChatManager that decouples the Textile and IndexedDB (and search) functionality. Either works for me.

2022-03-11 00:29 UTC, WanderingHogan approved these changes

2022-03-11 00:46 UTC, stavares843 approved these changes

2022-03-11 00:46 UTC, merged