fix(jest): resolved Skaler error import jest
Satellite-im/Core-PWA pull request #2283
Opened 2022-03-10 18:30 UTC by drepram

**What this PR does** 📖

Resolves Skaler import error by applying what was written on https://stackoverflow.com/questions/70829503/jest-gives-an-error-syntaxerror-unexpected-token-export-for-node-modules-mi

**Which issue(s) this PR fixes** 🔨

AP-1061

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-03-10 18:36 UTC, stavares843 commented on store/textile/actions.test.ts
> +        descrption: 'Test file description',
typo - descrption

2022-03-10 19:36 UTC, stavares843 approved these changes

2022-03-10 19:40 UTC, stavares843 requested changes
<img width="750" alt="Captura de ecrã 2022-03-10, às 19 39 54" src="https://user-images.githubusercontent.com/29093946/157741708-40972aab-a1d7-4bb7-bdc5-30e1747d8220.png">

phil saw this warning when compiling

doesn't happen on dev

can you take a look pls? 🔨

2022-03-10 23:19 UTC, WanderingHogan commented
You can import default exports as any name you want, so instead of `import { skaler as SkalerImported } from 'skaler'`, it would be `import SkalerImported from 'skaler'`, but why do you need to change this in the library?

2022-03-11 01:38 UTC, josephmcg commented
I pulled this down, reverted the import in TextileFileSystem back to the original and the tests were working.
`import skaler from 'skaler'`

Thanks for getting something working

2022-03-11 01:49 UTC, stavares843 approved these changes

2022-03-11 01:50 UTC, stavares843 commented
updated

tests are green and no longer returning warning when compiling

2022-03-11 01:52 UTC, josephmcg approved these changes
not sure if Andre wants to work on the other test in this same PR. current stuff looks great! I can re-review later if needed

2022-03-11 01:55 UTC, drepram commented
Looks good to me. Can this be merged?

2022-03-11 02:03 UTC, stavares843 approved these changes

2022-03-11 02:03 UTC, merged