fix(keybinds): prevend default behavior for shortcuts, add call short…
Satellite-im/Core-PWA pull request #2315
Opened 2022-03-14 15:04 UTC by AlexZakablukov

…cut, move call method to vuex

**What this PR does** 📖
prevend default behavior for shortcuts, add call shortcut for call active chat, move call method from toolbar to vuex

**Which issue(s) this PR fixes** 🔨
[AP-1020](https://satellite-im.atlassian.net/browse/AP-1020)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-03-14 17:27 UTC, Jekrimo approved these changes

2022-03-14 18:17 UTC, phillsatellite approved these changes

2022-03-14 18:21 UTC, phillsatellite commented
Found one little bug as I finished up testing, if user sets any keybinding to "control + letter" it will not work. In screen recording I set settings to "control + a" and was unable to open settings using that keybindin

https://user-images.githubusercontent.com/93608357/158236351-5e395cf3-7807-4614-a1d3-2f2c60bcbe95.mov

g

2022-03-15 16:49 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/158429202-e27142e3-5484-4265-9631-232b6dbac0b6.mov


What's the goal of this PR? I can't add any keybinds on this branch, I use a mac, and mac has control and seems control was removed from this PR to be a ctrl

I don't have the ctrl on my mac, only control

Works on dev branch

2022-03-16 11:40 UTC, molimauro commented
Whats the "single key already exists error"? Other than that i think its okay

2022-03-16 11:45 UTC, AlexZakablukov commented
> Whats the "single key already exists error"? Other than that i think its okay

It means you can use shortcut with two letters, for example shift + r + f, because mousetrap library that uses in this project does not suport it

2022-03-16 13:14 UTC, molimauro commented
> > Whats the "single key already exists error"? Other than that i think its okay
> 
> It means you can not use shortcut with two letters, for example shift + r + f, because mousetrap library that uses in this project does not support it

Ok i think its ok then!

2022-03-17 20:32 UTC, phillsatellite commented
Tested: Flow in screen recording

 - User tries to save Meta + C (copy on mac) gets error message 

- User edits keybinding and sets it to Meta + V (paste on mac) doesn't get error message and can save keybinding 

Should this issue be fixed on this pr? 

https://user-images.githubusercontent.com/93608357/158890152-126eebd1-cdcc-476b-b991-bbedfffa9ffb.mov

2022-03-18 10:36 UTC, AlexZakablukov commented
> Tested: Flow in screen recording
> 
> * User tries to save Meta + C (copy on mac) gets error message
> * User edits keybinding and sets it to Meta + V (paste on mac) doesn't get error message and can save keybinding
> 
> Should this issue be fixed on this pr?
> 
>  meta.v.mov

I added meta + v for mac and ctrl + v for windows into blocked shortcuts, the list of blocked shortcuts you can see here https://github.com/Satellite-im/Core-PWA/blob/f1f3d0b396216e96a1a432913784fb4832790d57/utilities/HotkeyList.ts, (31- 112 lines for windows and 114 to 188 for mac), if it needs to add more tell me, please.

2022-03-18 21:53 UTC, stavares843 commented
/rebase

2022-03-21 09:38 UTC, molimauro approved these changes

2022-03-22 03:59 UTC, stavares843 commented on components/views/navigation/toolbar/Toolbar.vue
> -      }
is this on purpose? doesn't seem related to the PR

2022-03-22 04:03 UTC, stavares843 requested changes
<img width="840" alt="Captura de ecrã 2022-03-22, às 04 01 56" src="https://user-images.githubusercontent.com/29093946/159405577-639ab88c-d0bd-4389-9fc8-89811cccf200.png">

dev branch

when using control, appear control

<img width="846" alt="Captura de ecrã 2022-03-22, às 04 02 44" src="https://user-images.githubusercontent.com/29093946/159405629-78c29289-838f-489e-b4f6-59bd36d9c84b.png">

this branch, when using control appears ctrl

im using a mac, should appear control instead of ctrl

2022-03-22 08:07 UTC, AlexZakablukov commented on components/views/navigation/toolbar/Toolbar.vue
> -      }
I moved this logic to vuex to make it possible to use via keybinds

2022-03-22 08:16 UTC, AlexZakablukov commented
> <img alt="Captura de ecrã 2022-03-22, às 04 01 56" width="840" src="https://user-images.githubusercontent.com/29093946/159405577-639ab88c-d0bd-4389-9fc8-89811cccf200.png">
> 
> dev branch
> 
> when using control, appear control
> 
> <img alt="Captura de ecrã 2022-03-22, às 04 02 44" width="846" src="https://user-images.githubusercontent.com/29093946/159405629-78c29289-838f-489e-b4f6-59bd36d9c84b.png">
> 
> this branch, when using control appears ctrl
> 
> im using a mac, should appear control instead of ctrl

try to use you keybind with control on dev branch - it does not work, lib used in the project does not support control, I will try  to fix it

2022-03-22 10:16 UTC, molimauro commented on utilities/Keybinds.ts
> +const isMac = navigator.platform.toLowerCase().includes('mac')
can you use this please:
```
typeof navigator !== 'undefined' && /Mac|iPad|iPhone|iPod/.test(navigator.userAgent)
```

2022-03-22 10:18 UTC, molimauro commented
The control/ctrl visualization hack is fine for now, later on we can change library if needed

2022-03-22 10:23 UTC, AlexZakablukov commented on utilities/Keybinds.ts
> +const isMac = navigator.platform.toLowerCase().includes('mac')
fixed

2022-03-22 10:30 UTC, molimauro approved these changes

2022-03-23 04:25 UTC, WanderingHogan commented
I fixed the merge conflict, removed the ^ from faker in package (and moved it to dev deps), adding typings for mousetrap

2022-03-23 17:09 UTC, stavares843 approved these changes

2022-03-23 17:10 UTC, merged