fix(chat): multiple files upload
Satellite-im/Core-PWA pull request #2326
Opened 2022-03-15 07:37 UTC by vimercati-samir

What this PR does 📖
posibility to upload a bulk of files

Which issue(s) this PR fixes 🔨
[AP-788](https://satellite-im.atlassian.net/browse/AP-788)

Special notes for reviewers 🗒️

Additional comments 🎤
This branch pr should replace the one already opened for the same issue, due to rebase complications creating a new branch was the only solution

2022-03-15 08:41 UTC, josephmcg requested changes
actions.ts has a lot of unrelated updates that would break things

2022-03-15 09:48 UTC, molimauro commented
#1676

2022-03-15 09:55 UTC, molimauro commented
Yeah a lot of files are totally corrupted, you should not copy and paste the whole file otherwise you'll break a lot of existing functionalities. You should go line by line, let me know if you need help

2022-03-15 11:06 UTC, molimauro approved these changes

2022-03-15 11:06 UTC, molimauro commented
Much better 👌

2022-03-15 16:38 UTC, stavares843 commented
<img width="1344" alt="Captura de ecrã 2022-03-15, às 16 34 39" src="https://user-images.githubusercontent.com/29093946/158427380-64067f66-859e-4aeb-bd0e-201555239b99.png">

it sends, but takes quite a while on that view

i'm gonna merge considering is better compared to dev

2022-03-15 16:41 UTC, stavares843 requested changes
i noticed that .heic preview is broken on this branch

this branch

<img width="1020" alt="Captura de ecrã 2022-03-15, às 16 40 19" src="https://user-images.githubusercontent.com/29093946/158427985-d372d016-7d75-44ec-9fb0-e0d756427552.png">

vs dev

<img width="1112" alt="Captura de ecrã 2022-03-15, às 16 40 24" src="https://user-images.githubusercontent.com/29093946/158428071-729a74b9-ed0b-458a-829f-8e8980c27ec0.png">

flow
- go to chat
- send heic file

2022-03-16 00:22 UTC, vimercati-samir commented
> fix: incorrect merge and missing latest dev changes

should be fixed in commit 7fb078486a8b593d19217d852b30feb2a10d5ddb

2022-03-16 00:23 UTC, vimercati-samir commented
> i noticed that .heic preview is broken on this branch
> 
> this branch
> 
> <img alt="Captura de ecrã 2022-03-15, às 16 40 19" width="1020" src="https://user-images.githubusercontent.com/29093946/158427985-d372d016-7d75-44ec-9fb0-e0d756427552.png">
> 
> vs dev
> 
> <img alt="Captura de ecrã 2022-03-15, às 16 40 24" width="1112" src="https://user-images.githubusercontent.com/29093946/158428071-729a74b9-ed0b-458a-829f-8e8980c27ec0.png">
> 
> flow
> 
> * go to chat
> * send heic file

should be fixed in commit 7fb078486a8b593d19217d852b30feb2a10d5ddb

2022-03-16 00:59 UTC, stavares843 commented
missing fixing conflict 🔨 cc @vimercati-samir

2022-03-16 11:03 UTC, molimauro approved these changes

2022-03-16 17:28 UTC, stavares843 commented
both @phillsatellite and CI are having this issue



https://wetransfer.com/downloads/be003b20c99e397c29e7ed8c3fc7bade20220316172325/3b5d664b7d93e2a566c4991811ae170920220316172354/5595ed

video above because is more than 100mb and github limit file size is max 100mb

dev
- send message, message appears on front of you

this branch
- send message, message doesn't appear in front of you

2022-03-17 12:37 UTC, vimercati-samir commented
> both @phillsatellite and CI are having this issue
> 
> https://wetransfer.com/downloads/be003b20c99e397c29e7ed8c3fc7bade20220316172325/3b5d664b7d93e2a566c4991811ae170920220316172354/5595ed
> 
> video above because is more than 100mb and github limit file size is max 100mb
> 
> dev
> 
> * send message, message appears on front of you
> 
> this branch
> 
> * send message, message doesn't appear in front of you

This problem should be resolved in commit ddf370b084a77bcca665e2320862b7edfec5b720

2022-03-17 18:49 UTC, stavares843 commented
/rebase

2022-03-17 21:31 UTC, phillsatellite approved these changes

2022-03-17 23:25 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/158909863-cef0f16e-91e3-4951-acf9-e946072b5fe9.mov

the scroll is fixed but is not as fluid on dev

also, there's a glitch when there are glyphs on the chat and that doesn't happen on dev

https://user-images.githubusercontent.com/29093946/158909907-3e9c2de6-1a0f-4f87-bb38-7e4b5e6c7a27.mov

2022-03-21 11:27 UTC, vimercati-samir commented
Reverted changes on scroll in commit 1d7091cfef292393a9c11ef09734b4e37cdb7216 to close this PR and open a new one just to fix the scroll problem

2022-03-21 14:35 UTC, stavares843 commented
/rebase

2022-03-21 19:45 UTC, stavares843 requested changes
this issue is happening again

https://github.com/Satellite-im/Core-PWA/pull/2326#issuecomment-1069382340


new video

https://user-images.githubusercontent.com/29093946/159351824-5e443e07-f2d9-4a45-998a-509884c9d720.mov

doesn't happen on dev

2022-03-22 11:18 UTC, vimercati-samir commented
> this issue is happening again
> 
> [#2326 (comment)](https://github.com/Satellite-im/Core-PWA/pull/2326#issuecomment-1069382340)
> 
> new video
> 
>  issue_001.mov 
> doesn't happen on dev

Should be fixed in commit a343228c6d02357be2d962d4d550aaaa25b7e753

2022-03-22 14:52 UTC, stavares843 commented
/rebase

2022-03-22 17:08 UTC, phillsatellite commented
Side Note* when tested I found a bug that if user rapid clicks send it will only send the first image as many times as you hit send, when tested on dev the same error codes appeared and it only sent the first image, I made a ticket for it and figured I should mention that on here still 

https://satellite-im.atlassian.net/jira/software/c/projects/AP/boards/5/backlog?view=detail&selectedIssue=AP-1143&issueLimit=100

2022-03-22 23:06 UTC, stavares843 commented on components/ui/Chat/Scroll/Scroll.vue
>      },
are these modifications on the Scroll.vue in purpose considering this PR is only to fix the multiple uploaded files?

2022-03-22 23:13 UTC, stavares843 commented
dev

<img width="861" alt="Captura de ecrã 2022-03-22, às 23 13 03" src="https://user-images.githubusercontent.com/29093946/159591411-66fe47c8-2aa4-473a-b438-c1a19cf75827.png">

this branch

<img width="865" alt="Captura de ecrã 2022-03-22, às 23 13 08" src="https://user-images.githubusercontent.com/29093946/159591425-19c8aae2-ae83-4774-a136-75f4cc020308.png">

2022-03-22 23:39 UTC, WanderingHogan commented on components/ui/Chat/Scroll/Scroll.vue
>      },
this wont affect it - when he added `...mapState(['ui', 'textile']),` he could remote $store.state

2022-03-22 23:54 UTC, stavares843 commented on components/ui/Chat/Scroll/Scroll.vue
>      },
🔨

2022-03-23 01:03 UTC, stavares843 commented
/rebase

2022-03-23 01:12 UTC, stavares843 commented
fixed after rebasing

2022-03-23 01:50 UTC, WanderingHogan commented
this works awesome for me, good work @vimercati-samir

2022-03-23 01:50 UTC, WanderingHogan approved these changes

2022-03-23 14:18 UTC, phillsatellite commented
Noted small bug on this branch went testing, Emoji's box will get cut off if browser window is too small

Dev
<img width="1728" alt="Screen Shot 2022-03-23 at 10 16 34 AM" src="https://user-images.githubusercontent.com/93608357/159720288-2145d7b4-4ee2-481e-ad56-d90de6f7bdea.png">


This Branch 
<img width="1230" alt="Screen Shot 2022-03-23 at 10 14 08 AM" src="https://user-images.githubusercontent.com/93608357/159720344-02f01b31-fb96-436d-a433-9fed389619ae.png">

2022-03-23 14:51 UTC, stavares843 commented
/rebase

2022-03-23 15:11 UTC, WanderingHogan commented
lets skip this and open a new ticket for it

2022-03-23 22:04 UTC, stavares843 approved these changes

2022-03-23 22:05 UTC, merged