feat(groupChats): update the group chat backend AP-951
Satellite-im/Core-PWA pull request #2347
Opened 2022-03-16 16:02 UTC by pavlzk

**What this PR does** 📖
Update the group chat backend library to use this new threadID according to the program
Add frontend integration

**Which issue(s) this PR fixes** 🔨
AP-951

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-03-17 13:11 UTC, Jekrimo requested changes
Do we need both libraries/Textile/GroupChatManager.new.ts And libraries/Textile/GroupChatManager.ts ? Can we merge the two so we don't have to have a .new?

2022-03-17 16:26 UTC, iltumio requested changes

2022-03-17 16:26 UTC, iltumio commented on components/views/group/create/Create.vue
> +      // if (this.$data.friends.length === 1) {
remove comment. Dead code

2022-03-17 16:26 UTC, iltumio commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +async function retryPromise<T>(
do we still need the retry mechanism? we can move it a utils file in case

2022-03-17 16:41 UTC, stavares843 requested changes

2022-03-17 16:41 UTC, stavares843 commented on libraries/Solana/GroupchatsProgram/GroupCrypto.ts
> +    // TODO consider to change random key generation
is there a ticket for this TODO? I can add if needed, let me know 🔨

2022-03-17 16:41 UTC, stavares843 commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +      groupId: 104, // TODO check
is there a ticket for this TODO? I can add if needed, let me know 🔨

2022-03-17 16:41 UTC, stavares843 commented on store/groups/actions.ts
> +  const account = $SolanaManager.getActiveAccount() // TODO payer or user account?
is there a ticket for this TODO? I can add if needed, let me know 🔨

2022-03-17 16:41 UTC, stavares843 commented on utilities/Messaging.ts
> +        sender: currentMessage.sender, // TODO add types
is there a ticket for this TODO? I can add if needed, let me know 🔨

2022-03-17 16:43 UTC, stavares843 commented on store/textile/actions.ts
> +        .catch((e) => console.log('error', e))
do we need this console.log? 🔨

2022-03-17 16:43 UTC, stavares843 commented on store/textile/actions.ts
> +      console.log(e)
do we need this console.log? 🔨

2022-03-17 16:43 UTC, stavares843 commented on components/views/group/create/Create.vue
> +        console.log(e)
do we need this console.log? 🔨

2022-03-17 16:43 UTC, stavares843 commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +      console.log('Unsubscribe failed:', e.message)
do we need this console.log? 🔨

2022-03-17 16:43 UTC, stavares843 commented
/rebase

2022-03-17 16:51 UTC, stavares843 commented
<img width="1114" alt="Captura de ecrã 2022-03-17, às 16 49 20" src="https://user-images.githubusercontent.com/29093946/158851956-50f56a09-8a90-42f8-ac3e-8d71d06dd4fa.png">

this was missing some linting, added 🔨 

you need to setup prettier locally as well 💥 

we have a pre-commit hook that automatically lints all the changed files when committing

2022-03-17 18:10 UTC, stavares843 commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
>  import { EventEmitter } from 'events'
i know the file was already created but maybe we should rename it to libraries/Solana/GroupchatsProgram/GroupChatsProgram.ts instead of libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts due to naming convention

2022-03-17 18:37 UTC, pavlzk commented on libraries/Solana/GroupchatsProgram/GroupCrypto.ts
> +    // TODO consider to change random key generation
yes add ticket pls. we need random string generation method. probably in our `libraries/Crypto/Crypto.ts`.
used approach works but is not optimal i think

2022-03-17 19:03 UTC, pavlzk commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +import { User } from '~/types/ui/user'
i have eslint error with proposed imports order
![image](https://user-images.githubusercontent.com/97599870/158876669-668b4c0b-941b-4f9b-8adc-d27911391922.png)

2022-03-17 19:12 UTC, stavares843 commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +import { User } from '~/types/ui/user'
strange 🔨

2022-03-17 19:43 UTC, stavares843 commented
/rebase

2022-03-17 19:47 UTC, stavares843 commented on libraries/Solana/GroupchatsProgram/GroupCrypto.ts
> +    // TODO consider to change random key generation
[AP-1102](https://satellite-im.atlassian.net/browse/AP-1102) 🔨

2022-03-18 02:18 UTC, WanderingHogan approved these changes

2022-03-18 02:19 UTC, WanderingHogan reviewed
i approved this on accident and haven't actually looked through it yet, sorry

2022-03-18 10:25 UTC, pavlzk commented on store/textile/actions.ts
> +      console.log(e)
actually instead of this console.log we need a way to let user know that message send failed
for now i will remove this console.log

2022-03-18 11:08 UTC, pavlzk commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +      groupId: 104, // TODO check
actually filtering by `groupId` not used yet in code, just added for possible further usages. i can remove it

2022-03-18 11:12 UTC, pavlzk commented on utilities/Messaging.ts
> +        sender: currentMessage.sender, // TODO add types
probably we need ticket for this

2022-03-18 11:16 UTC, pavlzk commented on store/textile/actions.ts
> +        .catch((e) => console.log('error', e))
it's from previous code. probably we need to handle message send errors there

2022-03-18 11:41 UTC, pavlzk commented on libraries/Solana/GroupchatsProgram/GroupCrypto.ts
> +import Crypto from '~/libraries/Crypto/Crypto'
done

2022-03-18 11:41 UTC, pavlzk commented on store/groups/actions.ts
> +  const account = $SolanaManager.getActiveAccount() // TODO payer or user account?
removed todo

2022-03-18 11:42 UTC, pavlzk commented on store/groups/actions.ts
> +    const { publicKey } = getUserAccount() // TODO should we use payer account instead?
removed todo

2022-03-18 11:42 UTC, pavlzk commented on store/groups/actions.ts
> +    // TODO or unsubscribe if subscribed?
removed todo

2022-03-18 11:43 UTC, pavlzk commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +import { User } from '~/types/ui/user'
removed

2022-03-18 11:43 UTC, pavlzk commented on components/views/group/create/Create.vue
> +        console.log(e)
added error message in create modal instead

2022-03-18 11:43 UTC, pavlzk commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
> +      console.log('Unsubscribe failed:', e.message)
removed

2022-03-18 11:45 UTC, pavlzk commented on libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
>  import { EventEmitter } from 'events'
renamed

2022-03-18 11:56 UTC, pavlzk commented
> 

it seems something css related, data present in html tree but have wrong position

> <img alt="Captura de ecrã 2022-03-17, às 17 08 43" width="1421" src="https://user-images.githubusercontent.com/29093946/158855747-5771a91d-cafb-46fc-b48f-a1b1195926cd.png">
> 
> when going to groups locally on this branch they are not displayed and returns an error on the console browser

it seems something with styles, group elements exists in html tree but not visible due to wrong positioning
![image](https://user-images.githubusercontent.com/97599870/158998777-8f8ec4ff-d2c5-4791-9a5a-1ab41c75bf5c.png)

2022-03-18 12:56 UTC, Jekrimo commented
> > 
> 
> it seems something css related, data present in html tree but have wrong position
> 
> > <img alt="Captura de ecrã 2022-03-17, às 17 08 43" width="1421" src="https://user-images.githubusercontent.com/29093946/158855747-5771a91d-cafb-46fc-b48f-a1b1195926cd.png">
> > when going to groups locally on this branch they are not displayed and returns an error on the console browser
> 
> it seems something with styles, group elements exists in html tree but not visible due to wrong positioning ![image](https://user-images.githubusercontent.com/97599870/158998777-8f8ec4ff-d2c5-4791-9a5a-1ab41c75bf5c.png)

Yup! I have the fix for this on my branch, i'm just trying to fix it for mobile now

2022-03-18 14:32 UTC, iltumio approved these changes

2022-03-18 21:55 UTC, stavares843 commented on utilities/Messaging.ts
> +        sender: currentMessage.sender, // TODO add types
[AP-1128](https://satellite-im.atlassian.net/browse/AP-1128)

2022-03-18 21:58 UTC, stavares843 commented
missing conflict 🔨

2022-03-20 19:53 UTC, stavares843 commented
/rebase

2022-03-21 14:37 UTC, stavares843 commented
/rebase

2022-03-21 17:06 UTC, Jekrimo approved these changes

2022-03-21 21:08 UTC, WanderingHogan commented
/rebase

2022-03-21 21:08 UTC, stavares843 commented
/rebase

2022-03-21 21:17 UTC, stavares843 commented
this branch

<img width="697" alt="Captura de ecrã 2022-03-21, às 21 15 52" src="https://user-images.githubusercontent.com/29093946/159365138-b9b1af6a-1323-4cb3-8a30-f1154e79a982.png">

dev

<img width="732" alt="Captura de ecrã 2022-03-21, às 21 16 24" src="https://user-images.githubusercontent.com/29093946/159365187-64776a30-507a-4d81-84da-39318b38b5dd.png">

2022-03-22 12:38 UTC, pavlzk commented
> this branch
> 
> <img alt="Captura de ecrã 2022-03-21, às 21 15 52" width="697" src="https://user-images.githubusercontent.com/29093946/159365138-b9b1af6a-1323-4cb3-8a30-f1154e79a982.png">
> 
> dev
> 
> <img alt="Captura de ecrã 2022-03-21, às 21 16 24" width="732" src="https://user-images.githubusercontent.com/29093946/159365187-64776a30-507a-4d81-84da-39318b38b5dd.png">

Returned placeholders from the previous modal window. I just thought for group create modal will be added new labels and descriptions

2022-03-22 17:45 UTC, phillsatellite approved these changes

2022-03-22 18:56 UTC, merged