fix(chat): fix unknown name issue when the user is registered with an avatar
Satellite-im/Core-PWA pull request #2401
Opened 2022-03-18 08:40 UTC by genie-magic

**What this PR does** 📖
fix unknown name issue when the user is registered with an avatar.

**Which issue(s) this PR fixes** 🔨

AP-920

2022-03-18 16:25 UTC, phillsatellite approved these changes

2022-03-18 21:56 UTC, stavares843 commented
/rebase

2022-03-29 12:04 UTC, iltumio requested changes

2022-03-29 12:04 UTC, iltumio commented on store/accounts/actions.ts
> +    if (preGeneratedTextilePubKey && !state.details?.textilePubkey)
looks that `textile/initialize` action is already commiting the public key to the state. Can you check why it is not working instead of commiting the same key again?

2022-03-29 15:27 UTC, genie-magic commented on store/accounts/actions.ts
> +    if (preGeneratedTextilePubKey && !state.details?.textilePubkey)
@iltumio  When no avatar, they first use setUserDetails to set user details and after that call 'textile/initialize' to set pubKey.... but when we register user info with avatar, we first set pubKey (without account details0 first and after that setUserDetails and pubKey is removed because setUserDetails reset value of account/details.

2022-03-30 14:37 UTC, phillsatellite approved these changes

2022-03-30 14:46 UTC, iltumio commented on store/accounts/actions.ts
> +    if (preGeneratedTextilePubKey && !state.details?.textilePubkey)
ok, let's investigate more later on

2022-03-30 14:46 UTC, iltumio approved these changes

2022-03-30 17:47 UTC, phillsatellite commented
When I went back to check something I noticed a crash on this branch. 
Browser: Safari
Flow: Select StorePin, select profile pic/Username, add a user - crash
<img width="1728" alt="Screen Shot 2022-03-30 at 1 39 26 PM" src="https://user-images.githubusercontent.com/93608357/160898825-160e866d-2c1e-4967-a613-2dbbe96021cd.png">

2022-03-30 17:48 UTC, stavares843 commented
🔨

2022-04-05 21:30 UTC, genie-magic commented
> When I went back to check something I noticed a crash on this branch. Browser: Safari Flow: Select StorePin, select profile pic/Username, add a user - crash <img alt="Screen Shot 2022-03-30 at 1 39 26 PM" width="1728" src="https://user-images.githubusercontent.com/93608357/160898825-160e866d-2c1e-4967-a613-2dbbe96021cd.png">

@phillsatellite  Is it only happen for this branch?

2022-04-05 21:33 UTC, stavares843 commented
yes phil tested on dev and was fine

2022-04-05 21:33 UTC, stavares843 commented
are you able to reproduce the issue?

2022-04-05 21:35 UTC, genie-magic commented
> are you able to reproduce the issue?

not yet...  I want him to test again if he can.

2022-04-05 22:54 UTC, phillsatellite commented
@genie-magic Hi Eric! I just tested again and verified I could only replicate crash on this branch. I noticed some other details that I think causes a crash I setup one account with Safari and the other with Chrome
(Github won't let me attach the image because its heic so I'm gonna dm it to you)
Safari User:
1. Store Pin 
2. Add profile picture with image I attach and create username
3. Login and add the Chrome user
4. Crash

Chrome User:
1. Do not store pin
2. Do not add a profile picture

2022-04-06 11:39 UTC, genie-magic commented
@phillsatellite  I fixed that issue and pushed. can you check on your side again? thanks.

2022-04-06 14:47 UTC, phillsatellite approved these changes

2022-04-06 17:09 UTC, WanderingHogan approved these changes

2022-04-07 13:42 UTC, stavares843 approved these changes

2022-04-07 13:42 UTC, merged