feat(indexedDB): clean up searchIndex, indexeddb
Satellite-im/Core-PWA pull request #2419
Opened 2022-03-18 21:26 UTC by aewing

**What this PR does** 📖
- Introduces the `libraries/SatelliteDB` library in place of the thirdparty `dexie` plugin (will revisit plugins as time allows)
- Refactors the SearchIndex class a bit, leveraging `minisearch` in place of the previous `dexie`
- Syncs new conversations, messages, and friends to indexeddb and search indexes

**Which issue(s) this PR fixes** 🔨
[AP-979](https://satellite-im.atlassian.net/browse/AP-979)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤
Feel free to reach out directly with any questions to try to keep the issue clean for other reviewers.

2022-03-18 21:40 UTC, stavares843 commented on libraries/SatelliteDB/SatelliteDB.test.ts
> +})
thanks for adding the test 🔨

2022-03-20 19:53 UTC, stavares843 commented
/rebase

2022-03-21 11:35 UTC, molimauro commented on libraries/SatelliteDB/SatelliteDB.ts
> +  public isInitialized: boolean
is this ever set?

2022-03-21 17:26 UTC, aewing commented on libraries/SatelliteDB/SatelliteDB.ts
> +  public isInitialized: boolean
Nice catch, it is now.

2022-03-21 19:05 UTC, stavares843 requested changes
<img width="1492" alt="Captura de ecrã 2022-03-21, às 19 04 42" src="https://user-images.githubusercontent.com/29093946/159345609-f7a2eec0-d557-45c9-bcfd-bb5426552eb5.png">

can you clarify exactly what is this PR adding related to the search?

I send messages saying ''a'', searched ''a'', no results found

is the search expected to be working on this PR?

2022-03-22 01:23 UTC, josephmcg approved these changes
I'll let Drew confirm, but I would guess it only searches after a certain character threshold. Searching for a single letter like 'a' wouldn't be very helpful since it would return any word with an 'a'. This seems like an under-the-hood change, UI updates coming in a later PR

2022-03-22 01:26 UTC, stavares843 commented
well, last time this was tested the search was far from perfect

also, that info is nowhere to be found on the PR, if it has or not a threshold which doesn't even make sense having that because if a user wants to search only by a number or an emoji, he couldn't due to the threshold

2022-03-22 04:08 UTC, stavares843 commented
also, both locally and CI the imported chats gets broken

<img width="831" alt="Captura de ecrã 2022-03-22, às 04 08 11" src="https://user-images.githubusercontent.com/29093946/159406185-e92d23aa-f7f1-4bef-9c28-92af2a7e68a1.png">

is this something expected within this PR?


doesn't seem to be any useful error on the log

2022-03-22 04:10 UTC, stavares843 commented
i also have that same issue with dexie on specific accounts, more details [here](https://satellite-im.atlassian.net/browse/AP-1105)

2022-03-22 19:20 UTC, aewing commented
> also, both locally and CI the imported chats gets broken
> 
> <img alt="Captura de ecrã 2022-03-22, às 04 08 11" width="831" src="https://user-images.githubusercontent.com/29093946/159406185-e92d23aa-f7f1-4bef-9c28-92af2a7e68a1.png">
> 
> is this something expected within this PR?
> 
> doesn't seem to be any useful error on the log

my small account imports without issue, so 

> also, both locally and CI the imported chats gets broken
> 
> <img alt="Captura de ecrã 2022-03-22, às 04 08 11" width="831" src="https://user-images.githubusercontent.com/29093946/159406185-e92d23aa-f7f1-4bef-9c28-92af2a7e68a1.png">
> 
> is this something expected within this PR?
> 
> doesn't seem to be any useful error on the log

I'm not seeing this issue when importing my account. When I attempt to import the seed phrase provided, I see a series of "Bad API key" messages locally and in the dev environment.

2022-03-22 19:23 UTC, stavares843 commented
very strange

thanks for checking 🔨

2022-03-22 19:29 UTC, aewing commented
> <img alt="Captura de ecrã 2022-03-22, às 01 27 48" width="1127" src="https://user-images.githubusercontent.com/29093946/159389210-57c31646-20a7-4077-8d07-155d8056ebb4.png">
> 
> tested again and ''a'' worked
> 
> but then tested ''test'' and crashed
> 
> <img alt="Captura de ecrã 2022-03-22, às 01 28 05" width="1481" src="https://user-images.githubusercontent.com/29093946/159389226-1e371cce-a04c-470a-af89-c08f0f2ac94e.png">
> 
> then sent ''SATELLITE'' and searched again by ''SATELLITE'' and crashed
> 
> so this crash's everything you send something > search for that > crash
> 
> reload, crash is gone, send other keyword > search for that one > crash's again

Thanks for finding this. I was able to reproduce this issue and have added a fix (appended the conversation address to new messages before adding them to the index, so the user can be attached in the UI)

2022-03-22 21:01 UTC, WanderingHogan commented on libraries/SatelliteDB/SatelliteDB.ts
> +    this.version(2).stores({
Why not just do this all in one version, eg:
```
    this.version(1).stores({
      conversations: 'key, lastInbound',
      conversationMessages:
        '&id, conversation, from, to, at, readAt, type, payload',
        friends: '&address, textilePubkey, name, photoHash, lastUpdate',
        keyValue: '&key, value, namespace',
    })
```

Backwards compatibility so when this goes in people don't have to wipe their local db?

2022-03-22 21:24 UTC, WanderingHogan commented on libraries/SatelliteDB/SatelliteDB.ts
> +    this.version(2).stores({
it doesn't really matter for now, will reduce conflicts if we dont combine them right now

2022-03-22 21:50 UTC, WanderingHogan approved these changes

2022-03-22 21:50 UTC, WanderingHogan commented
@stavares843 dont worry about anything in search, we have an upcoming task for Joe to refactor/work that

2022-03-22 22:53 UTC, stavares843 commented
dev

https://user-images.githubusercontent.com/29093946/159589267-af297420-cefb-41c6-af89-dc94a6263977.mov

this branch


https://user-images.githubusercontent.com/29093946/159589365-ca44fb58-6df0-427c-ad1b-b446fc44d283.mov

on dev, you send a glyph - that appears on the front of you
on this branch you send a glyph - that doesn't appear in front of you

2022-03-22 23:38 UTC, WanderingHogan commented
i can't for the life of me replicate the problem you are having

2022-03-22 23:38 UTC, stavares843 commented
so shady

2022-03-22 23:48 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/159595057-3d215310-a1de-4001-b8d2-540727d2791c.mov

flow
- go to dev
- send something
- appears in front of you (A)
- scroll up
- send something - will not appear in front of you, we don't have that type of scroll added yet (B)
- scroll down
- send something
- appears in front of you (because you were all scrolled down like the A above)


then
- go to dev
- send something
- appears in front of you (A)
- scroll up
- send something - will not appear in front of you, we don't have that type of scroll added yet (B)
- scroll down
- send something
- It DOESN'T appears in front of you (and you were all scrolled down like the A above so should be in front of you like dev)

2022-03-23 00:59 UTC, aewing commented
> Gravacao.do.ecra.2022-03-22.as.23.45.27.mov
> 
> flow
> 
>     * go to dev
> 
>     * send something
> 
>     * appears in front of you (A)
> 
>     * scroll up
> 
>     * send something - will not appear in front of you, we don't have that type of scroll added yet (B)
> 
>     * scroll down
> 
>     * send something
> 
>     * appears in front of you (because you were all scrolled down like the A above)
> 
> 
> then
> 
>     * go to this branch
> 
>     * send something
> 
>     * appears in front of you (A)
> 
>     * scroll up
> 
>     * send something - will not appear in front of you, we don't have that type of scroll added yet (B)
> 
>     * scroll down
> 
>     * send something
> 
>     * It DOESN'T appears in front of you (and you were all scrolled down like the A above so should be in front of you like dev)

just tested this on https://github.com/Satellite-im/Core-PWA/pull/2407 and a few other branches and the issue is consistent across the open PRs right now.

2022-03-23 01:02 UTC, stavares843 commented
on dev, is always good for me

Phil is checking as well

2022-03-23 01:29 UTC, aewing commented
https://user-images.githubusercontent.com/5033161/159603906-8d06615d-586c-4e79-9de9-6b11677b5e58.mp4

on dev.satellite.one

2022-03-23 01:53 UTC, merged