feat(importAccount): typeahead support using searchindex
Satellite-im/Core-PWA pull request #2422
Opened 2022-03-19 01:00 UTC by aewing

**What this PR does** 📖
Implements a typeahead filter on the import account page

**Which issue(s) this PR fixes** 🔨
AP-322

**Special notes for reviewers** 🗒️
Made some changes to the active item logic:
- Only one item can be active, mouse and keyboard will now take focus from one another
- Pressing enter will now select the first match in the list

**Additional comments** 🎤
extends #2179

2022-03-20 19:53 UTC, stavares843 commented
/rebase

2022-03-23 18:24 UTC, stavares843 commented
@aewing the other PR was merged, is this one still draft?

2022-03-23 21:24 UTC, phillsatellite commented
Tested: functionality works great but the list seems to be endless now and user cannot scroll to the bottom of i
<img width="422" alt="Screen Shot 2022-03-23 at 5 16 28 PM" src="https://user-images.githubusercontent.com/93608357/159798143-35df900f-9a42-4918-b5c8-5caff2d1bbd1.png">

https://user-images.githubusercontent.com/93608357/159798175-f4fd19b4-2c19-41ac-94bf-08d8c0db01c4.mov

t

2022-03-24 13:52 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/159931035-4e72aa42-0fb8-4156-b09f-a7d61356bb43.mov

this branch vs dev

import account is broken on this branch, video above

if you copy paste a whole key, only pastes the first word

2022-03-25 17:05 UTC, aewing commented
Thanks for finding these. Addressing these issues this morning, will have some updates soon.

2022-03-25 19:53 UTC, stavares843 commented
this is reverting this modification we did - https://github.com/Satellite-im/Core-PWA/pull/1499


basically, the first keyword shouldn't be highlighted

this branch

<img width="967" alt="Captura de ecrã 2022-03-25, às 19 52 10" src="https://user-images.githubusercontent.com/29093946/160191904-a344f480-8ea6-47fe-86d1-5efa0e82ccc8.png">

dev

<img width="981" alt="Captura de ecrã 2022-03-25, às 19 52 18" src="https://user-images.githubusercontent.com/29093946/160191916-3ad37eac-970e-42be-8140-baf6e4d5192e.png">

2022-03-28 22:37 UTC, aewing commented
> this is reverting this modification we did - #1499
> 
> basically, the first keyword shouldn't be highlighted

I can revert this change, but I found this to be flow breaking personally. I might save a few keypresses by having the item selected automatically and being able to press enter to continue to the next word. Reviewing the linked ticket, there isn't much detail about the 'why' behind this, so I thought perhaps it was related to a bug with the dual states of mouse hover and keyboard which have been resolved.

2022-03-28 22:38 UTC, aewing commented
@phillsatellite can you provider clarity on what we were actually solving for with #1499?

2022-03-28 22:43 UTC, stavares843 commented
basically, the first word on that PR was always highlighted, and Alex fix that

if you go to dev, the first word is not highlighted

but on this PR, was being highlighted again

basically we don't want words highlights when user is still searching unless user is hovering on those

2022-03-28 22:49 UTC, stavares843 commented
for speed's sake, not against in not reverting the above

cc @WanderingHogan

2022-03-30 20:27 UTC, WanderingHogan commented
I think this is good to go in if the functionality is there. The typeahead got very complex and it didn't need to be. We shouldn't add overrides for everything and try to steer towards using things without a million overrides

2022-03-30 20:27 UTC, WanderingHogan approved these changes

2022-03-30 20:31 UTC, stavares843 commented
sounds good 🔨

2022-03-30 21:48 UTC, WanderingHogan commented
🚀 🌔

2022-03-30 23:46 UTC, stavares843 approved these changes

2022-03-30 23:46 UTC, merged