fix(chat): scroll on iOS
Satellite-im/Core-PWA pull request #2431
Opened 2022-03-21 18:35 UTC by vimercati-samir

What this PR does 📖
fix chat scroll on iOS

Which issue(s) this PR fixes 🔨
[AP-1008](https://satellite-im.atlassian.net/browse/AP-1008)

Special notes for reviewers 🗒️

Additional comments 🎤

2022-03-21 23:55 UTC, genie-magic approved these changes

2022-03-22 03:37 UTC, stavares843 requested changes
![image](https://user-images.githubusercontent.com/29093946/159402969-dc5d3e61-88d3-4708-98c5-e5a0bf641b85.png)

i used the netlify URL on a real device, a iPhone 12 pro max and i can't scroll on the chat view

2022-03-23 07:58 UTC, molimauro commented on components/ui/Chat/Scroll/Scroll.less
> -  flex-direction: column-reverse;
@vimercati-samir cannot remove these, otherwise the messages in the chat are not at the bottom (try with a new chat)

2022-03-23 10:58 UTC, vimercati-samir commented on components/ui/Chat/Scroll/Scroll.less
> -  flex-direction: column-reverse;
flex-direction column-reverse was breaking the scroll, should be fixed in commit a3787878f04bd733667ce8409c6198df4c2ad59e

2022-03-23 11:28 UTC, vimercati-samir commented
fixing scroll to bottom to be preemptive instead of waiting for the message to be sent and scroll to bottom not going all the way to the bottom

2022-03-23 14:44 UTC, vimercati-samir commented
> fixing scroll to bottom to be preemptive instead of waiting for the message to be sent and scroll to bottom not going all the way to the bottom

should be fixed in commit 2da93f4f61b3bb6dec6224a34963604ee0730379

2022-03-23 17:07 UTC, molimauro commented
If you dont store the pin you'll encounter problems in scrolling once the messages are loaded. @vimercati-samir can you fix it?

2022-03-23 18:22 UTC, stavares843 commented
/rebase

2022-03-24 01:49 UTC, phillsatellite approved these changes

2022-03-24 09:22 UTC, molimauro commented
@vimercati-samir conflicts then ok :)

2022-03-24 09:23 UTC, molimauro approved these changes

2022-03-24 12:09 UTC, vimercati-samir commented
> @vimercati-samir conflicts then ok :)

rebased in commit 54d441410be32de12ce61eb3889d73996ce70f1f

2022-03-24 15:32 UTC, stavares843 requested changes
when you scroll up and add a reaction it scroll to the bottom - shouldn't happen

https://user-images.githubusercontent.com/29093946/159952622-856f9800-c88a-4b0e-b73e-d5ccffc5368c.mov

2022-03-24 22:35 UTC, vimercati-samir commented
> when you scroll up and add a reaction it scroll to the bottom - shouldn't happen
> 
>  Gravacao.do.ecra.2022-03-24.as.15.31.45.mov

Changed accordingly in commit be594758a1a5309defb462cb006ef439ae5b6961

2022-03-25 08:02 UTC, molimauro commented
Thanks @vimercati-samir, im doing some updates as well since i noticed some behaviour that needs to change. I'll let you all know once its done

2022-03-29 10:22 UTC, josephmcg approved these changes
🚀

2022-03-29 14:39 UTC, stavares843 approved these changes

2022-03-29 14:39 UTC, merged