fix(chat): reset emotes search on modal close/change
Satellite-im/Core-PWA pull request #2446
Opened 2022-03-22 10:59 UTC by AlexZakablukov

**What this PR does** 📖
reset emotes search on modal close/change

**Which issue(s) this PR fixes** 🔨
[AP-1118](https://satellite-im.atlassian.net/browse/AP-1118)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-03-22 14:10 UTC, stavares843 commented
/rebase

2022-03-22 21:03 UTC, phillsatellite commented
When tested with Netlify I noticed Search works for Glyphs and no longer works for emoji's.

https://user-images.githubusercontent.com/93608357/159575578-da0c4946-ce45-4a56-9eba-7ed404f86fcd.mov

2022-03-23 05:03 UTC, WanderingHogan commented on components/views/chat/enhancers/Enhancers.vue
> +        this.resetSearch()
Can you use a guard clause here, eg:

if (value) {
  this.openEmoji()
  return
}
this.resetSearch()

2022-03-23 05:05 UTC, WanderingHogan requested changes
ios is forcing capitalized first letter input, which is case sensitive. If you force lowercase on the v-model data it should fix Phils issue:

template: `<emoji-picker @emoji="addEmoji" :search="search.toLowerCase()">`

2022-03-23 15:08 UTC, AlexZakablukov commented on components/views/chat/enhancers/Enhancers.vue
> +        this.resetSearch()
ok, thx)

2022-03-23 15:14 UTC, AlexZakablukov commented
> ios is forcing capitalized first letter input, which is case sensitive. If you force lowercase on the v-model data it should fix Phils issue:
> 
> template: `<emoji-picker @emoji="addEmoji" :search="search.toLowerCase()">`

thank you, fixed)

2022-03-23 15:32 UTC, WanderingHogan approved these changes

2022-03-23 16:43 UTC, stavares843 approved these changes

2022-03-23 16:43 UTC, merged