feat(meta): dynamic head title
Satellite-im/Core-PWA pull request #2502
Opened 2022-03-25 00:02 UTC by vimercati-samir

What this PR does 📖
add dynamic head titles on every page

Which issue(s) this PR fixes 🔨
[AP-1157](https://satellite-im.atlassian.net/browse/AP-1157)

Special notes for reviewers 🗒️

Additional comments 🎤

2022-03-25 09:15 UTC, molimauro commented
Thanks @vimercati-samir. Put `head()` and `mapState` in a mixin and remove the middleware for now. Also import the mixin in `layouts` instead of all pages. 🚀

2022-03-25 19:08 UTC, iltumio requested changes

2022-03-29 09:56 UTC, vimercati-samir commented on components/mixins/Meta/WithMeta.ts
> +    ...mapState(['accounts', 'meta']),
Removed the conditional check to prevent pages where the user was not logged to have a custom title, it's best to change it programmatically when the user logout, hence the accounts spread has been removed as well

2022-03-29 09:59 UTC, vimercati-samir commented on components/mixins/Meta/WithMeta.ts
> +      title: isUserRegistered ? this.meta.title : 'Satellite-Absolute',
The only place now where the default title 'Satellite-Absolute' is in the store meta state, I don't know if placing it also in the Config it's a good idea because it will be replaced by the one in the store

2022-03-29 13:48 UTC, RetroPronghorn commented on components/mixins/Meta/WithMeta.ts
> +      title: isUserRegistered ? this.meta.title : 'Satellite-Absolute',
I agree though that any defaults should be an ENUM constant and or config value, but will differ to @iltumio on how we worry about this right now

2022-03-29 20:23 UTC, stavares843 commented
<img width="363" alt="Captura de ecrã 2022-03-29, às 21 22 49" src="https://user-images.githubusercontent.com/29093946/160700362-e100de67-bd0f-4250-b8e3-65eb94cea8d0.png">

seems this cant be rebased due to conflicts, @vimercati-samir can you rebase this manually?

2022-03-30 08:06 UTC, vimercati-samir commented
> <img alt="Captura de ecrã 2022-03-29, às 21 22 49" width="363" src="https://user-images.githubusercontent.com/29093946/160700362-e100de67-bd0f-4250-b8e3-65eb94cea8d0.png">
> 
> seems this cant be rebased due to conflicts, @vimercati-samir can you rebase this manually?

Done

2022-03-30 18:40 UTC, phillsatellite approved these changes

2022-03-30 21:46 UTC, WanderingHogan commented
@vimercati- this looks good - but @molimauro what do you think about using this as a chance to use the nuxt-bridge compostion api https://v3.nuxtjs.org/getting-started/bridge-composition-api/. @tooshel mentioned that Mixins are not part of Vue3

2022-03-31 07:32 UTC, molimauro commented
Ok sure, we'll close this one atm. We'll reopen it once its ready. Thanks!

2022-03-31 07:32 UTC, closed without merging