fix(files): rename quality of life update
Satellite-im/Core-PWA pull request #2654
Opened 2022-03-31 05:22 UTC by josephmcg

**What this PR does** 📖
- enforce invalid name rules on file/folder creation and rename
- refactor name validation to a separate method which can be called from the constructor

**Which issue(s) this PR fixes** 🔨
AP-1179

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-03-31 14:07 UTC, Jekrimo requested changes

2022-03-31 14:07 UTC, Jekrimo commented on libraries/Files/abstracts/Item.abstract.ts
> +      (this.constructor.name === 'Fil'
Is this a typo for 'File'?

2022-03-31 14:11 UTC, stavares843 commented on libraries/Files/abstracts/Item.abstract.ts
> +      (this.constructor.name === 'Fil'
i believe this is related to https://github.com/Satellite-im/Core-PWA/blob/dev/libraries/Files/Fil.ts and we use ''Fil'' because ''File'' is already in use for typescript itself or similar

2022-03-31 14:11 UTC, stavares843 commented on libraries/Files/abstracts/Item.abstract.ts
> +      (this.constructor.name === 'Fil'
but joe can better say

2022-03-31 15:19 UTC, Jekrimo commented on libraries/Files/abstracts/Item.abstract.ts
> +      (this.constructor.name === 'Fil'
You're totes right, I'mma close this, thank you!

2022-03-31 15:19 UTC, Jekrimo approved these changes

2022-04-01 00:21 UTC, phillsatellite commented
Tested: So when I create a new folder and go into it there will already be another folder named "un-named directory" in new folder. Is that intended
<img width="1057" alt="Screen Shot 2022-03-31 at 8 07 03 PM" src="https://user-images.githubusercontent.com/93608357/161170985-5aa675d6-8587-4eda-a14e-f8d6fca77198.png">
?

2022-04-01 01:14 UTC, josephmcg commented
I'm not encountering that issue. can you try this with a new account? There may be some issues importing current filesystem structure with these changes

2022-04-01 08:38 UTC, molimauro approved these changes

2022-04-04 00:46 UTC, josephmcg commented
Thanks, that was something from the original filesystem setup that I missed on this round of updates. should be fixed now

2022-04-04 14:31 UTC, phillsatellite approved these changes

2022-04-04 15:10 UTC, stavares843 approved these changes

2022-04-04 15:10 UTC, merged