fix(files): rework store for files modal
Satellite-im/Core-PWA pull request #2745
Opened 2022-04-06 05:57 UTC by josephmcg

**What this PR does** 📖
- if you open a file after uploading, it doesn't need to be fetched
- if you refresh and then open file, it needs to fetch the blob from textile for download. with the new modal, this causes a crash. PR fixes this crash
- less overhead in store, only keep track of name rather than full Fil

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-04-07 13:50 UTC, Jekrimo approved these changes

2022-04-07 16:59 UTC, phillsatellite approved these changes

2022-04-08 08:18 UTC, molimauro approved these changes

2022-04-08 18:34 UTC, stavares843 requested changes
<img width="831" alt="Captura de ecrã 2022-04-08, às 19 32 18" src="https://user-images.githubusercontent.com/29093946/162500890-4a884275-1d93-46c6-9387-81aaeeee7adc.png">

dev

vs this branch
<img width="925" alt="Captura de ecrã 2022-04-08, às 19 32 31" src="https://user-images.githubusercontent.com/29093946/162500922-0a4388d7-9909-44f5-8a48-6b5010d6ce3d.png">


same happens with a .avif 

dev

<img width="1420" alt="Captura de ecrã 2022-04-08, às 19 33 06" src="https://user-images.githubusercontent.com/29093946/162501002-52081db4-1d97-495b-bfb7-9272ba64d6bf.png">

this branch

<img width="1420" alt="Captura de ecrã 2022-04-08, às 19 33 49" src="https://user-images.githubusercontent.com/29093946/162501109-9164609c-46f7-4939-b1f7-6c423847a910.png">

2022-04-11 00:30 UTC, josephmcg commented
This does not impact chat messages

2022-04-11 08:07 UTC, stavares843 commented
if doesn't impact chat messages, why the difference in behavior above? @josephmcg

2022-04-11 09:04 UTC, josephmcg commented
I would suggest getting the latest rebased branch and running it locally, they're not my changes so I have no idea why chat is acting like that

2022-04-11 09:23 UTC, josephmcg commented
seems like our netlify pipeline takes commits from everywhere? idk, i never use it besides mobile testing. that would support the 'someone else's code' theory.

https://app.netlify.com/sites/adoring-edison-dbcef8/deploys

2022-04-11 12:10 UTC, stavares843 commented
the netlify commits are the ones on this branch, it takes this branch code changes and then deploys to netlify


but I can test locally as well

2022-04-11 12:12 UTC, stavares843 commented
checked locally and now is fine and has the same behavior in both dev and this branch

thanks for checking 🔨

2022-04-11 12:13 UTC, stavares843 approved these changes

2022-04-11 12:13 UTC, merged