feat(chat): create older messages info block above chatbar
Satellite-im/Core-PWA pull request #2784
Opened 2022-04-08 10:25 UTC by AlexZakablukov

**What this PR does** 📖
create older messages info block above chatbar

**Which issue(s) this PR fixes** 🔨
[AP-11](https://satellite-im.atlassian.net/browse/AP-11)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-04-11 08:40 UTC, stavares843 requested changes
<img width="1350" alt="Captura de ecrã 2022-04-11, às 09 38 49" src="https://user-images.githubusercontent.com/29093946/162698176-c1671588-97ef-440f-989a-b528a1506cc5.png">

I made 2 accounts
user A sends messages to user B until it has a scroll
users scrolls up
receives message from another user
no ''recent messages'' banner appears

brave browser

2022-04-12 08:48 UTC, molimauro commented
Yep that is the intended behaviour right now. I think its not easy for the QA team to know exactly when we pass the threshold, so as long as it appears when scrolling back i think we can approve it ;) let me know your thoughts thanks!

2022-04-12 11:51 UTC, stavares843 commented
thanks for clarifying 🔨

2022-04-12 14:20 UTC, AlexZakablukov commented on components/ui/Chat/Info/Info.vue
> +      default: () => {},
@molimauro I tried to make this component more flexible, it can be uses as error or warning info block also, so it can be different click handlers for them.

2022-04-12 14:27 UTC, molimauro commented on components/ui/Chat/Info/Info.vue
> +      default: () => {},
yeah and thats great! What i meant is that if we emit from this component an event like "click" then on the parent we can listen with @click and attach whatever function we want :) I dont think we lose some flexibility in this way

2022-04-12 14:35 UTC, AlexZakablukov commented
> Really great @AlexZakablukov! I noticed that when there are both a reply and the info block they overlap. Can you fix this? Thanks!

When reply is displayed, info block should disappear?

2022-04-12 14:36 UTC, molimauro commented
> > Really great @AlexZakablukov! I noticed that when there are both a reply and the info block they overlap. Can you fix this? Thanks!
> 
> When reply is displayed, info block should disappear?

Nope, simply adjust the css ;)

2022-04-12 15:00 UTC, AlexZakablukov commented
fixed

2022-04-12 15:02 UTC, molimauro commented
Thanks! QA time

2022-04-12 18:42 UTC, stavares843 approved these changes

2022-04-12 18:42 UTC, merged