fix(replies): display correct reply text
Satellite-im/Core-PWA pull request #2882
Opened 2022-04-14 11:41 UTC by AlexZakablukov

**What this PR does** 📖
display correct reply text

**Which issue(s) this PR fixes** 🔨
[AP-1310](https://satellite-im.atlassian.net/browse/AP-1310)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-04-14 19:37 UTC, phillsatellite approved these changes

2022-04-15 01:06 UTC, josephmcg requested changes
could you add translations for this? You can feed the translations parameters
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#named-interpolation

2022-04-15 09:12 UTC, AlexZakablukov commented
done

2022-04-15 16:27 UTC, phillsatellite approved these changes

2022-04-15 16:31 UTC, WanderingHogan approved these changes

2022-04-15 17:04 UTC, stavares843 approved these changes

2022-04-15 17:10 UTC, merged