fix(files): persistent files upload status
Satellite-im/Core-PWA pull request #2889
Opened 2022-04-15 01:52 UTC by josephmcg

**What this PR does** 📖
- remove file upload progress bar in favor of percentage in status message. more consistent ui, less jarring to see the progress bar appear & disappear. Liz also said we don't use progress bars, so this is more cohesive with the rest of the app
- upload status will remain if you navigate away from this page and come back

**Which issue(s) this PR fixes** 🔨
AP-1395

**Special notes for reviewers** 🗒️

**Additional comments** 🎤
- since we're using store, I'd like to add status updates for other file operations (rename, remove, favorite) after this

2022-04-15 17:27 UTC, phillsatellite approved these changes

2022-04-15 20:50 UTC, Jekrimo approved these changes

2022-04-19 13:57 UTC, molimauro approved these changes

2022-04-19 23:44 UTC, stavares843 requested changes
<img width="386" alt="Captura de ecrã 2022-04-20, às 00 43 49" src="https://user-images.githubusercontent.com/29093946/164118740-4fad3008-8714-45d0-971b-96f1dad65d33.png">


i was uploading a file on files and showed 105%

2022-04-20 01:18 UTC, josephmcg commented
weird lol, I added something to display the smaller number given the percentage and 100.

2022-04-20 13:36 UTC, stavares843 commented
thanks 😂

2022-04-20 13:53 UTC, stavares843 approved these changes

2022-04-20 13:53 UTC, merged