chore(scrollbar): added new scrollbar to emote
Satellite-im/Core-PWA pull request #2899
Opened 2022-04-15 14:33 UTC by ThomBos

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤
New scrollbar component's first add, can just be found on the emote choice, from chatbar.

2022-04-29 07:50 UTC, molimauro commented on assets/styles/base.less
> +  --flair-color: '#2761fd';
@ThomBos why arent you using the @primary-color var?

2022-05-02 07:58 UTC, molimauro commented on components/views/chat/enhancers/Enhancers.vue
> +            }, 200)
Why a setTimeout nested in another setTimeout?

2022-05-02 08:13 UTC, ThomBos commented on components/views/chat/enhancers/Enhancers.vue
> +            }, 200)
because we haven't the component yet, even if openEmoji() is called on mounted

2022-05-02 14:11 UTC, molimauro approved these changes

2022-05-02 19:15 UTC, Clayton215 approved these changes

2022-05-02 19:40 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/166314116-a4e98f4e-14ec-4233-a488-32fd0e21a1af.mov

seems that when switching from the glyphs tab to the emojis tab dev vs this branch, seems this branch is slower

would this be related to the new scroll?

browser - safari

btw is pretty neat on mobile 🎉

2022-05-02 21:15 UTC, ThomBos commented
> seems that when switching from the glyphs tab to the emojis tab dev vs this branch, seems this branch is slower


this issue it's going to be solved on another branch, i'm gonna open the PR tomorrow 👍 🎉

2022-05-02 21:27 UTC, stavares843 commented
thanks for clarifying 🔨

2022-05-03 08:13 UTC, ThomBos commented
This PR depends on https://github.com/Satellite-im/Core-PWA/pull/3042 💥

2022-05-03 17:16 UTC, stavares843 commented
https://github.com/Satellite-im/Core-PWA/pull/3042 merged 💥 

missing fixing conflict 🔨

2022-05-03 19:45 UTC, phillsatellite approved these changes

2022-05-04 08:32 UTC, molimauro commented
It's so good to see all those enhancers tricks gone. Thanks @ThomBos

2022-05-04 08:32 UTC, molimauro approved these changes

2022-05-04 11:53 UTC, merged