fix(friends): dispatch update store event on denied and accept request
Satellite-im/Core-PWA pull request #2953
Opened 2022-04-21 08:19 UTC by AlexZakablukov

… request

**What this PR does** 📖
dispatch update store event on denied and accept request

**Which issue(s) this PR fixes** 🔨
[AP-1409](https://satellite-im.atlassian.net/browse/AP-1409)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-04-22 14:40 UTC, Jekrimo requested changes

2022-04-22 14:40 UTC, Jekrimo commented on libraries/Solana/FriendsProgram/FriendsProgram.ts
> +    console.log('acceptFriendRequest')
Do we need all these consoles?

2022-04-25 07:15 UTC, AlexZakablukov commented on libraries/Solana/FriendsProgram/FriendsProgram.ts
> +    console.log('acceptFriendRequest')
removed

2022-04-25 19:04 UTC, phillsatellite approved these changes

2022-04-26 14:41 UTC, Jekrimo approved these changes

2022-04-27 12:42 UTC, iltumio commented
we should close this PR since we are integrating the new version of the friends program here https://github.com/Satellite-im/Core-PWA/pull/2469

2022-04-28 23:13 UTC, stavares843 commented
closing due to @iltumio comment above

2022-04-28 23:13 UTC, closed without merging