fix(message): update timestamp message every minute
Satellite-im/Core-PWA pull request #300
Opened 2021-11-23 17:02 UTC by vimercati-samir

**What this PR does** 📖
Update timestamp message every minute

**Which issue(s) this PR fixes** 🔨
timestamp message not updating (‘A few seconds ago' for ever unless component rebuilds)

Fixes #AP-43

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-11-23 18:26 UTC, stavares843 approved these changes
so it no longer gets stuck showing a few seconds ago 


<img width="490" alt="Captura de ecrã 2021-11-23, às 18 19 19" src="https://user-images.githubusercontent.com/29093946/143082413-89bef5f5-a9cc-4774-8022-f72b28c142f6.png">

when sending a message says a few seconds ago and then updates to a minute ago, 2 minutes ago, and so on

but the thing is, when you send a message and then wait 5 minutes and send another message, all those messages shows that were sent 5 minutes ago, even if the oldest one was 5m ago and the newest one was a couple of seconds ago

I'm gonna approve this because that's probably to be handled on other PR, let me know cc @WanderingHogan

2021-11-23 21:35 UTC, stavares843 commented
/rebase

2021-11-24 05:42 UTC, WanderingHogan commented
@stavares843 just added a few tickets to address what you brought up: AP-106 and AP-107

2021-11-24 06:02 UTC, WanderingHogan approved these changes
great idea with clearInterval when you tear down the component

2021-11-24 06:26 UTC, RetroPronghorn requested changes

2021-11-24 06:26 UTC, RetroPronghorn commented on components/tailored/messaging/group/Group.vue
> +      }, 60 * 1000)
Can we move this to a config value?

2021-11-24 06:26 UTC, RetroPronghorn commented on components/tailored/messaging/message/Message.vue
> +      }, 60 * 1000)
Config value

2021-11-24 06:31 UTC, RetroPronghorn commented on components/tailored/messaging/message/Message.vue
> +      }, 60 * 1000)
I suggest 
```ts
 chat: {
    defaultMessageLimit: 50,
    defalutLoadMoreLimit: 20,
    timestampUpdateInterval: 60 * 1000,
  },
  ```

2021-11-26 00:59 UTC, RetroPronghorn approved these changes

2021-11-26 01:00 UTC, merged