Feature/group calls
Satellite-im/Core-PWA pull request #3003
Opened 2022-04-27 15:38 UTC by aewing

**What this PR does** 📖
Implements group calling by establishing a full-mesh topology between participants
Adds screen sharing to calls

**Special notes for reviewers** 🗒️
There are likely going to be a number of small bugs on this PR as the interface was kind of ad-hoc for group calling. Please follow up on Discord.

**Additional comments** 🎤

2022-05-05 19:47 UTC, phillsatellite commented
I noticed this error message when User accepts a friend request I couldn't replicate this on dev branch or test.satellite.one

<img width="1096" alt="Screen Shot 2022-05-05 at 3 28 01 PM" src="https://user-images.githubusercontent.com/93608357/167013930-162dfd2c-456a-43b1-a1dd-702f4c9a1008.png">

2022-05-05 21:41 UTC, stavares843 requested changes
I also have the same error as Phil mentioned above

also,

- if we don't allow permissions to share screen, will crash when trying to do a share screen

<img width="1361" alt="Captura de ecrã 2022-05-05, às 22 11 58" src="https://user-images.githubusercontent.com/29093946/167026535-4d7f2b0e-28a2-4adf-ad5d-3c6a6c1475ce.png">

- when trying again, still crash's but doesn't ask again the permission it just crash's again


https://user-images.githubusercontent.com/29093946/167027497-94822aa8-19c3-4489-8d4b-5ef810c17d74.mov


- when trying to do a call with a user that is not online, the video call icon is still visible and console log returns `call - conversation not initialized or id not found`

<img width="1361" alt="Captura de ecrã 2022-05-05, às 22 13 22" src="https://user-images.githubusercontent.com/29093946/167026669-2c05945c-bd2f-4723-84c5-cdc1aa7758f2.png">

- if you are on a chat with 1 person and you also have a chat with a group, if you are on the DM and you get a group DM, even if you accept the call you are not redirected for the call, you stay on the DM

<img width="1305" alt="Captura de ecrã 2022-05-05, às 22 27 20" src="https://user-images.githubusercontent.com/29093946/167029225-8c8df81c-61c7-4174-8d76-7727fb995d79.png">
<img width="1292" alt="Captura de ecrã 2022-05-05, às 22 27 45" src="https://user-images.githubusercontent.com/29093946/167029234-f934a760-1b06-4fb1-80d7-d259ce01c3e9.png">
<img width="1289" alt="Captura de ecrã 2022-05-05, às 22 27 57" src="https://user-images.githubusercontent.com/29093946/167029255-f1e8af70-da81-4b3f-bcff-ebf66c832341.png">

- when you get a group DM, all is black on the modal, doesn't say who is calling

<img width="479" alt="Captura de ecrã 2022-05-05, às 22 27 14" src="https://user-images.githubusercontent.com/29093946/167029315-c8df57f7-df96-49c2-9769-3959485f163f.png">

- even when the video call icon is not available, user is still able to proceed to call the group 

https://user-images.githubusercontent.com/29093946/167029823-08671e2e-9152-4b9c-a05b-5400e3fcb9dd.mov


- when user A starts group call and user B accepts call, there are some grey cubes without name on the call

<img width="1265" alt="Captura de ecrã 2022-05-05, às 22 36 20" src="https://user-images.githubusercontent.com/29093946/167029568-2b670531-3301-487c-829f-e6aa8599d2fb.png">

- i'm already on a call and then without anyone calling because the call was just with users locally, the call modal was appearing anyway

https://user-images.githubusercontent.com/29093946/167030230-5791b16f-5d06-4327-b7f5-9824735603ae.mov

2022-05-05 22:44 UTC, phillsatellite commented
I also found a few more bugs on mobile (iOS) 
- If you add a iOS user to a group, that group will never appear in the sidebar
![IMG_5328](https://user-images.githubusercontent.com/93608357/167036880-0ac8bc6b-a263-4113-b7f4-67c2b4f2cbc8.PNG)
<img width="1728" alt="Screen Shot 2022-05-05 at 6 36 25 PM" src="https://user-images.githubusercontent.com/93608357/167036889-e00b0e9b-6c0a-4c43-8d9a-7882a1a18ca0.png">

- Calling someone with screen-share call will never appear on the other user's side (desktop as well)
- on IOS doesn't ask what screen you want to share just immediately starts calling (call will never go through to other user)

https://user-images.githubusercontent.com/93608357/167036914-3ae73e6b-c567-42b6-b93b-5da99278df8b.MP4

2022-05-11 17:47 UTC, phillsatellite commented
A few things I found after testing that I wasnt able to replicate on dev branch

1. I wasn't able to ever get screensharing to work. I would click which screen to share then nothing happens 
https://user-images.githubusercontent.com/93608357/167913216-05191620-ead9-4fc3-9219-df2b8f11d02a.mov

2. I noticed when you load into a chat the textbox and calling tools at the top will be missing. User has to navigate to a different page and back to the chat for it to appear 
https://user-images.githubusercontent.com/93608357/167913514-fcce3f4f-76d2-4025-91ce-ec139f4a3354.mov

3.The group chat screens overlapped, I tried this on dev branch but couldnt get 3 people in a group
<img width="1728" alt="group chat overlap" src="https://user-images.githubusercontent.com/93608357/167913566-b6a57eb2-f254-4f9f-9603-465414aca744.png">
 
4. After ending group chat call input box would be in the middle of the screen (this would persist to other chats as well)
<img width="1728" alt="input box" src="https://user-images.githubusercontent.com/93608357/167913736-e76372c9-817b-4049-90ab-373eb1dcd799.png">

2022-05-12 15:55 UTC, Clayton215 commented
Upon sending pictures in group messages the app crashes and shows this error.
The picture I used in this instance was a .PNG however the crash also happened with different types such as .jpegs and .heic

https://user-images.githubusercontent.com/96502187/168117305-b01953db-7859-4f93-a3df-b3f70ed61fec.mov
<img width="1717" alt="console log" src="https://user-images.githubusercontent.com/96502187/168117341-d04fe438-d4e4-41b3-97d4-45a5f853f8cc.png">

2022-05-12 17:42 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/168136253-68b10675-d726-4908-8a3e-3ae55d7b8368.mov


https://user-images.githubusercontent.com/29093946/168136286-2b448bbf-225b-49a6-af32-716774efec71.mov

if i'm not on a call, trying to use the toggles crash's

m1, chrome

2022-05-12 17:46 UTC, stavares843 requested changes
user A called user B

user B didn't get the call

user B called user A

user A declined the call and also closed the call on the user B's side

2022-05-12 18:00 UTC, aewing commented
> user A called user B
> 
> user B didn't get the call
> 
> user B called user A
> 
> user A declined the call and also closed the call on the user B's side

@stavares843 if User A calls User B before user B has a chance to establish a connection to User A, the call will not be delivered right away, but should dial through after the connection is established. Is this not the case? Could you maybe make a recording?

2022-05-12 18:04 UTC, stavares843 requested changes
<img width="1357" alt="Captura de ecrã 2022-05-12, às 18 55 39" src="https://user-images.githubusercontent.com/29093946/168140052-dc90e337-db7d-45b9-8ca8-ac0346a1906e.png">

hang up a call, the modal appeared like this

not always reproducible

brave, m1

2022-05-12 18:05 UTC, stavares843 requested changes
<img width="1349" alt="Captura de ecrã 2022-05-12, às 18 56 41" src="https://user-images.githubusercontent.com/29093946/168140219-b8610e4b-d7b5-4d3b-8d79-f7424ee4d748.png">

made a call and the modal was there if you see the glyph is cut off with the same size the call modal has but no call modal displaying

can't always reproduce

brave, m1

2022-05-12 18:07 UTC, stavares843 requested changes
<img width="1507" alt="Captura de ecrã 2022-05-12, às 19 07 18" src="https://user-images.githubusercontent.com/29093946/168140537-fd82d495-8667-4d05-8cb5-b4f37b72adb4.png">

this branch vs dev

user is not connected on the bottom is not showing on this branch

2022-05-12 18:09 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/168140782-1611d8b1-3542-4f7f-8dd5-b7b87241445b.mov

i can only sends glyphs if the user is online

on dev works fine

2022-05-12 18:25 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/168143452-2f14b184-d045-46f8-9252-2c59629c994e.mov

the icon is deactivated but is still clickable same with the call one

brave, m1

2022-05-12 18:27 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/168143781-230b4be7-f58b-4496-ad9c-424febf14ea2.mov


doing a call group is not appearing on both sides even after almost 1m

brave and opera, m1

2022-05-12 20:09 UTC, WanderingHogan approved these changes

2022-05-12 22:19 UTC, stavares843 commented on store/friends/mutations.ts
> +  // },
do we need this commented out?

2022-05-12 22:19 UTC, stavares843 commented
as discussed with the team, we will get this merged and add tickets for the bugs that this PR is introducing to be fixed separately

2022-05-12 22:19 UTC, merged