fix(chat reaction): Fix 'Emoji reactions will increase if user navigates to a different page and back to chat again'
Satellite-im/Core-PWA pull request #306
Opened 2021-11-24 13:16 UTC by genie-magic

**What this PR does** 📖
Fix 'Emoji reactions will increase if user navigates to a different page and back to chat again'

**Which issue(s) this PR fixes** 🔨

Fixes # AP-58

2021-11-24 14:05 UTC, Jekrimo approved these changes

2021-11-24 15:13 UTC, RetroPronghorn requested changes

2021-11-24 15:13 UTC, RetroPronghorn commented on utilities/Messaging.ts
> +    if(!reactors.includes(reactionMessage.from)) reactors = [...reactors, reactionMessage.from]
small change, please add space after `if`

2021-11-24 16:09 UTC, genie-magic commented on utilities/Messaging.ts
> +    if(!reactors.includes(reactionMessage.from)) reactors = [...reactors, reactionMessage.from]
@RetroPronghorn  I updated. thanks for your point.

2021-11-25 03:01 UTC, WanderingHogan approved these changes

2021-11-25 21:06 UTC, stavares843 commented
/rebase

2021-11-26 00:59 UTC, RetroPronghorn approved these changes

2021-11-26 00:59 UTC, merged