refactor(style): code refactor and clean up, added flair gradients
Satellite-im/Core-PWA pull request #3076
Opened 2022-05-06 17:20 UTC by ThomBos

**What this PR does** 📖
Moves all color/theme code into a single file in order to make it easier to change it
Added gradients for all flair colors

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-11 15:47 UTC, phillsatellite commented
Noticed something when first logged in, anything that is supposed to be default colored "#286CFE" it appears as black until the user sets moonlight theme and then back to default again

https://user-images.githubusercontent.com/93608357/167892247-08c7d55a-1aeb-4f7b-be7c-15efe31f960e.mov

2022-05-12 07:31 UTC, ThomBos commented
> Noticed something when first logged in, anything that is supposed to be default colored "#286CFE" it appears as black until the user sets moonlight theme and then back to default again
> 
>  resetting.theme.mov

If the account used isn't a new one, it's normal you get this issue: flairs are now passed as an array, but you have it just as a string.
Let me know if this is the case please 👍

2022-05-12 20:09 UTC, phillsatellite commented
@ThomBos Awesome I verified that I was using an old account, made a new one and verified that issue didnt happen 👍  I did see something a little shady I wanted to ask you about, should the notification message that appears when copying account id or sending request be themed as well? Right now it just appears as black with grey text

https://user-images.githubusercontent.com/93608357/168159533-639c05d9-e854-4f42-a881-b7d6832f0d17.mov

2022-05-12 20:16 UTC, ThomBos commented
> @ThomBos Awesome I verified that I was using an old account, made a new one and verified that issue didnt happen 👍 I did see something a little shady I wanted to ask you about, should the notification message that appears when copying account id or sending request be themed as well? Right now it just appears as black with grey text
> 
ah... yeah this isn't the correct behaviour. it should be colored with flair colors, thanks for reporting it! 👍

2022-05-16 09:54 UTC, molimauro commented on assets/styles/base.less
> +  --flair-color-secondary: #286cfe;
Can we use variables here instead of color value? I'd like to have all color values in one place like `colors.less`.

2022-05-16 10:15 UTC, ThomBos commented on assets/styles/base.less
> +  --flair-color-secondary: #286cfe;
it might look like a snake biting his tail, but it's possible doing it 👍 

anyway, that value gets overwritten when the app starts, so it's just like a placeholder

2022-05-17 09:37 UTC, molimauro commented on assets/styles/base.less
> +      background-color: rgba(var(--flair-color), 0.25);
here and in some other files we have to change this to @flair-color, can you check?

2022-05-17 09:43 UTC, ThomBos commented on assets/styles/base.less
> +      background-color: rgba(var(--flair-color), 0.25);
seems like something went wrong with the rebase, i go check it out

2022-05-17 14:57 UTC, ThomBos commented on assets/styles/base.less
> +      background-color: rgba(var(--flair-color), 0.25);
ok those variables are correct! i used css variables because rgba function doesn't work with less variables. (there are just 2 functions rgba)

2022-05-17 20:34 UTC, Jekrimo approved these changes

2022-05-18 07:46 UTC, molimauro commented on assets/styles/themes/moonless_night.less
> -        }
These colors are lost when active

dev

![image](https://user-images.githubusercontent.com/50131258/168985671-a7343ef2-52ac-49bc-ab92-9fadb90d6e08.png)

here

![image](https://user-images.githubusercontent.com/50131258/168985723-8d292aad-eae0-4552-be09-fc9b96fe9740.png)

2022-05-18 08:00 UTC, ThomBos commented on assets/styles/themes/moonless_night.less
> -        }
didn't notice both, thanks for reporting 🔨

2022-05-18 09:58 UTC, molimauro commented on components/interactables/Button/Button.less
> +  transition: 250ms all ease-in;
why this?

2022-05-18 10:26 UTC, molimauro commented on layouts/server.vue
> -    },
This was fixing a bug on safari [AP-1207](https://satellite-im.atlassian.net/browse/AP-1207)

2022-05-18 10:26 UTC, molimauro commented on layouts/friends.vue
> -    },
same bug

2022-05-18 10:27 UTC, molimauro commented on layouts/files.vue
> -    },
same bug

2022-05-18 16:24 UTC, ThomBos commented
i preferred to fix it in this way, still can go back though.
let me know what's the best way!

2022-05-18 16:27 UTC, ThomBos commented on components/interactables/Button/Button.less
> +  transition: 250ms all ease-in;
i was testing why buttons weren't working (they were keeping black/dark grey background at first),
but i forgot to remove it... do i have to change it? 😬

2022-05-19 07:05 UTC, molimauro commented
> i preferred to fix it in this way, still can go back though. let me know what's the best way!

Its ok as long as we dont reintroduce the bug resolved in the past. Did you check it? thanks :)

2022-05-19 07:06 UTC, molimauro commented on components/interactables/Button/Button.less
> +  transition: 250ms all ease-in;
I'd ask Liz if its ok to introduce a transition here ;)

2022-05-19 07:44 UTC, ThomBos commented
> > i preferred to fix it in this way, still can go back though. let me know what's the best way!
> 
> Its ok as long as we dont reintroduce the bug resolved in the past. Did you check it? thanks :)

yeah it's working right now! 👍 

the only issue you might have is the one phill reported, solved just changing theme once

2022-05-19 13:45 UTC, molimauro approved these changes

2022-05-19 13:58 UTC, stavares843 requested changes
when using the default blue theme, these warnings should be the same color as the theme, in this case, blue instead of red

this branch
<img width="1117" alt="Captura de ecrã 2022-05-19, às 14 57 07" src="https://user-images.githubusercontent.com/29093946/169311189-aef6f5fb-c220-4a01-b63b-83e54b62eca3.png">

dev


<img width="1067" alt="Captura de ecrã 2022-05-19, às 14 57 16" src="https://user-images.githubusercontent.com/29093946/169311206-eb5d9e74-7a87-4b94-a6e8-a6494f90339d.png">

2022-05-19 14:01 UTC, ThomBos commented
> when using the default blue theme, these warnings should be the same color as the theme, in this case, blue instead of red
> 
> this branch <img alt="Captura de ecrã 2022-05-19, às 14 57 07" width="1117" src="https://user-images.githubusercontent.com/29093946/169311189-aef6f5fb-c220-4a01-b63b-83e54b62eca3.png">
> 
> dev
> 
> <img alt="Captura de ecrã 2022-05-19, às 14 57 16" width="1067" src="https://user-images.githubusercontent.com/29093946/169311206-eb5d9e74-7a87-4b94-a6e8-a6494f90339d.png">

did you create that account right now? if not, you have to chage theme once to update and use the new flairs

2022-05-19 14:03 UTC, stavares843 requested changes
when you are using a theme example peach and hover on a already selected item

<img width="388" alt="Captura de ecrã 2022-05-19, às 15 02 44" src="https://user-images.githubusercontent.com/29093946/169312331-8e24c24f-99aa-45b8-a76e-1b555cc15782.png">
<img width="386" alt="Captura de ecrã 2022-05-19, às 15 02 48" src="https://user-images.githubusercontent.com/29093946/169312342-7af1d13b-bc5a-47d1-a44b-bc7b6b41cedc.png">

doesn't happen on dev

2022-05-19 14:10 UTC, stavares843 requested changes
the upgrade button on files should be grey

<img width="369" alt="Captura de ecrã 2022-05-19, às 15 09 24" src="https://user-images.githubusercontent.com/29093946/169314029-272c893d-0963-439c-943c-cb60900a7d92.png">

dev


<img width="362" alt="Captura de ecrã 2022-05-19, às 15 09 35" src="https://user-images.githubusercontent.com/29093946/169314053-2c8e0e46-93f0-4592-a139-e3f190e58ea6.png">

2022-05-19 14:15 UTC, stavares843 commented
> > when using the default blue theme, these warnings should be the same color as the theme, in this case, blue instead of red
> 
> did you create that account right now? if not, you have to chage theme once to update it and use the new flairs. ps. let me know if the issue persist 🐛
> 
> Edit. tested and got the same bug, going to fix it now



yes all the above was all with new accounts 💥

2022-05-19 14:18 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/169315997-a300d61d-b4ea-4f80-933a-881bcb4e33a2.mov

on this branch vs dev, its adding a shadow of the theme color on the call buttons on the corner, video above

2022-05-19 14:36 UTC, ThomBos commented
i've almost fixed all bugs above, but i think we should change something for the buttons: we have `:disabled` and `:active` html props, then ```.is-active``` and `.active` as css classes, and this is kinda messy when it's about styling and changing props... 
@molimauro are we going to make any refactor for that?

2022-05-19 14:51 UTC, stavares843 commented
thanks @ThomBos 🔨

2022-05-19 15:15 UTC, molimauro commented
> i've almost fixed all bugs above, but i think we should change something for the buttons: we have `:disabled` and `:active` html props, then `.is-active` and `.active` as css classes, and this is kinda messy when it's about styling and changing props... @molimauro are we going to make any refactor for that?

We're using buefy for the UI design so we have some predefined classes like `is-active` etc. I'm already considering ditching it in the future, we'll see when. But if there is one thing sure is that it'll be your job @ThomBos, you're our refactor man

2022-05-19 15:16 UTC, stavares843 commented
😂

2022-05-19 16:44 UTC, molimauro approved these changes

2022-05-19 17:51 UTC, phillsatellite commented
Hi Thomas! Everything above is fixed on my end! I only found one small issue when retesting, looks like the usernames in call are missing the grey box behind them. Other than that looked perfect thanks for everything! 🔥 
This branch 
<img width="1728" alt="flare branch" src="https://user-images.githubusercontent.com/93608357/169365220-5ecde448-7f79-49c9-96be-23d77be083c8.png">

Dev branch 
<img width="1728" alt="dev branch" src="https://user-images.githubusercontent.com/93608357/169365239-8bec78e3-85d9-4c5b-895a-ba041cb21c94.png">

2022-05-19 18:07 UTC, stavares843 commented
thanks @phillsatellite 🔨 

i'm gonna merge this and add that as a ticket

2022-05-19 18:08 UTC, stavares843 commented
[AP-1603](https://satellite-im.atlassian.net/browse/AP-1603)

2022-05-19 18:09 UTC, stavares843 approved these changes

2022-05-19 18:09 UTC, merged