feat(files): store export version number in threaddb
Satellite-im/Core-PWA pull request #3107
Opened 2022-05-10 08:24 UTC by josephmcg

**What this PR does** 📖
- move textile bucket index update to vuex action. Also update threaddb with new version number in that same action
- In a future PR, I will add a listener which checks for a threaddb update and pulls the most recent filesystem version from the bucket

**Which issue(s) this PR fixes** 🔨
AP-1522

**Special notes for reviewers** 🗒️
- no new functionality, just thought I would break this larger change into two parts

**Additional comments** 🎤

2022-05-11 16:55 UTC, phillsatellite approved these changes

2022-05-12 06:22 UTC, josephmcg commented
@phillsatellite , I improved the ux when you toggle those two settings. now it gets disabled while it's updating the remote textile value and provides a status message at the bottom

2022-05-13 02:28 UTC, josephmcg commented
@stavares843 thanks, I broke it with that ui refactor. should be better now

2022-05-19 16:44 UTC, iltumio commented
it looks like we are still using the old instance of textile hub for buckets:

BucketManager.ts line 51. Can you have a look at it?
```
    const result = await this.buckets.getOrCreate(
      `hub.textile.io/ipfs/${this.identity}/${this.prefix}`,
    )
```

2022-05-19 23:30 UTC, josephmcg commented
> it looks like we are still using the old instance of textile hub for buckets:
> 
> 
> 
> BucketManager.ts line 51. Can you have a look at it?
> 
> ```typescript
> 
>     const result = await this.buckets.getOrCreate(
> 
>       `hub.textile.io/ipfs/${this.identity}/${this.prefix}`,
> 
>     )
> 
> ```

I can see why it appears that way, but that's just the cosmetic bucket name. Like how the personal files encrypted bucket is named 'personal-files'. I ultimately plan on switching chat to use the newer Bucket class

2022-05-20 13:10 UTC, iltumio commented
Perfect. Thanks for the explanation. We should chose a better name that is agnostic to the platform we are using

2022-05-23 14:47 UTC, iltumio requested changes
Looks like this PR is still waiting for Textile initialization

2022-05-23 14:47 UTC, iltumio commented on store/textile/actions.ts
> +      console.log('update', update.instance)
remove console log

2022-05-23 14:47 UTC, iltumio commented on store/textile/actions.ts
> +        console.log('todo - update file system based on bucket index')
remove console log or use custom logger

2022-05-23 14:47 UTC, iltumio commented on store/ui/getters.test.ts
> +    // const result: any = inst.isFilesIndexLoading(InitialUIState())
should we keep this comment as reference for the QA team or remove them?

2022-05-23 15:05 UTC, stavares843 commented on store/ui/getters.test.ts
> +    // const result: any = inst.isFilesIndexLoading(InitialUIState())
was this failing? @josephmcg i can ask andre to update this

2022-05-24 00:58 UTC, josephmcg commented
yep, it's been sitting here for a week or two so I'm not surprised it's outdated. I'll rebase and clean up logs

![image](https://user-images.githubusercontent.com/33670767/169927416-9e200a46-0d0a-4b47-b619-85ade1a9b9a7.png)

2022-05-24 01:09 UTC, josephmcg commented on store/ui/getters.test.ts
> +    // const result: any = inst.isFilesIndexLoading(InitialUIState())
yeah i changed the getter to disable file system ui while textile is initializing. thanks for catching

2022-05-25 15:21 UTC, molimauro commented on libraries/Textile/UserManager.ts
> +      return await this._findRecord()
return await redundant, simply return :)

2022-05-26 03:57 UTC, josephmcg commented on store/ui/getters.test.ts
> +    // const result: any = inst.isFilesIndexLoading(InitialUIState())
@stavares843 I would appreciate Andre's help in fixing this, thanks

2022-05-26 06:58 UTC, molimauro approved these changes

2022-05-27 16:40 UTC, phillsatellite approved these changes

2022-05-28 00:41 UTC, stavares843 requested changes
when sending a file on the chat example a zip returns always this error, doesn't happen on the dev branch

<img width="1387" alt="Captura de ecrã 2022-05-28, às 01 40 04" src="https://user-images.githubusercontent.com/29093946/170802968-a15cbf2a-6676-4ee5-8a71-52771ba919b9.png">

2022-05-28 00:43 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/170803012-972d1f6b-7f50-4546-ba14-61d87f4efa87.mov

if you already gave the permissions to scan files, and the chat is loading and you try to upload a file will say to the user to consent the permission but the permission was already there

2022-05-28 00:47 UTC, stavares843 requested changes
<img width="543" alt="Captura de ecrã 2022-05-28, às 01 01 52" src="https://user-images.githubusercontent.com/29093946/170803156-8e1927a4-5d8e-4bb3-8448-3f7e397665fa.png">

minor but noticed the toggle appears all grey out when updating, considering is a toggle seems a layout bug

2022-05-28 00:58 UTC, stavares843 commented
to not block any further work I will get this merged and add tickets for the stuff above

2022-05-28 01:00 UTC, stavares843 commented
[AP-1653](https://satellite-im.atlassian.net/browse/AP-1653)
[AP-1654](https://satellite-im.atlassian.net/browse/AP-1654)
[AP-1655](https://satellite-im.atlassian.net/browse/AP-1655)

2022-05-28 01:00 UTC, stavares843 approved these changes

2022-05-28 01:01 UTC, merged