Ap 1549
Satellite-im/Core-PWA pull request #3159
Opened 2022-05-13 14:31 UTC by WanderingHogan

**What this PR does** 📖
This PR adds back in the offline notices in dm and group chat.

**Which issue(s) this PR fixes** 🔨
AP-1549

**Special notes for reviewers** 🗒️
Added a third state for 'All users are offline'

**Additional comments** 🎤

2022-05-16 05:07 UTC, josephmcg requested changes

2022-05-16 05:07 UTC, josephmcg commented on components/views/chat/chatbar/footer/is-connected/Connected.vue
> +        }
dynamic translation would be a lot better. checkout how I did it for `'pages.files.item_count'` 
good links
https://vue-i18n.intlify.dev/guide/essentials/syntax.html
https://vue-i18n.intlify.dev/guide/essentials/pluralization.html

2022-05-16 15:11 UTC, WanderingHogan commented on components/views/chat/chatbar/footer/is-connected/Connected.html
> +    :class="`status is-${ participantStatus.CONNECTED.length > 0 ? $t('ui.online') : $t('ui.offline') }`"
good eye on the not using translations here, but we have to keep length > 0 because an empty array would still evaluate as true

2022-05-16 15:56 UTC, WanderingHogan commented on components/views/chat/chatbar/footer/is-connected/Connected.vue
> +    ...mapState(['friends', 'conversation']),
good idea

2022-05-17 01:08 UTC, josephmcg commented on components/views/chat/chatbar/footer/is-connected/Connected.html
> +    :class="`status is-${ participantStatus.CONNECTED.length > 0 ? $t('ui.online') : $t('ui.offline') }`"
i was saying you can just do array.length. it will either be 0 (falsy) or non-zero (truthy)

2022-05-17 01:10 UTC, josephmcg commented on components/views/chat/chatbar/footer/is-connected/Connected.html
> +    :class="`status ${ participantStatus.CONNECTED.length > 0 ? 'is-online' : 'is-offline' }`"
it would be just .online or .offline, yes?

2022-05-17 01:20 UTC, josephmcg commented on components/views/chat/chatbar/footer/is-connected/Connected.vue
> +        }
oh my bad, I'll take a closer look at the logic and see if I can come up with anything. idk I guess it uses the same principles lol

2022-05-17 03:10 UTC, WanderingHogan commented on locales/en-US.js
> +    all_offline: 'All Users are Offline',
you can delete this now

2022-05-17 12:25 UTC, molimauro approved these changes

2022-05-17 12:25 UTC, molimauro commented
Love the getters

2022-05-17 13:55 UTC, stavares843 requested changes
<img width="346" alt="Captura de ecrã 2022-05-17, às 14 53 34" src="https://user-images.githubusercontent.com/29093946/168827497-9c7aa029-b2f7-42a0-b3b5-e590af4c141f.png">

before

now

<img width="353" alt="Captura de ecrã 2022-05-17, às 14 52 32" src="https://user-images.githubusercontent.com/29093946/168827543-c2d85d22-c0eb-4f9d-acf3-b6286aba9dc5.png">


its appearing but the username is no longer bold and says offline instead of connected

2022-05-17 17:17 UTC, WanderingHogan commented
don't worry about the bold RN, language updated to be what you want

2022-05-17 18:22 UTC, stavares843 approved these changes

2022-05-17 18:22 UTC, merged

2022-05-17 18:22 UTC, stavares843 commented
thanks @WanderingHogan 🔨