fix(status): position and size of status
Satellite-im/Core-PWA pull request #3160
Opened 2022-05-13 14:34 UTC by AlexZakablukov

**What this PR does** 📖
fix position and size of status (on the message list on the sidebar it was slightly wrong)

**Which issue(s) this PR fixes** 🔨
[AP-1462](https://satellite-im.atlassian.net/browse/AP-1462)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-16 05:29 UTC, josephmcg requested changes

2022-05-16 05:29 UTC, josephmcg commented on components/ui/User/State/State.less
>    }
I would probably setup a variable, then change the value of the variable for .is-large. something like this
`  .circle {
    --circle-size: 8px;
    mask: radial-gradient(circle var(--circle-size) at 86% 86%, #0000 98%, #000)
      100% 100%/100% 100% no-repeat;
    overflow: hidden;
    &.is-large {
      --circle-size: 12px;
    }
  }`

2022-05-16 05:29 UTC, josephmcg commented on components/views/chat/group/Group.html
> +      :size="36"
any place you're passing in the default of 36 can be removed, right?

2022-05-17 08:09 UTC, AlexZakablukov commented on components/ui/User/State/State.less
>    }
great point, thx)

2022-05-17 08:14 UTC, AlexZakablukov commented on components/views/chat/group/Group.html
> +      :size="36"
ofc, I removed them

2022-05-17 08:15 UTC, AlexZakablukov commented
fixed

2022-05-17 08:39 UTC, josephmcg approved these changes
great, thanks Alex

2022-05-17 14:02 UTC, stavares843 approved these changes

2022-05-19 11:10 UTC, AlexZakablukov commented
fixed

2022-05-20 15:54 UTC, phillsatellite approved these changes

2022-05-20 16:53 UTC, molimauro commented
On non-retina screens i see the problem persisting. I'm fixing it, in the meanwhile let this PR go in since it contains useful minor improvements :)

2022-05-20 16:53 UTC, molimauro approved these changes

2022-05-20 16:57 UTC, stavares843 approved these changes

2022-05-20 16:57 UTC, merged