Feat(Timestamp): Add timestamp to Message Actions (AP-106)
Satellite-im/Core-PWA pull request #318
Opened 2021-11-26 00:41 UTC by nickjjang

2021-11-26 04:08 UTC, RetroPronghorn commented on components/tailored/messaging/message/Message.html
>        :messageOwner="this.$props.message.from" />
can we nuke the messageOwner prop if we're passing in the whole message?

2021-11-26 16:37 UTC, nickjjang commented on components/tailored/messaging/message/Message.html
>        :messageOwner="this.$props.message.from" />
removed messageOwner

2021-11-27 14:47 UTC, Jekrimo approved these changes

2021-11-28 19:34 UTC, nickjjang commented
@RetroPronghorn will you review it again?

2021-11-29 16:31 UTC, RetroPronghorn requested changes

2021-11-29 16:31 UTC, RetroPronghorn commented on components/tailored/messaging/message/actions/Actions.vue
> +    }
comma dangle missing

2021-11-29 16:53 UTC, RetroPronghorn approved these changes

2021-11-29 16:53 UTC, merged