feat(sounds): combine deafen/undeafen into one toggle control
Satellite-im/Core-PWA pull request #3218
Opened 2022-05-18 04:56 UTC by jasonwoodland

**What this PR does** 📖
- Removes the undeafen sound toggle in the audio & video settings.
- Adds a `toggleSounds` method which accepts an array of `Sounds` to set the value
- Combines the deafen/undeafen sounds into one toggle control

**Which issue(s) this PR fixes** 🔨
AP-1537

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-18 14:53 UTC, Jekrimo requested changes

2022-05-18 14:53 UTC, Jekrimo commented on components/views/settings/pages/audio/sounds/Sounds.vue
> +      }
can we use a forEach() here? lika:

keys.forEach((key) => this.$store.commit('sounds/set', { key, value }))

2022-05-19 04:14 UTC, jasonwoodland commented on components/views/settings/pages/audio/sounds/Sounds.vue
> +      }
Hey @Jekrimo, nice to meet you! Can you explain the benefit of `forEach` in this scenario?
The for...of statement iterates over iterable objects, including arrays in this case.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

2022-05-23 00:59 UTC, josephmcg commented on components/views/settings/pages/audio/sounds/Sounds.vue
> +      }
for of is good here, it also allows for object shorthand in the mutation params. this page provides some good distinctions between the various iterators https://thecodebarbarian.com/for-vs-for-each-vs-for-in-vs-for-of-in-javascript.html

marking as resovled

2022-05-23 01:25 UTC, josephmcg requested changes
could you update the mute settings in the same way? it still has a sound effect when you toggle mute `on`.

Unrelated, but I was confused by this settings section at first. I think a sentence explaining that these are sound effects settings would be helpful. probably better in a separate ticket though

2022-05-23 05:07 UTC, jasonwoodland commented
@josephmcg combined unmute into mute.
I think the section title could change, maybe just "Notifications"?
If there's a paragraph you can write up I'll add it in another ticket.

2022-05-23 05:33 UTC, josephmcg requested changes

2022-05-23 05:33 UTC, josephmcg commented on components/views/settings/pages/audio/sounds/Sounds.html
> +    @toggle="toggleSound([Sounds.MUTE, Sounds.UNMUTE], $event)"
toggleSound**s**

2022-05-23 05:39 UTC, josephmcg approved these changes

2022-05-23 07:19 UTC, molimauro commented
> could you update the mute settings in the same way? it still has a sound effect when you toggle mute `on`.
> 
> Unrelated, but I was confused by this settings section at first. I think a sentence explaining that these are sound effects settings would be helpful. A user could easily think that these settings control the actual mute/deafen. probably better in a separate ticket though

I'm confused too honestly. Why should be combine mute/unmute and deafen/undeafen? I was reading those settings as: If i have the switch on for mute and off for unmute it means sound will be played once i mute but not when i unmute. So i would have add here only the unmute switch and nothing else. Or am i wrong? What do you guys think? :)

2022-05-23 07:21 UTC, josephmcg commented
@molimauro the whole concept just seems strange to me. I think audio indicators for significant setting changes (mute, video) are a good thing. I can't imagine wanting to disable them from a user perspective

2022-05-23 17:28 UTC, molimauro commented
i talked with Liz and it's ok to combine deafen/undeafen for now for keeping things simple. If users will complain in the future we'll split them ;) Thanks for your patience!

2022-05-23 17:29 UTC, molimauro approved these changes

2022-05-23 18:18 UTC, stavares843 commented
thanks @molimauro 🔨

2022-05-23 18:20 UTC, stavares843 commented
added ticket [here](https://satellite-im.atlassian.net/browse/AP-1619) 🔨

2022-05-23 18:20 UTC, stavares843 approved these changes

2022-05-23 18:20 UTC, merged