feat(friends): autofocus add friend input if you have no friends
Satellite-im/Core-PWA pull request #3222
Opened 2022-05-18 06:31 UTC by jasonwoodland

**What this PR does** 📖
- Adds an `autofocus` prop to the InputGroup component
- Autofocuses the add friend input field if there are no friends

**Which issue(s) this PR fixes** 🔨
AP-1572

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-18 07:06 UTC, josephmcg requested changes

2022-05-18 07:06 UTC, josephmcg commented on components/views/friends/add/Add.vue
> +    },
1. could you add typescript return doc `hasNoFriends(): boolean`? if any computed are missing return types, the context of `this` breaks in the file. plus documentation is good :)
2. this works, but we typically use mapState when accessing store. could you update the file like this?
`...mapState({
      activeAccount: (state) => (state as RootState).accounts.active,
      allFriends: (state) => (state as RootState).friends.all,
    }),`

name the mapped variables however you like, this was just an example

2022-05-18 07:13 UTC, josephmcg commented on components/views/friends/add/Add.vue
> +    },
also from a ux perspective I actually like this being autofocused regardless of how many friends the user has. if i were to click this page, it would most likely be to add a friend (just paste, rather than click and paste)

2022-05-18 07:27 UTC, jasonwoodland commented on components/views/friends/add/Add.vue
> +    },
updated to autofocus unconditionally!

2022-05-18 07:27 UTC, josephmcg approved these changes

2022-05-18 08:14 UTC, josephmcg commented on components/views/friends/add/Add.html
> +    autofocus
thought about this some more. could we autofocus true on desktop, false for mobile?
you can use `$device.isMobile`
the virtual keyboard coming up everytime would be kind of annoying

2022-05-19 04:34 UTC, josephmcg commented on components/views/friends/add/Add.html
> +    autofocus
nvm, mobile layout doesn't render this component

2022-05-19 04:37 UTC, josephmcg approved these changes

2022-05-19 13:36 UTC, stavares843 commented
sounds good, thanks 🔨

2022-05-19 13:36 UTC, stavares843 approved these changes

2022-05-19 13:36 UTC, merged