David/fixing
Satellite-im/Core-PWA pull request #323
Opened 2021-11-27 04:37 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨
I added :server field on the <TailoredCoreStatusbar> component
Fixes #
Chat Window Status Bar User Info
**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-11-27 14:44 UTC, Jekrimo approved these changes

2021-11-27 22:30 UTC, stavares843 requested changes

2021-11-27 22:30 UTC, stavares843 commented on store/friends/actions.ts
> +      commit('updateFriend', friend);
remove ;

not supposed to be used on the project

2021-11-27 22:50 UTC, stavares843 reviewed
status bar dynamic content is working ✅ 
<img width="1176" alt="Captura de ecrã 2021-11-27, às 22 37 48" src="https://user-images.githubusercontent.com/29093946/143722548-8a4dcda6-42db-4e97-961d-804e1ad92b76.png">

2021-11-29 15:34 UTC, WanderingHogan commented on store/friends/actions.ts
> +    } else {
can you also get rid of this else statement - something like
```
if() {
  // logic
  return
} 
commit('updateFriend', friend)
```

2021-11-29 15:35 UTC, WanderingHogan requested changes
use guard pattern instead of else

2021-11-29 16:35 UTC, WanderingHogan commented
The last change are the semi colons, everything else looks good!

2021-11-29 16:54 UTC, RetroPronghorn approved these changes

2021-11-29 16:55 UTC, WanderingHogan approved these changes

2021-11-29 17:57 UTC, stavares843 approved these changes

2021-11-29 17:58 UTC, merged