Ap1581
Satellite-im/Core-PWA pull request #3236
Opened 2022-05-19 06:38 UTC by jasonwoodland

**What this PR does** 📖
- update `$store.dispatch` calls for toggling audio/video muting in sidebar so that the buttons behave correctly.
- fix audio stream indicator visibility logic in media/user component so it only shows the audio stream indictor when unmuted.

**Which issue(s) this PR fixes** 🔨
AP-1581

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-19 13:37 UTC, Jekrimo approved these changes

2022-05-19 15:09 UTC, phillsatellite commented
Tested: Found a crash when trying to make a phone call Browsers used were Chrome and Brave 🚀 
https://user-images.githubusercontent.com/93608357/169329424-97b31c69-bfe5-42f8-9802-f4fcf69ecb17.mov

2022-05-20 03:06 UTC, jasonwoodland commented
@phillsatellite thanks for spotting it! Fixed in last commit

2022-05-20 16:25 UTC, stavares843 commented
thanks @jasonwoodland 🔨

2022-05-20 16:26 UTC, phillsatellite commented
Retested: Crash is gone! Functionality was good on my end the only differences I noticed from this branch and dev is the sound feedback that happens when the user hits mute or video

https://user-images.githubusercontent.com/93608357/169571403-b4897233-06cb-49aa-a95a-87d6fcad55c2.mov

2022-05-23 05:31 UTC, josephmcg requested changes
mic and video toggles no longer work
![image](https://user-images.githubusercontent.com/33670767/169749923-8364527d-b7ad-4a7a-9151-90aa7a0e6d50.png)

2022-05-23 05:31 UTC, josephmcg commented on components/views/media/user/User.html
> +      :class="`${audioStream ? 'calling' : ''}`"
this has some unnecessary wrappers
`:class='{calling : audioStream}'`

2022-05-23 06:44 UTC, jasonwoodland commented on components/views/media/user/User.html
> +      :class="`${audioStream ? 'calling' : ''}`"
fixed the class

2022-05-23 06:45 UTC, jasonwoodland commented on components/views/media/user/User.html
> +      :class="`${audioStream ? 'calling' : ''}`"
I can't reproduce the bug you're getting with the toggle buttons

2022-05-24 12:13 UTC, stavares843 commented
rebase wasn't working, added latest dev here to update Cypress

2022-05-24 19:59 UTC, phillsatellite approved these changes

2022-05-24 20:47 UTC, Clayton215 approved these changes

2022-05-24 23:30 UTC, josephmcg reviewed
The mute/video toggles don't work while you are not in a call. If this is intended functionality, then this is ok

2022-05-25 04:07 UTC, jasonwoodland commented
@stavares843 I made some other changes to sync the muted state in the sidebar with the active calls. (see [234b7b7](https://github.com/Satellite-im/Core-PWA/pull/3236/commits/234b7b7dc533f0d7516544f0e275953431b66f79)) So please re-review!

2022-05-25 07:33 UTC, josephmcg requested changes
change the first line of Actions.vue to this. I've noticed linting breaks if the template is self closing
![image](https://user-images.githubusercontent.com/33670767/170205443-855e5630-9820-42d8-909a-0ddb9252920a.png)

2022-05-25 07:33 UTC, josephmcg commented on store/audio/actions.ts
>      }
we typically use guard clauses, could you rewrite?
`if (!call) {
        return
      }
      if (muted) {
        call.mute({ kind: 'audio' })
        return
      }
      call.unmute({ kind: 'audio' })
`

2022-05-25 07:33 UTC, josephmcg commented on components/views/media/actions/Actions.vue
>      toggleMute(kind = 'audio') {
this automatic value is never used. could we use keyof PeerMutedState for kind param

2022-05-25 07:33 UTC, josephmcg commented on components/views/navigation/sidebar/controls/Controls.vue
>      async toggleMute(kind = 'audio') {
could do same improvement here for types. also change self closing template at the top

2022-05-26 01:37 UTC, josephmcg commented on store/audio/actions.ts
>      }
double check your implementation of this. we want to eliminate else. we also want to return if `!call`, right?

2022-05-26 02:18 UTC, josephmcg requested changes
check previous comment

2022-05-26 02:35 UTC, jasonwoodland commented
@josephmcg fixed!

2022-05-26 02:36 UTC, jasonwoodland commented on store/audio/actions.ts
>      }
my bad, fixed

2022-05-26 03:46 UTC, josephmcg commented on store/audio/actions.ts
> +    call.unmute({ kind: 'audio' })
guard clause still funky, missing return

2022-05-26 03:51 UTC, josephmcg approved these changes

2022-05-26 17:49 UTC, stavares843 requested changes
the video toggle doesn't work if you are not on a call, works on dev

<img width="288" alt="Captura de ecrã 2022-05-26, às 18 48 13" src="https://user-images.githubusercontent.com/29093946/170546122-4c37a9f0-ac9c-40de-866f-bcef1bc81325.png">


btw I noticed when hovering it says ''Toggle'' but that issue is on dev as well so I added a ticket [here](https://satellite-im.atlassian.net/browse/AP-1637)

2022-05-27 22:30 UTC, WanderingHogan commented
@stavares843 I don't think we actually want to allow the video toggle if you are not on a call since we are forcing all calls to start as audio. I think another ticket to disable the button when not on a call might be warranted, what do you think?

2022-05-27 22:46 UTC, stavares843 commented
sounds good, thanks @WanderingHogan 🔨

2022-05-27 22:47 UTC, stavares843 commented
added ticket [here](https://satellite-im.atlassian.net/browse/AP-1647)

2022-05-27 23:02 UTC, stavares843 approved these changes

2022-05-27 23:02 UTC, merged