feat(call): add permission error alert for screen sharing
Satellite-im/Core-PWA pull request #3244
Opened 2022-05-20 01:08 UTC by jasonwoodland

**What this PR does** 📖
Adds a notification if the browser doesn't have permission to screen share

**Which issue(s) this PR fixes** 🔨

AP-1545
**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-20 16:15 UTC, stavares843 requested changes

2022-05-20 16:15 UTC, stavares843 commented on libraries/WebRTC/Call.ts
> +      alert(
can you add this on [locales](https://github.com/Satellite-im/Core-PWA/blob/dev/locales/en-US.js) pls? 🔨

2022-05-23 04:35 UTC, jasonwoodland commented on libraries/WebRTC/Call.ts
> +      alert(
@stavares843 done! Now it shows an error toast instead of a native alert too.

2022-05-23 05:37 UTC, josephmcg commented on libraries/WebRTC/Call.ts
> +      throw new Error('errors.webRTC.permission_denied')
since we're throwing the same string, could you make an enum for this? either create a new error file in the same folder, or add the enum to this class.

there are other error messages that should be added to that enum/translated too, but I understand how difficult it can be to track all of them down. We can do those in a separate ticket

2022-05-25 06:27 UTC, josephmcg approved these changes

2022-05-25 15:55 UTC, stavares843 commented
thanks @phillsatellite 🔨

2022-05-26 03:10 UTC, jasonwoodland commented
@phillsatellite @stavares843 I tried with opera and opera GX and both crashed. It was crashing on dev and this branch, so I think it's an opera-specific issue.

https://user-images.githubusercontent.com/5356544/170407811-64c0df1b-bb8e-419a-9f16-293cfe42d078.mov

2022-05-26 03:40 UTC, josephmcg commented
good catch Phill, thanks for your thorough testing. While overall support would be wonderful, Opera is ~2% of market share at the moment. If it works on the major browsers, I would suggesting merging this and creating a separate ticket for Opera support

2022-05-26 13:33 UTC, stavares843 commented
thanks @phillsatellite for testing 🔨 

and thanks for checking @josephmcg @jasonwoodland 💥 if this is opera only, I agree with joe as well in fixing separately

2022-05-27 22:29 UTC, WanderingHogan approved these changes

2022-05-30 18:24 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/171044281-f48297a6-c055-4ce8-8166-e4ede7379b81.mov

this branch vs dev

we don't need to trigger the permissions denied error when the user just cancelled the share

2022-06-01 00:04 UTC, josephmcg approved these changes

2022-06-01 19:57 UTC, stavares843 approved these changes

2022-06-01 19:57 UTC, merged