AP-1158: Blockchain client integration
Satellite-im/Core-PWA pull request #3249
Opened 2022-05-20 13:42 UTC by JustZacca

**What this PR does** 📖
This PR implements the new BlockchainClient / Solana adapter, which is an abstraction of the other Solana programs. 

**Which issue(s) this PR fixes** 🔨
This PR will be useful for future Blockchain integrations, since we have abstracted the Solana programs, the integration of a new network will be easier, since now it is enough to create a new adapter or modify the already existing one to be able to carry out the integration.

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/BlockchainClient.ts
> +import {
<img width="501" alt="Captura de ecrã 2022-05-20, às 23 07 00" src="https://user-images.githubusercontent.com/29093946/169618583-11e13ff6-4bd7-411c-89a3-71c7cf887aef.png">

most of these imports are not being used

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/BlockchainClient.ts
> +   * /
do we need a multi-line comment for this?

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/BlockchainClient.ts
> +   */
do we need a multi-line comment for this?

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +import {
<img width="593" alt="Captura de ecrã 2022-05-20, às 23 08 54" src="https://user-images.githubusercontent.com/29093946/169618723-4859b598-4416-431e-959e-20078672621e.png">

imports not used 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = null
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +   */
is there any further docs to add here?

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +   */
is there any further docs to add here?

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +    // this.friendsProgram = new FriendsProgram(this.solanaManager)
do we need this commented out? 🔨

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
> +   */
any further info to add here?

2022-05-20 22:11 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/utils.ts
> +import { Keypair, PublicKey } from '@solana/web3.js'
<img width="461" alt="Captura de ecrã 2022-05-20, às 23 10 55" src="https://user-images.githubusercontent.com/29093946/169618867-a5fc3211-7a94-4138-9c00-bcd0afc8d8f5.png">

not used imports 🔨

2022-05-20 22:17 UTC, stavares843 commented on libraries/BlockchainClient/interfaces.ts
> +  UNINITALIZED,
typo should say - UNINITIALIZED

2022-05-20 22:17 UTC, stavares843 commented
also please install prettier locally 🔨

2022-05-23 01:30 UTC, JustZacca commented on libraries/BlockchainClient/interfaces.ts
> +  UNINITALIZED,
I can't change the typo because it would conflict with the FriendsProgram since in the friendsprogra.types.ts there is the same error.

Should I modify even that?

2022-05-23 13:58 UTC, stavares843 commented on libraries/BlockchainClient/interfaces.ts
> +  UNINITALIZED,
there isn't, that's updated on dev

2022-05-23 13:58 UTC, stavares843 commented on libraries/BlockchainClient/interfaces.ts
> +  UNINITALIZED,
https://github.com/Satellite-im/Core-PWA/blob/dev/libraries/Solana/FriendsProgram/FriendsProgram.types.ts#L2

2022-05-23 14:06 UTC, JustZacca commented on libraries/BlockchainClient/interfaces.ts
> +  UNINITALIZED,
okay, I'll fix that

2022-05-23 15:19 UTC, iltumio requested changes
The blockchain client/adapter can be abstracted even more

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.getUserInfo(userAddress)
if this.adapter.getUserInfo already returns a Promise, there is no need for the await keyword

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +  async subscribeToEvents(): Promise<void> {
this function looks sync

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.getFriendsPayer()
non need for the await keyword

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.makeFriendRequest(request, first, second, k)
no need for the await keyword

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.acceptFriendRequest(request, k)
same

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.removeFriendRequest(request)
same

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.createGroup(groupId, name)
same

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.getUserGroups(address)
same

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.getGroupsUsers(groupIds)
same

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.addGroupListener(id, cb)
same

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.getGroupById(groupId)
same

2022-05-23 15:19 UTC, iltumio commented on libraries/BlockchainClient/BlockchainClient.ts
> +    return await this.adapter.getGroupUsers(groupId)
same

2022-05-23 15:19 UTC, iltumio commented on plugins/local/classLoader.ts
> +Vue.prototype.$BlockchainClient = new BlockchainClient(new SolanaAdapter())
can we use the singleton pattern like we did for Libp2p?

2022-05-23 15:19 UTC, iltumio commented on store/friends/actions.test.ts
> +  /* test('module.default.removeFriend without payer account', async () => {
are this commented as reference for the QA team?

2022-05-23 15:19 UTC, iltumio commented on store/friends/actions.ts
> +    const $BlockchainClient: BlockchainClient = Vue.prototype.$BlockchainClient
to update if we use the singleton pattern

2022-05-23 15:24 UTC, JustZacca commented on store/friends/actions.test.ts
> +  /* test('module.default.removeFriend without payer account', async () => {
Yes, this was failing so me and Pavel thought to just comment it out

2022-05-23 15:24 UTC, stavares843 commented on store/friends/actions.test.ts
> +  /* test('module.default.removeFriend without payer account', async () => {
@drepram tomorrow can you take a look at this test and update directly here pls? thanks 🔨

2022-05-25 11:14 UTC, drepram commented on store/friends/actions.test.ts
> +  /* test('module.default.removeFriend without payer account', async () => {
Hey! I put a fix, please check and let me know what you think 😄

2022-05-25 11:14 UTC, stavares843 commented on store/friends/actions.test.ts
> +  /* test('module.default.removeFriend without payer account', async () => {
thanks for adding 🔨

2022-05-30 15:59 UTC, stavares843 commented
<img width="787" alt="Captura de ecrã 2022-05-30, às 16 58 33" src="https://user-images.githubusercontent.com/29093946/171027885-3e442c8f-c713-4af2-afc9-c0eab67d7612.png">

store/friends/actions.test.ts is failing on this branch 🔨

2022-06-01 09:51 UTC, iltumio approved these changes

2022-06-01 18:54 UTC, phillsatellite approved these changes

2022-06-03 11:15 UTC, pavlzk approved these changes
I have couple of notes about implementation, but it will take some time to make changes so corresponding tasks will be added later after merge

2022-06-03 15:24 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/171883879-0726caeb-e63b-4cef-83da-5b723c53bf84.mov


i made 2 new accounts
added both as friends
user A sends message to user B or image or glyph, user B doesn't get any of the messages and vice versa

2022-06-03 15:35 UTC, stavares843 requested changes
also when importing a wrong seed is not showing the error message we have


dev

<img width="1040" alt="Captura de ecrã 2022-06-03, às 16 34 17" src="https://user-images.githubusercontent.com/29093946/171890115-ebe27a91-2ded-4bc6-978f-3df2991e62c2.png">


this branch

<img width="999" alt="Captura de ecrã 2022-06-03, às 16 34 14" src="https://user-images.githubusercontent.com/29093946/171890280-d84b1a3f-b84b-43e7-83a5-21400f71281f.png">

how to reproduce
- import account
- use a non existent seed
- wrong error is displayed

2022-06-06 16:12 UTC, stavares843 requested changes
<img width="419" alt="Captura de ecrã 2022-06-06, às 17 12 11" src="https://user-images.githubusercontent.com/29093946/172200818-944d959c-8a0e-4558-8e7b-2351990836ad.png">

this is adding the submodules again 🔨

2022-06-06 16:13 UTC, JustZacca commented
> <img alt="Captura de ecrã 2022-06-06, às 17 12 11" width="419" src="https://user-images.githubusercontent.com/29093946/172200818-944d959c-8a0e-4558-8e7b-2351990836ad.png">
> 
> this is adding the submodules again 🔨

okay, what should I do to fix that?

2022-06-06 16:16 UTC, stavares843 commented
`git rm android`
`git rm electron`

2022-06-06 16:23 UTC, stavares843 commented
thanks 🔨

2022-06-08 19:35 UTC, tooshel approved these changes

2022-06-09 00:47 UTC, stavares843 requested changes
![image](https://user-images.githubusercontent.com/29093946/172740969-503198d4-83df-4d23-a381-87a8109003cf.png)

opening any chat returns the above error

works fine on dev and other branches

seed
end electric swear hurdle business priority salad ancient wire change please purpose

2022-06-09 06:22 UTC, JustZacca commented
Is funny how every time you get errors I've never got before 

Yesterday we tested and got nothing like that, can you please tell me exactly what you did? 
@stavares843

2022-06-09 07:57 UTC, JustZacca commented
Okay, found the error, It was because of a recent Push that changed some stuff on the EventListener

2022-06-09 14:55 UTC, phillsatellite approved these changes

2022-06-09 15:06 UTC, stavares843 commented
thanks for fixing 🔨

2022-06-09 15:06 UTC, merged