feat(import account): 'Create Import Account Page, linked from Import Account button'
Satellite-im/Core-PWA pull request #327
Opened 2021-11-29 11:37 UTC by genie-magic

**What this PR does** 📖
This PR is draft preparation PR for Import account bip39.
Create import account button and implement basic ui/ux
**Which issue(s) this PR fixes** 🔨
Jira ref: AP-15
**Special notes for reviewers** 🗒️
@WanderingHogan 
1. Do we need to update InteractablesInputGroup component for showing limited bip39 words?
2. When we input all 12 phrases and click recover button, which function do I need to call ?
3. Do we need to add option to remove added phrases?

2021-11-29 14:52 UTC, Jekrimo approved these changes

2021-11-29 18:03 UTC, WanderingHogan commented
Per your notes:
1. We don't want to show the words, but we want to limit what the typeahead lets them click to be just bip39 words
2. I am not sure of the exact function - I think it is `loadAccount` from `store/accounts/actions.ts`, but we might need to add a method in here. If that is the case can you make another subtasks ticket for it?
3. Yes - the user needs to be able to remove words that they didn't intend to type. That word should be added back to the list of potential words they can pick

2021-12-01 03:38 UTC, WanderingHogan requested changes
Great work, works well. One change - `middleware/authenticated.ts` forces you to be routed to /setup/disclaimer if you don't have a phrase and are not locked, update that to allow navigating to the import account page

2021-12-01 03:39 UTC, WanderingHogan commented
Also - I was wrong re: `1. We don't want to show the words, but we want to limit what the typeahead lets them click to be just bip39 words` but you wont have the data to make that until you do the bip39 service ticket, and the new AP-154 typeahead ticket

2021-12-01 03:51 UTC, WanderingHogan approved these changes

2021-12-01 08:27 UTC, RetroPronghorn requested changes
Can you rebase to dev, this is hard to read which changes are yours vs stuff from other PRs

2021-12-01 08:27 UTC, RetroPronghorn commented on .eslintrc.js
> -    'comma-dangle': ['error', 'never'],
why was this removed?

2021-12-01 08:27 UTC, RetroPronghorn commented on components/tailored/messaging/message/actions/Actions.html
> +  <div class="reply-text">{{$dayjs(message.at).from()}}</div>
Small change, please add a newline and add spacing after `{{`

2021-12-01 08:27 UTC, merged