refactor(scrollbar): spread new scroll component
Satellite-im/Core-PWA pull request #3284
Opened 2022-05-24 08:13 UTC by ThomBos

**What this PR does** 📖
Substitutes old scroll component with a new native one
**Which issue(s) this PR fixes** 🔨
AP-1604

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-24 13:50 UTC, molimauro commented on assets/styles/base.less
> +      box-sizing: border-box;
why this?

2022-05-24 13:54 UTC, molimauro commented on components/views/chat/chatbar/Chatbar.less
> +      max-height: 25vh;
revert

2022-05-24 13:55 UTC, molimauro commented on components/views/chat/chatbar/Chatbar.less
> +      }
revert

2022-05-24 13:55 UTC, molimauro commented on components/views/chat/chatbar/Chatbar.vue
> -</style>
revert

2022-05-24 13:56 UTC, molimauro commented
The editable css is so easy to break that its better to ask me before touching it. Revert please the updates related to that thanks!

2022-05-25 08:01 UTC, ThomBos commented on assets/styles/base.less
> +      box-sizing: border-box;
can't tell you... i don't remember if this style was usefull when i tried removing the wrapper from the new scroll component or is needed to fix its position. i can't test it rn due to textile issues

2022-05-25 08:08 UTC, ThomBos commented on components/views/chat/chatbar/Chatbar.less
> +      padding-bottom: @light-spacing;
reverting this i've to go back to the previous scrollbar component. the problem is that the chatbar component has 2 things overlapped and needs this class to be sent to the new scrollbar component to wrap chatbar properly

2022-05-25 08:23 UTC, molimauro commented on components/views/chat/chatbar/Chatbar.less
> +      padding-bottom: @light-spacing;
But why white-space: normal;?

2022-05-25 08:33 UTC, ThomBos commented on components/views/chat/chatbar/Chatbar.less
> +      padding-bottom: @light-spacing;
> But why `white-space: normal;`?
it's a mistake

2022-05-25 08:39 UTC, molimauro commented on components/views/chat/chatbar/Chatbar.less
> +      padding-bottom: @light-spacing;
Remove it and revert all the others then ill test thanks

2022-05-25 08:40 UTC, ThomBos commented on components/views/chat/chatbar/Chatbar.less
> +      max-height: 25vh;
this 50vh has some overlapping problems (test it with the search feature on the toolbar)

2022-05-25 09:14 UTC, molimauro commented on components/views/chat/chatbar/Chatbar.less
> +      white-space: normal;
still seeing this

2022-05-25 09:15 UTC, ThomBos commented on assets/styles/base.less
> +      box-sizing: border-box;
yeah i'm testing it

2022-05-25 09:37 UTC, molimauro commented
Seems much better!! :) I'll review the remaining code 💥

2022-05-30 12:49 UTC, molimauro approved these changes

2022-05-30 12:49 UTC, molimauro commented
Great! How much components are left with the old scollbar library?

2022-05-30 13:14 UTC, ThomBos commented
> Great! How much components are left with the old scollbar library?

like 2 or 3

2022-05-30 15:07 UTC, molimauro commented
Ok perfect, we need to talk about them and understand how to purge them

2022-05-30 15:12 UTC, stavares843 requested changes
dev

<img width="812" alt="Captura de ecrã 2022-05-30, às 16 10 45" src="https://user-images.githubusercontent.com/29093946/171020727-22399567-78e0-48c0-8f2a-16b56050e4b7.png">


this branch

<img width="825" alt="Captura de ecrã 2022-05-30, às 16 09 40" src="https://user-images.githubusercontent.com/29093946/171020747-0e731272-e555-4b1e-8df4-f20b2e96519e.png">



is missing the pagination numbers on the bottom when searching

2022-05-30 16:59 UTC, ThomBos commented
> is missing the pagination numbers on the bottom when searching

i'm fixing it rn, but i have some questions about that...
should we have scroll and pagination here?? isn't it confusing having both?

2022-05-31 12:04 UTC, molimauro approved these changes

2022-06-03 07:26 UTC, molimauro approved these changes

2022-06-03 08:21 UTC, ThomBos commented
are submodules still there? (because i don't see them😅) @molimauro

2022-06-03 08:22 UTC, molimauro commented
Doesnt seem so

2022-06-03 14:02 UTC, phillsatellite commented
Tested: Looked good! I could only find one little issue when user is trying to send a bulk amount of files the scroll is gone and the files will stack up on each other 
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-03 at 09 54 44](https://user-images.githubusercontent.com/93608357/171869466-86343288-7155-427c-8272-3638f6c0d8b9.png)

https://user-images.githubusercontent.com/93608357/171869467-b1e9d52d-a798-4a04-9238-ad755e7aa0d6.mov

2022-06-03 14:19 UTC, ThomBos commented
> Tested: Looked good! I could only find one little issue when user is trying to send a bulk amount of files the scroll is gone and the files will stack up on each other 
Thanks Phill! 👍 
The correct behaviour should be showing just the last image, while to see the others the user has to scroll down, right?

2022-06-03 15:24 UTC, ThomBos commented
should work now! 👍

2022-06-03 17:50 UTC, phillsatellite commented
Tested: Looks like one more tiny bug appeared from recent changes that I couldn't replicate on dev or test.satellite. If the user adjust the browser size it will eventually start to cover up the names on the preview 

Video shows this branch vs test.satellite (I tested dev branch but just used test.satellite for the screen recording)


https://user-images.githubusercontent.com/93608357/171918940-87a8a0ef-a268-4567-8c10-46151218776f.mov

2022-06-04 08:20 UTC, iltumio approved these changes

2022-06-06 18:54 UTC, phillsatellite approved these changes

2022-06-06 18:54 UTC, phillsatellite commented
Note - Was able to test on desktop and android but wasnt able to get past linking satellites on iOS

2022-06-07 11:53 UTC, ThomBos commented
Need this PR to be merged before opening another PR for AP-1730

2022-06-08 14:22 UTC, stavares843 commented
was only fixing the conflict, and bot removed the label 😂 will retest and merge

2022-06-09 10:30 UTC, molimauro commented on components/ui/SimpleScroll/SimpleScroll.vue
> +      type: [String, Boolean, Number, Array],
whats this type?

2022-06-10 13:51 UTC, stavares843 approved these changes

2022-06-10 13:51 UTC, merged