feat(chat): implement infinite scroll for chat messages
Satellite-im/Core-PWA pull request #3286
Opened 2022-05-24 09:11 UTC by AlexZakablukov

**What this PR does** 📖
implement infinite scroll for chat messages

**Which issue(s) this PR fixes** 🔨
[AP-1596](https://satellite-im.atlassian.net/browse/AP-1596)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-24 14:12 UTC, Jekrimo requested changes

2022-05-24 14:12 UTC, Jekrimo commented on store/chat/actions.ts
> +      if (direction === 'top') {
Can you add an Enum for 'top'? Either add it to one that makes sense for it in libraries/enums or make a new one. I feel like it exists but maybe not

2022-05-25 08:06 UTC, molimauro commented on components/views/chat/conversation/Conversation.vue
> +      }
guard clause

2022-05-25 08:07 UTC, molimauro commented on components/views/chat/conversation/Conversation.vue
> +        rootMargin: '100px 0px 0px 0px',
do we need this?

2022-05-25 08:08 UTC, molimauro commented on layouts/chat.vue
> -                $store.state.webrtc.activeCall.callId
Without this when we are on a call the users wont appear above the chat

2022-05-25 08:09 UTC, molimauro commented on components/ui/Chat/InfiniteScroll/InfiniteScroll.html
> +    <div>No more data.</div>
Use i18n :)

2022-05-25 08:15 UTC, molimauro commented on store/textile/mutations.ts
>        reactions: state.conversations[address]?.reactions || [],
Do we need these if we have now `groupedMessages`?

2022-05-25 08:27 UTC, molimauro commented on store/chat/actions.ts
> +    }
Is there a case in which the conv does not have the groupedMessages?

2022-05-25 08:35 UTC, AlexZakablukov commented on components/views/chat/conversation/Conversation.vue
> +      }
if(condition){
...
loaded()
return 
}
complete() 

like this?

2022-05-25 08:36 UTC, AlexZakablukov commented on layouts/chat.vue
> -                $store.state.webrtc.activeCall.callId
I will check it and return it if needed

2022-05-25 08:36 UTC, AlexZakablukov commented on components/ui/Chat/InfiniteScroll/InfiniteScroll.html
> +    <div>No more data.</div>
oh, I am sorry, missed it (

2022-05-25 08:37 UTC, AlexZakablukov commented on store/textile/mutations.ts
>        reactions: state.conversations[address]?.reactions || [],
I don't think so, we can remove these fields

2022-05-25 08:38 UTC, AlexZakablukov commented on store/chat/actions.ts
> +    }
this is just in case, but I don't know of such a case)

2022-05-25 08:39 UTC, molimauro commented on components/views/chat/conversation/Conversation.vue
> +      }
yes

2022-05-25 08:40 UTC, molimauro commented on store/textile/mutations.ts
>        reactions: state.conversations[address]?.reactions || [],
I saw messages being used somewhere maybe just check replies and reactions :)

2022-05-25 08:43 UTC, AlexZakablukov commented on components/views/chat/conversation/Conversation.vue
> +        rootMargin: '100px 0px 0px 0px',
There are options for infinite scroll

2022-05-25 10:21 UTC, AlexZakablukov commented on store/chat/actions.ts
> +    }
If wrong conversation Id was passed

2022-05-25 10:23 UTC, AlexZakablukov commented on store/textile/mutations.ts
>        reactions: state.conversations[address]?.reactions || [],
messages used for last message in sidebar  and last update time

2022-05-25 14:22 UTC, molimauro commented on components/views/chat/conversation/Conversation.vue
> +        rootMargin: '100px 0px 0px 0px',
ok

2022-05-25 14:23 UTC, molimauro commented
@stavares843 im not totally sure Alex finished all the reqs

2022-05-25 14:24 UTC, stavares843 commented
added label again 😂 thanks @molimauro 🔨

2022-05-25 14:36 UTC, molimauro commented
Sorry @AlexZakablukov i see that when we loadMore we are not fetching new messages from Textile but simply slicing onto the already loaded array. This is a problem in large chat, it should be better to load page by page from Textile instead of loading the whole chat once and slicing. Are you planning to do so on the next PR maybe? Let me know thanks!

I'll leave you an account with a large chat so you can also have a "real" life example.

```
impulse betray amateur food kid laundry hurry valid dish twin believe palm
```

2022-05-26 06:48 UTC, molimauro commented
> Sorry @AlexZakablukov i see that when we loadMore we are not fetching new messages from Textile but simply slicing onto the already loaded array. This is a problem in large chat, it should be better to load page by page from Textile instead of loading the whole chat once and slicing. Are you planning to do so on the next PR maybe? Let me know thanks!
> 
> I'll leave you an account with a large chat so you can also have a "real" life example.
> 
> ```
> impulse betray amateur food kid laundry hurry valid dish twin believe palm
> ```

This is fine @AlexZakablukov atm. Let's keep the Textile loading as is for the moment or we will mess up also with the "search" functionality and others. We'll come back to this later on

2022-05-26 08:28 UTC, AlexZakablukov commented on layouts/chat.vue
> -                $store.state.webrtc.activeCall.callId
fixed

2022-05-26 10:02 UTC, molimauro commented
* sometimes after the loading placeholders i have a chat already scroll on top and not at the bottom;
* when i scroll on top very quickly at a certain point it does not load new msg because the scrollbar stays at the top. I have to scroll down a bit and then up again to make it work

2022-05-27 08:23 UTC, AlexZakablukov commented
Fixed, I added a debounce timeout for infinite scroll.

2022-05-30 14:53 UTC, molimauro commented
@AlexZakablukov can you resolve conflicts please?

2022-05-31 08:31 UTC, AlexZakablukov commented
> @AlexZakablukov can you resolve conflicts please?

done

2022-05-31 09:20 UTC, molimauro commented on store/chat/actions.ts
> +          : [...messages, ...newMessages],
Can we concat instead of spreading?

2022-05-31 09:26 UTC, molimauro commented
The scroll is much better!

Sometimes on smaller screen height (try resize the window) the chat scroll is not always at the bottom. Can you try to understand why and see if it should be fixed here or on a separate ticket? thanks

2022-05-31 09:44 UTC, molimauro commented on components/views/chat/conversation/Conversation.html
> +      :data-id="chat.currentChat.lastLoadedMessageId"
whats the purpose of this?

2022-05-31 14:15 UTC, AlexZakablukov commented on components/views/chat/conversation/Conversation.html
> +      :data-id="chat.currentChat.lastLoadedMessageId"
What do you mean?

2022-05-31 14:19 UTC, molimauro commented on components/views/chat/conversation/Conversation.html
> +      :data-id="chat.currentChat.lastLoadedMessageId"
The `:data-id`

2022-05-31 14:40 UTC, AlexZakablukov commented on store/textile/actions.ts
> +            messages: [...messages, ...newMessages],
fixed

2022-05-31 14:40 UTC, AlexZakablukov commented on components/views/chat/conversation/Conversation.html
> +      :data-id="chat.currentChat.lastLoadedMessageId"
Forgot to remove it, done

2022-06-01 07:57 UTC, AlexZakablukov commented
> AP-1596

I think i fixed it

2022-06-01 08:32 UTC, molimauro commented on components/views/chat/conversation/Conversation.vue
> +    },
These sounds like getters, refactor to something like:
```
...mapState({
      ui: (state) => (state as RootState).ui,
      textile: (state) => (state as RootState).textile,
      messages: (state) => (state as RootState).chat.currentChat.messages,
      // etc...
    }),
    ```

2022-06-01 12:00 UTC, molimauro approved these changes

2022-06-01 14:37 UTC, phillsatellite commented
Tested and the functionality is great! I was still able to replicate bug on iOS when entering chat, chatscroll will not start at the bottom. Since everything else worked so great I think we can approve this and I'll write up a ticket for the autoscroll starting at bottom (I think we've had a ticket for it already so I might just re open that one) cc: @molimauro @stavares843

2022-06-01 14:37 UTC, phillsatellite approved these changes

2022-06-01 17:03 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/171460410-f1a88639-8715-42a1-867e-9e8da1505eda.mov

when i scroll up it goes down

seed - genius super farm cabbage come muscle cancel veteran spoil tip cinnamon delay

browser - chrome

2022-06-01 17:08 UTC, stavares843 commented
actually @molimauro clarified this is intended behavior, thanks mauro 💥

2022-06-02 09:37 UTC, AlexZakablukov commented
> <img alt="Captura de ecrã 2022-06-01, às 17 46 18" width="643" src="https://user-images.githubusercontent.com/29093946/171457679-de577084-2b67-4cbd-bc32-50d81c1805df.png">
> 
> empty file 🔨

removed

2022-06-03 07:26 UTC, molimauro approved these changes

2022-06-03 18:07 UTC, phillsatellite commented
I gave this a quick run through before approving and noticed something I must've missed earlier. If a user enters a chat with no messages sent in it yet on the bottom left corner it will flash "loading messages" I couldn't replicate this on dev branch 

https://user-images.githubusercontent.com/93608357/171921594-75d6070d-bb79-4796-929c-e94adfab8b22.mov

2022-06-06 09:14 UTC, AlexZakablukov commented
> I gave this a quick run through before approving and noticed something I must've missed earlier. If a user enters a chat with no messages sent in it yet on the bottom left corner it will flash "loading messages" I couldn't replicate this on dev branch
> 
>  loading.messages.mov

I stylized the message loader, I think now everything is ok

2022-06-06 09:37 UTC, molimauro commented on components/views/chat/conversation/Conversation.less
> +    color: var(--flair-color);
`&:extend(.font-flair);`

2022-06-06 10:03 UTC, AlexZakablukov commented on components/views/chat/conversation/Conversation.less
> +    color: var(--flair-color);
fixed

2022-06-06 19:05 UTC, phillsatellite approved these changes

2022-06-08 13:29 UTC, molimauro commented
@AlexZakablukov can you fix the conflicts when you get a chance? Thanks!

2022-06-08 19:54 UTC, WanderingHogan commented
@AlexZakablukov there was a conflict with the frienfsList in this pr: https://github.com/Satellite-im/Core-PWA/pull/3496/files#diff-b07d518d5130fc9c2de6edd6fcdeb65597c567dab1b2d18adbfeae8073cdec6a

so i updated the conflict and updated your PR

2022-06-09 07:23 UTC, molimauro commented
And here we go again.. @AlexZakablukov can you fix conflicts?

@stavares843 can we prioritize this some way?

Thanks!

2022-06-09 07:36 UTC, molimauro commented
Watch out groups, they seem broken

2022-06-09 09:57 UTC, AlexZakablukov commented
fixed

2022-06-09 10:06 UTC, AlexZakablukov commented
@stavares843 @molimauro Hello, I resolved conflicts and fixed group chat but we have a bug with reply and reaction on group chat this bug is also on test.satellite, I think it can be another task.

2022-06-09 15:17 UTC, stavares843 commented
yes that's correct reply and reactions doesn't work for groups, it's not from the PR

2022-06-09 15:24 UTC, phillsatellite approved these changes

2022-06-09 17:06 UTC, stavares843 approved these changes

2022-06-09 17:06 UTC, merged