fix(friends): show error toast if friend request not found
Satellite-im/Core-PWA pull request #3308
Opened 2022-05-26 07:34 UTC by jasonwoodland

**What this PR does** 📖
- Removes a superfluous throw
- Displays an error toast if the friend request isn't found

**Which issue(s) this PR fixes** 🔨
AP-1565

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-26 13:39 UTC, Jekrimo approved these changes

2022-05-26 14:40 UTC, stavares843 requested changes
<img width="1035" alt="Captura de ecrã 2022-05-26, às 15 40 21" src="https://user-images.githubusercontent.com/29093946/170511179-b97b8b6a-5d92-4ce5-83dd-9b53707e8b44.png">

still happens

same flow as the one on the ticket 🔨

2022-05-30 21:09 UTC, WanderingHogan approved these changes

2022-05-30 21:10 UTC, WanderingHogan commented on components/views/friends/friend/Friend.vue
>          this.loadCheck = false
could be removed but not important

2022-05-30 21:35 UTC, stavares843 approved these changes

2022-05-30 21:36 UTC, merged