Ap 10
Satellite-im/Core-PWA pull request #331
Opened 2021-11-30 23:38 UTC by Jekrimo

**What this PR does** 📖
Refactor our state to prepare using system sounds, refactor the media volume to effect output volume in settings and vice versa. 

**Which issue(s) this PR fixes** 🔨
AP-10

**Additional comments** 🎤

2021-12-01 08:23 UTC, RetroPronghorn requested changes

2021-12-01 08:23 UTC, RetroPronghorn commented on components/tailored/settings/pages/audio/index.vue
> +      this.$Sounds.changeLevels(volume / 100);
remove `;`

2021-12-01 08:23 UTC, RetroPronghorn commented on store/audio/state.ts
> +    system: 100
add `,`

2021-12-01 08:23 UTC, RetroPronghorn commented on store/audio/state.ts
> +  }
add `,`

2021-12-02 08:03 UTC, molimauro approved these changes

2021-12-02 17:37 UTC, RetroPronghorn approved these changes

2021-12-02 17:37 UTC, merged