fix(message): disable save on empty message
Satellite-im/Core-PWA pull request #3317
Opened 2022-05-27 03:10 UTC by jasonwoodland

**What this PR does** 📖
- Prevents saving an edited message as an empty message
- Fixes styling and locale strings in the edit message UI

**Which issue(s) this PR fixes** 🔨
AP-1631

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-05-27 08:23 UTC, josephmcg requested changes
I like the solution. Could you remove `$data` and `$props` mentions and fix intellisense in the file? The computed need return types. Then you can remove the declaration stuff (screenshot below).

Please make a habit of fixing this whenever you see it

![image](https://user-images.githubusercontent.com/33670767/170660764-c659b522-42f5-4145-bb82-342874e35cb4.png)

2022-05-30 22:37 UTC, WanderingHogan commented on components/views/chat/message/edit/Edit.vue
> +      this.$emit('commitMessage', this.content.slice(0, this.maxChars))
why not just `if (this.content.length > 0) this.$emit('commitMessage', this.content.slice(0, this.maxChars))`

2022-05-30 22:37 UTC, WanderingHogan approved these changes

2022-05-31 00:37 UTC, josephmcg commented on components/views/chat/message/edit/Edit.vue
> +      this.$emit('commitMessage', this.content.slice(0, this.maxChars))
I believe the current way falls more in line with our 'guard clause' philosophy. although I'm lazy, I would write `!this.content.length`

2022-05-31 00:39 UTC, josephmcg approved these changes

2022-05-31 01:09 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/171073731-b87a9f08-67de-42c3-828e-f1487283bf13.mov

if you try to save a empty message doesn't return any feedback to the user when clicking on save

2022-05-31 03:04 UTC, josephmcg commented
true. error toast would be enough.
a nice bonus feature would be making the blue outline red if error, that would be fairly involved though

2022-05-31 12:05 UTC, stavares843 approved these changes

2022-05-31 12:05 UTC, merged