fix(chat): fix 'unable to paste text into chat'
Satellite-im/Core-PWA pull request #332
Opened 2021-12-01 04:44 UTC by genie-magic

**What this PR does** 📖
fix 'unable to paste the text into chat'

**Which issue(s) this PR fixes** 🔨
Jira ref: AP-108

2021-12-01 08:22 UTC, RetroPronghorn requested changes

2021-12-01 08:22 UTC, RetroPronghorn commented on components/tailored/core/chatbar/Chatbar.vue
> +      if(clipboardItems && clipboardItems.length) {
spacing here, should be `if (` not `if(`

2021-12-01 16:58 UTC, stavares843 approved these changes
copy pasting text works 

fixed ✅

2021-12-01 18:40 UTC, genie-magic commented on components/tailored/core/chatbar/Chatbar.vue
> +      if(clipboardItems && clipboardItems.length) {
@RetroPronghorn  I fixed that. I will care about that in the future. Thanks.

2021-12-02 17:36 UTC, RetroPronghorn approved these changes

2021-12-02 17:37 UTC, merged