David/fixing
Satellite-im/Core-PWA pull request #333
Opened 2021-12-01 12:38 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

Fixes #
Updated Streamline add friend functionality
**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-01 15:29 UTC, Jekrimo requested changes

2021-12-01 15:29 UTC, Jekrimo commented on layouts/chat.vue
> +    }
put trailing , back in

2021-12-01 15:29 UTC, Jekrimo commented on layouts/chat.vue
> +  }
put trailing , back in

2021-12-01 15:29 UTC, Jekrimo commented on store/friends/actions.ts
> +      return;
remove ;

Literally just had Matt on my review asking for these haha, good job David!

2021-12-02 02:41 UTC, WanderingHogan commented on .eslintrc.js
> +    'comma-dangle': ['error', 'never'],
please take this out - I believe @stavares843 took it out a few days ago

2021-12-02 02:44 UTC, WanderingHogan commented on package.json
> +=======
It looks like you might not have finished a rebase?

2021-12-02 02:45 UTC, WanderingHogan commented on jest.config.js
>      '^.+\\.module\\.(css|sass|scss)$'
another rebase problem it looks like?

2021-12-02 02:46 UTC, WanderingHogan commented on components/tailored/friends/add/Add.vue
> +        this.error = this.$t('friends.invalid_characters') as string
prefer guard clause over if...else

2021-12-02 02:48 UTC, WanderingHogan commented on components/tailored/messaging/message/Message.html
> +      :messageOwner="this.$props.message.from"
can this just be `message.from` since the props are available in the template

2021-12-02 02:50 UTC, WanderingHogan requested changes
Looks like this PR might have had some issues while rebasing

2021-12-02 03:42 UTC, stavares843 commented on .eslintrc.js
> +    'comma-dangle': ['error', 'never'],
correct yes

2021-12-02 13:30 UTC, davidchan1219 commented
fixed conflict and merged with dev branch.

2021-12-02 16:03 UTC, WanderingHogan commented
A couple things - 

This looks like it is meant to address a few different tickets. Can you make 1 pull request per ticket. I see ap-158 here and i believe ap-151? Multiple tickets in a single ticket are okay if it's a very minor update to fix something, but these are two pretty big totally independent tickets

Please fill out the commit message with what the PR does, what ticket it addresses, notes, etc

When you are updating your branch to address conflicts, can you rebase your changes on top of dev instead of merging? we would like to see as few files changed and as few commits as possible to make the changes, it makes reviewing a lot easier.

Jeff and I made a few requests in the github ticket for changes, that i don't see updated, either.

2021-12-03 02:26 UTC, closed without merging

2021-12-03 02:26 UTC, stavares843 commented
the fixes from this PR were added on separate PR's