fix(volume): bind output slider volume to stream volume
Satellite-im/Core-PWA pull request #3453
Opened 2022-06-03 00:14 UTC by maljuburi

**What this PR does** 📖
- add a volume watcher to update the audioStream element
- set initial volume when audioStream is set to the current volume state

**Which issue(s) this PR fixes** 🔨
- Adjusting output volume slider doesn't affect the audio.

**Additional comments** 🎤
- 🎊  This is my first PR, please review carefully and don't hesitate to give feedback and share knowledge 🙂

2022-06-06 13:37 UTC, molimauro commented on components/ui/Chat/TypingIndicator/TypingIndicator.vue
> +      if (this.users.length <= 3 && this.users.length !== 0) {
Can be refactored to `if (this.users.length <= 3 && this.users.length)`

2022-06-06 13:38 UTC, molimauro commented on components/views/media/Media.vue
> +        ) as HTMLCollectionOf<HTMLAudioElement>
Instead of getting the element through `getElementsByClassName` you can use `ref`. Or are there more than one audio elements?

2022-06-06 13:39 UTC, molimauro requested changes
Hey Muhammad! Thanks for the first PR :) just a couple of minors and the rest looks good!

2022-06-06 17:50 UTC, maljuburi commented on components/views/media/Media.vue
> +        ) as HTMLCollectionOf<HTMLAudioElement>
as far as I understand, we would expect multiple audio elements in a group call. so I tried to future proof it. good feedback though

2022-06-06 17:50 UTC, maljuburi commented on components/views/media/user/User.vue
> +      ) as HTMLCollectionOf<HTMLAudioElement>
addressed above

2022-06-07 07:06 UTC, molimauro commented on components/views/media/Media.vue
> +        ) as HTMLCollectionOf<HTMLAudioElement>
Ok thanks for the clarification! :)

2022-06-07 07:06 UTC, molimauro approved these changes

2022-06-07 15:10 UTC, stavares843 commented
Hogan has a couple changes to request on these code changes.

2022-06-07 22:15 UTC, WanderingHogan approved these changes

2022-06-07 22:16 UTC, WanderingHogan commented
i dunno what i was thinking on that call earlier. When i skimmed it i thought this was doing something else. Good job, Muhammad!

2022-06-07 22:23 UTC, phillsatellite approved these changes

2022-06-07 23:03 UTC, merged