fix(groups): members order sorted alpha
Satellite-im/Core-PWA pull request #3460
Opened 2022-06-03 08:10 UTC by josephmcg

**What this PR does** 📖
- set group members with an alpha sort. it seems like the backend returns them in a random order every time

**Which issue(s) this PR fixes** 🔨
AP-1698

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-03 15:20 UTC, molimauro approved these changes

2022-06-03 15:54 UTC, stavares843 requested changes
<img width="1295" alt="Captura de ecrã 2022-06-03, às 16 53 17" src="https://user-images.githubusercontent.com/29093946/171901402-c22dc29f-8531-4740-855a-ba8443e3cc71.png">

fixed

<img width="516" alt="Captura de ecrã 2022-06-03, às 16 49 37" src="https://user-images.githubusercontent.com/29093946/171901446-b8f16552-8230-41a4-99f3-5639c39214a5.png">

but the order is not the same then the one that we have on friends list

2022-06-03 16:14 UTC, phillsatellite commented
One little thing I wanted to ask was when you are adding users in the new group chat modal should they be listed alphabetical or add as user selected? 
<img width="444" alt="Screen Shot 2022-06-03 at 12 05 24 PM" src="https://user-images.githubusercontent.com/93608357/171904713-970b8d15-f9a8-482f-bdd8-c6c377f312be.png">

2022-06-06 00:58 UTC, josephmcg commented
These changes do not affect the quick chat popup. That pulls from the 'friends' store namespace. this sets the 'groups' namespace list to alphabetical order so the group chat icons/names don't change order every time you click on a group

2022-06-06 02:25 UTC, stavares843 approved these changes

2022-06-06 02:25 UTC, merged

2022-06-06 02:25 UTC, stavares843 commented
thanks for clarifying