fix(call): add possibility to call user via context menu
Satellite-im/Core-PWA pull request #3484
Opened 2022-06-06 15:20 UTC by AlexZakablukov

**What this PR does** 📖
add posibility to call user via context menu

**Which issue(s) this PR fixes** 🔨
[AP-1097](https://satellite-im.atlassian.net/browse/AP-1097)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-06 16:07 UTC, Jekrimo requested changes

2022-06-06 16:07 UTC, Jekrimo commented on components/views/user/User.vue
> +    // },
Can we delete this bit?

2022-06-06 16:07 UTC, Jekrimo commented on components/views/user/User.vue
> +            // { text: this.$t('context.video'), func: this.testFunc },
Prob delete this too right?

2022-06-07 00:32 UTC, josephmcg commented on components/views/user/User.vue
> +    // },
agreed

2022-06-07 00:32 UTC, josephmcg commented on components/views/user/User.vue
> +            // { text: this.$t('context.video'), func: this.testFunc },
this should stay, we're going to add it back eventually

2022-06-07 07:46 UTC, josephmcg commented on components/views/user/User.vue
>        return this.user.state === 'online'
can use your new computed here

2022-06-08 14:09 UTC, AlexZakablukov commented on components/views/user/User.vue
>        return this.user.state === 'online'
done

2022-06-09 05:30 UTC, WanderingHogan approved these changes

2022-06-09 05:36 UTC, josephmcg approved these changes

2022-06-09 16:17 UTC, phillsatellite approved these changes

2022-06-09 22:56 UTC, stavares843 approved these changes

2022-06-09 22:57 UTC, merged