feat(interactables): user picker component
Satellite-im/Core-PWA pull request #3506
Opened 2022-06-08 05:45 UTC by jasonwoodland

**What this PR does** 📖
- add new checkbox component
- add reusable friend picker component
- upgrade quick component to use new friend picker
- fix button animation speed when switching `type` prop in quick component
- add missing type definition

**Which issue(s) this PR fixes** 🔨
AP-1742

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-08 06:02 UTC, josephmcg requested changes

2022-06-08 06:02 UTC, josephmcg commented on components/interactables/UserPicker/UserPicker.vue
> +      return this.friends.all
i think you can skip the guard clause, includes('') will be true

2022-06-08 06:02 UTC, josephmcg commented on components/interactables/UserPicker/UserPicker.vue
> +      console.log('emit', this.selected)
remove logs

2022-06-08 06:21 UTC, jasonwoodland commented on components/interactables/UserPicker/UserPicker.vue
> +      return this.friends.all
I feel if we can skip a superfluous filter call then we should from the perspective of performance.

2022-06-08 06:37 UTC, josephmcg approved these changes

2022-06-08 08:08 UTC, josephmcg commented
making a note that we want to add some sort of list to keep track of currently selected users. thought it would be best in a separate PR to keep things simple

2022-06-09 00:50 UTC, jasonwoodland commented
@phillsatellite fixed :)

2022-06-09 00:50 UTC, stavares843 commented
thanks @jasonwoodland 🔨

2022-06-09 16:43 UTC, phillsatellite approved these changes

2022-06-09 23:10 UTC, stavares843 commented
very neat 🎉 

i noticed that it doesn't show feedback if the search doesn't have results and the user tries to click on chat now even if the button is already not tinted but maybe we could improve that on other PR

<img width="1228" alt="Screenshot 2022-06-10 at 00 08 25" src="https://user-images.githubusercontent.com/29093946/172959848-af30e8cc-c330-46dc-bc13-c1d2040caf5c.png">

this branch vs dev where we don't show the button if there are no results

but this component is way prettier 🎉 

cc @josephmcg

2022-06-09 23:10 UTC, stavares843 approved these changes

2022-06-09 23:10 UTC, merged

2022-06-10 13:47 UTC, stavares843 commented on components/interactables/UserPicker/UserPicker.html
> +<div class="user-picker">
<img width="1108" alt="Captura de ecrã 2022-06-10, às 14 47 05" src="https://user-images.githubusercontent.com/29093946/173079588-f1806560-acd1-4e98-a196-c5c90a9802f5.png">

this is adding a warning when we build locally, could fix you on a separate PR? @jasonwoodland 🔨

2022-06-10 13:48 UTC, stavares843 commented on components/interactables/UserPicker/UserPicker.html
> +<div class="user-picker">
added ticket here - [AP-1766](https://satellite-im.atlassian.net/browse/AP-1766)