Refactor(Scrollbar): Clearing remaining components
Satellite-im/Core-PWA pull request #3514
Opened 2022-06-08 12:26 UTC by ThomBos

**What this PR does** 📖
Clears last few scrollbar components and clear all related code
**Which issue(s) this PR fixes** 🔨
AP-1730

**Special notes for reviewers** 🗒️
This PR depends on #3284  
**Additional comments** 🎤

2022-06-10 13:51 UTC, stavares843 commented
https://github.com/Satellite-im/Core-PWA/pull/3284 merged 🎉

2022-06-10 16:36 UTC, phillsatellite approved these changes

2022-06-13 10:04 UTC, molimauro commented on components/views/navigation/slimbar/Slimbar.html
> +    <UiSimpleScroll scrollMode="vertical" scrollShow="scroll" v-else>
line 22 should go under the div in line 23

2022-06-13 10:05 UTC, molimauro requested changes
* minor
* remove uiscroll component in `components/interactables/UserPicker/UserPicker.html`
* remove uiscroll component

2022-06-13 10:18 UTC, ThomBos commented on components/views/navigation/slimbar/Slimbar.html
> +    <UiSimpleScroll scrollMode="vertical" scrollShow="scroll" v-else>
should we scroll also the horizontal line?

2022-06-13 12:40 UTC, molimauro commented on components/views/navigation/slimbar/Slimbar.html
> +    <UiSimpleScroll scrollMode="vertical" scrollShow="scroll" v-else>
without this when we have the user circles (above communities) nothing will appear on screen:
![image](https://user-images.githubusercontent.com/50131258/173355746-bff4cdda-c754-458b-96b2-c131df03be2a.png)

2022-06-13 12:58 UTC, ThomBos commented on components/views/navigation/slimbar/Slimbar.html
> +    <UiSimpleScroll scrollMode="vertical" scrollShow="scroll" v-else>
is it supposed to disappear when we don't have any chat?

2022-06-13 13:10 UTC, molimauro commented on components/views/navigation/slimbar/Slimbar.html
> +    <UiSimpleScroll scrollMode="vertical" scrollShow="scroll" v-else>
nope, but in this case we have both and nothing appears

2022-06-13 13:18 UTC, ThomBos commented on components/views/navigation/slimbar/Slimbar.html
> +    <UiSimpleScroll scrollMode="vertical" scrollShow="scroll" v-else>
ok, so the real issue is the if

2022-06-13 13:46 UTC, molimauro commented
I have these overlapping:
![image](https://user-images.githubusercontent.com/50131258/173367647-d08fa449-afc0-481d-bd96-a2e0393dae7c.png)

Also the horizontal div is not centered:

![image](https://user-images.githubusercontent.com/50131258/173367758-5866d9ea-f1c1-49b1-a885-c42e7319b103.png)

2022-06-13 17:59 UTC, phillsatellite commented
Tested: Mauro's bugs were fixed now but it looks like the changes brought up a new bug. Seems the pages within Settings are all being crunched to the left side of the screen
![IMG_5605](https://user-images.githubusercontent.com/93608357/173415741-b2ff121e-ac27-4445-a4f5-d186fc4c8dca.PNG)

2022-06-13 18:26 UTC, ThomBos commented
> Tested: Mauro's bugs were fixed now but it looks like the changes brought up a new bug. Seems the pages within Settings are all being crunched to the left side of the screen !

....it looks pretty bad... can you send also a pic of each tab inside the modal please?

2022-06-13 22:30 UTC, ThomBos commented
Fixed this issue, but it's necessary check every scrollbar now

2022-06-14 09:07 UTC, molimauro commented on components/ui/SimpleScroll/SimpleScroll.less
> +    height: fit-content;
Does this work on Firefox? https://caniuse.com/?search=fit-content

2022-06-14 09:07 UTC, molimauro commented on components/views/navigation/slimbar/Slimbar.less
> +  padding-left: 0.5rem;
@light-spacing

2022-06-14 09:08 UTC, molimauro commented on components/views/navigation/slimbar/Slimbar.less
> +      padding: 0.25rem 0;
@xlight-spacing

2022-06-14 09:09 UTC, molimauro commented on components/views/navigation/slimbar/Slimbar.less
> +    max-height: calc(@full - 11rem);
Can you explain this calc on a comment? :)

2022-06-14 10:06 UTC, ThomBos commented on components/views/navigation/slimbar/Slimbar.less
> +    max-height: calc(@full - 11rem);
11 rem is settings and new community buttons' total height, in order to push those buttons out of the screen i had to leave that margin. maybe it's better creating a constant for that

2022-06-14 10:08 UTC, ThomBos commented on components/views/navigation/slimbar/Slimbar.less
> +      max-height: calc(@full - 3rem);
this 3 rems are for an inner padding/margin given by a divider

2022-06-14 10:08 UTC, ThomBos commented on components/ui/SimpleScroll/SimpleScroll.less
> +    height: fit-content;
searching for another solution...

2022-06-14 15:08 UTC, molimauro commented
@ThomBos if you modify the code put the Missing review label thanks :)

2022-06-14 15:08 UTC, molimauro approved these changes

2022-06-14 15:12 UTC, ThomBos commented
> @ThomBos if you modify the code put the Missing review label thanks :)

my bad 😬

2022-06-14 21:51 UTC, stavares843 approved these changes

2022-06-14 21:56 UTC, merged