fix(chat): fix scroll to bottom in chat not working properly when non fixed size images are present
Satellite-im/Core-PWA pull request #3521
Opened 2022-06-08 19:02 UTC by vimercati-samir

What this PR does 📖
Fix scroll to bottom in chat not working properly when non fixed size images are present

Which issue(s) this PR fixes 🔨
[AP-1731](https://satellite-im.atlassian.net/browse/AP-1731)

Special notes for reviewers 🗒️

Additional comments 🎤

2022-06-09 08:47 UTC, molimauro commented
Ok @vimercati-samir good draft, let me dm you for some changes!

2022-06-13 21:07 UTC, stavares843 commented
is this ready? 🔨

2022-06-14 08:53 UTC, molimauro commented
Yes it is!

2022-06-14 13:11 UTC, molimauro commented on utilities/ImageSize.ts
> +  return source
why this?

2022-06-14 13:13 UTC, molimauro commented
Images with error keep loading:
![image](https://user-images.githubusercontent.com/50131258/173585559-c8ebe00f-5fb5-444d-a06b-291936376955.png)

2022-06-14 13:59 UTC, vimercati-samir commented on utilities/ImageSize.ts
> +  return source
This logic was already there I only moved it, basically every sticker has an URL associated, for example https://satellite.mypinata.cloud/ipfs/QmXmpYrNUankzCCWR1U5ASDHcwhSJynQayMy1gT7RTU4ck/$1/AHHcloseup.gif,  this link return not found, but if you replace "$1" with "small" you can see the sticker, I don't know if it's intended to have links associated with stickers with that portion in the URL

2022-06-14 14:27 UTC, molimauro commented on utilities/ImageSize.ts
> +  return source
ok thanks!

2022-06-14 14:29 UTC, vimercati-samir commented
> Images with error keep loading: ![image](https://user-images.githubusercontent.com/50131258/173585559-c8ebe00f-5fb5-444d-a06b-291936376955.png)

This bug occurs only when using older chats with glyphs in them (meaning chats that have been created without the fixes of this branch)

2022-06-14 14:51 UTC, molimauro commented on components/views/files/upload/Upload.vue
> +          })
it is necessary to spread this?

2022-06-14 23:06 UTC, vimercati-samir commented on components/views/files/upload/Upload.vue
> +          })
nope, has been removed in commit 0133d4fd884e065fdfd9950862b01b70e48a1a1c

2022-06-14 23:09 UTC, vimercati-samir commented
I made some more changes because I wasn't saving the sizes in the textile payload and as a result of that the recipient wasn't receiving any sizes and the images would scale without control, now everything should be working fine

2022-06-15 09:08 UTC, molimauro requested changes
Something broke in the last changes, can you check @vimercati-samir? Thanks

2022-06-15 09:23 UTC, molimauro commented
got also this:
![image](https://user-images.githubusercontent.com/50131258/173793040-69f3fc0c-eae4-402f-900e-787951f925ce.png)

2022-06-15 10:33 UTC, vimercati-samir commented
> The image aspect ratio is not correct: ![image](https://user-images.githubusercontent.com/50131258/173789588-14cf1d17-7689-4246-ad0f-5f31b33b92df.png)

resolved

2022-06-15 10:34 UTC, vimercati-samir commented
> got also this: ![image](https://user-images.githubusercontent.com/50131258/173793040-69f3fc0c-eae4-402f-900e-787951f925ce.png)

Starting from a clean chat from this branch (with the latest commits) would result in not having this error in console

2022-06-15 12:57 UTC, molimauro approved these changes

2022-06-15 18:53 UTC, stavares843 requested changes
the images are way bigger on this PR

this branch

<img width="1451" alt="Captura de ecrã 2022-06-15, às 19 51 28" src="https://user-images.githubusercontent.com/29093946/173903099-e77b4258-4ce3-43ba-b4c4-00ae365593fc.png">

vs dev

<img width="1246" alt="Captura de ecrã 2022-06-15, às 19 52 13" src="https://user-images.githubusercontent.com/29093946/173903142-ddf9e87e-3b5e-4b7f-b259-530cfa98250e.png">


same image, same seed, same browser

seed
whisper tired egg over alert reduce carpet asset draft whisper must lawn

2022-06-15 19:45 UTC, stavares843 commented
no, these was images that were already there

thanks for clarifying

2022-06-16 15:21 UTC, phillsatellite commented
Noticed a small bug when testing, seems like when the user sends images or files in chat there will be a second loading bar when the picture is posting 
https://user-images.githubusercontent.com/93608357/174103759-ff222530-b27f-4778-9e8c-b7d2382804ce.mov

2022-06-16 17:06 UTC, phillsatellite commented
> > Noticed a small bug when testing, seems like when the user sends images or files in chat there will be a second loading bar when the picture is posting
> > 2nd.loading.bar.mov
> 
> It's not a bug, every image has a loading state that's independent from the upload state, if you refresh the page you will see that every image loads before appearing, maybe we can improve the ux by adding a label to distinguish the two types of loading (image and upload)

Awesome! Thanks for clarifying!

2022-06-20 22:51 UTC, stavares843 commented
<img width="1102" alt="Screenshot 2022-06-20 at 23 51 16" src="https://user-images.githubusercontent.com/29093946/174686342-ec754dcf-3e7c-436b-b0f1-949b471d4baa.png">

if you send a image that will fail to load such as a svg for example will not scroll to the bottom properly

2022-06-22 13:09 UTC, vimercati-samir commented
> <img alt="Screenshot 2022-06-20 at 23 51 16" width="1102" src="https://user-images.githubusercontent.com/29093946/174686342-ec754dcf-3e7c-436b-b0f1-949b471d4baa.png">
> 
> if you send a image that will fail to load such as a svg for example will not scroll to the bottom properly

Should be resolved in commit 1bdec1ad0345a71b02cba06e5e194b5461c2cb6c, I also rebased and resolved conflicts

2022-06-23 07:49 UTC, josephmcg requested changes
looking good Samir, a couple stylistic things

let me know if you have any questions

2022-06-23 07:49 UTC, josephmcg commented on components/ui/Chat/Image/Image.less
> -    max-width: 300px;
bring back `overflow: hidden`. It prevents a blurred nsfw image from blurring the surrounding area
![image](https://user-images.githubusercontent.com/33670767/175239561-ef31f56d-e11c-4f13-bc8a-4ca13a0fc0df.png)

2022-06-23 07:49 UTC, josephmcg commented on components/ui/Chat/Image/Image.html
> +    </div>
I don't particularly enjoy the loading icon. I think a skeleton image would be better (just a div with darker background color than the surrounding area)

2022-06-23 07:49 UTC, josephmcg commented on components/ui/Chat/Image/Image.html
> +      :class="`${(image.nsfw && blockNsfw) ? 'blur-image' : ''} ${ loading ? 'hidden' : 'visible'}`"
This is somewhat hard to read, avoid using ternary if one of the cases is blank.

using template literals inside v-bind is helpful if you need to mix plain strings in with js values (like you're doing with height and width for the `image-container` above). Try this out instead:
`:class="[{'blur-image': image.nsfw && blockNsfw }, loading ? 'hidden': 'visible']"`

2022-06-23 07:49 UTC, josephmcg commented on components/ui/Chat/Image/Image.html
> +      :class="`${(image.nsfw && blockNsfw) ? 'blur-image' : ''} ${ loading ? 'hidden' : 'visible'}`"
Even better, I would probably apply one of the visibility statues to the plain is-image class. Then you're only applying one class based on `loading`

2022-06-23 07:49 UTC, josephmcg commented on components/views/chat/message/Message.html
> +      :size="{width: message.payload.width, height: message.payload.height}"
it's bad practice to pass data twice. you're already passing size values inside the file prop

2022-06-23 07:49 UTC, josephmcg commented on components/ui/Chat/Embeds/File/File.html
> +    :alt="file.name"
since the file prop here contains size and width, you shouldnt double up the data here, just extract directly from file in child component
<img width="434" alt="image" src="https://user-images.githubusercontent.com/33670767/175243023-5f6bc03b-e938-4340-be4f-2c51d98c9fa8.png">

2022-06-23 07:49 UTC, josephmcg commented on components/ui/Chat/Embeds/File/File.vue
> +    },
delete this

2022-06-23 07:49 UTC, josephmcg commented on components/ui/Chat/Image/Image.html
> +    </div>
you can switch size to be image.height and image.width

2022-06-23 07:49 UTC, josephmcg commented on components/ui/Chat/Image/Image.vue
> +    },
redundant, remove

2022-06-23 07:49 UTC, josephmcg commented on components/views/chat/message/Message.vue
> +    console.log(this.$props.message)
remove console

2022-06-23 07:49 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +          const originalSize = await getOriginalSizeFromDataUrl(fileAsDataURL)
anytime you createObjectURL, you need to revoke or it causes memory leaks

2022-06-23 07:49 UTC, josephmcg commented on components/views/chat/message/Message.html
> +      :sizeType="message.payload.sizeType"
if this component is only used here, it would make sense to pass the payload as one prop to reduce the complexity here. If we want to use this in other places, I could see leaving this

2022-06-23 07:49 UTC, josephmcg commented on components/views/chat/message/glyph/Glyph.html
> +    :class="`glyph ${ loading ? 'hidden' : 'visible'}`"
dont use template literals for classes if you dont have to

2022-06-23 08:02 UTC, josephmcg commented on components/views/files/upload/Upload.vue
> +          const originalSize = await getOriginalSizeFromDataUrl(fileAsDataURL)
It would probably be better to refactor the getOriginalSizeFromDataUrl to accept a blob instead, and create the data url inside that utility function. That way you only need to create and revoke url once

2022-06-23 08:06 UTC, josephmcg commented on utilities/ImageSize.ts
> +}
im not sure how this would handle corrupt files or unembeddable images. Try using stuff from the FileType utilities instead

2022-06-24 08:39 UTC, vimercati-samir commented
Thanks @josephmcg, all the issues should be resolved in commit d134bb2433518fbb9e7a67924c6cb144a30ca99a

2022-06-24 19:01 UTC, phillsatellite commented
Tested with most recent commits: found a few issues if the chat has a glyph in it before you switch to this branch it'll crash when you try to enter that chat 
<img width="1728" alt="Screen Shot 2022-06-24 at 2 59 32 PM" src="https://user-images.githubusercontent.com/93608357/175648457-326f78f6-b912-4c7a-a71f-43bcc0441d62.png">

Another issue I had was whenever I would send a new glyph after already switching to this branch it would appear huge 
<img width="1728" alt="Screen Shot 2022-06-24 at 2 59 32 PM" src="https://user-images.githubusercontent.com/93608357/175648583-d0c0a3a8-e6a1-47d8-b51a-2491dc259173.png">

2022-06-27 00:28 UTC, josephmcg commented
@molimauro @iltumio seems like that action call was moved [here](https://github.com/Satellite-im/Core-PWA/pull/3383/files). not sure how long this has been an issue. I would suggest moving it back unless Jeff moved it here for a good reason. its current location doesn't really fit with the rest of the method. 

@phillsatellite I'll let Samir confirm, but I believe this is intended to be a breaking change. At least the glyph size, maybe crash should be resolved with some optional chaining

2022-06-27 00:37 UTC, josephmcg approved these changes
wonderful, thanks Samir. I really like the new loading animation!

2022-06-27 07:37 UTC, vimercati-samir commented
As @josephmcg mentioned to test the functionality of this PR you have to start on a fresh account and send messages from this branch, crashes or wrong sizes on old messages occurs due to the fact that this pr changed the behaviour of how the messages are saved and displayed

2022-06-27 13:03 UTC, stavares843 commented
we need to prevent the crash

 I was aware of the bad sizing, but we can't merge crashes on purpose

also, regarding the glyphs phil said

''I would send a new glyph after already switching to this branch it would appear huge'' so the glyph was sent already on this branch not before

2022-06-27 16:30 UTC, vimercati-samir commented
crashes and wrong images/glyphs size due to being sent on another branch or to an older version of this branch have been resolved in commit 7ae52e20c37068ba3c185c44bd7c3168f6f5cc61

2022-06-28 07:52 UTC, molimauro commented
I dont totally understand why do we want to prevent old chats from breaking since this is an intended breaking change. However Samir already fixed that so fine for now!

2022-06-28 08:09 UTC, molimauro commented on components/views/chat/enhancers/glyphs/item/Item.vue
> +      const sizeType = 'small'
Is this ever going to change?

2022-06-28 08:57 UTC, vimercati-samir commented on components/views/chat/enhancers/glyphs/item/Item.vue
> +      const sizeType = 'small'
Added comment in the code to address this concern in commit 909c2776c1a3816a0338ed8c3639fc4fca090e75

2022-06-28 08:58 UTC, vimercati-samir commented on components/views/chat/message/Message.html
> +      :sizeType="message.payload.sizeType"
Changed accordingly in commit 909c2776c1a3816a0338ed8c3639fc4fca090e75

2022-06-28 09:40 UTC, molimauro approved these changes

2022-06-28 09:54 UTC, molimauro commented
Btw love the new loader

2022-06-28 10:07 UTC, molimauro commented
Sorry @vimercati-samir noticed a small reflow on the image placeholder, lets keep it at the same height of the original image thanks!

2022-06-28 23:32 UTC, vimercati-samir commented
> Sorry @vimercati-samir noticed a small reflow on the image placeholder, lets keep it at the same height of the original image thanks!

Should be resolved in commit bb5df4f848b77d16feb05d4882757bc87d140341

2022-06-29 07:33 UTC, molimauro commented on components/ui/Chat/Image/Image.html
> +    :style="{ width: `${image.width}px`, height: `${image.height}px` }"
sorry @vimercati-samir, isnt this going to change the aspect ratio of the placeholder image? Its important to have the same height, but if we also force the same width this can lead to a strange aspect ratio right?

2022-06-29 10:55 UTC, vimercati-samir commented on components/ui/Chat/Image/Image.html
> +    :style="{ width: `${image.width}px`, height: `${image.height}px` }"
Should be resolved in commit 0b2a64f14341422c2e6dc751d54fb7ae75e31fa1

2022-06-29 13:09 UTC, molimauro approved these changes

2022-06-29 17:55 UTC, phillsatellite approved these changes

2022-07-01 02:24 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/176811049-05e856ea-af3d-4df9-85df-b5c2e36d4f2f.mov

is there a way to prevent these glitches? sometimes doesn't scroll all the way down or it scrolls but goes up and then down

seed
oval dignity twist coyote frozen exchange fiscal april doll conduct pudding meat

macOS, Chrome

2022-07-01 07:04 UTC, molimauro commented
> Gravacao.do.ecra.2022-07-01.as.03.22.42.mov 
> is there a way to prevent these glitches? sometimes doesn't scroll all the way down or it scrolls but goes up and then down
> 
> seed oval dignity twist coyote frozen exchange fiscal april doll conduct pudding meat
> 
> macOS, Chrome

@vimercati-samir at 0:17 the bitmap images create a reflow, can you see it?

2022-07-01 16:22 UTC, molimauro commented
Isnt the scrollbar glitch pretty much this one? https://satellite-im.atlassian.net/browse/AP-1925
I dont think its related to this PR. Does this happen on dev too? :)

2022-07-05 07:47 UTC, molimauro commented
> Gravacao.do.ecra.2022-07-01.as.03.22.42.mov 
> is there a way to prevent these glitches? sometimes doesn't scroll all the way down or it scrolls but goes up and then down
> 
> seed oval dignity twist coyote frozen exchange fiscal april doll conduct pudding meat
> 
> macOS, Chrome

@stavares843 was this one on this branch or on an old one with images already in the chat?

2022-07-21 13:06 UTC, stavares843 commented
> old one with images already in the chat

2022-07-21 13:07 UTC, stavares843 commented
> Does this happen on dev too? :)


yes but I was wondering if this PR would address that as well 😂

2022-07-27 15:20 UTC, stavares843 reviewed
testing webhook

2022-07-27 15:32 UTC, stavares843 reviewed
testing webhook 2

2022-08-08 15:57 UTC, WanderingHogan commented
closing but leaving branch to come back to if we need it

2022-08-08 15:57 UTC, closed without merging