fix(settings-modal): fixed modal style
Satellite-im/Core-PWA pull request #3560
Opened 2022-06-10 13:29 UTC by ThomBos

**What this PR does** 📖
Fixes settings' modal style

**Which issue(s) this PR fixes** 🔨
AP-1765

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-13 14:02 UTC, ThomBos commented
forgot to report this depends on #3514

2022-06-14 21:57 UTC, stavares843 commented
https://github.com/Satellite-im/Core-PWA/pull/3514 is merged 🎉

2022-06-15 12:58 UTC, molimauro commented on components/ui/SimpleScroll/SimpleScroll.vue
> +    },
what is this?

2022-06-15 13:08 UTC, ThomBos commented on components/ui/SimpleScroll/SimpleScroll.vue
> +    },
this allows us to program when it's time to show the scrollbar. 
with the select we have a little graphic issue related to the scrollbar: it keeps the space even if the scrollbar isn't necessary (due to webkit styling, even removing paddings that space remains)

2022-06-15 13:10 UTC, ThomBos commented on components/interactables/Select/Select.html
> +        :invisibleScrollbar="options.length < 7"
check this out

2022-06-15 13:12 UTC, ThomBos commented on components/interactables/Select/Select.html
> +        :invisibleScrollbar="options.length < 7"
or it would be like 50/80px tall 😓

2022-06-16 12:58 UTC, molimauro commented
@ThomBos we merged a PR from Joe regarding the select fix, is the invisible thing still needed?

2022-06-16 13:06 UTC, ThomBos commented
> @ThomBos we merged a PR from Joe regarding the select fix, is the invisible thing still needed?

it depends if in the fix there's the scrollbar component... i'm checking it

2022-06-16 14:41 UTC, ThomBos commented
> @ThomBos we merged a PR from Joe regarding the select fix, is the invisible thing still needed?

yes, need until we change select component!
if the new component is going to use "simplescrollbar" too, we'll keep that invisible option 

that invisible option wouldn't be necessary just if there was a way to tell the scrollbar not to keeping those 5px padding (scrollbar-width/height)

2022-06-22 10:11 UTC, josephmcg commented
you can remove any edits to Select in your rebase

2022-06-24 12:49 UTC, molimauro requested changes

2022-06-24 12:49 UTC, molimauro commented on components/ui/SimpleScroll/SimpleScroll.vue
> +    },
So is this still necessary after the rework?

2022-06-24 18:39 UTC, phillsatellite approved these changes

2022-06-28 14:15 UTC, molimauro approved these changes

2022-06-28 15:36 UTC, stavares843 approved these changes

2022-06-28 15:36 UTC, merged