fix(quickchat): improve quickchat/sidebar css
Satellite-im/Core-PWA pull request #3588
Opened 2022-06-13 09:32 UTC by josephmcg

**What this PR does** 📖
- rather than assigning a relatively arbitrary `left:` value to quickchat, now it will render beneath the parent button.
- I saw some simple improvements in sidebar as well while I was there
  - flex + gap
  - remove isMobile conditionals since this component will only be rendered on desktop

**Which issue(s) this PR fixes** 🔨
AP-1780

**Special notes for reviewers** 🗒️
quickchat would occasionally get shifted to the left during active calls, this will no longer do that. zindexes are working fine

**Additional comments** 🎤

2022-06-14 14:59 UTC, molimauro approved these changes

2022-06-14 17:40 UTC, phillsatellite approved these changes

2022-06-14 23:05 UTC, stavares843 requested changes
friend requests badge is not properly placed on this branch

<img width="875" alt="Captura de ecrã 2022-06-15, às 00 01 13" src="https://user-images.githubusercontent.com/29093946/173703459-e85ddd8e-5bb4-40ca-bc13-59d8c33096e3.png">


vs dev

<img width="865" alt="Captura de ecrã 2022-06-15, às 00 02 09" src="https://user-images.githubusercontent.com/29093946/173703473-491d6093-093c-4f0b-bd54-76f31c70d404.png">

2022-06-15 00:32 UTC, josephmcg commented
thanks! just fixed it

2022-06-16 00:56 UTC, josephmcg commented
whoops, my b. should be fixed now

2022-06-16 12:12 UTC, stavares843 approved these changes

2022-06-16 12:12 UTC, merged