feat(call): create background call component
Satellite-im/Core-PWA pull request #3591
Opened 2022-06-13 12:27 UTC by AlexZakablukov

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨
[AP-1781](https://satellite-im.atlassian.net/browse/AP-1781)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-13 12:49 UTC, AlexZakablukov commented
[AP-1753](https://satellite-im.atlassian.net/browse/AP-1753) also done in this pr

2022-06-14 08:16 UTC, josephmcg requested changes
may not be everything, would appreciate if @molimauro took a look too

2022-06-14 08:16 UTC, josephmcg commented on components/ui/BackgroundCall/BackgroundCall.html
> +>
move this `v-if` up to Global, otherwise this component is always in the virtual dom.
It's not relevant to this component since there's no local state (data), but this technique allows for data to be reset when it is not being rendered.

2022-06-14 08:16 UTC, josephmcg commented on components/ui/Global/Global.html
> +  <UiBackgroundCall />
move v if here

2022-06-14 08:16 UTC, josephmcg commented on assets/styles/framework/ui.less
> +@backgroundCall-height: 36px;
keep-it-kebab-case to fit the convention

2022-06-14 08:16 UTC, josephmcg commented on components/ui/BackgroundCall/BackgroundCall.html
> +  <span v-if="elapsedTime">- {{elapsedTime}}</span>
not sure how scalable this translation structure is.
I would probably make name and elapsed time translation params. You would lose some control over styles, but the translations would be more robust

2022-06-14 08:16 UTC, josephmcg commented on components/ui/BackgroundCall/BackgroundCall.html
> +  <span v-if="elapsedTime">- {{elapsedTime}}</span>
Are the if's necessary? would we ever have an active call without a caller or elapsed time?

2022-06-14 08:16 UTC, josephmcg commented on components/ui/BackgroundCall/BackgroundCall.less
> +  cursor: pointer;
I think we have a class for border radius 4px. `&:extend(.round-corners)`
either that or variable `@corner-rounding: 4px;`

2022-06-14 08:16 UTC, josephmcg commented on components/ui/BackgroundCall/BackgroundCall.vue
> +      return this.friends.all.find(
always add return types to computed or `this` breaks

2022-06-14 08:16 UTC, josephmcg commented on components/views/media/heading/Heading.html
> +  <TypographyTag v-if="elapsedTime" :text="`${$t('ui.live')} ${elapsedTime}`" />
feed elapsed time as translation param

2022-06-14 09:14 UTC, AlexZakablukov commented on components/ui/BackgroundCall/BackgroundCall.html
> +  <span v-if="elapsedTime">- {{elapsedTime}}</span>
We can have a call without an elapsed time if he hasn't accepted it yet but the request has gone

https://user-images.githubusercontent.com/38879804/173541063-4b0bab66-7e94-4972-afba-64b3635ceb81.mp4

2022-06-14 09:25 UTC, AlexZakablukov commented on components/ui/Global/Global.html
> +  <UiBackgroundCall />
done

2022-06-14 09:26 UTC, AlexZakablukov commented on components/ui/BackgroundCall/BackgroundCall.less
> +  cursor: pointer;
done

2022-06-14 09:27 UTC, AlexZakablukov commented on components/ui/BackgroundCall/BackgroundCall.vue
> +      return this.friends.all.find(
done

2022-06-14 09:51 UTC, AlexZakablukov commented on assets/styles/framework/ui.less
> +@backgroundCall-height: 36px;
done

2022-06-14 12:47 UTC, molimauro commented on components/ui/BackgroundCall/BackgroundCall.vue
> +    },
this can be undefined

2022-06-15 08:04 UTC, AlexZakablukov commented on components/ui/BackgroundCall/BackgroundCall.vue
> +    },
fixed

2022-06-15 09:21 UTC, molimauro commented on components/ui/BackgroundCall/BackgroundCall.vue
> +    },
Can you instead return something that wont break the `caller.name` in the html? thanks!

2022-06-16 21:26 UTC, phillsatellite commented
Tested: Only found a few minor things

on IOS the display bar will appear in the very top status bar of IOS device forcing it to be unclickable 
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-16 at 17 23 40](https://user-images.githubusercontent.com/93608357/174168595-6ceed03b-3466-4465-b0b9-8a597cab4942.png)

other minor issue was when user has a theme selected the glow will be blue. I checked with Sara and she thought that the glow was supposed to be white
<img width="1710" alt="Screen Shot 2022-06-16 at 5 10 24 PM" src="https://user-images.githubusercontent.com/93608357/174168708-648ae709-561a-4c78-a038-9caf97d1f7f3.png">

2022-06-17 07:22 UTC, molimauro commented
@AlexZakablukov on body we have this rule, but the fixed position breaks it:
```
padding: env(safe-area-inset-top) env(safe-area-inset-right)
    env(safe-area-inset-bottom) env(safe-area-inset-left) !important;
    ```

2022-06-17 07:53 UTC, AlexZakablukov commented
I think it fixed, check, please

2022-06-18 16:22 UTC, stavares843 commented
if you are on a call and the banner is displayed and you go to settings and then click on the banner, it goes to the chat but settings are still on the front of the chat

<img width="1362" alt="Captura de ecrã 2022-06-18, às 17 20 51" src="https://user-images.githubusercontent.com/29093946/174447632-c7e6382e-3ca8-4e06-b02b-74e18341542b.png">
<img width="1352" alt="Captura de ecrã 2022-06-18, às 17 21 09" src="https://user-images.githubusercontent.com/29093946/174447634-6e06574d-b45b-452b-8da4-71bd04addcf6.png">

2022-06-18 16:23 UTC, stavares843 commented
- chat
- call 
- go to friends
- remove friend
- banner is still displayed even after the chat was removed 

<img width="1362" alt="Captura de ecrã 2022-06-18, às 17 21 30" src="https://user-images.githubusercontent.com/29093946/174447672-e85367a4-d80d-4290-9f77-a8651625560d.png">

2022-06-18 16:25 UTC, stavares843 commented
<img width="1106" alt="Captura de ecrã 2022-06-18, às 17 24 50" src="https://user-images.githubusercontent.com/29093946/174447747-bd4eb588-9ac5-42ad-b620-d822e87487e3.png">

if you start a call before chat loaded, no name appears on the banner

2022-06-18 16:27 UTC, stavares843 commented
<img width="587" alt="Captura de ecrã 2022-06-18, às 17 26 21" src="https://user-images.githubusercontent.com/29093946/174447835-79a18d9e-de55-49d8-90f6-0469cc6711ff.png">

if you zoom in, the corners on the banner are rounded

2022-06-18 16:30 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/174447975-5b998872-041f-48a3-9e57-4d1adfae5b94.mov


going to files while in a call, the banner disappears

2022-06-18 16:32 UTC, stavares843 requested changes
added comment above

2022-06-20 09:15 UTC, AlexZakablukov commented
fixed

2022-06-20 23:28 UTC, stavares843 commented
there are no new commits, can you push pls? @AlexZakablukov 🔨

2022-06-21 08:05 UTC, AlexZakablukov commented
> there are no new commits, can you push pls? @AlexZakablukov 🔨

ohh, I am sorry ( 
Done

2022-06-21 12:52 UTC, stavares843 commented
thanks 🎉

2022-06-23 19:23 UTC, Clayton215 commented
I went through the entire app on chrome and safari and the call banner stayed and worked as it should.

https://user-images.githubusercontent.com/96502187/175380795-b7b67365-4bab-492a-88ad-36713dc85aae.mov

2022-06-23 19:24 UTC, Clayton215 approved these changes

2022-06-28 07:44 UTC, AlexZakablukov commented on components/views/media/heading/Heading.html
> +      v-bind:key="ui.fullscreen"
done

2022-06-28 10:53 UTC, molimauro commented
Added QA tested directly since this change is just syntactic

2022-06-28 12:36 UTC, molimauro commented
Sorry changed idea, he also rebased better retest sorry

2022-06-28 15:26 UTC, phillsatellite commented
Found a few small issues when testing
If you click the banner it will take you to an empty chat screen with no call

https://user-images.githubusercontent.com/93608357/176218469-c6d7d231-e540-4e70-b310-ada9496aec17.mov

On IOS the banner looks better but it doesnt appear as soon as the user opens the sidebar, should it?

https://user-images.githubusercontent.com/93608357/176218680-f732a136-aaf1-42ff-8435-3aec7fbd456b.mp4

2022-06-29 09:20 UTC, AlexZakablukov commented
fixed

2022-06-29 10:26 UTC, molimauro commented on components/ui/Global/Global.html
> +    v-if="$device.isMobile ? isBackgroundCall || (isActiveCall && ui.showSidebar) : isBackgroundCall"
Create a computed without the ternary but with if/return

2022-06-29 10:26 UTC, molimauro requested changes
minors

2022-06-29 11:37 UTC, AlexZakablukov commented on components/ui/Global/Global.html
> +    v-if="$device.isMobile ? isBackgroundCall || (isActiveCall && ui.showSidebar) : isBackgroundCall"
fixed

2022-06-29 13:15 UTC, stavares843 requested changes

2022-06-29 13:15 UTC, stavares843 commented on components/views/media/heading/Heading.html
> -    data-cy="elapsed-time"
can you add the `data-cy="elapsed-time"` again pls? 🔨

2022-06-29 14:30 UTC, AlexZakablukov commented on components/views/media/heading/Heading.html
> -    data-cy="elapsed-time"
fixed

2022-06-29 14:34 UTC, stavares843 commented on components/views/media/heading/Heading.html
> -    data-cy="elapsed-time"
thanks! 😄

2022-06-29 16:48 UTC, phillsatellite approved these changes

2022-06-29 19:00 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/176515034-edb12850-b84e-436b-bfbb-32760ee82e15.mov


STR:
- chat
- call
- go to friends
- banner appear
- click
- goes to the chat and shows the call modal
- go to friends
- click on the message icon
- goes to the chat that has the call but no call modal and still shows the banner

2022-06-29 19:03 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/176515666-f45156d1-7170-48fa-9a6d-4902a29a8807.mov


if you have a coming soon modal, and click on the banner goes to the call but still has the coming soon banner in front

2022-06-29 19:18 UTC, stavares843 commented
<img width="1368" alt="Captura de ecrã 2022-06-29, às 20 12 23" src="https://user-images.githubusercontent.com/29093946/176517748-22b72e83-9fd1-453c-bfa1-f4d60514a6e8.png">

atm we only allow 32 chars when signing up, if we remove that limit or if we use this for group calling when we add that, the layout would break

2022-06-30 08:39 UTC, AlexZakablukov commented
fixed

2022-06-30 12:42 UTC, molimauro commented on components/ui/BackgroundCall/BackgroundCall.less
> +  right: 0;
`&:extend(.absolute-coverage)`

2022-06-30 12:45 UTC, molimauro commented
Instead of forcing the modal to close can we make this component on layer behind it so that the user cannot click on it until the modal is closed?

2022-06-30 14:21 UTC, AlexZakablukov commented on components/ui/BackgroundCall/BackgroundCall.less
> +  right: 0;
fixed

2022-07-01 06:59 UTC, molimauro approved these changes

2022-07-01 15:55 UTC, phillsatellite approved these changes

2022-07-01 19:37 UTC, stavares843 approved these changes

2022-07-01 19:37 UTC, stavares843 commented
🎉

2022-07-01 19:37 UTC, merged