feat(groupinvite): use userpicker component
Satellite-im/Core-PWA pull request #3607
Opened 2022-06-14 01:16 UTC by jasonwoodland

**What this PR does** 📖
- Use the new user picker component in the group invite UI
- Add exclude prop to userpicker so we can hide members from the group invite UI

**Which issue(s) this PR fixes** 🔨
AP-1777

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-14 20:41 UTC, WanderingHogan commented on components/views/group/invite/Invite.vue
> +                group: this.modal.group,
group does not exist

2022-06-14 20:43 UTC, WanderingHogan requested changes
good when that one issue is accounted for

2022-06-14 23:16 UTC, jasonwoodland commented on components/views/group/invite/Invite.vue
> +                group: this.modal.group,
Good spot

2022-06-15 03:27 UTC, josephmcg approved these changes

2022-06-15 04:24 UTC, WanderingHogan approved these changes

2022-06-15 19:32 UTC, stavares843 commented
<img width="395" alt="Captura de ecrã 2022-06-15, às 20 31 31" src="https://user-images.githubusercontent.com/29093946/173909191-84792d71-e24b-451a-98a5-592a9ab1f631.png">

if you click on add member without selecting any users, the picker just gets dismissed

2022-06-17 06:15 UTC, josephmcg requested changes

2022-06-17 06:15 UTC, josephmcg commented on components/views/navigation/toolbar/Toolbar.html
> +    />
I removed this GroupCreate component. it was the redundant one, we're replacing with quickChat at a later date

2022-06-17 19:32 UTC, iltumio approved these changes

2022-06-18 17:27 UTC, stavares843 approved these changes

2022-06-18 17:29 UTC, merged