fix(account): client side validation for user status
Satellite-im/Core-PWA pull request #3639
Opened 2022-06-15 05:55 UTC by josephmcg

**What this PR does** 📖
- client side validation for status (max length 128)
- switch account errors to array in case there are status and username errors at the same time

**Which issue(s) this PR fixes** 🔨
AP-1806

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-15 13:18 UTC, molimauro approved these changes

2022-06-15 15:57 UTC, stavares843 requested changes

2022-06-15 23:46 UTC, josephmcg commented on locales/en-US.js
> +      status_error: 'Status cannot exceed {max} characters',
I wrote a comment about this in the code. you cant prevent the user from editing source, so we need a js check in case they manually adjusted maxlength of either field

2022-06-16 12:49 UTC, stavares843 requested changes
dev

<img width="972" alt="Captura de ecrã 2022-06-16, às 13 44 12" src="https://user-images.githubusercontent.com/29093946/174073085-61c53f9d-6499-40a3-be37-290ed7b6e6fb.png">

this branch

<img width="1083" alt="Captura de ecrã 2022-06-16, às 13 44 30" src="https://user-images.githubusercontent.com/29093946/174073155-004c3008-d6f2-46f5-81a0-51dd60a4b896.png">


has a extra spacing before the error messages

2022-06-16 12:59 UTC, stavares843 approved these changes

2022-06-16 12:59 UTC, merged