feat(newmessage): use userpicker
Satellite-im/Core-PWA pull request #3643
Opened 2022-06-15 10:25 UTC by jasonwoodland

**What this PR does** 📖
- Update the mobile new message UI to use the user picker component
- Fixes the creating a group on mobile

**Which issue(s) this PR fixes** 🔨
AP-1761
AP-1757

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-16 13:23 UTC, molimauro approved these changes

2022-06-17 04:52 UTC, jasonwoodland commented
Fixed the multi issue. Couldn't reproduce the not loading issue though:
https://user-images.githubusercontent.com/5356544/174227289-b58dcc58-ca1f-47a0-86a1-8fa192f88427.mov

2022-06-17 19:34 UTC, phillsatellite commented
> Fixed the multi issue. Couldn't reproduce the not loading issue though:
> 
>  Screen.Recording.2022-06-17.at.2.19.15.pm.mov

Sounds good! I'll go back in and see if I can still replicate or not 💥

2022-06-18 05:07 UTC, WanderingHogan approved these changes

2022-06-18 14:58 UTC, stavares843 commented
![image](https://user-images.githubusercontent.com/29093946/174444053-b9c2b43c-70c8-4869-9d56-2e49a515ff8d.png)


the account has a bunch of friends added, but it has that box on the middle of the screen with a scroll instead of just showing the whole list until the bottom

2022-06-18 14:59 UTC, stavares843 commented
![image](https://user-images.githubusercontent.com/29093946/174444096-991c3cd0-a903-4a15-ba18-d9ad7c4caf7a.png)


the avatars are cut off on mobile browser, safari, iPhone 12 pro max

2022-06-18 15:00 UTC, stavares843 commented
![image](https://user-images.githubusercontent.com/29093946/174444180-85839c52-e1d1-45b3-aca3-d83ea63dfff6.png)

the scroll bar is black and is barely visible

2022-06-18 15:01 UTC, stavares843 commented
if you add too many friends the create chat button gets hidden

![image](https://user-images.githubusercontent.com/29093946/174444203-fdc2e098-2126-4c30-8762-68a94b0c4022.png)


![image](https://user-images.githubusercontent.com/29093946/174444215-9e32bf05-fc49-4ba1-af22-e2741f13081c.png)

2022-06-18 15:03 UTC, stavares843 commented
btw @phillsatellite noticed that group created on mobile appears on desktop but never appears on mobile sidebar

https://user-images.githubusercontent.com/93608357/174444014-63b80b8d-02f3-4b4d-89b5-b81754445143.mov

2022-06-19 02:27 UTC, jasonwoodland commented
> <img alt="" height="500" src="https://user-images.githubusercontent.com/29093946/174444180-85839c52-e1d1-45b3-aca3-d83ea63dfff6.png">
> 
> the scroll bar is black and is barely visible

Because the OS is in light mode, it's using the dark scrollbar variant. In dark mode it looks correct. This seems to be an issue across the rest of the app if you want to open an issue for it.

2022-06-20 23:20 UTC, stavares843 commented
thanks for clarifying about the scroll bar 🔨 

rest is fixed 🎉

2022-06-20 23:27 UTC, stavares843 requested changes
dev 

<img width="1338" alt="Captura de ecrã 2022-06-21, às 00 26 17" src="https://user-images.githubusercontent.com/29093946/174688508-78ddc0db-c3ea-4074-9057-9366e7420ade.png">


vs this branch

<img width="1347" alt="Captura de ecrã 2022-06-21, às 00 26 30" src="https://user-images.githubusercontent.com/29093946/174688515-35b94752-9347-4611-ac2d-1b97f8104d80.png">

seed

end electric swear hurdle business priority salad ancient wire change please purpose

2022-06-21 12:55 UTC, stavares843 commented
<img width="410" alt="Screenshot 2022-06-21 at 13 55 18" src="https://user-images.githubusercontent.com/29093946/174804285-ed510640-4d0a-46e6-8f07-446f51d15bb6.png">


missing scroll

on dev has scroll on that component

seed

end electric swear hurdle business priority salad ancient wire change please purpose

2022-06-22 04:54 UTC, josephmcg requested changes

2022-06-22 04:54 UTC, josephmcg commented on components/ui/SatelliteCircle/SatelliteCircle.less
> +
whats the significance of this red?

2022-06-22 04:54 UTC, josephmcg commented on pages/message/index.vue
> +      }
rather than this guard clause, how about we show a loader instead of the icon while the group is being created? I didn't receive any feedback that the group was being created and wasn't sure if it worked

2022-06-22 04:55 UTC, josephmcg commented
I wonder if the group name input placement could be improved as well. that friends list could get pretty long, may be better at the top than the bottom

2022-06-23 03:03 UTC, jasonwoodland commented on components/ui/SatelliteCircle/SatelliteCircle.less
> +
leftover from testing, thanks for spotting

2022-06-23 03:33 UTC, jasonwoodland commented on pages/message/index.vue
> +      }
I kept the guard, so the user can't spam call the method, but I did add the loading indicator

2022-06-23 05:34 UTC, josephmcg approved these changes

2022-06-23 14:34 UTC, stavares843 commented
![image](https://user-images.githubusercontent.com/29093946/175324966-cd522039-5955-409e-8754-961b7ae402cf.png)

missing scroll on mobile 

seed

end electric swear hurdle business priority salad ancient wire change please purpose

2022-06-27 02:13 UTC, josephmcg commented
missing scroll as in the container doesn't scroll and the user can't see content? or its just missing the scrollbar?
I'm working on scrollbar visual stuff in a separate ticket. If there's minor visual issues, I can fix them separately

2022-06-29 02:48 UTC, josephmcg commented
@stavares843 mine is scrolling ok, could you look again?
![image](https://user-images.githubusercontent.com/33670767/176340433-dbaa0735-7067-436f-815f-22ea5546588a.png)

2022-06-29 05:36 UTC, josephmcg commented
latest change works on simulator for me

2022-06-29 12:57 UTC, stavares843 approved these changes

2022-06-29 12:58 UTC, merged