fix(sidebar): get last message and display it in sidebar
Satellite-im/Core-PWA pull request #3677
Opened 2022-06-16 13:40 UTC by AlexZakablukov

**What this PR does** 📖
get last message and display it in sidebar

**Which issue(s) this PR fixes** 🔨
[AP-1410](https://satellite-im.atlassian.net/browse/AP-1410)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-17 18:43 UTC, phillsatellite commented
Is there anything we can do about all the loading bars appearing when user logs in? Sara and I we're both thinking it looked kinda messy 
https://user-images.githubusercontent.com/93608357/174358463-a2a513dd-be46-4cb1-8589-a72e409cf97f.mov

2022-06-17 18:43 UTC, stavares843 commented
agree

2022-06-17 18:46 UTC, molimauro commented
We can change the loader or we can remove it and show the last msg we have in store (even though can be that is not the last) and once the real last is fetched show finally that

2022-06-20 10:29 UTC, AlexZakablukov commented
Fixed, now it shows the last message from the store while the actual last message is loading, without any loaders

2022-06-21 23:10 UTC, Clayton215 commented
The sidebar works as should, however, I am not able to send pictures out of local. They show as sent on the local account but they don't actually go through. 
<img width="1728" alt="Screen Shot 2022-06-21 at 7 07 16 PM" src="https://user-images.githubusercontent.com/96502187/174911326-b7be031c-5e5f-4913-a8b3-801ea987b8d3.png">

2022-06-22 01:15 UTC, josephmcg requested changes
whats the goal of switching it from the textile store namespace to friends? I thought we already had a decent foundation and would just build that out

2022-06-22 10:58 UTC, AlexZakablukov commented
> whats the goal of switching it from the textile store namespace to friends? I thought we already had a decent foundation and would just build that out

I made it because we use friends and groups but not conversations in sidebar, when we add a new friend conversation does not create and till we enter the chat a conversation will not create, but a friend can write us and the last message should be 
 changed. 
But if you think it is the wrong way, I can return it to textile

2022-06-23 01:38 UTC, josephmcg commented
Thanks Alex, I'm honestly not sure what the 'correct place' for it is. I think it would be ideal if it could be more centralized, rather than spread across multiple store modules. but that's probably a separate discussion altogether

2022-06-23 16:10 UTC, molimauro commented
Sara has the same problem too, @AlexZakablukov can you double check please?

2022-06-23 16:11 UTC, stavares843 commented
correct tried here, and was the same

I was able to send images but not receiving them 🔨

2022-06-28 09:57 UTC, AlexZakablukov commented
done, check pls)

2022-06-28 13:17 UTC, molimauro commented on store/textile/getters.ts
> +      }
this can be removed since we have the `?`

2022-06-28 13:27 UTC, molimauro commented on components/views/user/User.html
> +      v-if="lastMessage"
isnt this always true?

2022-06-28 13:29 UTC, molimauro commented on store/textile/mutations.ts
> +    state.conversations = conversations
are you spreading for reactivity right?

2022-06-29 08:11 UTC, AlexZakablukov commented on store/textile/mutations.ts
> +    state.conversations = conversations
Yes, I don't want to mutate the state

2022-06-29 08:12 UTC, AlexZakablukov commented on components/views/user/User.html
> +      v-if="lastMessage"
you are right

2022-06-29 09:02 UTC, molimauro commented on store/textile/mutations.ts
> +    state.conversations = conversations
Ok perfect then!

2022-06-29 09:23 UTC, AlexZakablukov commented on store/textile/getters.ts
> +      }
fixed

2022-06-29 10:24 UTC, molimauro commented on components/views/user/User.html
> +      v-if="lastMessage"
still can see this

2022-06-29 11:24 UTC, AlexZakablukov commented on components/views/user/User.html
> +      v-if="lastMessage"
changed

2022-06-30 15:29 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/176716230-a73f044c-489d-45ef-bafe-856eac7da15b.mov

the messages were both showing 1:00 as a timestamp until user opened the conversation

2022-07-01 08:21 UTC, AlexZakablukov commented
fixed

2022-07-01 19:02 UTC, phillsatellite approved these changes

2022-07-05 07:24 UTC, molimauro approved these changes

2022-07-15 23:34 UTC, WanderingHogan commented
Closing this one and leaving the branch for now. We can come back to it when we get to it. This PR touches on a major change that iridium brings - the textile store and messages being stored in indexeddb are going away. We can come back to this close PR and branch though when we are able to port any needed changes to iridium

2022-07-15 23:34 UTC, closed without merging