fix(friendslist): scroll list
Satellite-im/Core-PWA pull request #3760
Opened 2022-06-20 10:30 UTC by jasonwoodland

**What this PR does** 📖
- Adds scroll wrapper to friend invitation list

**Which issue(s) this PR fixes** 🔨
AP-1857

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-20 13:11 UTC, Jekrimo approved these changes

2022-06-20 23:33 UTC, stavares843 requested changes
<img width="991" alt="Captura de ecrã 2022-06-21, às 00 33 10" src="https://user-images.githubusercontent.com/29093946/174688892-43a2f81b-1bc7-4be9-bb0c-5651f07d541a.png">

<img width="958" alt="Captura de ecrã 2022-06-21, às 00 33 05" src="https://user-images.githubusercontent.com/29093946/174688896-fd3e0561-a098-4759-99fe-113cd2bec48f.png">

dev vs this branch

seed
room pause scissors protect run mammal mass holiday cliff add lounge reveal

2022-06-21 15:32 UTC, stavares843 approved these changes

2022-06-22 05:00 UTC, josephmcg requested changes
i think 3 scrollbars for one page is a bit much. Could we try one large scroll on the page?
make this overflow-y:auto, let global scroll css handle the rest
<img width="181" alt="image" src="https://user-images.githubusercontent.com/33670767/174947171-86a3de70-1450-4257-a8fd-fc3791434275.png">

2022-06-23 04:43 UTC, josephmcg commented
after consulting with Jason, I'll handle this in a more global scroll css update

2022-06-23 04:43 UTC, closed without merging