fix(chatbar-mobile): fixed chatbar focus when pressed
Satellite-im/Core-PWA pull request #3777
Opened 2022-06-21 14:38 UTC by ThomBos

**What this PR does** 📖
Fixes the issue that occurs when a mobile user presses on the chatbar (it loses focus when trying to type a message and closes the keyboard)
**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-23 00:11 UTC, WanderingHogan commented
https://user-images.githubusercontent.com/2993032/175180930-bd0d5519-e1b6-465b-8024-bfd3bffe21cc.mp4

2022-06-23 14:10 UTC, ThomBos commented
> telegram-cloud-document-1-5017426283185832685.mp4

reverse typing is a feature, not a bug :joy:

i'm testing again, but should be all solved

2022-06-28 14:24 UTC, molimauro commented on components/ui/Chat/Scroll/Scroll.html
> +  v-on:scroll="onScrolled()"
`@scroll`

2022-06-28 14:31 UTC, molimauro requested changes

2022-06-28 14:33 UTC, ThomBos commented on components/views/chat/message/Message.vue
> +      }, 150)
this fixes a reply issue that caused the chatbar to lose focus when the reply button was pressed (due to v-click-outside)

2022-06-28 14:54 UTC, ThomBos commented on components/views/chat/message/Message.vue
> +      }, 150)
the chatbar appears and you have to close it and press back again, to make it work

2022-06-29 07:30 UTC, molimauro approved these changes

2022-06-29 07:45 UTC, ThomBos commented on components/views/chat/message/Message.vue
> +      }, 150)
> Could we go for nextTick rather than timeout?
idk, i go check if it works 👍

2022-07-01 16:29 UTC, phillsatellite approved these changes

2022-07-01 22:10 UTC, stavares843 approved these changes

2022-07-01 22:10 UTC, merged