Ap 1807
Satellite-im/Core-PWA pull request #3806
Opened 2022-06-23 17:03 UTC by Jekrimo

**What this PR does** 📖
adds missed call alert, adds friend request alert

**Which issue(s) this PR fixes** 🔨

AP-1807 & AP-1532

2022-06-24 22:02 UTC, stavares843 commented
good point 🔨 i'd say if the user declined the call, maybe we don't need the alert regarding a missing call

2022-06-27 16:28 UTC, Jekrimo commented
> good point 🔨 i'd say if the user declined the call, maybe we don't need the alert regarding a missing call

Good call! Got a fix up!

2022-06-30 16:34 UTC, Clayton215 approved these changes

2022-07-05 07:44 UTC, molimauro requested changes

2022-07-05 07:44 UTC, molimauro commented on store/textile/actions.ts
> -  addMessageToConversation(
Why this has been deleted?

2022-07-05 07:44 UTC, molimauro commented on store/textile/actions.ts
> -      dispatch('addMessageToConversation', {
also, why these changes?

2022-07-05 07:47 UTC, molimauro commented
The notifications part looks neat!! Some questions about the code not related to this PR ;)

2022-07-05 14:10 UTC, molimauro commented
Mmmm @stavares843 why are we merging dev in the PRs?

@Jekrimo if they are not related to this PR id try to remove them, can you try it? Or close this one and keep only the commit related to your work.. Thanks!

2022-07-05 14:17 UTC, stavares843 commented
because rebase wasn't available due to conflicts @molimauro 

merging dev didn't deleted anything, it just updated the PR with the latest dev


as you can see on dev branch - screenshot below, these lines are available on dev

<img width="1240" alt="Captura de ecrã 2022-07-05, às 15 16 58" src="https://user-images.githubusercontent.com/29093946/177349168-cfbce7fe-3ab8-4615-90aa-8e9dd2b57b8a.png">



but they are being removed on this PR, so these changes are related to the PR, and not from merging dev or rebasing or anything similar



<img width="1074" alt="Captura de ecrã 2022-07-05, às 15 15 48" src="https://user-images.githubusercontent.com/29093946/177348913-b0fa0c33-41ee-4f62-84f5-c202af951ad0.png">

2022-07-05 14:19 UTC, stavares843 commented
such as if you go to the initial commits, that was already removed here on the first commit

https://github.com/Satellite-im/Core-PWA/pull/3806/commits/f43b461fc393102f08deac6706b6897a137808a8#diff-263e7ed642b6b3ea140ee1955884bf4d42f4cfc4f286eac45d08f7bac78dcf7dL203

2022-07-05 14:20 UTC, josephmcg commented
There are definitely issues here. If it can't be rebased without solving conflicts, a dev should rebase locally. A lot of files work i did recently is being removed

2022-07-05 14:27 UTC, josephmcg commented
It seems like conflicts were 'resolved' by accepting current changes and disregarding incoming, rather than picking what we need from both

2022-07-05 14:27 UTC, stavares843 commented
@josephmcg 

if you go to the initial commits, that was already removed here on the first commit

https://github.com/Satellite-im/Core-PWA/commit/f43b461fc393102f08deac6706b6897a137808a8#diff-263e7ed642b6b3ea140ee1955884bf4d42f4cfc4f286eac45d08f7bac78dcf7dL203


its not related to any rebase or merging dev 😅

2022-07-05 14:45 UTC, Jekrimo commented
I think that fixed it?

2022-07-05 14:57 UTC, molimauro commented
@Jekrimo this one is needed? `store/textile/actions.ts`

2022-07-05 16:00 UTC, stavares843 commented on store/textile/actions.ts
> +    // Since this is async, we have to check that we are still in the chat, if
can we add the comments using multi line? 💥 

/**

2022-08-08 15:58 UTC, WanderingHogan commented
closing, but leaving branch in case we come back to it when we integrate notifications in iridium

2022-08-08 15:58 UTC, closed without merging