fix(notifications): text overflow for notifications
Satellite-im/Core-PWA pull request #3839
Opened 2022-06-28 01:36 UTC by josephmcg

**What this PR does** 📖
- fix overflow for long notifications, add full text on hover with html title attribute
- refactor alerts css to be relative to the icon
- remove floating container since this is the only place we're using it

**Which issue(s) this PR fixes** 🔨
AP-1907

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-28 15:56 UTC, phillsatellite approved these changes

2022-06-29 13:28 UTC, molimauro approved these changes

2022-06-29 14:50 UTC, stavares843 commented on components/views/navigation/toolbar/alerts/alert/Alert.html
> +    :data-cy="alertImage ? 'satellite-circle-profile' : 'circle-without-picture'"
the format of the `data-cy` should be 

`data-cy="circle-without-picture"`

instead of 

`'':data-cy="alertImage ? 'satellite-circle-profile' : 'circle-without-picture'"''`

you can update the naming if you want, but can you revert the format pls? 🔨

2022-06-29 14:50 UTC, stavares843 requested changes

2022-06-29 14:50 UTC, stavares843 commented on components/views/navigation/toolbar/alerts/alert/Alert.html
> +    :data-cy="alertImage ? 'satellite-circle-profile' : 'circle-without-picture'"
the format of the data-cy should be

data-cy="circle-without-picture"

instead of

'':data-cy="alertImage ? 'satellite-circle-profile' : 'circle-without-picture'"''

you can update the naming if you want, but can you revert the format pls? 🔨

2022-06-30 02:00 UTC, josephmcg commented on components/views/navigation/toolbar/alerts/alert/Alert.html
> +    :data-cy="alertImage ? 'satellite-circle-profile' : 'circle-without-picture'"
I wanted to provide flexibility for a new test. This will have a value of circle-without-picture if there is no picture provided

2022-06-30 02:05 UTC, josephmcg commented on components/views/navigation/toolbar/alerts/alert/Alert.html
> +    :data-cy="alertImage ? 'satellite-circle-profile' : 'circle-without-picture'"
now it will only have the cy attribute if there is no picture provided.

2022-06-30 13:47 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/176693644-dca80671-35bf-4757-a3c2-912760e587f5.mov


seed 
oval dignity twist coyote frozen exchange fiscal april doll conduct pudding meat

Chrome, macOS

2022-07-01 04:01 UTC, josephmcg commented
@stavares843 I got the same visual bug just switching branches. I deleted a parent component of the alerts, so this needs a hard restart to work properly

2022-07-01 12:28 UTC, stavares843 commented
thought was a scroll issue, thanks 💥

2022-07-01 12:28 UTC, stavares843 approved these changes

2022-07-01 12:28 UTC, merged