fix(friends): add friend picture shrinking
Satellite-im/Core-PWA pull request #3842
Opened 2022-06-28 04:07 UTC by josephmcg

**What this PR does** 📖
- prevent shrink of profile picture on outgoing friend request
- simplify logic to show uistate or just plain circle on outgoing friend request

**Which issue(s) this PR fixes** 🔨
AP-1881

**Special notes for reviewers** 🗒️
ticket mentioned it disappears at a certain point. that's the mobile breakpoint

**Additional comments** 🎤

2022-06-28 17:00 UTC, Clayton215 commented
Tested on chrome and Safari, the profile pictures no longer shrink. the name shrinks as it should

https://user-images.githubusercontent.com/96502187/176239444-52162194-3afb-4ffa-926b-2b747afbf8d3.mov

.

2022-06-29 16:33 UTC, stavares843 requested changes

2022-06-29 16:34 UTC, stavares843 commented
regarding the comment above


dev

<img width="852" alt="Captura de ecrã 2022-06-29, às 17 32 15" src="https://user-images.githubusercontent.com/29093946/176489119-ecaf5f49-5daa-4166-94e6-d9efaff3e928.png">


vs this branch

<img width="856" alt="Captura de ecrã 2022-06-29, às 17 31 51" src="https://user-images.githubusercontent.com/29093946/176489184-190d6716-fc5c-4bd0-bde4-d8650cfb927d.png">

2022-06-30 02:25 UTC, josephmcg commented on components/views/friends/friend/Friend.vue
> -    showStatus(): boolean {
I removed it because it's unnecessary to rely on store for this check, you can conditionally render based on other props. I recommended this approach in that very same PR

2022-06-30 02:30 UTC, josephmcg commented
didn't realize we were hiding status there as well, adjusted render condition

2022-06-30 02:32 UTC, josephmcg commented on components/views/friends/friend/Friend.vue
> -    showStatus(): boolean {
its a lot easier to check for various booleans rather than do an array search. This should probably be refactored to have an optional 'type' prop, rather than 3 different props for type

2022-06-30 16:46 UTC, phillsatellite approved these changes

2022-06-30 21:09 UTC, stavares843 approved these changes

2022-06-30 21:09 UTC, merged