fix(files): keyboard accessible, hit esc to close
Satellite-im/Core-PWA pull request #3847
Opened 2022-06-28 07:45 UTC by josephmcg

**What this PR does** 📖
- keyboard nav for files preview. It's difficult to see while we still disable outline on focus, but the tooltips should help a bit

**Which issue(s) this PR fixes** 🔨
AP-1909

**Special notes for reviewers** 🗒️
This is ONLY the fullscreen file preview for filesystem. not chat preview, and not regular files page
![image](https://user-images.githubusercontent.com/33670767/176123036-a14ac614-6b27-4b5c-8097-659509860161.png)

**Additional comments** 🎤

2022-06-28 17:42 UTC, phillsatellite approved these changes

2022-06-29 13:54 UTC, molimauro requested changes

2022-06-29 13:54 UTC, molimauro commented on components/views/files/view/View.vue
> +    },
can we remove the async?

2022-06-30 02:34 UTC, josephmcg commented on components/views/files/view/View.vue
> +    },
that's currently a dummy function that has no way of being called (ui button has been removed because it isn't ready). I imagine it will have async logic since it needs to interact with textile/iridium

2022-06-30 03:53 UTC, josephmcg commented on components/views/files/view/View.vue
> +    },
commented out for now

2022-06-30 12:30 UTC, molimauro commented on components/views/files/view/View.vue
> +    },
perfect

2022-07-01 03:39 UTC, josephmcg commented
oh interesting. maybe this was an existing bug, I'll add a check to prevent this

2022-07-01 03:50 UTC, josephmcg commented
should be resolved now. I also cleaned up some css since my other pr added a global rule

2022-07-01 12:30 UTC, stavares843 commented
neat, thanks 💥 

yes could be a existing bug that was more reproducible with the esc button 🔨 i was only able to reproduce with the flow above

2022-07-01 19:22 UTC, stavares843 approved these changes

2022-07-01 19:22 UTC, merged