feat(modal): add fade animation
Satellite-im/Core-PWA pull request #3859
Opened 2022-06-29 05:42 UTC by jasonwoodland

**What this PR does** 📖
- Add fade in/out animation to modal

**Which issue(s) this PR fixes** 🔨
AP-1917

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-06-29 07:21 UTC, josephmcg requested changes

2022-06-29 07:21 UTC, josephmcg commented on assets/styles/framework/animations.less
> +@animation-speed-slow: 0.25s;
could you clean these up while you're working on it? maybe remove micro and switch all instances of that to animation-speed

2022-06-29 07:21 UTC, josephmcg commented on components/ui/Modal/Modal.less
> +    filter: @light-blur !important;
any way to avoid important? if this is overriding other important, try removing those instead

2022-06-30 13:01 UTC, jasonwoodland commented on assets/styles/framework/animations.less
> +@animation-speed-slow: 0.25s;
you mean consolidate all mentions of `@animation-speed-micro` to just `@animation-speed`?

I know they're the same value now, but maybe we might want to differentiate in the future? Or is it safe to do so?

2022-06-30 13:02 UTC, jasonwoodland commented on components/ui/Modal/Modal.less
> +    filter: @light-blur !important;
oops, forgot to remove that 😅

2022-06-30 13:15 UTC, josephmcg commented on assets/styles/framework/animations.less
> +@animation-speed-slow: 0.25s;
Yep, thats what i mean. If theyre the same value, they might as well use the same variable. If somebody wants to add a third speed later, they can

2022-07-01 04:32 UTC, josephmcg approved these changes

2022-07-01 18:02 UTC, phillsatellite commented
Found small UI issue when navigating from friends page to the Coming Soon modal looks like you can see the modal sliding in
https://user-images.githubusercontent.com/93608357/176947139-c53c0282-449c-4522-9173-f7562dbc8fa9.mp4

2022-07-06 12:04 UTC, jasonwoodland commented
@phillsatellite good spot, was this on safari? I think it was animating the transform-origin value which caused the glitch. Anyway I've moved the transform-origin outside of the animation ruleset.

2022-07-06 17:15 UTC, phillsatellite commented
> @phillsatellite good spot, was this on safari? I think it was animating the transform-origin value which caused the glitch. Anyway I've moved the transform-origin outside of the animation ruleset.

Hey @jasonwoodland! It was on Safari 🔥

2022-07-28 07:36 UTC, josephmcg approved these changes

2022-07-28 07:38 UTC, merged