feat(iridium): add settings manager
Satellite-im/Core-PWA pull request #3946
Opened 2022-07-11 11:07 UTC by jasonwoodland

**What this PR does** 📖
- Implement iridium SettingsManager
- Refactor IridiumManager so that the managers are not typed as optional (removes need for null checking at component-level)
- Apply iridium theme settings values across app

**Which issue(s) this PR fixes** 🔨
AP-1952

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-07-11 13:29 UTC, molimauro commented on assets/styles/base.less
> -      background: rgba(var(--flair-color-rgb), 0.99) !important;
the `rgba(var(--flair-color-rgb), 0.99) !important` was needed for a text selection bug in Safari

2022-07-11 13:31 UTC, molimauro requested changes

2022-07-12 00:29 UTC, josephmcg commented on assets/styles/base.less
> -      background: rgba(var(--flair-color-rgb), 0.99) !important;
I think he meant to switch this to a new variable. Rather than keep track of rbg, we decided to append 'fe' to the regular primary color, making an 8 digit hex code that achieves the same thing

2022-07-12 01:28 UTC, jasonwoodland commented on assets/styles/base.less
> -      background: rgba(var(--flair-color-rgb), 0.99) !important;
@molimauro @josephmcg you're right I did forget to update the variable name here. I decided a better solution would be to generate the rgb value instead so we can keep it like this with less overhead. See https://github.com/Satellite-im/Core-PWA/pull/3946/commits/cead93821ee9c751986a86f1b84eb35157b5bb39

2022-07-14 08:40 UTC, josephmcg approved these changes
excellent work Jason, sets a strong foundation and creates some great utilities that can be implemented in other iridium modules

2022-07-14 08:47 UTC, molimauro approved these changes

2022-07-14 08:48 UTC, merged