fix(files): add all functionality to iridium filesManager
Satellite-im/Core-PWA pull request #3954
Opened 2022-07-12 06:35 UTC by josephmcg

**What this PR does** 📖
- remove dependence on FilSystem class. previous functionality has been divided in the following ways
  - files index - iridium FilesManager store.items
  - path - files store
  - rename, like, delete - iridium FilesManager
- move ui store items to the new files module, since it's more fitting

**Which issue(s) this PR fixes** 🔨
AP-1953

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-07-12 13:34 UTC, molimauro requested changes
Super, awesome Joe. Just a minor question, thanks!!

2022-07-12 14:26 UTC, josephmcg commented on components/views/files/filepath/Filepath.html
> +      v-if="path.length"
the v-if? guess not, ill remove rn

2022-07-14 09:09 UTC, josephmcg commented
made some minor adjustments after Jason's settings manager got merged. I may adjust how the store is being handled in a separate PR. a utility he added could help simplify the issue of remote instances

2022-07-15 00:57 UTC, josephmcg commented on libraries/Iridium/files/FilesManager.ts
> +      // TODO- maybe store thumbnail blob in ipfs as second object, then store hash here and lazy load
yep,
https://satellite-im.atlassian.net/browse/AP-1877

2022-07-15 00:59 UTC, josephmcg commented on components/views/files/list/List.vue
> +    // this.$data.timer = setInterval(
thanks, i commented out while removing a bunch of old logic. reimplemented a decent version. will refactor later
https://satellite-im.atlassian.net/browse/AP-1990

2022-07-15 01:01 UTC, josephmcg commented on locales/en-US.js
> +        invalid: 'Item name cannot contain invalid symbols (/:"*?<>|~#%&+{}\\)',
it's straight from the regex used to check the name
https://github.com/Satellite-im/Core-PWA/blob/dev/config.ts#:~:text=//%20invalid%20characters%20in%20filesystem%20name

2022-07-15 01:03 UTC, josephmcg commented
sidebar will have correct value on initial page load. it doesn't react to new additions, strangely. I'll set something up for that in a separate ticket
https://satellite-im.atlassian.net/browse/AP-1991

2022-07-15 01:52 UTC, merged