fix(friends-requests): improved requests and notifications display
Satellite-im/Core-PWA pull request #3955
Opened 2022-07-12 13:14 UTC by ThomBos

**What this PR does** 📖
Fixed friends requests display
**Which issue(s) this PR fixes** 🔨
AP-1954

**Special notes for reviewers** 🗒️

**Additional comments** 🎤
Still missing some data to show (name and image, just when the other user hasn't accepted the request)

2022-07-12 13:17 UTC, ThomBos commented on components/views/friends/add/Add.vue
> +      this.user = {
i think we should add a check function here to see if the id exists and show the confirm button (now we are just showing it, after clicking it we check the id)
the previous version sent automatically the request when the id was valid

2022-07-12 13:25 UTC, ThomBos commented on libraries/Iridium/friends/FriendsManager.ts
> +    await this.set(`/details/${friendId}`, null)
this doesn't really remove the friend (just removes from the display) 😬 
other user doesn't get any event or notification

2022-07-12 13:51 UTC, molimauro commented on libraries/Iridium/friends/FriendsManager.ts
> +    await this.set(`/details/${friendId}`, null)
because is still not implemented in iridium?

2022-07-12 13:57 UTC, ThomBos commented on libraries/Iridium/friends/FriendsManager.ts
> +    await this.set(`/details/${friendId}`, null)
no idea, i have to ask Drew, but i don't see any other function that removes friends

2022-07-12 13:59 UTC, ThomBos commented on libraries/Iridium/friends/FriendsManager.ts
> +    await this.set(`/details/${friendId}`, null)
> because is still not implemented in iridium?

the only thing i know that's missing rn on iridium (so in this pr), is the name display when sending a friend request (we can see just the id)

2022-07-13 00:49 UTC, josephmcg commented on libraries/Iridium/friends/FriendsManager.ts
> +      return FriendsError.REQUEST_ALREADY_SENT
why return errors rather than throw?

2022-07-13 15:40 UTC, ThomBos commented on libraries/Iridium/friends/FriendsManager.ts
> +      return FriendsError.REQUEST_ALREADY_SENT
i need to show those error strings in the ui

2022-07-13 18:57 UTC, aewing commented on components/views/friends/friend/Friend.vue
> +        return this.$emit('requestSent', err)
Do we still need this emitter? Could we just listen to the emitted event on FriendsManager?

2022-07-13 19:22 UTC, ThomBos commented on components/views/friends/friend/Friend.vue
> +        return this.$emit('requestSent', err)
yeah i think it would work the same

2022-07-14 01:06 UTC, josephmcg requested changes

2022-07-14 01:06 UTC, josephmcg commented on components/views/navigation/sidebar/Sidebar.vue
> +    })
are we fully replacing the state value inside iridium anytime a request change comes in? Then we lose the observer in the component (setup in data). If you did a deepMerge, or just added the new request data to store individually, you wouldn't need to do this with the observers.

Jason implemented the deepMerge approach here
https://github.com/Satellite-im/Core-PWA/pull/3946

2022-07-14 01:06 UTC, josephmcg commented on components/views/friends/friend/Friend.vue
> +      this.$emit('requestSent')
I think we should just emit the did and pass it to a method in the parent component. Then that component would handle the try catch. Having an optional error param in the parent make it more complicated than it needs to be

2022-07-14 08:28 UTC, ThomBos commented on components/views/navigation/sidebar/Sidebar.vue
> +    })
a deepmerge seem a good solution, but can it work if it's done on the friendsmanager? (since it's there where we manage requests)

2022-07-14 08:36 UTC, ThomBos commented on components/views/friends/friend/Friend.vue
> +      this.$emit('requestSent')
yeah, i'm going to remove this and add what you and Drew suggested 👍

2022-07-14 10:01 UTC, josephmcg commented on components/views/navigation/sidebar/Sidebar.vue
> +    })
Good point, i'll take a closer look at this tomorrow

2022-07-15 09:10 UTC, ThomBos commented
@josephmcg let me know what you think about these changes! 🔨

2022-07-19 01:47 UTC, josephmcg requested changes
a couple ideas regarding FriendsManager state structure. If we switched details and requests to arrays, it would simplify a lot of this logic and improve Vue reactivity

2022-07-19 01:47 UTC, josephmcg commented on components/views/friends/add/Add.vue
> +    })
would it be simpler to wrap the possible error creating methods in a try/catch (or promise.catch if async)?

2022-07-19 01:47 UTC, josephmcg commented on components/views/navigation/sidebar/Sidebar.vue
> +    })
I see why this is needed with the current architecture. Vue observers can't pickup newly created objects. If we switched details & requests to arrays instead, we could get rid of this
![image](https://user-images.githubusercontent.com/33670767/179645933-bcd723ee-78b1-4931-be27-ef84d5e40cea.png)

2022-07-19 01:47 UTC, josephmcg commented on libraries/Iridium/friends/FriendsManager.ts
>      }
I mentioned in a similar comment above, but I think it would be easier to directly throw the error, then let the component method handle it

2022-07-19 07:57 UTC, ThomBos commented on components/views/navigation/sidebar/Sidebar.vue
> +    })
yeah, currently i've removed details and moved all it's content into a list[user object].
also we are keeping requests just if pending and it's now an array

2022-07-19 08:01 UTC, ThomBos commented on libraries/Iridium/friends/FriendsManager.ts
>      }
don't look at the code now, because it's going to change pretty soon, but the logic is the same... so i can tell you that i'm keeping the try catch also on the new code, but the reason is that both user are calling that function to create the request

2022-07-19 10:22 UTC, ThomBos commented
**Quick recap:**

- all states are now arrays instead of objects, removed details state because it's now stored into list
- requestSave clears non-pending requests and sends requests change events using requestSendUpdate
- removeFriend is disconnected from requestSendUpdate (but it does basically the same thing) because 'accepted' or 'rejected' requests are no more stored in the state
- removed unused functions

**Errors management is still in progress and has to be improved.** 🔨
At the moment i'm thinking of adding a new state to contain an error string, so the components can render that as it changes, this would cause to all throw to be removed though, in order to remove all try/catches around the app... 
 

**Any suggestion to improved this code are well welcomed!!** 💥🚀

2022-07-19 16:09 UTC, merged