feat(account): ux improvement to import account functionality
Satellite-im/Core-PWA pull request #4038
Opened 2022-07-22 13:20 UTC by vimercati-samir

What this PR does 📖
UX improvement to import account functionality:
- auto completion when inserting single / multiple words 
- button inside input to clear input text
- button to reset the passphrase 
- message error when one of multiple words inserted is incorrect

Which issue(s) this PR fixes 🔨
[AP-2000](https://satellite-im.atlassian.net/browse/AP-2000)

Special notes for reviewers 🗒️

Additional comments 🎤

2022-07-25 12:18 UTC, molimauro requested changes
some minors

2022-07-25 12:18 UTC, molimauro commented on components/ui/TypeAhead/TypeAhead.html
> +      v-on:keydown.down="onDownBrowseItem"
v-on => @

2022-07-25 12:18 UTC, molimauro commented on components/ui/TypeAhead/TypeAhead.vue
> +        }
cant we use `.every`?

2022-07-25 12:19 UTC, molimauro commented
![image](https://user-images.githubusercontent.com/50131258/180775964-e5666e74-5c1e-4150-94c4-0561af1b032b.png)

A bit off on mobile :)

2022-07-26 08:03 UTC, molimauro commented on components/ui/TypeAhead/TypeAhead.vue
> +        }
oh sorry didnt see the for, closing

2022-07-26 13:27 UTC, vimercati-samir commented on pages/setup/ImportAccount/index.vue
> +    bipList: function () {
resolved in commit 76e52f4e3781a7f02e9056aeda55d7da75ccfd7a

2022-07-26 13:28 UTC, vimercati-samir commented on components/ui/TypeAhead/TypeAhead.html
> +      v-on:keydown.down="onDownBrowseItem"
resolved in commit 76e52f4e3781a7f02e9056aeda55d7da75ccfd7a

2022-07-26 13:28 UTC, vimercati-samir commented on components/ui/TypeAhead/TypeAhead.html
> +  <div :class="{'search-box': true, 'right-icon': clearIcon && searchText.length > 0}">
resolved in commit 76e52f4e3781a7f02e9056aeda55d7da75ccfd7a

2022-07-26 13:29 UTC, vimercati-samir commented
> ![image](https://user-images.githubusercontent.com/50131258/180775964-e5666e74-5c1e-4150-94c4-0561af1b032b.png)
> 
> A bit off on mobile :)

resolved in commit 76e52f4e3781a7f02e9056aeda55d7da75ccfd7a

2022-07-26 14:03 UTC, molimauro approved these changes

2022-07-26 15:29 UTC, merged