refactor(buttons): remove old button's library
Satellite-im/Core-PWA pull request #4110
Opened 2022-08-02 09:12 UTC by ThomBos

**What this PR does** 📖
Refactor buttons in order to remove the old library, while keeping the same style
**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-02 09:15 UTC, ThomBos commented
Right now there's just the glowing effect that can be tested at the login page (moving the cursor near the pin box)
I'm aiming to create buttons with the same effect ASAP

2022-08-02 11:09 UTC, josephmcg commented on components/interactables/Button/HoverShader/HoverGlow.vue
> +      const target = e.target
params are MouseEvent

2022-08-02 16:58 UTC, ThomBos commented
thanks @josephmcg ! 🔨 💥

2022-08-03 16:01 UTC, ThomBos commented
i'm proceeding switching to new buttons all around the app, then (after it's tested) removing the old style used by old buttons (there's a lot 🙈)

2022-08-03 16:06 UTC, ThomBos commented
i'm proceeding changing old buttons with new ones, then i'm going to remove old styles
at the moment the only new button in the app is the one on the register page (the first of the two "random account generation")

2022-08-08 04:00 UTC, josephmcg requested changes

2022-08-08 07:37 UTC, josephmcg commented on components/interactables/Button/Button.less
> +  }
jason and I have a new font size 'framework' in progress. you can end up using these once it merges

https://github.com/Satellite-im/Core-PWA/pull/4145/files#diff-72c0c56d722c0bc5f5af8c978baed74d8f83b5072c67c4e522ee40e20011a780

2022-08-08 07:46 UTC, ThomBos commented on components/interactables/ButtonGroup/ButtonGroup.less
>      }
oh yeah, there are a lot of this...

2022-08-08 07:50 UTC, ThomBos commented on components/interactables/Button/Button.less
> +  }
> jason and I have a new font size 'framework' in progress. you can end up using these once it merges
> 
> https://github.com/Satellite-im/Core-PWA/pull/4145/files#diff-72c0c56d722c0bc5f5af8c978baed74d8f83b5072c67c4e522ee40e20011a780

sure!

2022-08-08 07:53 UTC, ThomBos commented on components/interactables/Button/Button.less
> +  }
> normal & medium are kind of confusing. maybe better sizes would be xs, sm, md, lg. Also would be less keystrokes when you're typing a prop

are we going to change these props on other components too? otherwise i think it might be better keeping them like this, just to keep props aligned

2022-08-08 07:58 UTC, ThomBos commented on components/interactables/Button/Button.less
> +    padding-top: calc(0.5em - 1px);
this style is here just to match what bulma's styled buttons, that one pixel doesn't make any difference...

2022-08-08 08:00 UTC, ThomBos commented on components/interactables/Button/Button.less
> +  }
checking it, but i think we are using it for mute/unmute buttons

2022-08-08 08:02 UTC, ThomBos commented on components/interactables/Button/HoverGlow/HoverGlow.less
> +    z-index: 1;
yes, it is for the mask that handles the hover and shows the glow effect

2022-08-08 08:04 UTC, ThomBos commented on components/interactables/Button/HoverGlow/HoverGlow.html
> +  </div>
i think it can be removed since its goal was to make it easier to handle the content, but it can be done with any element passed with a class

2022-08-08 08:10 UTC, ThomBos commented on components/interactables/Button/Button.vue
> +    },
idk... around the app it looks like 100% width is still very used, when it's not needed i just didn't put the prop and managed it from the parent (using .styled-button selector... but i'm gonna change it)

2022-08-08 08:12 UTC, josephmcg commented on components/interactables/Button/Button.less
> +  }
yep, I plan on moving the type definition to a more generic location. I can do that in a quick PR now so it's accessible

2022-08-08 08:14 UTC, ThomBos commented on components/interactables/Button/Button.less
> +  cursor: pointer;
no, but it's my fault, gonna fixing it

2022-08-08 08:16 UTC, ThomBos commented on components/interactables/Button/Button.less
> +  }
perfect! 👍

2022-08-08 08:25 UTC, ThomBos commented on components/interactables/Button/Button.less
> +    &:extend(.background-success-gradient);
> rather than adding these various :not rules, could you place these styles below the definition for .is-outlined?
can outlined be removed? i've never seen a single outlined button

2022-08-08 08:45 UTC, josephmcg commented on components/interactables/Button/Button.less
> +  }
if you pull latest changes, you can access the Size type here
types/typography.d.ts

2022-08-08 08:55 UTC, ThomBos commented on components/interactables/Button/Button.less
> +  }
ok thanks! keep me updated

2022-08-08 10:31 UTC, ThomBos commented
i've just noticed a weird thing.... 
we are just using 2 button sizes, normal (now sm) and small (now xs).
the other two: medium (md) and large (lg) are never used!

2022-08-10 07:33 UTC, ThomBos commented
@josephmcg since you're working on bulma as well, should i keep this pr updated or it might break something for you?

2022-08-10 08:02 UTC, josephmcg commented
@ThomBos 
I talked with Mauro yesterday and we decided that it would be simpler to handle this after bulma is removed. I planned on giving it to Jason since it's very similar with his input work from the other day

2022-08-12 14:39 UTC, josephmcg commented
Closing this out since button refactor is done

2022-08-12 14:39 UTC, closed without merging