fix(mute-toggle): cleared previous sounds played
Satellite-im/Core-PWA pull request #4187
Opened 2022-08-10 10:15 UTC by ThomBos

**What this PR does** 📖
Clears previous sounds played when mute/unmute button is pressed
**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-15 17:36 UTC, stavares843 commented on libraries/SoundManager/SoundManager.test.ts
> +    const result: any = inst.stopSounds([Sounds.CALL])
thanks for updating 🔨

2022-08-16 13:53 UTC, ThomBos commented on libraries/SoundManager/SoundManager.test.ts
> +    const result: any = inst.stopSounds([Sounds.CALL])
no prob!  👍

2022-08-16 19:00 UTC, aewing requested changes

2022-08-16 19:00 UTC, aewing commented on libraries/SoundManager/SoundManager.ts
> +      this.existsSound(sound)
since existsSound throws, the first sound that isn't loaded will short circuit this forEach and prevent the following sounds from stopping. Should we forEach playingSounds()?

2022-08-23 09:55 UTC, ThomBos commented on libraries/SoundManager/SoundManager.ts
> +      this.existsSound(sound)
it should throw only if the sound passed as payload doesn't exist, doesn't throw if the sound isn't playing

2022-08-23 12:56 UTC, ThomBos commented on libraries/SoundManager/SoundManager.test.ts
> +    const result: any = inst.stopSounds([Sounds.CALL])
had to remove it to... does it work like this? 🙈😅

2022-08-23 23:51 UTC, aewing commented on libraries/SoundManager/SoundManager.ts
> +        this.existsSound(sound)
this line is redundant now that we are checking for inclusion in sounds

2022-08-23 23:52 UTC, aewing approved these changes

2022-08-24 00:13 UTC, stavares843 commented on libraries/SoundManager/SoundManager.test.ts
> +    const result: any = inst.stopSounds([Sounds.CALL])
yes all green 🎉

2022-08-24 08:03 UTC, ThomBos commented on libraries/SoundManager/SoundManager.ts
> +        this.existsSound(sound)
oh yeah, playingSounds already executes existsSound on its own

2022-08-24 09:00 UTC, merged