feat(files-search): add simple implementation
Satellite-im/Core-PWA pull request #4269
Opened 2022-08-15 02:32 UTC by nathan-power

**What this PR does** 📖
- Adds simple implementation of file search that searches through currently selected directory.

**Which issue(s) this PR fixes** 🔨
AP-2096

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-15 03:24 UTC, jasonwoodland requested changes

2022-08-15 03:24 UTC, jasonwoodland commented on components/interactables/Input/types.d.ts
> +  | 'range'
remove
- radio
- range
- file
- date related ones?
- image?

2022-08-15 18:26 UTC, phillsatellite approved these changes

2022-08-16 08:40 UTC, jasonwoodland approved these changes
LGTM

2022-08-16 08:40 UTC, merged