feat(jest): 15% coverage for IdentityManager
Satellite-im/Core-PWA pull request #4291
Opened 2022-08-16 06:50 UTC by drepram

**What this PR does** 📖

Self-explanatory

**Which issue(s) this PR fixes** 🔨

AP-2128

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-16 14:33 UTC, stavares843 requested changes

2022-08-16 14:33 UTC, stavares843 commented on libraries/Iridium/IdentityManager.test.ts
> +describe('', () => {
can we add a name on the describe instead of being empty?

2022-08-16 18:43 UTC, aewing commented on libraries/Iridium/IdentityManager.test.ts
> +    expect(result).toEqual(
I think we should snapshot this

2022-08-16 18:44 UTC, aewing commented on libraries/Iridium/IdentityManager.test.ts
> +Object.defineProperty(global.self, 'crypto', {
Nice, can we maybe put this in a location where we can reuse it as a mock?

2022-08-16 18:45 UTC, stavares843 commented on libraries/Iridium/IdentityManager.test.ts
> +    expect(result).toEqual(
agree, avoids the spam below

2022-08-16 18:46 UTC, aewing commented on libraries/Iridium/IdentityManager.test.ts
> +  test('generateEntropyMessage', () => {
I might have structured these tests with a describe for each function, i.e.:

describe someFn:
  it should throw an error if a string is passed in
  it should return a uint8array
  it should execute prescribed some computation

The verbosity here helps us to be semantic about what we are testing and why, and makes it clear from a quick review which features we are promising or supporting.

2022-08-16 18:49 UTC, aewing commented on libraries/Iridium/IdentityManager.test.ts
> +    expect(result).toEqual(
Snapshots are useful when you get a lot of text or markup output because it's often easier to just gatekeep changes to it manually.

2022-08-16 18:50 UTC, stavares843 commented on libraries/Iridium/IdentityManager.test.ts
> +  test('generateEntropyMessage', () => {
btw I also added additional jest matchers [here](https://github.com/Satellite-im/Core-PWA/pull/4300) that will be available when the PR gets merged that could be useful when creating tests

2022-08-16 18:50 UTC, stavares843 commented on libraries/Iridium/IdentityManager.test.ts
> +    expect(result).toEqual(
also true

2022-08-18 11:05 UTC, stavares843 commented
<img width="847" alt="Captura de ecrã 2022-08-18, às 12 05 31" src="https://user-images.githubusercontent.com/29093946/185380396-0abcdb21-6c3e-40bc-86e3-7fad55d501af.png">

2022-08-22 11:17 UTC, drepram commented
Closing this PR because something's wrong with GitHub Actions. Will open a new one!

2022-08-22 11:17 UTC, closed without merging