feat(jest): 100% coverage for Iridium/chat/types
Satellite-im/Core-PWA pull request #4292
Opened 2022-08-16 06:56 UTC by drepram

**What this PR does** 📖

Self-explanatory

**Which issue(s) this PR fixes** 🔨

AP-2132

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-16 13:25 UTC, stavares843 commented
this needs to be added in iridium repo instead, please add this on that repo

2022-08-16 14:33 UTC, stavares843 requested changes

2022-08-16 14:33 UTC, stavares843 commented on libraries/Iridium/chat/types.test.ts
> +describe('', () => {
can we add a name on the describe instead of being empty?

2022-08-18 02:54 UTC, drepram commented
After I committed my changes, 1 test failed `libraries/BlockchainClient/adapters/Phantom/PhantomAdapter.test.ts`.  

I do not see the relation between the file in this PR with that test that's returning an error, but I find the use in bringing it up so that we may resolve it quickly.

2022-08-18 11:03 UTC, stavares843 commented
<img width="997" alt="Captura de ecrã 2022-08-18, às 12 03 41" src="https://user-images.githubusercontent.com/29093946/185380075-1c14aeda-9505-4226-9f89-5a2f12b37e00.png">

its all green on CI

is also all green locally, not sure why you got that error

2022-08-18 11:04 UTC, stavares843 approved these changes

2022-08-18 19:28 UTC, merged