feat(jest): 91% coverage for Iridium/utils
Satellite-im/Core-PWA pull request #4293
Opened 2022-08-16 07:19 UTC by drepram

**What this PR does** 📖

Self-explanatory

**Which issue(s) this PR fixes** 🔨

AP-2130

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-16 13:25 UTC, stavares843 commented
this needs to be added in iridium repo instead, please add this on that repo

2022-08-16 14:32 UTC, stavares843 requested changes

2022-08-16 14:32 UTC, stavares843 commented on libraries/Iridium/utils.test.ts
> +describe('', () => {
can we add a name on the describe instead of being empty?

2022-08-16 18:42 UTC, aewing commented on libraries/Iridium/utils.test.ts
> +describe('', () => {
I second this, as a dev it's really helpful if the test text is descriptive enough to tell me what this function was testing specifically so I can go straight to the code that it impacts without needing to read the test file.

2022-08-16 18:43 UTC, aewing commented on libraries/Iridium/utils.test.ts
> +describe('', () => {
(thought I should read the test file anyway)

2022-08-18 02:56 UTC, drepram commented
After I committed my changes, 3 snapshots of 1 test suite (`libraries/WebRTC/encoders.test.ts`) failed. If this error is reproducible in other people's machine I see that we must open a ticket to resolve the error.

I do not see the relation between the file in this PR with that test that's returning an error, but I find the use in bringing it up so that we may resolve it quickly.

2022-08-18 11:06 UTC, stavares843 commented
<img width="978" alt="Captura de ecrã 2022-08-18, às 12 06 07" src="https://user-images.githubusercontent.com/29093946/185380496-b4a34ed7-4dc4-49c0-8992-0682ceea1aca.png">

is all green on CI and locally not sure how you got that error

2022-08-18 11:06 UTC, stavares843 approved these changes

2022-08-18 21:05 UTC, merged