fix(register): adjust and improve broken styling for all pages
Satellite-im/Core-PWA pull request #4370
Opened 2022-08-19 05:02 UTC by nathan-power

**What this PR does** 📖
- Fixes styling for register related pages.
- Creates InfoModal.
- Moves the pin-info section in the signup unlock page into the InfoModal. 

**Which issue(s) this PR fixes** 🔨
AP-2022

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-19 09:12 UTC, WanderingHogan commented
Lets try to get Nicholas' wallet PR in first if it's ready to go before merging this

2022-08-19 10:08 UTC, WanderingHogan commented
actually, there are no conflicting files with his PR, sorry, removing merge blocked tag

2022-08-19 15:23 UTC, aewing commented on components/ui/InfoButton/InfoButton.vue
> +<template>
Nice. Very clean.

2022-08-19 15:26 UTC, molimauro requested changes
Look good i just have a minor question :) Why have we added a bounce effect on the info modal?

2022-08-22 01:20 UTC, nathan-power commented
> Looks good i just have a minor question :) Why have we added a bounce effect on the info modal?

@molimauro 
Good call. I've replaced the internal animation styling of InfoModal by wrapping the UiModal component inside of it. We can keep the animation styling centralized this way as well.

2022-08-22 01:22 UTC, nathan-power commented
> Looks good i just have a minor question :) Why have we added a bounce effect on the info modal?

@molimauro
Good call. I've replaced the internal animation styling of InfoModal by wrapping the UiModal component inside of it. We can keep the animation styling centralized this way as well.

2022-08-22 07:16 UTC, molimauro approved these changes
Dope, thanks!

2022-08-22 20:33 UTC, merged