feat(jest): 79% coverage for IdentityManager
Satellite-im/Core-PWA pull request #4391
Opened 2022-08-22 11:19 UTC by drepram

**What this PR does** 📖

Reopening #4291 in the hopes of not having identical GitHub Actions error!

**Which issue(s) this PR fixes** 🔨

AP-2128

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-22 12:17 UTC, stavares843 requested changes
<img width="1073" alt="Captura de ecrã 2022-08-22, às 13 17 10" src="https://user-images.githubusercontent.com/29093946/185919177-01ab3831-34a4-4857-b9ed-f343417e28da.png">

when running locally this is generating the snapshot, can you commit the snapshot as well?

2022-08-23 20:36 UTC, stavares843 commented
added the snapshot

2022-08-23 20:49 UTC, stavares843 approved these changes

2022-08-23 20:49 UTC, stavares843 commented on libraries/Iridium/IdentityManager.test.ts
> +  // For some reason, this does not update coverage
if it doesn't update the coverage maybe we can ditch the test

2022-08-23 23:54 UTC, aewing commented on libraries/Iridium/IdentityManager.test.ts
> +  it('should return an error: Incorrect signature hash size', async () => {
maybe this could be `it('throws on invalid private key length')`

2022-08-23 23:55 UTC, aewing approved these changes

2022-08-24 03:12 UTC, merged

2022-08-24 15:54 UTC, drepram commented on libraries/Iridium/IdentityManager.test.ts
> +  it('should return an error: Incorrect signature hash size', async () => {
Hi! Please check #4435