chore(jest): add jest tests
Satellite-im/Core-PWA pull request #4393
Opened 2022-08-22 12:08 UTC by stavares843

**What this PR does** 📖

- Adds `iridium` and `dist` folder on `.eslintrc.js` to be ignored on eslint
- Adds `iridium` on `.prettierignore` to be ignored on prettier
- Adds empty lines on `components/mixins/UserPermissions/index.test.ts` and `libraries/Security/Security.test.ts` for better readability
- Minor linting on `components/views/navigation/toolbar/alerts/Alert.html` and components/views/navigation/toolbar/alerts/Alerts.html
- Renames deactivated tests to `.test.deactivated.ts` and adds that extension to be ignored on the coverage on Jest on `jest.config.js`
- Adds `iridium` to be ignored on `jest.config.js` to avoid running tests from iridium repo
- Fix warning on `libraries/Crypto/Crypto.test.ts`
- Adds test on `libraries/Crypto/Crypto.test.ts`
- Adds test on `libraries/Iridium/IdentityManager.test.ts`
- Fix warning on `libraries/BlockchainClient/adapters/Phantom/PhantomAdapter.test.ts`
- Adds `libraries/Iridium/friends/types.test.ts`
- Adds `libraries/Iridium/notifications/types.test.ts`
- Adds `libraries/Iridium/settings/types.test.ts`
- Adds `libraries/Iridium/users/types.test.ts`
- Adds `libraries/Iridium/webrtc/hooks.test.disabled.ts` deactivated atm until we upgrade libp2p to 3.0
- Adds `libraries/Solana/GroupChatsProgram/GroupCrypto.test.ts`
- Removes not used vars on `libraries/Solana/ServerProgram/ServerProgram.test.ts`
- Removes not used vars on `libraries/Solana/SolanaManager/SolanaManager.test.ts`
- Updates commands related to Jest on `package.json`
- Updates `store/friends/actions.test.ts` 
- Adds tests on `utilities/BlobManip.test.ts`
- Fix eslint warning on `utilities/Keybinds.test.ts`
- Fix warning on `utilities/Logger.test.ts`
- Removes not needed empty lines on `utilities/Timezone.test.ts`

2022-08-22 14:29 UTC, WanderingHogan commented on components/mixins/UserPermissions/index.test.ts
> +
these kind of linting commits drive me crazy

2022-08-22 14:35 UTC, stavares843 commented on components/mixins/UserPermissions/index.test.ts
> +
💣

2022-08-22 14:40 UTC, WanderingHogan commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +    expect(instance instanceof SolanaAdapter).toBeTruthy()
We don't need to check to see if something exists if we can do more thorough tests on them. We should focus on quality of tests not quantity.

2022-08-22 14:53 UTC, WanderingHogan requested changes
Comments sent in a DM

2022-08-22 15:02 UTC, stavares843 commented
thanks, will update 🔨

2022-08-22 21:43 UTC, stavares843 commented on components/mixins/UserPermissions/index.test.ts
> +
reverted 🔨

2022-08-22 21:44 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +    expect(instance instanceof SolanaAdapter).toBeTruthy()
removed 🔨

2022-08-23 17:38 UTC, WanderingHogan commented on libraries/Iridium/webrtc/hooks.test.disabled.ts
> +    expect(useCallElapsedTime).toBeDefined()
not really useful

2022-08-23 17:39 UTC, WanderingHogan commented on libraries/Iridium/webrtc/hooks.test.disabled.ts
> +    expect(useCallElapsedTime).toBeDefined()
all of these 'do these functions exist' tests

2022-08-23 17:39 UTC, WanderingHogan commented on libraries/Solana/ServerProgram/ServerProgram.test.ts
>    let inst9: any
why remove these? These tests are ripe for re-writing and made a higher quality

2022-08-23 17:40 UTC, WanderingHogan commented on libraries/Solana/ServerProgram/ServerProgram.test.ts
>    let inst9: any
these being the ServerProgram and SolanaManager

2022-08-23 17:40 UTC, WanderingHogan commented on utilities/Timezone.test.ts
> -
don't touch files just to link them in the future

2022-08-23 17:43 UTC, stavares843 commented on libraries/Solana/ServerProgram/ServerProgram.test.ts
>    let inst9: any
<img width="535" alt="Captura de ecrã 2022-08-23, às 18 43 24" src="https://user-images.githubusercontent.com/29093946/186228068-4b6b556f-35b6-4701-b1f8-a55261d4eedd.png">

<img width="596" alt="Captura de ecrã 2022-08-23, às 18 43 34" src="https://user-images.githubusercontent.com/29093946/186228112-caba9ce0-214f-4eee-9cbb-7204c78cf5ea.png">

i removed because wasn't being used lol

2022-08-23 17:44 UTC, stavares843 commented on utilities/Timezone.test.ts
> -
reverted 🔨

2022-08-23 17:45 UTC, stavares843 commented on libraries/Iridium/webrtc/hooks.test.disabled.ts
> +    expect(useCallElapsedTime).toBeDefined()
removed 🔨

2022-08-24 00:00 UTC, aewing reviewed
@WanderingHogan this seems like it could cause merge drift, should we get this in before it gets complicated?

2022-09-02 02:42 UTC, WanderingHogan approved these changes

2022-09-02 02:44 UTC, merged

2022-09-02 02:44 UTC, aewing approved these changes