fix(call-ui): fixed loader ui
Satellite-im/Core-PWA pull request #4397
Opened 2022-08-22 14:53 UTC by ThomBos

**What this PR does** 📖
fixes loader's ui 
**Which issue(s) this PR fixes** 🔨
AP-2173

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-22 21:15 UTC, josephmcg requested changes

2022-08-22 21:15 UTC, josephmcg commented on package.json
> -    "@satellite-im/iridium": "git+https://git@github.com/Satellite-im/iridium.git#main",
Probably an accident :)

2022-08-22 21:30 UTC, WanderingHogan commented on package.json
> -    "@satellite-im/iridium": "git+https://git@github.com/Satellite-im/iridium.git#main",
it doesn't really matter if it's in there or not if people are using the linkscript, @aewing mentioned making it an npm module that can be installed now that iridium is mostly stabilized soon, so it will matter then

2022-08-23 00:19 UTC, josephmcg commented on package.json
> -    "@satellite-im/iridium": "git+https://git@github.com/Satellite-im/iridium.git#main",
oh cool, makes commits a lot easier

2022-08-23 00:26 UTC, josephmcg approved these changes

2022-08-23 00:26 UTC, merged