fix(reply): correct name of reply recipient
Satellite-im/Core-PWA pull request #4410
Opened 2022-08-23 15:31 UTC by Jekrimo

**What this PR does** 📖
Fix name display in reply bar

**Which issue(s) this PR fixes** 🔨

ASP-2154

2022-08-23 16:57 UTC, stavares843 commented
> I have no idea why a snapshots/getters.test.ts.snap was included. Never touched it, let me know if we need to delete it or anything.


no worries i deleted it 🔨 i also updated the test in order to avoid adding any more snapshots

2022-08-24 00:32 UTC, josephmcg requested changes

2022-08-24 00:32 UTC, josephmcg commented on components/views/chat/message/Message.vue
> +      // iridium.users.getUser can not return self, check if it's you first. On reload this would be missing,
the iridium users manager was recently updated to include your own user's details, so this workaround isn't necessary anymore. check `components/views/chat/message/Message.vue` for an example

2022-08-24 00:32 UTC, josephmcg commented on components/views/chat/chatbar/reply/Reply.vue
> +    },
we don't necessary want the conversation name there. We want the name of the message author. you should be able to pass message sender did into user manager.

2022-08-25 00:35 UTC, josephmcg commented
fixed here
https://github.com/Satellite-im/Core-PWA/pull/4452

2022-08-25 00:35 UTC, closed without merging