fix(call-ui): fixed call display on mobile devices
Satellite-im/Core-PWA pull request #4448
Opened 2022-08-24 16:42 UTC by ThomBos

**What this PR does** 📖
Fixes call ui for mobile devices
**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-24 23:59 UTC, josephmcg requested changes

2022-08-24 23:59 UTC, josephmcg commented on components/ui/Global/Global.vue
> +      }${callId}`
there is no sidebar in mobile, no commit needed. You'd want to append call id to both mobile and desktop paths

2022-08-24 23:59 UTC, josephmcg commented on pages/mobile/chat/_id.vue
> +              this.$store.commit('ui/showSidebar', true)
dont need this

2022-08-24 23:59 UTC, josephmcg commented on pages/mobile/chat/_id.vue
> +              this.$store.commit('ui/showSidebar', false)
dont need this

2022-08-24 23:59 UTC, josephmcg commented on components/views/media/incomingCall/IncomingCall.less
> +      width: 3rem;
I prefer the old margin. button size will be increased soon.

Also avoid using these variables

2022-08-24 23:59 UTC, josephmcg commented on components/ui/Pip/Pip.vue
> +  &:extend(.first-layer);
is this necessary? There's a general overuse of z-index in this project that I've been trying to cut back.

2022-08-24 23:59 UTC, josephmcg commented on components/views/media/Media.less
> +  &:extend(.first-layer);
same z index comment

2022-08-25 07:33 UTC, ThomBos commented on components/ui/Global/Global.vue
> +      }${callId}`
how do we detect if the sidebar is open on mobile?

2022-08-25 07:36 UTC, ThomBos commented on components/views/media/incomingCall/IncomingCall.less
> +      width: 3rem;
with margin auto it breaks on mobile, do i have to set a fixed margin? (to avoid variables)

2022-08-25 08:03 UTC, josephmcg commented on components/ui/Global/Global.vue
> +      }${callId}`
its all in the swiper config here
[pages/mobile/chat/_id.vue](https://github.com/Satellite-im/Core-PWA/blob/4da3ac92fe085108de156a252e8ac1bf5567b83b/pages/mobile/chat/_id.vue#L61)

2022-08-25 08:07 UTC, josephmcg commented on components/views/media/incomingCall/IncomingCall.less
> +      width: 3rem;
I merged this change. rebase and let me know if there's still issues

2022-08-25 08:08 UTC, josephmcg commented on components/ui/Pip/Pip.vue
> +  &:extend(.first-layer);
could you explain why it is necessary? I hid this from mobile in my recently merged PR as well, takes up too much room to be viable

2022-08-25 08:30 UTC, ThomBos commented on components/views/media/incomingCall/IncomingCall.less
> +      width: 3rem;
no no, this was the only issue, it just looked so bad 😂

2022-08-25 08:32 UTC, josephmcg commented on components/views/media/incomingCall/IncomingCall.less
> +      width: 3rem;
thinking about it from the perspective of an actual mobile user, you want the buttons at the bottom.

actually increased button size here so I can stop parroting that line about 'it will look so much better when we...'
https://github.com/Satellite-im/Core-PWA/pull/4471

2022-08-25 14:04 UTC, ThomBos commented on components/ui/Global/Global.vue
> +      }${callId}`
> its all in the swiper config here [pages/mobile/chat/_id.vue](https://github.com/Satellite-im/Core-PWA/blob/4da3ac92fe085108de156a252e8ac1bf5567b83b/pages/mobile/chat/_id.vue#L61)

can't find a way to use swiper's functions on external components, is there any way to do that?

2022-08-25 22:44 UTC, josephmcg commented on components/ui/Global/Global.vue
> +      }${callId}`
You dont need to do anything. It will hide itself on slide 2 with this config. If you pass a route param, it will automatically go to slide 2

2022-08-26 01:47 UTC, josephmcg commented
dont resolve unless its actually fixed

2022-08-26 02:40 UTC, josephmcg commented
fixed here, closing
https://github.com/Satellite-im/Core-PWA/pull/4490

2022-08-26 02:40 UTC, closed without merging

2022-08-26 07:40 UTC, ThomBos commented on components/ui/Global/Global.vue
> +      }${callId}`
it doesn't if the route is the same and on mobile you don't change route while opening and closing the sidebar

2022-08-26 07:41 UTC, ThomBos commented on pages/mobile/chat/_id.vue
> +              this.$store.commit('ui/showSidebar', true)
need this as a workaround for the problem above

2022-08-26 07:46 UTC, ThomBos commented on components/ui/Pip/Pip.vue
> +  &:extend(.first-layer);
exactly, this is necessary on mobile since some ui goes upfront.
yeah it takes a quarter of a screen (don't think it might be helpful going with a smaller PiP), but it can be moved by touch (working on this rn)

2022-08-26 08:39 UTC, josephmcg commented on components/ui/Pip/Pip.vue
> +  &:extend(.first-layer);
@ThomBos 
You don't need z-index to make something appear on top of the other thing. HTML simply needs to be below to appear on top. Because the <global> component (therefore all the modals inside of it) are placed below the rest of the app content, they're automatically on top.

Read this article and let me know if you have any questions

https://www.codegram.com/blog/stop-ab-using-z-index/

2022-08-26 08:40 UTC, josephmcg commented on components/ui/Pip/Pip.vue
> +  &:extend(.first-layer);
regarding the mobile call indicator, I made a solution here that avoids a large draggable element https://github.com/Satellite-im/Core-PWA/pull/4492