feat(jest): 15% coverage for SolanaAdapter
Satellite-im/Core-PWA pull request #4515
Opened 2022-08-29 15:38 UTC by drepram

**What this PR does** 📖

Increase coverage

**Which issue(s) this PR fixes** 🔨

AP-2126

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-29 15:45 UTC, stavares843 requested changes

2022-08-29 15:45 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +  it('should get connection status before solanaManager is is initialized', () => {
before solanaManager is is initialized

instead of

before solanaManager is initialized

2022-08-29 15:45 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +  it('should get(ter) friendsProgram and return error', () => {
what does get(ter) mean? is that expected to say getter instead?

2022-08-29 15:46 UTC, drepram commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +  it('should get(ter) friendsProgram and return error', () => {
In a sense, because `getter` is not a verb. Do you want me to change it to getter?

2022-08-29 15:47 UTC, drepram commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +  it('should get(ter) friendsProgram and return error', () => {
`get` on the other hand, is a verb :D

2022-08-29 15:48 UTC, stavares843 commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +  it('should get(ter) friendsProgram and return error', () => {
thanks for updating 🔨

2022-08-29 17:06 UTC, stavares843 approved these changes

2022-08-30 00:52 UTC, josephmcg commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +    expect(() => konstruktor).not.toThrow(Error)
the constructor is what you're calling when you do new Class().
The returned value would be an instance of that class :)

2022-08-30 00:53 UTC, josephmcg commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +    expect(() => konstruktor).not.toThrow(Error)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor

2022-08-30 01:51 UTC, drepram commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +    expect(() => konstruktor).not.toThrow(Error)
Ah yes, my apologies. Please check again :D

2022-08-30 02:11 UTC, josephmcg commented on libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
> +    expect(() => konstruktor).not.toThrow(Error)
hm I still see a bunch of things named konstructor

2022-08-30 02:20 UTC, josephmcg approved these changes

2022-08-30 02:20 UTC, merged