feat(refactor): pre-launch cleanup (wip, will be broken up)
Satellite-im/Core-PWA pull request #4525
Opened 2022-08-29 22:10 UTC by aewing

**What this PR does** 📖
- Fixes multiple subscription handler issue (onSyncSubscribeResponse in ChatManager & WebRTCManager)
- Fixes multiple emitter handler bug (UserManager.peerSearch)
- Adds support for new subscribe changes in Iridium (sync & offline sync as options)
- Add friend by partial, name, name#did.substr(-6)
- Standardizes approach to reactivity
- Removes the WebRTC hooks & moves that logic to manager (so we have the option to reuse it elsewhere, to reduce duplication)
- Fixes timing issues on startup
- Fixes & restores `lastReadAt`
- Addresses some issues with peer announce
- Addresses some issues with WebRTC publishing events for every single peer, including all users in usermanager (search result matches)
- Misc. additional cleanup

2022-08-29 22:13 UTC, WanderingHogan approved these changes

2022-08-30 00:21 UTC, josephmcg requested changes

2022-08-30 00:21 UTC, josephmcg commented on components/ui/BackgroundCall/BackgroundCall.vue
> +      }
we can remove this

2022-08-30 00:21 UTC, josephmcg commented on components/ui/Global/Global.html
> +      <MediaIncomingCall :accept-call="acceptCall" :deny-call="denyCall" />
these props got moved down to the component level instead

2022-08-30 00:21 UTC, josephmcg commented on components/ui/Global/Global.vue
> +      return this.webrtc.incomingCall
console info, plus return type needed on computed

2022-08-30 00:21 UTC, josephmcg commented on components/ui/Global/Global.vue
> +      return this.isBackgroundCall || (this.isActiveCall && this.ui.showSidebar)
this was removed

2022-08-30 00:21 UTC, josephmcg commented on components/views/friends/search/Search.vue
> +      const query = this.query.trim()
you can do `v-model.trim` in the html template to automatically trim before processing

2022-08-30 00:21 UTC, josephmcg commented on components/views/navigation/mobile/toolbar/Toolbar.vue
> +    isActiveCall() {
add return type

2022-08-30 00:21 UTC, josephmcg commented on components/views/navigation/mobile/toolbar/Toolbar.vue
> +      console.info('enableRTC', this.details, this.isGroup)
console

2022-08-30 00:21 UTC, josephmcg commented on components/views/navigation/toolbar/alerts/Alerts.vue
> +      return iridium.notifications.deleteAll()
do we need to return?

2022-08-30 00:21 UTC, josephmcg commented on libraries/Iridium/NotificationManager.ts
>    }
this pattern used to break reactivity in friends manager and was subsequently removed

2022-08-30 00:21 UTC, josephmcg commented on libraries/Iridium/friends/FriendsManager.ts
> +    }
I think this was confirmed to have worse performance than set

2022-08-30 00:42 UTC, aewing commented on components/views/navigation/mobile/toolbar/Toolbar.vue
> +    isActiveCall() {
hover over the function name, it is inferred

2022-08-30 00:44 UTC, josephmcg commented on components/views/navigation/mobile/toolbar/Toolbar.vue
> +    isActiveCall() {
Vue flips shit if computed don't have return types. It breaks the context of `this` in the component intellisense

2022-08-30 00:47 UTC, aewing commented on components/views/navigation/mobile/toolbar/Toolbar.vue
> +    isActiveCall() {
so THAT's why it keeps doing that. good to know.

2022-08-30 00:49 UTC, aewing commented on components/views/navigation/toolbar/alerts/Alerts.vue
> +      return iridium.notifications.deleteAll()
It's a promise, best to not leave it floating around out of scope.

2022-08-30 00:51 UTC, aewing commented on libraries/Iridium/NotificationManager.ts
>    }
It only breaks reactivity if `this.state.notifications` isn't referenced in `data`, afaik.

2022-08-30 00:51 UTC, aewing commented on libraries/Iridium/friends/FriendsManager.ts
> +    }
It wasn't.

2022-08-30 04:44 UTC, merged