feat(media): call ui updates
Satellite-im/Core-PWA pull request #4553
Opened 2022-08-31 11:58 UTC by jasonwoodland

**What this PR does** 📖
- Improve volume slider
- Improve drag bar
- Calculate optimal MediaUser dimensions
- Refactor calling UI
- Update talking indicator

**Which issue(s) this PR fixes** 🔨
- #4526

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-31 17:13 UTC, stavares843 commented on components/views/media/user/User.less
> +    //   0px 1px 2px rgba(43, 43, 59, 0.65);
do we need this commented out?

2022-09-01 00:15 UTC, WanderingHogan commented on components/views/media/user/User.less
> +    //   0px 1px 2px rgba(43, 43, 59, 0.65);
commented out doesn't matter right now

2022-09-01 00:15 UTC, WanderingHogan commented
the only issue I saw was there was three video windows on a direct call

2022-09-01 01:39 UTC, jasonwoodland commented
> the only issue I saw was there was three video windows on a direct call

@WanderingHogan got a screenshot? probably the corrupt video state problem I mentioned before, the video/screen stream muted state is not being initialised correctly.

2022-09-02 00:37 UTC, stavares843 commented
> the only issue I saw was there was three video windows on a direct call

this is also on dev, phil noticed this as well yesterday


https://user-images.githubusercontent.com/29093946/188034891-b9eb2b0d-5b37-4b9e-8c45-1a95de16cbfc.mov

2022-09-02 05:30 UTC, WanderingHogan commented
the rebase on this one isn't so bad, conflicts are pretty minor, but it looks like a lot of other things changed a little bit so we will need to test it pretty well

2022-09-02 05:35 UTC, WanderingHogan commented on components/views/media/Media.vue
> +    call(): Call | undefined {
something in here

2022-09-05 23:46 UTC, jasonwoodland commented
> > the only issue I saw was there was three video windows on a direct call
> 
> this is also on dev, phil noticed this as well yesterday
> 
>  Screen_Recording_2022-08-31_at_11.16.09_AM.1.mov 
> the flow was when using screen share would do a extra window as phil mentioned on dev

This was due to invalid muted stream state. Will be fixed by another PR

2022-09-07 01:49 UTC, josephmcg requested changes
the volume sliders on the settings page use the same component as the call (for some reason lol). may need some refactoring
![image](https://user-images.githubusercontent.com/33670767/188770773-aae06fd9-725f-4aa1-9223-d06a5d8aab09.png)

also get this error on receiver side
![image](https://user-images.githubusercontent.com/33670767/188770796-4816343c-3ca0-47a5-9a67-8494d267db00.png)

2022-09-07 05:09 UTC, josephmcg commented
still getting the same error from before. Looks like the refs inside of the mounted logic are coming up undefined (for one side only)

2022-09-07 09:04 UTC, josephmcg approved these changes

2022-09-07 09:07 UTC, merged