feat(jest): 42% coverage for BlobManip
Satellite-im/Core-PWA pull request #4560
Opened 2022-08-31 14:57 UTC by drepram

**What this PR does** 📖

Self-explanatory. Commented out code at the last part of the code is due to possibly JSDOM being weird and not functioning well with FileStreams

**Which issue(s) this PR fixes** 🔨

AP-2257

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-08-31 17:00 UTC, WanderingHogan requested changes
If blob doesn't exist in jsdom, is there a polyfill we can use, or can we mock it? As it stands this will always just fail out and never run this test

2022-08-31 17:11 UTC, stavares843 commented
in case if we can't do what hogan mentioned above, please just ditch the commented out code

2022-09-01 02:05 UTC, josephmcg commented on utilities/BlobManip.test.ts
> +      const jpegBlob = await new Blob(['testing'], { type: 'image/jpeg' })
this would be a text file right? not really a jpeg

2022-09-01 06:16 UTC, drepram commented on utilities/BlobManip.test.ts
> +      const jpegBlob = await new Blob(['testing'], { type: 'image/jpeg' })
ah yes, correct. please check again

2022-09-01 16:04 UTC, stavares843 commented
@drepram 


in case if we can't do what hogan mentioned above, please just ditch the commented-out code

2022-09-01 18:39 UTC, WanderingHogan commented
There are a couple things here - 

We shouldn't worry about commented out code when it's stuff that's in flight and might help figure things out later. We should remove dead code, but I don't think this is the case here.

As-is, i don't think we should check this in, because it will never actually get to the test unless we can mock it (which i couldn't figure out how to do in the time I had to look at this)

![Screen Shot 2022-09-01 at 12 14 31 PM](https://user-images.githubusercontent.com/2993032/187988180-ba7dddde-a933-4d41-b7c6-a7e404f8c181.png)
![Screen Shot 2022-09-01 at 12 14 35 PM](https://user-images.githubusercontent.com/2993032/187988190-d899f4ed-783f-4cf2-b4ce-35843fd2a8a6.png)

2022-09-01 18:40 UTC, stavares843 commented
will close this then, if you figure out a solution we can reopen @drepram

2022-09-01 18:40 UTC, closed without merging