feat(jest): 14% coverage for store/files
Satellite-im/Core-PWA pull request #4610
Opened 2022-09-02 14:40 UTC by drepram

**What this PR does** 📖

- 43% coverage for store/files/mutations
- 100% coverage for store/files/state
- Progress on coverage for store/files/getters

**Which issue(s) this PR fixes** 🔨

No ticket

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-09-02 15:16 UTC, stavares843 approved these changes

2022-09-07 04:42 UTC, WanderingHogan approved these changes

2022-09-07 04:57 UTC, WanderingHogan requested changes

2022-09-07 04:57 UTC, WanderingHogan commented on store/files/state.test.ts
> +    expect(InitialFilesState).toMatchSnapshot()
this is kind of weird - just checking that it's a function when the next text accomplishes this, can you remove this one

2022-09-07 12:30 UTC, drepram commented on store/files/state.test.ts
> +    expect(InitialFilesState).toMatchSnapshot()
Removed for duplicate!

2022-09-07 12:36 UTC, stavares843 commented
<img width="848" alt="Screenshot 2022-09-07 at 13 36 36" src="https://user-images.githubusercontent.com/29093946/188879759-0b4215f3-f6d8-4434-9e17-6166e706aba1.png">

remove the snapshot pls  🔨

2022-09-07 12:46 UTC, drepram commented
> <img alt="Screenshot 2022-09-07 at 13 36 36" width="848" src="https://user-images.githubusercontent.com/29093946/188879759-0b4215f3-f6d8-4434-9e17-6166e706aba1.png">
> 
> remove the snapshot pls 🔨

Please check again 😄

2022-09-07 18:59 UTC, WanderingHogan approved these changes

2022-09-07 19:35 UTC, merged