feat(welcome): welcome popup functioning and prelim copy
Satellite-im/Core-PWA pull request #4622
Opened 2022-09-06 21:00 UTC by Jekrimo

**What this PR does** 📖
Create new Welcome Popup that explains notable things about the app like where to find permissions and a warning that we are in EA
**Which issue(s) this PR fixes** 🔨

Resolve #
4559

**Special notes for reviewers** 🗒️
I just put in first thoughts for what to have for the copy. Let me know anything we would like added or anything like that.

2022-09-07 03:05 UTC, josephmcg requested changes

2022-09-07 03:05 UTC, josephmcg commented on components/ui/WelcomeModal/WelcomeModal.html
> +          type="primary"
I think type prop is the native type attribute. If it's just a regular button, this can be removed.

2022-09-07 03:05 UTC, josephmcg commented on store/accounts/actions.ts
> +  },
I feel like attaching a boolean to the account is kind of heavy. I'd prefer some different approach, like adding a vuex mutation to some kind of accountCreate method/action

2022-09-07 03:05 UTC, josephmcg commented on store/ui/types.ts
> +  welcomeMessage: boolean
using the variable name welcomeMessage makes me think of a string, not boolean. Maybe something like `isFirstVisit` or `isNewAccount`. Starting with `is` is often a good practice for booleans

2022-09-07 13:21 UTC, Jekrimo commented on store/accounts/actions.ts
> +  },
I thought that as well. Do you know a way of ensuring that the welcome would not show up across different instances, like opening a mobile app, different pc, or even just clearing your cache, etc?

2022-09-07 13:29 UTC, Jekrimo commented on components/ui/WelcomeModal/WelcomeModal.html
> +          type="primary"
Good call. There was a prop type that I was trying to get to work within the button earlier that wasn't working for adding the danger and that was left over. Thanks!

2022-09-07 15:26 UTC, Jekrimo commented on components/ui/WelcomeModal/WelcomeModal.html
> +      <UiSpacer :height="30" />
I switched over to the rem, I tried everything I could think of to get  gap to work and for some reason it just won't register so I went with the margin-top, hopefully that's cool?

2022-09-07 15:54 UTC, Jekrimo commented on components/ui/WelcomeModal/WelcomeModal.html
> +      />
No problemo! Got it switched over.

2022-09-07 16:28 UTC, Jekrimo commented on store/ui/types.ts
> +  welcomeMessage: boolean
Totes makes sense, and def can see that now. Gratci.

2022-09-08 01:55 UTC, josephmcg commented on components/ui/WelcomeModal/WelcomeModal.html
> +      <UiSpacer :height="30" />
you set gap on the container, and it spaces out child elements

2022-09-08 02:51 UTC, josephmcg commented
another note, I don't think this is getting hooked up to the github issue. I believe you need to put a pound directly before the number

2022-09-08 21:30 UTC, WanderingHogan commented on store/accounts/actions.ts
> +  },
this is good for now, @josephmcg can you add a description of what you want to do here tot he backlog project in github? 

@stavares843 can you review this, and advise copy changes in a DM so we can make a ticket.

@Jekrimo great first pass and getting this component in!

2022-09-08 21:34 UTC, stavares843 commented on store/accounts/actions.ts
> +  },
sounds good 🔨

2022-09-09 00:17 UTC, phillsatellite approved these changes

2022-09-09 00:17 UTC, merged