feat(jest): 100% coverages
Satellite-im/Core-PWA pull request #4667
Opened 2022-09-08 04:09 UTC by drepram

**What this PR does** 📖

100% coverage for store/accounts/mutations.test.ts
100% coverage for store/sounds/actions.test.ts

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-09-08 21:44 UTC, WanderingHogan requested changes

2022-09-08 21:44 UTC, WanderingHogan commented on store/accounts/mutations.test.ts
> +    const localStateForUnitTest = InitialAccountsState()
would this be a good change to use beforeEach?

```
  let localStateForUnitTest

  beforeEach(() => {
    localStateForUnitTest = InitialAccountsState()
  })
```

2022-09-08 21:44 UTC, WanderingHogan commented on store/sounds/actions.test.ts
> +          newMessage: true,
you could clean this up a lot if you made an object at the top somewhere like this:

```
       const state = {
          newMessage: true,
          hangup: true,
          call: true,
          mute: true,
          unmute: true,
          deafen: true,
          undeafen: true,
          upload: true,
          connected: true,
        },
```

and then in the object you pass in, if you want undeafen to be false, for example

```
{
  state: {...state, undeafen: false}
}
        ```

2022-09-09 10:15 UTC, drepram commented on store/sounds/actions.test.ts
> +          newMessage: true,
resolved!

2022-09-09 10:15 UTC, drepram commented on store/accounts/mutations.test.ts
> +    const localStateForUnitTest = InitialAccountsState()
resolved!

2022-09-09 12:27 UTC, stavares843 commented
🎉 

feel free to update the label for missing review for hogan to re check 🔨 and thanks for updating 🎉

2022-09-10 05:34 UTC, WanderingHogan approved these changes

2022-09-10 05:34 UTC, merged