fix(chatbar): replies style and focus on reply
Satellite-im/Core-PWA pull request #468
Opened 2021-12-06 09:01 UTC by molimauro

**What this PR does** 📖
* Fix a style bug on the chatbar when a reply is in place;
* Remove a reply when switching conversations;
* Does not persist the reply in the store;
* Focus the chatbar when hitting reply.

**Which issue(s) this PR fixes** 🔨
JIRA: AP-155

**Special notes for reviewers** 🗒️

**Additional comments** 🎤
We should persist the replies when switching conversations but this needs a refactor in the way we store replies. Please open a ticket to keep track of this, thanks!

2021-12-06 13:23 UTC, RetroPronghorn approved these changes

2021-12-06 14:22 UTC, Jekrimo approved these changes

2021-12-06 17:20 UTC, stavares843 reviewed
Remove a reply when switching conversations - this one still happens

https://user-images.githubusercontent.com/29093946/144891941-670eea84-f4ba-4a79-ab2e-da80a31b11fd.mp4

rest seems good 🎨

2021-12-06 23:15 UTC, WanderingHogan requested changes
Sara's change, then good

2021-12-07 14:15 UTC, molimauro commented
Updated! Thanks for noticing

2021-12-07 18:40 UTC, WanderingHogan commented on components/tailored/core/chatbar/Chatbar.vue
> +      else wrap.style.borderRadius = '41px'
In the future we want to avoid else clauses everywhere we can, but this is ok for right now/can be cleaned up later

2021-12-07 18:41 UTC, molimauro commented on components/tailored/core/chatbar/Chatbar.vue
> +      else wrap.style.borderRadius = '41px'
You're right, I had in mind the change but forgot. I'll update no problem

2021-12-07 20:06 UTC, WanderingHogan approved these changes

2021-12-07 21:12 UTC, stavares843 approved these changes

2021-12-07 21:12 UTC, merged

2021-12-08 00:12 UTC, stavares843 commented
phil added a ticket for what you mentioned regarding

> We should persist the replies when switching conversations but this needs a refactor in the way we store replies. Please open a ticket to keep track of this, thanks!



[AP-235](https://satellite-im.atlassian.net/browse/AP-235)