feat(typehead): Create Reusable Typeahead Component to be used in the Import Account Component
Satellite-im/Core-PWA pull request #470
Opened 2021-12-06 14:56 UTC by genie-magic

**What this PR does** 📖
Create Reusable Typeahead Component to be used in the Import Account Component
**Which issue(s) this PR fixes** 🔨

Fixes # AP-154

2021-12-06 17:05 UTC, WanderingHogan approved these changes

2021-12-06 17:22 UTC, Jekrimo approved these changes

2021-12-06 17:31 UTC, WanderingHogan requested changes
Make it so when a word is selected, it is taken out of what the typeahead can show, and puts it back if it's removed from the selected words

2021-12-07 09:54 UTC, genie-magic commented
> Make it so when a word is selected, it is taken out of what the typeahead can show, and puts it back if it's removed from the selected words

@WanderingHogan  I updated the code about that. Please let me know when you have done the review.

2021-12-07 20:30 UTC, WanderingHogan approved these changes

2021-12-07 21:34 UTC, stavares843 approved these changes

2021-12-07 21:34 UTC, merged