fix(typing-indicator): restored indicator
Satellite-im/Core-PWA pull request #4734
Opened 2022-09-12 15:15 UTC by ThomBos

### What this PR does 📖
- Restores typing indicator on the sidebar

### Which issue(s) this PR fixes 🔨
- Resolve #4734 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-09-12 19:43 UTC, phillsatellite commented
Only 2 small things I found that I will create tickets for in the QA Jira board just wanted to share findings here as well, iOS typing indicator was appearing wrong and I noticed it didnt appear for Groupchats either but other than those 2 small things it worked extremely well! 🔥 
![IMG_6572](https://user-images.githubusercontent.com/93608357/189741503-7280e340-993e-4ec7-8b45-796a843ce850.jpeg)
https://user-images.githubusercontent.com/93608357/189741484-fbb447cc-c4d7-48b0-b965-0b5b3e3b1596.mov

2022-09-12 19:44 UTC, phillsatellite approved these changes

2022-09-12 20:48 UTC, molimauro commented
Thanks @phillsatellite! The group thing is not a bug, it’s intended :) we lo look into the ios bug though!! Thanks ;) all good on android?

2022-09-12 20:54 UTC, molimauro commented on components/ui/User/State/State.vue
> +      if (this.isTyping) {
This should be redundant

2022-09-12 20:55 UTC, stavares843 commented
thanks for testing @phillsatellite 💥 thanks for clarifying @molimauro 🔨

2022-09-13 00:38 UTC, nathan-power commented on components/views/navigation/sidebar/list/item/Item.vue
> +        false
Hey Thomas!
Tried adding a new friend but was met with this error. It might be good to include a guard clause here for if the conversation doesn't exist yet for the user.
![image](https://user-images.githubusercontent.com/40599535/189782498-29d1ea75-92f3-4e4f-8285-af1731029b59.png)
![image](https://user-images.githubusercontent.com/40599535/189782507-008ebfe5-4eb6-4fee-904e-21670b7ac9e9.png)

2022-09-13 00:40 UTC, nathan-power requested changes
Hey Thomas 👋
It's looking good, just one change I noticed that might be important

2022-09-13 00:40 UTC, stavares843 commented on components/views/navigation/sidebar/list/item/Item.vue
> +        false
i saw this error before on dev as well

2022-09-13 05:51 UTC, josephmcg commented
https://github.com/Satellite-im/Core-PWA/pull/4745
Thanks for your work on this Thomas. I took some inspiration from your approach and resolved it here.

I opted for a conversationId prop to determine typing status render because the sidebarListItem component doesn't need to be aware of typing status. It was only calculating it to pass as a prop.

In that case, I think it's better to handle everything in the child component. This will also work well with a new group member sidebar I have in progress here
https://github.com/Satellite-im/Core-PWA/pull/4747

2022-09-13 05:51 UTC, closed without merging