fix(homeIconOnFiles): adjust home icon down to avoid icon clash
Satellite-im/Core-PWA pull request #474
Opened 2021-12-06 18:46 UTC by KemoPaw

**What this PR does** 📖

https://satellite-im.atlassian.net/browse/AP-121

**Which issue(s) this PR fixes** 🔨

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-06 20:42 UTC, Jekrimo approved these changes

2021-12-06 22:28 UTC, stavares843 approved these changes
<img width="467" alt="Captura de ecrã 2021-12-06, às 22 28 01" src="https://user-images.githubusercontent.com/29093946/144932930-d699ff22-cfef-401e-9745-3525885e63b0.png">

fixed ✅

2021-12-06 23:08 UTC, WanderingHogan requested changes
This looks alright when it is collapsed, but when it is not the padding pushes everything down too far
![Screen Shot 2021-12-06 at 4 05 19 PM](https://user-images.githubusercontent.com/2993032/144937152-4df26828-f34f-44a2-90db-5d33984006e8.png)
![Screen Shot 2021-12-06 at 4 05 16 PM](https://user-images.githubusercontent.com/2993032/144937155-26284e20-0a13-4101-83c8-dc09cb84186b.png)

Can you do something like watch for the left bar being collapsed, and only applying that padding if that is true?

2021-12-06 23:24 UTC, KemoPaw commented
@WanderingHogan That sounds like a good suggestion, will look into implementing it!

2021-12-07 01:31 UTC, josephmcg commented
It seems like this was formatted using eslint rather than prettier, is that because of husky? You can configure prettier to format files on save so you don't have to think about it.
![image](https://user-images.githubusercontent.com/33670767/144949121-10c9b31c-939b-4e37-a5c9-84cf948fc443.png)

I think template literals (`${}`) are redundant inside a v-bind.
https://vuejs.org/v2/api/#v-bind

Could be rewritten like this
![image](https://user-images.githubusercontent.com/33670767/144948874-a551a6f6-3f98-4e65-bb95-1a7e895416d1.png)

2021-12-07 01:38 UTC, stavares843 commented
yes husky is using `eslint` instead of prettier, but we look into setup that to use both

we added the `vue` plugin for `eslint` as well, do you feel those template literals (${}) that you mentioned are something that should have been captured by the linter? @josephmcg

2021-12-07 02:00 UTC, stavares843 commented
@josephmcg added that here
https://github.com/Satellite-im/Core-PWA/pull/479

2021-12-07 02:01 UTC, KemoPaw commented
@josephmcg Thank you so much for explaining how to clean up the classes in files.vue + have my code format to Prettier on save!

2021-12-07 02:01 UTC, josephmcg commented
@stavares843 
Not necessarily, there is definitely a use case for template literals inside a v-bind. I just felt it was redundant this time.

It could be used to dynamically set attributes
<h3 v-bind:data="`haha-${test}`">{{ test }}</h3>

Thanks for checking!

2021-12-07 02:02 UTC, stavares843 commented
thanks for clarifying! 🎉

2021-12-07 02:03 UTC, josephmcg commented
oh github messed with my code example.. one sec

2021-12-07 02:54 UTC, WanderingHogan approved these changes
Good job Kat

2021-12-07 04:19 UTC, merged