Ap 151
Satellite-im/Core-PWA pull request #475
Opened 2021-12-06 18:52 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-06 20:45 UTC, Jekrimo approved these changes

2021-12-06 22:24 UTC, stavares843 requested changes
<img width="1444" alt="Captura de ecrã 2021-12-06, às 22 23 08" src="https://user-images.githubusercontent.com/29093946/144932397-6f661470-8be6-402e-81c7-9c35ad989541.png">

screen has the chat bar, can we add the proper string instead of showing `global.talk` there?

2021-12-07 03:40 UTC, WanderingHogan commented on components/tailored/core/chatbar/Chatbar.vue
> -    debounceTypingStop: Function
Can you add these back in - they allow for the typescript code hints/without them we get the typescript is angry red squiggles

2021-12-07 03:50 UTC, WanderingHogan commented on components/tailored/core/chatbar/Chatbar.vue
> -      recipientTyping: false,
we need this back in

2021-12-07 03:53 UTC, WanderingHogan commented on components/tailored/core/chatbar/controls/Controls.html
> +    :data-tooltip="$t('global.glyphs')"
Where is global coming from? When I look at `https://github.com/Satellite-im/locales/blob/main/en-US.js` - I think these should be set back to ui

2021-12-07 03:53 UTC, davidchan1219 commented on components/tailored/core/chatbar/Chatbar.vue
> -      recipientTyping: false,
I added it

2021-12-07 03:58 UTC, davidchan1219 commented on components/tailored/core/chatbar/controls/Controls.html
> +    :data-tooltip="$t('global.glyphs')"
I updated it

2021-12-07 04:09 UTC, WanderingHogan commented on components/tailored/core/chatbar/controls/Controls.html
> +      ${editable ? 'active' : 'inactive'}`
Can you make this
class="control-tooltip-wrap  has-tooltip has-tooltip-top has-tooltip-primary"
:class="editable ? 'active' : 'inactive'", and make the the other v-bind classes in this file  also split like this

2021-12-07 04:10 UTC, WanderingHogan commented on components/tailored/core/fileupload/FileUpload.html
> +    :class="`has-tooltip has-tooltip-top has-tooltip-primary upload-label ${editable ? 'active' : 'inactive'}`"
same as in controls.html

2021-12-07 04:12 UTC, WanderingHogan commented on components/tailored/core/fileupload/FileUpload.vue
> -        if (file.file.size > Config.uploadByteLimit) {
Were these couple lines removed on purpose?

2021-12-07 04:13 UTC, WanderingHogan requested changes
Good start, please check comments when you get a chance

2021-12-07 04:18 UTC, davidchan1219 commented on components/tailored/core/fileupload/FileUpload.html
> +    :class="`has-tooltip has-tooltip-top has-tooltip-primary upload-label ${editable ? 'active' : 'inactive'}`"
I updated it

2021-12-07 04:19 UTC, davidchan1219 commented on components/tailored/core/chatbar/controls/Controls.html
> +      ${editable ? 'active' : 'inactive'}`
I made classes

2021-12-07 04:25 UTC, davidchan1219 commented on components/tailored/core/fileupload/FileUpload.vue
> -        if (file.file.size > Config.uploadByteLimit) {
I reverted it on AP-151 branch

2021-12-08 15:46 UTC, WanderingHogan commented
Per the DM - please put the changes for this ticket in a new pull request

2021-12-08 15:46 UTC, closed without merging