fix(typing-indicator): fixed on safari
Satellite-im/Core-PWA pull request #4760
Opened 2022-09-13 15:55 UTC by ThomBos

### What this PR does 📖
- Fixes typing indicator on safari

### Which issue(s) this PR fixes 🔨
- Resolve #

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-09-13 15:57 UTC, ThomBos commented on assets/styles/base.less
> +    /* this breaks icons
left this because i don't know if there's any part of the app is still using this media query

2022-09-13 17:05 UTC, molimauro requested changes
Minor comments, also seems that on safari the Satellite logo is overlapping:

<img width="63" alt="image" src="https://user-images.githubusercontent.com/50131258/189963393-0c406067-aba7-405e-86be-5e4224153106.png">

2022-09-13 17:05 UTC, molimauro commented on components/ui/User/State/State.less
> -  position: relative;
restore this

2022-09-13 17:05 UTC, molimauro commented on components/ui/User/State/State.vue
> +        :mask="`url(#${isTyping ? 'typing' : 'circle'}-mask)`"
better restore the computed here

2022-09-13 17:05 UTC, molimauro commented on components/ui/User/State/State.vue
> +        :mask="`url(#mask-state-${status})`"
put this back to the rect, should make no difference

2022-09-14 15:01 UTC, molimauro approved these changes

2022-09-14 15:24 UTC, phillsatellite commented
Noticed the blue doesn't fill the entire typing indicator. Otherwise functionality worked great! 🔥  
https://user-images.githubusercontent.com/93608357/190196583-e7f9a9f0-2073-49f0-b0de-a24f2cddb993.mov

2022-09-14 15:26 UTC, molimauro commented
> Noticed the blue doesn't fill the entire typing indicator. Otherwise functionality worked great! 🔥 [user-images.githubusercontent.com/93608357/190196583-e7f9a9f0-2073-49f0-b0de-a24f2cddb993.mov](https://user-images.githubusercontent.com/93608357/190196583-e7f9a9f0-2073-49f0-b0de-a24f2cddb993.mov)

Are you on Chrome or where? Desktop? :)

2022-09-14 15:26 UTC, phillsatellite commented
> > Noticed the blue doesn't fill the entire typing indicator. Otherwise functionality worked great! 🔥 [user-images.githubusercontent.com/93608357/190196583-e7f9a9f0-2073-49f0-b0de-a24f2cddb993.mov](https://user-images.githubusercontent.com/93608357/190196583-e7f9a9f0-2073-49f0-b0de-a24f2cddb993.mov)
> 
> Are you on Chrome or where? Desktop? :)

Desktop and Safari

2022-09-14 15:45 UTC, molimauro approved these changes

2022-09-14 15:45 UTC, molimauro commented
ok thanks!! Can you try again please? :)

2022-09-14 16:02 UTC, phillsatellite commented
> ok thanks!! Can you try again please? :)

Re tested and worked and looked great on Safari and iOS!

2022-09-14 16:02 UTC, phillsatellite approved these changes

2022-09-14 17:07 UTC, merged