feat(chat): unblock sending while file upload in progress
Satellite-im/Core-PWA pull request #4824
Opened 2022-09-15 08:26 UTC by josephmcg

### What this PR does 📖
- move Chatbar uploading local state variable to vuex store.
  - I did this to put the message loader in a different component
  - it also ensures the state is maintained even if chatbar is unmounted
- display loader if store array contains this conversationId
- still allow new messages to be sent even if a previous upload is still in progress

### Which issue(s) this PR fixes 🔨
- Resolve #4823 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-09-15 14:18 UTC, molimauro commented on components/views/chat/chatbar/Chatbar.vue
> +        !this.files.length &&
if i have a file all the next conditions are skipped (i can send a message with more that maxChars)

2022-09-15 14:19 UTC, molimauro requested changes
only one minor thing

2022-09-16 01:27 UTC, josephmcg commented on components/views/chat/chatbar/Chatbar.vue
> +        !this.files.length &&
very true, fixed

2022-09-16 01:36 UTC, aewing approved these changes

2022-09-16 01:39 UTC, merged