feat(jest): increase coverage for time utilities
Satellite-im/Core-PWA pull request #4903
Opened 2022-09-16 13:50 UTC by drepram

### What this PR does 📖

100% coverage for utilities/Timezone
88% coverage for utilities/duration

### Which issue(s) this PR fixes 🔨

Ticket: AP-2691

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-09-16 16:48 UTC, stavares843 requested changes
<img width="710" alt="Captura de ecrã 2022-09-16, às 17 48 36" src="https://user-images.githubusercontent.com/29093946/190689393-0ce65bfe-eb98-4610-85ab-fdf915f7bed0.png">

this fails locally 


works on CI but fails locally

2022-09-19 05:38 UTC, drepram commented
> <img alt="Captura de ecrã 2022-09-16, às 17 48 36" width="710" src="https://user-images.githubusercontent.com/29093946/190689393-0ce65bfe-eb98-4610-85ab-fdf915f7bed0.png">
> 
> this fails locally
> 
> works on CI but fails locally

Okay, I will try to change the city today

2022-09-19 13:21 UTC, stavares843 commented
<img width="734" alt="Captura de ecrã 2022-09-19, às 14 21 38" src="https://user-images.githubusercontent.com/29093946/191027101-11e7ec11-3a47-4f5b-8bb0-6501b703ccee.png">

still fails locally

2022-09-20 16:02 UTC, stavares843 approved these changes

2022-09-20 16:16 UTC, merged