fix(signin-loading): removed auth middleware
Satellite-im/Core-PWA pull request #4936
Opened 2022-09-19 20:57 UTC by ThomBos

### What this PR does 📖
- fixes "forever linking" issue

### Which issue(s) this PR fixes 🔨
- Resolve #4933 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-09-19 21:00 UTC, aewing approved these changes

2022-09-19 21:01 UTC, stavares843 commented
since the last deploy i haven't had that linking issue

2022-09-21 20:38 UTC, stavares843 requested changes
<img width="1315" alt="Captura de ecrã 2022-09-21, às 21 37 47" src="https://user-images.githubusercontent.com/29093946/191605615-b313d239-4dc4-4e48-8b50-3f86e0f5d913.png">



when using this PR, it goes right away to this page, instead of the create account view

2022-09-21 20:54 UTC, stavares843 commented
can we reuse the same logic we did [here](https://github.com/Satellite-im/Core-PWA/pull/3062) instead? when we were using solana, we added a modal that would appear after 30s, can we reuse that but for the nodes timeout?

2022-09-22 08:41 UTC, ThomBos commented
> when using this PR, it goes right away to this page, instead of the create account view
> 
> and then if you try to create an account, it returns an error because the user didn't have the previous view to setup a PIN
oh yeah, didn't noticed when refreshing, this happens the first time you open the app.
i'm working on it

2022-09-22 17:25 UTC, stavares843 commented
is this ready to review again? @ThomBos 🔨

2022-09-22 20:06 UTC, ThomBos commented
> is this ready to review again? @ThomBos 🔨

yes, check if you see any issue 👍

2022-09-23 07:08 UTC, molimauro requested changes

2022-09-23 07:08 UTC, molimauro commented on components/views/friends/friend/Friend.vue
> +      }
revert this, already fixed in dev

2022-09-23 07:08 UTC, molimauro commented on components/views/friends/search/Search.vue
> -      this.$toast.show(this.$t('friends.request_sent') as string)
revert this

2022-09-23 17:49 UTC, aewing approved these changes

2022-09-23 20:46 UTC, stavares843 requested changes
<img width="1390" alt="Captura de ecrã 2022-09-23, às 21 46 08" src="https://user-images.githubusercontent.com/29093946/192053875-daa035d0-c6fd-431e-bf1e-36ed2e8299ba.png">


using fleek on this PR, returns error when doing a new account

2022-09-23 22:00 UTC, aewing commented
> <img alt="Captura de ecrã 2022-09-23, às 21 46 08" width="1390" src="https://user-images.githubusercontent.com/29093946/192053875-daa035d0-c6fd-431e-bf1e-36ed2e8299ba.png">
> 
> using fleek on this PR, returns error when doing a new account

Looking at the logs it looks like the dev environment is misconfigured (probably CORS headers).
I don't think it's related to this PR. Can we test it locally while the dev & prod deployments are being worked on?

2022-09-23 22:02 UTC, stavares843 commented
> Looking at the logs it looks like the dev environment is misconfigured (probably CORS headers).

fleek URL's were fine yesterday so

2022-09-23 22:03 UTC, stavares843 commented
i can check locally though, but we shouldn't merge this before the deployment, also that this seems a overkill PR, we could have just reused the same logic we did [here](https://github.com/Satellite-im/Core-PWA/pull/3062) instead

2022-09-23 22:08 UTC, stavares843 commented
<img width="1333" alt="Captura de ecrã 2022-09-23, às 23 08 04" src="https://user-images.githubusercontent.com/29093946/192063112-7ff9525d-f198-46c7-b0b3-0babbd5b3d45.png">


locally is the same though

2022-09-24 00:36 UTC, aewing commented
> > Looking at the logs it looks like the dev environment is misconfigured (probably CORS headers).
> 
> fleek URL's were fine yesterday so

fleek and sync nodes weren't auto

2022-09-26 08:33 UTC, ThomBos commented
> using fleek on this PR, returns error when doing a new account

added catch for this, it should redirect to a network error modal now 👍

2022-09-26 08:40 UTC, ThomBos commented
> locally is the same though

It's not the same from the pictures you posted 😅 
Can't see any CORS errors in console in the last one... The only issue i see there, is the timeout error we throw.
It should be good with the catch just added

2022-09-27 07:56 UTC, josephmcg commented
Is there a way we could approach more simply that doesn't spread across so many different components?

Perhaps adding a check on the Global.vue component (which is rendered in desktop and mobile layouts. we can add it to default as well). It could determine if iridium is ready on mount, then kick the user back to the main login page if they aren't on another auth page

2022-09-27 08:10 UTC, ThomBos commented
> Is there a way we could approach more simply that doesn't spread copy pasted code across so many different components?
> 
> Perhaps adding a check on the Global.vue component (which is rendered in desktop and mobile layouts. we can add it to default as well). It could determine if iridium is ready on mount, then kick the user back to the main login page if they aren't on another auth page


Everytime we call "loadaccount" the catch is necessary, that's why that pasted code can't be removed. Maybe making changes on Global.vue can be removed stuff from layouts components 👍

2022-09-27 08:14 UTC, molimauro commented
Why do we want to ditch the middleware? Any particular reason?

2022-09-27 08:59 UTC, ThomBos commented
> Why do we want to ditch the middleware? Any particular reason?

@aewing was it to make it more simple, or you had something to integrate?

2022-09-27 09:51 UTC, ThomBos commented
> Is there a way we could approach more simply that doesn't spread copy pasted code across so many different components?
> 
> Perhaps adding a check on the Global.vue component (which is rendered in desktop and mobile layouts. we can add it to default as well). It could determine if iridium is ready on mount, then kick the user back to the main login page if they aren't on another auth page

Can tell you it didn't change when putting this code in Global.vue

2022-09-27 10:59 UTC, josephmcg commented
That's only half the process. Global isn't rendered on the default layout

2022-09-29 17:58 UTC, aewing commented
> Why do we want to ditch the middleware? Any particular reason?

We see some strange redirect loops and errors with the middleware approach. I think throwing a catch-all solution at this isn't necessarily the answer. We should be able to implement a view on the homepage (`/`) that checks for stored pin & attempts to restore, failing that it could redirect to the import/create account screen, which can redirect to profile entry if one isn't present. We shouldn't need to globally check state every time it changes if we think about when to redirect the user in the UI.

2022-10-05 12:36 UTC, molimauro commented
I think we should consider closing this one and:
- introducing a timeout for the signin starting from what we have in dev
- keep the middleware (its purpose is to run before every page so more reliable then a custom one) but refactor it since it is based on a old logic

Let me know your thoughts!

2022-10-06 00:01 UTC, josephmcg commented
yeah it seems like we could write some middleware that checks your current route + iridium status and knocks back appropriately. 

According to the doc it runs before render
https://nuxtjs.org/docs/directory-structure/middleware/

2022-10-07 07:28 UTC, molimauro commented
Opened the tickets for those, closing this one

2022-10-07 07:28 UTC, closed without merging