feat(jest): 67% coverage for store/webrtc/getters
Satellite-im/Core-PWA pull request #4984
Opened 2022-09-22 07:01 UTC by drepram

### What this PR does 📖
- Increase coverage for store/webrtc/getters by adding an extensive unit test

### Which issue(s) this PR fixes 🔨
- Resolve AP-2797

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-09-22 07:02 UTC, drepram commented
This PR is related to #4979, due to one part of the code using primitive types and the other doesn't (store/audio).

2022-09-22 17:14 UTC, stavares843 approved these changes

2022-09-22 17:14 UTC, stavares843 commented
🎉

2022-09-22 17:49 UTC, stavares843 requested changes

2022-09-22 17:49 UTC, stavares843 commented on store/webrtc/getters.test.ts
> +import * as module from './getters'
this is failing due to this import

>    Cannot find module './getters' from 'store/webrtc/getters.test.ts'

2022-09-22 20:41 UTC, Jekrimo approved these changes
Approved pending Sara's fix

2022-09-23 16:25 UTC, drepram commented
Hi, the CI is failing because Joe removed these files, one of which was store/webrtc/getters:

![image](https://user-images.githubusercontent.com/34530026/192007859-c47f9af4-5025-45ed-9791-0abcb7bcaf49.png)

I will be closing this PR 😄

2022-09-23 16:25 UTC, closed without merging

2022-09-23 16:26 UTC, stavares843 commented
thanks 🔨