chore(fix): fixing recover account and minor changes
Satellite-im/Core-PWA pull request #5000
Opened 2022-09-23 09:48 UTC by JustZacca

### What this PR does 📖
Self-explanatory: This PR fixes the recover account function and does some other minor changes.

### Which issue(s) this PR fixes 🔨
- Resolve #4759 

### Special notes for reviewers 🗒️

There is some stuff that is commented, leave it there, we might need it in the future (Manuel commented it, I just did it too).
Yes I execute twice `await this.$PhantomWalletAdapter.connect() ` it does not bother the user but ensures the connection is working properly

### Additional comments 🎤

2022-09-23 13:32 UTC, stavares843 requested changes
![image](https://user-images.githubusercontent.com/29093946/191971423-0a79387b-aa0d-4bbd-ae5c-031bb2acc2e6.png)


when you import a account asks you the username again


also, not as relevant but its cut off in the top when importing the account

![image](https://user-images.githubusercontent.com/29093946/191971587-824cfcc4-2227-438e-ab09-3c318a99e7e6.png)

2022-09-23 13:32 UTC, stavares843 commented on libraries/Phantom/PhantomManager.ts
> +      await this.$PhantomWalletAdapter.connect()
do we need this duplicated line of code?

2022-09-23 13:32 UTC, stavares843 commented on store/accounts/actions.ts
> +    // )
do we need this commented out code?

2022-09-23 13:36 UTC, JustZacca commented on store/accounts/actions.ts
> +    // )
Same as before

2022-09-23 13:38 UTC, JustZacca commented
Maybe is a configuration of your iridium node, because for me it works without re asking for the username.
It's a strange topic, maybe if @WanderingHogan can test it to verify

2022-09-23 13:41 UTC, stavares843 commented
my iridium node? im using the fleek URL

hogan has better things to do than going to test something that i already did @JustZacca

2022-09-23 13:47 UTC, JustZacca commented on libraries/Phantom/PhantomManager.ts
> +      await this.$PhantomWalletAdapter.connect()
removed
I'll wait for the proper fix on Multi Wallet

2022-09-23 13:53 UTC, JustZacca commented
Okay, talking with @molimauro I've discovered an issue with the remote nodes of Iridium. We thought that it would be better to wait for the merge till it gets fixed.

2022-09-23 17:54 UTC, aewing approved these changes

2022-09-27 00:54 UTC, josephmcg commented
I could not successfully recover my account. it pushed me to new registration then was spinning forever

2022-09-27 09:41 UTC, JustZacca commented
> I could not successfully recover my account. it pushed me to new registration then was spinning forever

Okay, then is not an Iridium problem, the account recovery is inconsistent (sometimes it happens, sometimes it does not) I will investigate that

It could be still an Iridium Problem (not a version problem but a settings problem) so idk
I'll investigate

2022-09-29 09:52 UTC, closed without merging