5151 add mention functionality to chatbar
Satellite-im/Core-PWA pull request #5163
Opened 2022-10-06 02:12 UTC by jasonwoodland

### What this PR does 📖
- Add ChatbarAutocomplete component
- Username autocompletion in conversations triggered by typing '@'

### Which issue(s) this PR fixes 🔨
- Resolve #5151

### Special notes for reviewers 🗒️
We're going to add rich text insertion in a future PR! 🙇

### Additional comments 🎤

2022-10-06 04:59 UTC, josephmcg requested changes

2022-10-07 01:05 UTC, jasonwoodland commented on components/interactables/Editable/Editable.vue
> +      this.updateAutocomplete()
Makes sense, I checked for presence of a `$listener`

2022-10-07 01:05 UTC, jasonwoodland commented
@josephmcg made some improvements!

2022-10-07 07:19 UTC, molimauro approved these changes
Great!!

2022-10-07 07:19 UTC, molimauro approved these changes

2022-10-07 15:25 UTC, stavares843 reviewed
![image](https://user-images.githubusercontent.com/29093946/194590666-8ab9587f-cd5f-4215-83e0-ba383534d8e3.png)


not sure why, sometimes the auto complete component layout appears like this 

instead of this

![image](https://user-images.githubusercontent.com/29093946/194590651-2571820a-2cc4-40c1-8c6f-725f0b23bea5.png)

Chrome, macOS

2022-10-07 15:26 UTC, stavares843 reviewed
<img width="1462" alt="Captura de ecrã 2022-10-07, às 16 14 34" src="https://user-images.githubusercontent.com/29093946/194590894-00fd864b-f54b-4bcc-b73d-67ad21601736.png">

the satellite avatar doesn't seem in the right size

if you compare with other places, is not as small

2022-10-07 15:28 UTC, stavares843 reviewed
minor misalignment here

<img width="600" alt="Captura de ecrã 2022-10-07, às 16 28 07" src="https://user-images.githubusercontent.com/29093946/194591273-68d8a2fc-6606-4cee-b6c9-b00c6ec26e2a.png">

2022-10-07 15:29 UTC, stavares843 reviewed
there's no autocomplete when we edit a message is that for a future PR?

same question for when we send a @ name in the chat, is not bold or clickable to show the quick profile or similar for example

2022-10-07 15:30 UTC, stavares843 reviewed
<img width="364" alt="Captura de ecrã 2022-10-07, às 16 29 48" src="https://user-images.githubusercontent.com/29093946/194591604-0e9257d4-3be2-47cd-a1d7-16d096658014.png">


do we need this "" before we start to search?

2022-10-07 15:30 UTC, stavares843 commented on components/views/chat/chatbar/autocomplete/Autocomplete.less
> +  // background-color: @midground;
do we need this commented out? 🔨

2022-10-07 15:34 UTC, stavares843 commented
@molimauro what do you think? should we address this before or merge and address it after? is usable so, just some minor bugs

2022-10-07 15:34 UTC, phillsatellite approved these changes

2022-10-07 15:34 UTC, phillsatellite commented
Besides bugs Sara and I found above, approved 👍

2022-10-07 15:39 UTC, molimauro commented
> @molimauro what do you think? should we address this before or merge and address it after? is usable so, just some minor bugs

Seems that those are all minor problems/adjustments that we can address later. I think we can merge this!

Do you want me to add the tickets or could you do that? Thanks

2022-10-07 15:41 UTC, stavares843 commented
sounds good! will merge and add tickets 🔨

2022-10-07 15:41 UTC, merged

2022-10-07 15:44 UTC, stavares843 commented
added 🔨