feat(jest): untested clipboard improvement
Satellite-im/Core-PWA pull request #5233
Opened 2022-10-12 13:15 UTC by drepram

### What this PR does 📖
- Uses capacitor plugin for copying text on Accounts page. Haven't been able to test the APK, so reviews are most certainly awaited :D

### Which issue(s) this PR fixes 🔨
- Tries to solve #5199 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-10-12 16:00 UTC, stavares843 commented on components/views/settings/pages/accounts/index.vue
> +      this.$toast.show(this.$t('ui.copied') as string)
is

`      this.$toast.show(this.$t('ui.copied') as string)`



supposed to appear 2x?

2022-10-12 19:12 UTC, WanderingHogan commented
Hey @drepram, great first pass. In addition to Sara T's comments above and my comments inline, can you look at making this changes globally? Anywhere you might see navigator.clipboard?

2022-10-12 19:12 UTC, WanderingHogan requested changes

2022-10-12 19:12 UTC, WanderingHogan commented on components/views/settings/pages/accounts/index.vue
> +      const copyTextPromise = new Promise((resolve, reject) => {
you can instead make the whole function async, like this:
```
    async copyAddress(copyText: string) {
      await Clipboard.write({
        string: copyText,
      })
        .then(() => {
          this.$toast.show(this.$t('ui.copied') as string)
        })
        .catch(() => {
          this.$toast.error('Error when copying') // TODO: Put this in en-US later
        })
    },
    ```

2022-10-12 19:12 UTC, WanderingHogan commented on components/views/settings/pages/accounts/index.vue
> +      const copyTextPromise = new Promise((resolve, reject) => {
you can get rid of this whole copyPhrase method if you update the template. Instead of where you see @click="copyPhrase" you could do @click="copyAddress(accountPhrase)"

I would suggest renaming copyAddress to just something like copyMethod, or something generic

2022-10-13 01:43 UTC, josephmcg commented on components/views/settings/pages/accounts/index.vue
> +      const copyTextPromise = new Promise((resolve, reject) => {
imo, one of the benefits of using async await would be avoiding `then`. I'll push something up

2022-10-13 04:08 UTC, josephmcg commented
consulted with Andre, he's going to break this out into a reusable composition and update other components accordingly

2022-10-13 06:24 UTC, josephmcg commented
Looks good, I fixed a missing import and made some changes to calm the linter down.

everything works well on desktop, if someone else could confirm the apk works then we're good to go

2022-10-13 11:53 UTC, merged