fix(context-menu): fix action sheet styles
Satellite-im/Core-PWA pull request #5323
Opened 2022-10-19 08:02 UTC by nathan-power

### What this PR does 📖
- Fixes the styling for action sheets in mobile

### Which issue(s) this PR fixes 🔨
- Resolve #5322 

### Special notes for reviewers 🗒️
- To bring up an action sheet long press a list item in the chat list on mobile.
- Styling bug for action sheets opened inside the friends screen will be fixed in a separate PR.

2022-10-20 00:56 UTC, josephmcg requested changes
nice, just 1 minor change. we can take a look at the mixin later and remove it

2022-10-20 00:56 UTC, josephmcg commented on components/ui/ActionSheet/ActionSheet.vue
> +})
we saw copilot doing this yesterday, but maybe a function watcher is better if we use props
https://stackoverflow.com/questions/59125857/how-to-watch-props-change-with-vue-composition-api-vue-3

2022-10-24 07:36 UTC, josephmcg commented on components/views/navigation/mobile/nav/Nav.less
>    width: 100%;
maybe we dont need this height value since jason adjusted the transitions in a separate PR

2022-10-24 23:26 UTC, nathan-power commented on components/views/navigation/mobile/nav/Nav.less
>    width: 100%;
You're right it's not required anymore
I'll remove it now

2022-10-25 00:45 UTC, josephmcg requested changes
upon closing context menu on mobile, it feels like there's a second where you can't click anything

2022-10-25 02:29 UTC, josephmcg requested changes
this currently renders bottom nav on slide 2 of a chat page once you close the action sheet.

Do we need to hide/show the bottom nav on action sheet render?

2022-10-25 04:24 UTC, josephmcg approved these changes

2022-10-25 04:24 UTC, merged