chore(add): lock app button
Satellite-im/Core-PWA pull request #5327
Opened 2022-10-19 17:09 UTC by JustZacca

### What this PR does 📖
- Add app lock button

### Which issue(s) this PR fixes 🔨
- Resolve #5326 

### Special notes for reviewers 🗒️
- 

### Additional comments 🎤
-

2022-10-19 17:10 UTC, stavares843 commented on components/interactables/QuickProfile/QuickProfile.vue
> +  window.console.log('pressdsafads')
can we ditch this? 🔨

2022-10-19 17:11 UTC, JustZacca commented on components/interactables/QuickProfile/QuickProfile.vue
> +  window.console.log('pressdsafads')
yeah, I'm dumb, I forgot to delete it

2022-10-19 18:58 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/196780180-b4221574-74ab-4cb4-a004-692fe95d7a06.mov

neat 🎉

2022-10-20 00:40 UTC, josephmcg requested changes

2022-10-20 00:40 UTC, josephmcg commented on components/interactables/QuickProfile/QuickProfile.vue
> +    </TypographyText>
could you conditionally render this for only your own quick profile? There should be a computed that you can use

you can remove the typographyText around the button. Also double check the color prop options, white isn't a valid color in the type declaration. I think you want 'dark'

2022-10-20 00:40 UTC, josephmcg commented on components/interactables/QuickProfile/QuickProfile.vue
> +}
doesnt need to be async

2022-10-21 00:43 UTC, josephmcg commented
I adjusted store so this is only rendered in the bottom left quick profile since there are several ways to toggle your own quick profile (message name click, right sidebar click).

2022-10-21 00:44 UTC, josephmcg approved these changes

2022-10-21 00:44 UTC, merged