fix(actionsheet): style and behaviour
Satellite-im/Core-PWA pull request #5429
Opened 2022-10-28 06:09 UTC by jasonwoodland

### What this PR does 📖
- Fix viewport meta tag (by disabling meta on nuxt bridge config)
- Set user-scalable to no – fixes triple tapping zooming in on some elements on iOS
- Disable dragging anchor tags on iOS
- Fix iOS long touch events for context menu
- Fix action sheet style and animation

### Which issue(s) this PR fixes 🔨
- Resolve #5427 
- Resolve #5428

### Special notes for reviewers 🗒️
- 

### Additional comments 🎤
-

2022-10-28 07:09 UTC, molimauro commented on assets/styles/base.less
> -    env(safe-area-inset-bottom) env(safe-area-inset-left) !important;
Are these not needed anymore in mobile? :)

2022-10-28 09:00 UTC, jasonwoodland commented on assets/styles/base.less
> -    env(safe-area-inset-bottom) env(safe-area-inset-left) !important;
No, we're doing it in the layout components now using the new `var(--safe-area-inset-*)` variables 😎

2022-10-28 09:02 UTC, molimauro commented on assets/styles/base.less
> -    env(safe-area-inset-bottom) env(safe-area-inset-left) !important;
Dope thanks 🚀

2022-10-30 23:55 UTC, nathan-power requested changes
Looking good, just a little issue when opening the action-sheet on the friends screen (found in browser)
<img width="397" alt="スクリーンショット 2022-10-31 10 55 11" src="https://user-images.githubusercontent.com/40599535/198908174-0f8b9d3e-b3ce-4c9b-838e-c0fda8a89ec7.png">

2022-10-31 05:19 UTC, jasonwoodland commented
@nathan-power should be fixed

2022-11-03 08:21 UTC, molimauro approved these changes

2022-11-03 08:31 UTC, jasonwoodland commented
@phillsatellite 
I fixed some of these, still have to tackle the action sheet being hidden outside of the container. But I hope to fix this in a future PR so we can avoid conflicts. 😊

2022-11-03 08:32 UTC, merged