refactor(callTimer): add duration function to webrtc hooks
Satellite-im/Core-PWA pull request #5434
Opened 2022-10-28 15:50 UTC by drepram

### What this PR does 📖
- Extract duration timestamp functionality into composable on webrtcHooks
- Implement duration timestamp function composable on Call
- Implement duration timestamp function composable on Heading

### Which issue(s) this PR fixes 🔨

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-10-31 06:59 UTC, josephmcg requested changes

2022-10-31 06:59 UTC, josephmcg commented on components/compositions/webrtc.ts
> +
rather than passing this callStartedAt value in, you can access it directly inside of the composable.

2022-10-31 06:59 UTC, josephmcg commented on components/views/chat/message/call/Call.vue
>    },
Rather than keeping this logic copy/pasted and tracking two different values with two intervals, I imagined all of it being centralized

2022-11-02 16:21 UTC, drepram commented on components/compositions/webrtc.ts
> +
good point! thank you

2022-11-04 01:24 UTC, josephmcg commented
solution here
https://github.com/Satellite-im/Core-PWA/pull/5452

2022-11-04 01:24 UTC, closed without merging