[AP-121]-Friend req count
Satellite-im/Core-PWA pull request #554
Opened 2021-12-07 23:18 UTC by KemoPaw

**What this PR does** 📖

https://satellite-im.atlassian.net/browse/AP-121

**Which issue(s) this PR fixes** 🔨

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-07 23:43 UTC, stavares843 requested changes
neat 🎉 

any suggestions on how to avoid 2 digits to be overlapping the copy of the request? maybe 9+ instead? we can ask on the channel as well

<img width="1446" alt="Captura de ecrã 2021-12-07, às 23 41 39" src="https://user-images.githubusercontent.com/29093946/145123003-c0824d4b-90df-4193-8afe-d417b096ece8.png">

2021-12-08 06:01 UTC, RetroPronghorn commented
We should add some padding right to the button when there are notifications to avoid the overlap

2021-12-08 06:57 UTC, josephmcg requested changes

2021-12-08 06:57 UTC, josephmcg commented on components/tailored/friends/nav/Nav.less
> +  }
avoid using important. probably just switch the order of these

2021-12-08 06:57 UTC, josephmcg commented on components/tailored/friends/nav/Nav.html
> +    :text="`${$device.isMobile ? '' : 'Active'}`"
prob don't need template literal

2021-12-08 06:57 UTC, josephmcg commented on components/tailored/friends/nav/Nav.html
> +      :class="this.friends.incomingRequests.length ? 'big-button' : 'button' "
same here^

2021-12-08 06:57 UTC, josephmcg commented on components/tailored/friends/nav/Nav.html
> +  >
and here^

2021-12-08 06:57 UTC, josephmcg commented on components/tailored/friends/nav/Nav.html
> +  >
and here

2021-12-08 06:57 UTC, josephmcg commented on components/tailored/friends/nav/Nav.vue
> +  computed: {
switch order of props and computed to make eslint happy

2021-12-08 06:57 UTC, josephmcg commented on components/tailored/friends/nav/Nav.vue
> +      }
if (replyLength >**=** 100) {

otherwise it would show 100

2021-12-08 06:59 UTC, KemoPaw commented on components/tailored/friends/nav/Nav.html
> +    :text="`${$device.isMobile ? '' : 'Active'}`"
Okay, will change that one!

2021-12-08 07:00 UTC, KemoPaw commented on components/tailored/friends/nav/Nav.less
> +  }
@josephmcg Okay, will change & test this out.

2021-12-08 07:00 UTC, KemoPaw commented on components/tailored/friends/nav/Nav.vue
> +  computed: {
@josephmcg Okay, thank you very much for catching that one!

2021-12-08 07:01 UTC, KemoPaw commented on components/tailored/friends/nav/Nav.vue
> +      }
@josephmcg Good catch, was testing out something else beforehand and missed this one. Much appreciated!

2021-12-08 22:48 UTC, WanderingHogan commented
/rebase

2021-12-08 22:55 UTC, WanderingHogan commented
/rebase

2021-12-08 23:02 UTC, stavares843 commented
/rebase

2021-12-08 23:38 UTC, WanderingHogan approved these changes

2021-12-09 00:27 UTC, RetroPronghorn approved these changes

2021-12-09 00:33 UTC, stavares843 approved these changes

2021-12-09 00:46 UTC, josephmcg reviewed
a couple minor things, mostly removing dead code

2021-12-09 00:46 UTC, josephmcg commented on components/tailored/friends/nav/Nav.less
> +  }
this can be removed

2021-12-09 00:46 UTC, josephmcg commented on components/tailored/friends/nav/Nav.vue
> +      const length = this.friends.incomingRequests.length.toString().length
could sub for
const length = currentIncomingRequests.length

2021-12-09 00:46 UTC, josephmcg commented on components/tailored/friends/nav/Nav.html
> +      :class="friends.incomingRequests.length ? 'big-button' : 'button' "
this line can be removed. class is set in the component

2021-12-09 00:46 UTC, josephmcg commented on components/tailored/friends/nav/Nav.less
> +    right: 0.25rem;
there's a global for this
@xlight-spacing

2021-12-09 00:46 UTC, josephmcg commented on components/tailored/friends/nav/Nav.html
> +      :class="friends.incomingRequests.length ? 'big-button' : 'button' "
*class line. highlight was wonky

2021-12-09 07:50 UTC, KemoPaw commented
@josephmcg Changes have been made, thank you for the notes/feedback!

2021-12-10 00:36 UTC, josephmcg approved these changes
🚀

2021-12-10 00:57 UTC, merged