feat(import account): recover account from phrases you input
Satellite-im/Core-PWA pull request #565
Opened 2021-12-08 11:49 UTC by genie-magic

**What this PR does** 📖
Recover account from phrases you input

**Which issue(s) this PR fixes** 🔨

Fixes # AP-15

**Special notes for reviewers** 🗒️
Test Case for reviewers:
1. create an account
2. while creating an account, you should save recover phrases
![image](https://user-images.githubusercontent.com/28632174/145203451-a193e6e5-0193-4009-a896-ea5f488be88c.png)
3. after you register and login.. clear localStorage and go to '/'
4. input pin and click import account
5. input recover phrases you saved
6. after clicking import account you can log in with your created account

2021-12-08 15:01 UTC, iltumio commented on store/accounts/actions.ts
> +   * @method generateWallet DocsTODO
wrong method name

2021-12-08 15:04 UTC, iltumio commented on pages/setup/InputAccount/index.vue
> +     * @param
remove @param since is not needed

2021-12-08 15:05 UTC, iltumio commented on pages/setup/InputAccount/index.vue
> +     * @example
provide an example like
```
this.recoverAccount()
```

2021-12-08 15:08 UTC, iltumio requested changes
The functionality is ok. There are some errors in the comments to be fixed.
From the UX point of view the component does not allow to paste a whole phrase at once. We should open a separate ticket for that

2021-12-08 15:10 UTC, iltumio commented
@RetroPronghorn we should allow users to paste the whole phrase at once otherwise they have to input every single word by hand that is not user friendly

2021-12-08 15:43 UTC, stavares843 requested changes
<img width="1181" alt="Captura de ecrã 2021-12-08, às 15 36 29" src="https://user-images.githubusercontent.com/29093946/145237848-6dcb1f5f-f5f9-44e7-b80a-53e917f90276.png">

on the seed, appeared the same word 2x, birth birth

but when trying to add birth 2x, is not allowed because is already added

check hogan's comment [here](https://discord.com/channels/773445116572073995/859670812856418314/918165565984632872) regarding how to address it

2021-12-08 15:49 UTC, genie-magic commented
> <img alt="Captura de ecrã 2021-12-08, às 15 36 29" width="1181" src="https://user-images.githubusercontent.com/29093946/145237848-6dcb1f5f-f5f9-44e7-b80a-53e917f90276.png">
> 
> on the seed, appeared the same word 2x, birth birth
> 
> but when trying to add birth 2x, is not allowed because is already added
> 
> check hogan's comment [here](https://discord.com/channels/773445116572073995/859670812856418314/918165565984632872) regarding how to address it

I understand you.. yes. that is problem but not issue on this PR.. that is issue when creating account which populate same word.
What do you think abou that @WanderingHogan ?  We can make separate ticket or something but for this PR, we can skip that.

2021-12-08 16:04 UTC, stavares843 commented
hogan already had replied that [here](https://discord.com/channels/773445116572073995/859670812856418314/918165565984632872)


to address that on this PR

2021-12-08 16:23 UTC, WanderingHogan commented
Alright - so changes -
please make the changes Manuel requested
please make it so when a word is selected it is no longer removed from the list of words, and so that there is no limit on the number of times it is selected in the words list up to the max number of words that can be selected

2021-12-08 19:28 UTC, genie-magic commented
@WanderingHogan , @iltumio , @stavares843 
I fixed all you mentioned. plz check and let me know.

2021-12-08 19:34 UTC, stavares843 commented
great, thanks! 🎉 checking

2021-12-08 22:56 UTC, stavares843 commented
<img width="1455" alt="Captura de ecrã 2021-12-08, às 22 54 42" src="https://user-images.githubusercontent.com/29093946/145304460-419c3f30-7ff4-4d62-a554-3493b1e12420.png">

getting the above error trying to import

2021-12-09 03:29 UTC, WanderingHogan commented
@stavares843 I was wrong - the words do have to be in order. We should update the text so the user knows to enter them in order. This works greats when they are in the correct order.

2021-12-09 03:46 UTC, WanderingHogan commented
Language changed to tell user to put words in order & error message added in the translations file.

2021-12-09 05:11 UTC, stavares843 commented
thanks for clarifying!

2021-12-09 15:27 UTC, stavares843 commented
thanks for adding the locales! 💥

2021-12-09 15:34 UTC, stavares843 approved these changes
approved ✅

2021-12-09 19:39 UTC, iltumio approved these changes

2021-12-09 19:47 UTC, merged