fix(replies): show replies when expanding message chain
Satellite-im/Core-PWA pull request #596
Opened 2021-12-10 04:32 UTC by josephmcg

template was looking for attributes that don't exist yet
Added temporary fix until we confirm intended object structure

**What this PR does** 📖
Fix replies

**Which issue(s) this PR fixes** 🔨

Fixes #AP-124

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-10 04:33 UTC, josephmcg commented on components/tailored/messaging/message/reply/Reply.html
> +          />
Mostly linter formatting updates. only changes here

2021-12-10 04:51 UTC, WanderingHogan approved these changes

2021-12-10 06:04 UTC, RetroPronghorn approved these changes

2021-12-10 13:15 UTC, stavares843 requested changes
is the same on my side

I'm using the correct branch rebooted mac, and deployed a new local server


<img width="1213" alt="Captura de ecrã 2021-12-10, às 13 13 58" src="https://user-images.githubusercontent.com/29093946/145579585-2f819acf-7d8c-41da-acae-bbb3af5c7016.png">


STR:
- Go to a chat
- Reply on thread
- Reply
- Reply is empty

2021-12-13 00:19 UTC, josephmcg commented
Manuel gave me some ideas regarding reply structure. This was just a temp fix, so I'm gonna close and open another after I implement a better solution

2021-12-13 00:19 UTC, closed without merging