Eric/ap 19
Satellite-im/Core-PWA pull request #600
Opened 2021-12-10 15:07 UTC by genie-magic

**What this PR does** 📖
Privacy Settings Step during Sign Up Flow
**Which issue(s) this PR fixes** 🔨

Fixes # AP-19

**Special notes for reviewers** 🗒️
1.  When test , first clear local storage -> input pin -> create account -> privacy page
2. This needs locales change. please test this after https://github.com/Satellite-im/locales/pull/10 is merged to locales.

2021-12-10 18:30 UTC, stavares843 commented
merged https://github.com/Satellite-im/locales/pull/11

2021-12-10 18:34 UTC, stavares843 requested changes
<img width="879" alt="Captura de ecrã 2021-12-10, às 18 33 34" src="https://user-images.githubusercontent.com/29093946/145624334-baf975a7-f17b-40b0-9ad6-d2e2f7d1c02d.png">

ignore the locales, I can't use the last toggle

returns the following error

`[vuex] unknown mutation type: settings/displayCurrentActivity`

2021-12-10 20:40 UTC, genie-magic commented
> displayCurrentActivity

Can you send me screenshot of your console. I can't see that issue. Also did you get latest code?

2021-12-10 22:25 UTC, stavares843 commented
yes i already have the latest code, when i pulled out the branch, already went with those 3 commits


but the issue is no longer happening not sure why

this was the error

<img width="1403" alt="Captura de ecrã 2021-12-10, às 18 33 55" src="https://user-images.githubusercontent.com/29093946/145648775-6f1820d0-4a6a-4264-9b0e-fc67df939bc4.png">

2021-12-10 22:26 UTC, stavares843 commented
that error no longer happens and all toggles work fine now but I noticed on mobile, we can only see 3 toggles, and there is no scroll - note: already fixed that privacy typo on the title here - https://github.com/Satellite-im/locales/commit/63be50399e5c8b0e51b6aa83cd8be912d68cf268


<img width="644" alt="Captura de ecrã 2021-12-10, às 22 20 13" src="https://user-images.githubusercontent.com/29093946/145649077-fbd3e561-d4eb-49e4-accc-86a5d1e64d92.png">

2021-12-13 14:35 UTC, genie-magic commented
> that error no longer happens and all toggles work fine now but I noticed on mobile, we can only see 3 toggles, and there is no scroll - note: already fixed that privacy typo on the title here - [Satellite-im/locales@63be503](https://github.com/Satellite-im/locales/commit/63be50399e5c8b0e51b6aa83cd8be912d68cf268)
> 
> <img alt="Captura de ecrã 2021-12-10, às 22 20 13" width="644" src="https://user-images.githubusercontent.com/29093946/145649077-fbd3e561-d4eb-49e4-accc-86a5d1e64d92.png">

@stavares843  I fixed issue on mobile. plz check.

2021-12-13 14:35 UTC, stavares843 commented
thanks! 🎉 checking

2021-12-13 15:58 UTC, WanderingHogan approved these changes
looks good

2021-12-13 15:58 UTC, WanderingHogan commented on pages/setup/privacy/index.vue
> +    ...mapState(['ui', 'accounts', 'settings']),
this doesn't need to be updated here

2021-12-13 16:22 UTC, Jekrimo approved these changes

2021-12-13 16:48 UTC, stavares843 commented
mobile issue fixed 🎉

2021-12-13 16:58 UTC, stavares843 approved these changes

2021-12-13 16:58 UTC, merged