Sara/cypress stuff
Satellite-im/Core-PWA pull request #602
Opened 2021-12-10 18:13 UTC by stavares843

**What this PR does** 📖

- chore: add `data-cy` label to submit pass phrase
- test: add import account test
- chore: revert PR [#335](https://github.com/Satellite-im/Core-PWA/pull/335), there weren't any `data-cy` labels appearing locally
- test: add import test on commands to be reusable

**Special notes for reviewers** 🗒️

N/A

**Additional comments** 🎤

N/A

2021-12-10 20:03 UTC, WanderingHogan approved these changes

2021-12-10 21:10 UTC, WanderingHogan requested changes

2021-12-10 21:10 UTC, WanderingHogan commented on nuxt.config.js
>        config.node = {
can you add this back in, and everything inside `extend(config,ctx) {` with       `if (process.env.ENVIRONMENT === 'DEV' || 'PRODUCTION') {` and see if it lets cypress run it's tests?

2021-12-10 21:11 UTC, stavares843 commented on nuxt.config.js
>        config.node = {
checking

2021-12-10 22:15 UTC, stavares843 commented on nuxt.config.js
>        config.node = {
tried that, labels get removed on non prod as well 💥

2021-12-13 15:37 UTC, stavares843 commented on nuxt.config.js
>        config.node = {
added @josephmcg 's fix, works fine 🎉

2021-12-13 15:59 UTC, WanderingHogan approved these changes

2021-12-13 16:22 UTC, Jekrimo approved these changes

2021-12-13 16:23 UTC, merged