fix(importaccount): entire page sits off center on mobile (AP-253)
Satellite-im/Core-PWA pull request #604
Opened 2021-12-11 02:02 UTC by nickjjang

2021-12-11 16:36 UTC, stavares843 requested changes
_

2021-12-11 16:39 UTC, stavares843 approved these changes
fixed

<img width="1107" alt="Captura de ecrã 2021-12-11, às 16 38 08" src="https://user-images.githubusercontent.com/29093946/145684451-b21642a1-ca87-4a6a-a523-b58981d12b6b.png">

still gets a bit cut off on smaller screens but we can address that on other ticket

2021-12-13 16:06 UTC, WanderingHogan approved these changes

2021-12-13 16:46 UTC, stavares843 commented
fixed on smaller screens as well 🎉

2021-12-13 16:46 UTC, merged