Ap 99 Glyph Modal Overhaul(include AP-102)
Satellite-im/Core-PWA pull request #608
Opened 2021-12-11 14:18 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

Fixes #
fixed Glyph Modal Overhaul with AP-102
**Special notes for reviewers** 🗒️

**Additional comments** 🎤
Must install yarn again.

2021-12-11 16:32 UTC, stavares843 commented on components/tailored/messaging/enhancers/glyphs/Glyphs.vue
> +      // )
do we need this commented out block code?

2021-12-11 16:46 UTC, stavares843 requested changes
every time I do any action on this branch, it auto collapses


the same doesn't happen on dev

video below

https://user-images.githubusercontent.com/29093946/145684664-5f47e391-7035-4d00-816d-f94f16daf494.mp4

2021-12-11 16:47 UTC, davidchan1219 commented on components/tailored/messaging/enhancers/glyphs/Glyphs.vue
> +      // )
yes we don't need it

2021-12-11 16:48 UTC, stavares843 requested changes
the horizontal scroll bar is no longer invisible, now it appears blue

on dev is invisible


video below


https://user-images.githubusercontent.com/29093946/145684713-45845a9a-9cee-4846-a8a3-1e900cd45b8b.mp4

2021-12-11 16:53 UTC, stavares843 requested changes
the ticket description includes the following

<img width="430" alt="Captura de ecrã 2021-12-11, às 16 52 01" src="https://user-images.githubusercontent.com/29093946/145684861-c4a7ff36-a143-407f-aea7-874c297b9625.png">

I forced slow internet, but no loading appears, just empty spaces

<img width="1466" alt="Captura de ecrã 2021-12-11, às 16 51 46" src="https://user-images.githubusercontent.com/29093946/145684869-e20cd759-6d42-4586-9ffd-1c593c3817a2.png">

2021-12-11 16:59 UTC, stavares843 requested changes
left side, this PR

right side, dev branch

<img width="1479" alt="Captura de ecrã 2021-12-11, às 16 58 31" src="https://user-images.githubusercontent.com/29093946/145685034-14846dc2-e6cf-4542-aa13-cbfd68199f2a.png">


on this branch, the scroll bar gets behind the section on the bottom, that doesn't happen on dev

Chrome, macOS

2021-12-13 14:32 UTC, davidchan1219 commented
> every time I do any action on this branch, it auto collapses
> 
> the same doesn't happen on dev
> 
> video below
> 
>  Screen.Recording.2021-12-11.at.4.44.51.PM.mp4 
> Chrome, macOS

Sorry, I can't see this issue in my branch. Can you check this issue again?

2021-12-13 16:36 UTC, stavares843 commented
taking a look!

2021-12-13 16:39 UTC, stavares843 requested changes
the loading is only visible if you scroll all the way down

<img width="1494" alt="Captura de ecrã 2021-12-13, às 16 38 02" src="https://user-images.githubusercontent.com/29093946/145852176-ba0521cd-bdb7-4900-8447-48727ad72ccc.png">
<img width="1488" alt="Captura de ecrã 2021-12-13, às 16 38 23" src="https://user-images.githubusercontent.com/29093946/145852219-416a76d8-5ae3-4bd3-b0f6-68abda6f82e3.png">

Chrome, macOS

2021-12-13 16:40 UTC, stavares843 commented
> every time I do any action on this branch, it auto collapses

this issue no longer happens ✅

2021-12-13 16:43 UTC, stavares843 commented
the blue bar on the horizontal scroll is fixed, but now is barely scrollable

https://user-images.githubusercontent.com/29093946/145853027-baacc833-f749-4fd2-96ec-3d00186be661.mp4

Chrome, macOS

2021-12-13 16:45 UTC, davidchan1219 commented
> the loading is only visible if you scroll all the way down
> 
> <img alt="Captura de ecrã 2021-12-13, às 16 38 02" width="1494" src="https://user-images.githubusercontent.com/29093946/145852176-ba0521cd-bdb7-4900-8447-48727ad72ccc.png">
> 
> <img alt="Captura de ecrã 2021-12-13, às 16 38 23" width="1488" src="https://user-images.githubusercontent.com/29093946/145852219-416a76d8-5ae3-4bd3-b0f6-68abda6f82e3.png">
> 
> Chrome, macOS

It takes some time to load images. Let me find the better solution.

2021-12-14 17:59 UTC, stavares843 commented
did you check this one?

https://github.com/Satellite-im/Core-PWA/pull/608#issuecomment-992665616

is better, but still strange when scrolling there

2021-12-15 06:28 UTC, WanderingHogan requested changes
What happened in 'mock/glyphs.ts'? Is it safe to reset this file? Also the tailored components are gone - i think it might be `EnhancersGlyphsPack` now?

2021-12-15 06:28 UTC, WanderingHogan commented on components/views/chat/enhancers/glyphs/packGroup/packGroup.vue
> +      <TailoredMessagingEnhancersGlyphsPack :key="source.id" :pack="source" />
This component is gone/needs to be updated

2021-12-15 09:22 UTC, davidchan1219 commented on components/views/chat/enhancers/glyphs/packGroup/packGroup.vue
> +      <TailoredMessagingEnhancersGlyphsPack :key="source.id" :pack="source" />
To implement virtual scroll component, I changed the data structure in "mock/glyphs.ts". But this would be not appeared fatal issue for other page or components. I have already tested enough. And changed component name as you wrote.

2021-12-15 09:27 UTC, RetroPronghorn commented on components/views/chat/enhancers/glyphs/packGroup/packGroup.vue
> +      <TailoredMessagingEnhancersGlyphsPack :key="source.id" :pack="source" />
@davidchan1219 it looks like you just needed an array of the packs. Please remove the spaces after each line, and instead make a export called 

`export const GlyphsArray = Object.values(Glyphs)`

2021-12-15 10:04 UTC, davidchan1219 commented on components/views/chat/enhancers/glyphs/packGroup/packGroup.vue
> +      <TailoredMessagingEnhancersGlyphsPack :key="source.id" :pack="source" />
Okay, I used Object.values() function for Glyph array.

2021-12-15 14:36 UTC, davidchan1219 commented on components/views/chat/enhancers/glyphs/packGroup/packGroup.vue
> +      <TailoredMessagingEnhancersGlyphsPack :key="source.id" :pack="source" />
Have one question.
Where should I run loading component? for individual images or for individual groups?
I think it should be run in every image. right?

2021-12-15 18:18 UTC, WanderingHogan commented on components/views/chat/enhancers/glyphs/item/Item.html
> +  :src=""
I can't get this to build with the src being blank here:
![Screen Shot 2021-12-15 at 11 17 56 AM](https://user-images.githubusercontent.com/2993032/146242808-7cc34073-dd07-474f-b2f8-b8ff9ae48c76.png)

2021-12-15 18:19 UTC, WanderingHogan commented on components/views/chat/enhancers/glyphs/packGroup/packGroup.vue
> +      <TailoredMessagingEnhancersGlyphsPack :key="source.id" :pack="source" />
I think the individual loaders are a good choice. There needed to be some kind of feedback for the user that a glyph was loading, we can send this to design when it's working and come back to it later for this ui update

2021-12-15 18:30 UTC, davidchan1219 commented on components/views/chat/enhancers/glyphs/item/Item.html
> +  :src=""
Sorry for my fault. I will send the commit again

2021-12-15 21:40 UTC, WanderingHogan approved these changes

2021-12-15 23:09 UTC, stavares843 requested changes
dev vs this branch

![image](https://user-images.githubusercontent.com/29093946/146278935-5b72c20f-2d93-42ae-93e2-be01c330337a.png)


it has some hidden stuff near the toast egg

2021-12-15 23:11 UTC, stavares843 requested changes
the scroll on the glyphs section is not as stuck compared with this branch

https://user-images.githubusercontent.com/29093946/146279122-a41bb9a8-5015-4ec2-be76-2549212417df.mp4


Chrome, macOS

2021-12-15 23:14 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/146279483-6205dcf0-9169-4ecd-bd97-95094d0949d7.mp4

also gets stuck when all the loaders are loading

2021-12-15 23:16 UTC, stavares843 requested changes
maybe we should not allow the user to send out the glyph is not loaded yet because will send out empty space on the chat - then will update to the glyph


<img width="1119" alt="Captura de ecrã 2021-12-15, às 23 01 12" src="https://user-images.githubusercontent.com/29093946/146279586-2676ea7a-6f86-4a90-aa02-93b0a5c3b2f9.png">

2021-12-15 23:16 UTC, stavares843 requested changes
loading is not centered within the section

<img width="704" alt="Captura de ecrã 2021-12-15, às 23 16 28" src="https://user-images.githubusercontent.com/29093946/146279694-97525eac-2fed-4590-b722-1bd8dfb103a9.png">

2021-12-16 05:10 UTC, davidchan1219 commented
> maybe we should not allow the user to send out the glyph is not loaded yet because will send out empty space on the chat - then will update to the glyph
> 
> <img alt="Captura de ecrã 2021-12-15, às 23 01 12" width="1119" src="https://user-images.githubusercontent.com/29093946/146279586-2676ea7a-6f86-4a90-aa02-93b0a5c3b2f9.png">

For loading component, I made to not allow to add image to chatbox and made "not-allowed" cursor when hover that.

2021-12-16 06:19 UTC, WanderingHogan commented
@davidchan1219, we really like what you did with the virtual scroll, but there are some performance issues and a few other changes to tie this in with the current glyphs implementation that need to be worked through. joe is going to take over this ticket and fold many of your changes in with what's currently on dev because your swiper ticket is more important right now

2021-12-20 05:37 UTC, josephmcg commented
pulled in here
https://github.com/Satellite-im/Core-PWA/pull/700

2021-12-20 05:37 UTC, closed without merging