feat(emoji): Track Emoji Usage, display most frequent emojis on context menu & emoji dialog
Satellite-im/Core-PWA pull request #609
Opened 2021-12-13 13:57 UTC by genie-magic

**What this PR does** 📖
Track Emoji Usage, display most frequent emojis on context menu & emoji dialog
**Which issue(s) this PR fixes** 🔨

Fixes # AP-236

**Special notes for reviewers** 🗒️

1. when you not choose emoji, frequently used emoji not appear on context menu & emoji dialog
2. when you click emoji and it is tracked via vuex store and it is showed on context menu & emoji dialog

2021-12-13 16:31 UTC, Jekrimo approved these changes

2021-12-13 16:31 UTC, Jekrimo commented on store/ui/mutations.ts
> +        typeof options.containerWidth !== 'undefined'
Will you see if we have an enum for the string 'undefined' we could throw here for all of these? If not make one real quick if you have time? Definitely a good one for us to have.

2021-12-13 16:31 UTC, Jekrimo commented on store/ui/mutations.ts
> +        typeof options.containerWidth !== 'undefined'
![image](https://user-images.githubusercontent.com/19398153/145850802-474f2954-5251-4660-b5b0-42eb714a321d.png)

would be here, Maybe common-types.ts ,

2021-12-13 16:36 UTC, stavares843 requested changes
the feature itself seems good

but there's a behavior on this branch that doesn't happen on dev


https://user-images.githubusercontent.com/29093946/145851559-19d54408-3376-4813-a172-4d5d86885599.mp4


when you click on an emoji, selects all the emojis, and appears all blue

the same doesn't happen on dev

Chrome, macOS

2021-12-13 18:33 UTC, WanderingHogan approved these changes
I think this is good once you have that weird ui thing @stavares843 found, fixed

2021-12-13 18:33 UTC, WanderingHogan commented on components/tailored/messaging/enhancers/Enhancers.html
> +              placeholder="Search..."
Can you put this in the translations

2021-12-15 06:29 UTC, WanderingHogan commented
This needs the highlighting issue fixed, and to be rebased on dev

2021-12-15 09:42 UTC, genie-magic commented
> the feature itself seems good
> 
> but there's a behavior on this branch that doesn't happen on dev
> 
>  Screen.Recording.2021-12-13.at.4.31.44.PM.mp4 
> when you click on an emoji, selects all the emojis, and appears all blue
> 
> the same doesn't happen on dev
> 
> Chrome, macOS

@stavares843  @WanderingHogan  , highlight issue is fixed .. plz check.

2021-12-15 18:26 UTC, WanderingHogan commented
Looks good to me, @stavares843 if it looks ok to you please merge, we can add the translation updates to https://satellite-im.atlassian.net/browse/AP-277

2021-12-15 19:28 UTC, stavares843 commented
thanks @WanderingHogan checking 💥

2021-12-15 22:56 UTC, stavares843 approved these changes
neat! 🎉

2021-12-15 22:57 UTC, merged