fix(importaccount): presuggestion not working on mobile devices if word start capitalized (AP-254)
Satellite-im/Core-PWA pull request #613
Opened 2021-12-13 18:29 UTC by nickjjang

2021-12-13 18:56 UTC, stavares843 approved these changes
fixed ✅

2021-12-14 07:14 UTC, josephmcg approved these changes

2021-12-14 08:52 UTC, WanderingHogan commented on components/ui/TypeHead/TypeHead.vue
> +      if (this.$props.textTransform === 'lowercase') {
Can you remove the pieces where you force lowercase input and instead favor just casting the input to lowercase to compare with the list? I think you can accomplis this in the update with something similar to ```      this.searchList = this.list.filter((item: any) => { 
        return item.indexOf(this.searchText.toLowerCase()) !== -1
      }```

2021-12-14 08:53 UTC, WanderingHogan requested changes
Can you make this so the user can still input any case, but we cast it to lower case when comparing to the list?

2021-12-14 17:01 UTC, WanderingHogan approved these changes
works good!

2021-12-14 17:08 UTC, stavares843 approved these changes

2021-12-14 17:09 UTC, merged