AP235 We should persist the replies when switching conversations
Satellite-im/Core-PWA pull request #614
Opened 2021-12-13 19:31 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-13 19:51 UTC, stavares843 requested changes
fixed but this is introducing a bug that doesn't happen on dev


it doesn't allow sending out emojis


https://user-images.githubusercontent.com/29093946/145878678-a7ad28dd-ba3c-434f-ae3e-f818adfdaf50.mp4

2021-12-14 17:26 UTC, stavares843 requested changes
always getting this error going to any DM on this branch

<img width="1488" alt="Captura de ecrã 2021-12-14, às 17 25 20" src="https://user-images.githubusercontent.com/29093946/146048733-c33374d7-2b08-4abf-8683-e871452715d1.png">

2021-12-15 01:55 UTC, stavares843 commented on components/tailored/core/chatbar/Chatbar.vue
> +  // },
we can burn this commented out code

2021-12-15 10:26 UTC, davidchan1219 commented on components/tailored/core/chatbar/Chatbar.vue
> +  // },
Removed that commented part

2021-12-16 04:57 UTC, RetroPronghorn commented
@davidchan1219 This approach is a bit too complex for what we need to acheive. Instead let's follow a pattern like so.


Make a new state section for message replies (create a Chat folder in store)

add the correct typings for it like 

```
type ChatState = {
    replies: {
        User.ID: string
    },
    text: {
       User.ID: string
    }
}
```

Make a mutation to add text based on the user we're chatting with and allow us to choose if it's a reply or generic chatbar text.

before the component unmounts call the mutation to store the text

```
beforeUnmount() {
   ...if we have an active reply being typed
       ...call chat mutation to store in reply state
  ...if we have active message in chatbar
       ...call chat mutation to store in text state
 }
 ```
 now when the component mounts, we can simply check the state to see if a reply is being made. We should also clear the reply from state when remounting.
 
 ```
 mounted() {
 ...if store.state.chat.replies[user]
    ...this.$data.reply = store.state.chat.replies[user]
    ...call mutation to clear
 ...if store.state.chat.text[user]
    ...this.store.state.chatbarContent = this.store.state.chat.text[user]
    ...call mutation to clear
}
```

this is psuedo code but please feel free to ask questions if you have any. I think we should start fresh from the dev branch on this. It will be a better approach in the long run.

2021-12-16 17:15 UTC, stavares843 commented
the crash is fixed ✅ 

persisting message bug is fixed ✅ 

sending emojis works ✅

2021-12-16 17:16 UTC, stavares843 approved these changes

2021-12-16 17:16 UTC, WanderingHogan approved these changes

2021-12-16 18:40 UTC, merged