feat(send images): images are sent to textile and display in conversations
Satellite-im/Core-PWA pull request #618
Opened 2021-12-13 22:39 UTC by Jekrimo

**What this PR does** 📖
Allows users to send images within conversations.  Initializes textile buckets to store images.

**Which issue(s) this PR fixes** 🔨
AP-78 / AP-249

**Additional comments** 🎤
This is a start for our images, there will need to be tweaks to support file types other than images.

2021-12-13 23:38 UTC, stavares843 reviewed
<img width="1492" alt="Captura de ecrã 2021-12-13, às 23 36 17" src="https://user-images.githubusercontent.com/29093946/145906184-04b824ff-9546-47b8-8044-438113d3efb0.png">

the download file icon seems pretty small

and not sure if the filename maybe would be better on the bottom instead on side, but that's a question for design team to take a look

2021-12-13 23:40 UTC, stavares843 requested changes
https://user-images.githubusercontent.com/29093946/145906293-225308ff-40c8-4bcd-b493-65ee97f28f4c.mp4

when sending an image, the box with the send button doesn't go away after you click it to send it and if you keep clicking sends out the same image multiple times

so seems we need to
- dismiss the box right after user clicks on send 
- add some limit to avoid spamming requests

2021-12-13 23:46 UTC, stavares843 requested changes
<img width="1492" alt="Captura de ecrã 2021-12-13, às 23 45 51" src="https://user-images.githubusercontent.com/29093946/145906930-e30b1b97-9793-4f35-a0b1-4c7239bbc2c8.png">

is missing a loading when the images are still loading

2021-12-13 23:49 UTC, stavares843 requested changes
<img width="1489" alt="Captura de ecrã 2021-12-13, às 23 48 09" src="https://user-images.githubusercontent.com/29093946/145907119-82fbde34-65a5-4836-8281-b041944265e3.png">

are we compacting the images after sending them on chat? I sent a 100MB image and the tab on the browser is very slow 

in case you need 100MB images NASA website has a bunch of those
https://visibleearth.nasa.gov/images/73751/july-blue-marble-next-generation-w-topography-and-bathymetry

2021-12-14 18:48 UTC, WanderingHogan commented on components/tailored/core/fileupload/FileUpload.vue
> +      imageURL: String,
primitives should be lower case

2021-12-14 18:49 UTC, WanderingHogan commented on components/tailored/core/fileupload/FileUpload.vue
> +        file: this.$data.files[0]
this is fine for this first pass but we should add a ticket to handle multiple file upload

2021-12-14 21:48 UTC, WanderingHogan commented on components/ui/Embeds/File/File.vue
> +    getFileSize() {
where is this defined?

2021-12-14 21:52 UTC, WanderingHogan commented on types/textile/manager.ts
> +import * as t from "io-ts";
i don't think we are using this

2021-12-14 21:57 UTC, stavares843 commented on components/tailored/core/fileupload/FileUpload.vue
> +      imageURL: String,
is this something expected to be burned by the linter?

2021-12-14 22:39 UTC, WanderingHogan commented on components/ui/Embeds/File/File.vue
> +      const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB']
this is a neat way to do this

2021-12-14 22:40 UTC, Jekrimo commented on components/tailored/core/fileupload/FileUpload.vue
> +        file: this.$data.files[0]
100%, I'll add a couple new tickets, this being one, but also one for handling other types of emails

2021-12-14 22:41 UTC, WanderingHogan commented on store/textile/actions.ts
> +    const imageURL = `https://hub.textile.io${result?.root}${path}`
can you add this to the config

2021-12-14 22:44 UTC, Jekrimo commented on components/ui/Embeds/File/File.vue
> +      const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB']
I stole it from lega.... I mean, yeah I'm real smart

2021-12-14 22:58 UTC, WanderingHogan commented on libraries/Textile/BucketManager.ts
> +  }
can you add the inline documentation here when you get a chance

2021-12-14 23:16 UTC, WanderingHogan approved these changes

2021-12-15 23:30 UTC, WanderingHogan commented on components/tailored/core/fileupload/FileUpload.vue
> +      imageURL: String,
I am not sure about the linter, an error should be shown in the ide though. Do you think anything that throws an error in the IDE should be in the linter?  I also think this will transpile fine but could potentially cause problems in the typescript, but is more of a best practices thing

string is a primitive, String is an object, so object assignment could get wonky in typescript, example:

![Screen Shot 2021-12-15 at 4 26 52 PM](https://user-images.githubusercontent.com/2993032/146280712-2d50c084-f8b0-4bf5-9cbe-3aafc0afee76.png)

2021-12-16 00:13 UTC, WanderingHogan commented
@stavares843 going through your comments:

- `the download file icon seems pretty small` - this will be addressed in a ui ticket, AP-276
- `dismiss the box right after user clicks on send` - i think this is in? I see the reactions when you hover on the image
- add some limit to avoid spamming requests - button appears to be deactivated in recent pushes after you click the upload button
- `is missing a loading when the images are still loading`- a ticket Jeff will create when his internet comes back
- `are we compacting the images after sending them on chat...` we are not, we need to look more into the speed of uploading files to the encrypted textile buckets, see if speeds slow down for specific file sizes or if it's a distance thing or some other problem slowing uploads down

2021-12-16 00:14 UTC, WanderingHogan commented
related tickets are:
```
1. multi file upload (AP-274)
2. handling other file types (AP-275)
3. UI updates (AP-276)
4. Download button (tbd)
5. Downloading indicator (tbd)
6. Adding glyphs to image posts (tbd)
```

2021-12-16 00:49 UTC, stavares843 reviewed
first time sending the file crashed

https://user-images.githubusercontent.com/29093946/146287629-914ec175-2ada-4023-995f-dea403f64e69.mp4

non reproducible

Chrome, macOS

2021-12-16 00:51 UTC, stavares843 commented
pretty neat! 🎉 

![image](https://user-images.githubusercontent.com/29093946/146287866-2ca966ca-a849-4787-9552-9499c025fa58.png)

2021-12-16 00:55 UTC, stavares843 requested changes
if you try to send 4 images, only sends 1

is that expected? if is something to be added later?

2021-12-16 00:56 UTC, stavares843 requested changes
<img width="1022" alt="Captura de ecrã 2021-12-16, às 00 55 49" src="https://user-images.githubusercontent.com/29093946/146288195-4c6f8920-95db-488c-b193-4519a6fd0bfd.png">

it says upload blocked but has the send button activated and if you click, it sends the image

on dev doesn't have the send button on a blocked image

<img width="809" alt="Captura de ecrã 2021-12-16, às 01 00 33" src="https://user-images.githubusercontent.com/29093946/146288690-d08d9377-3b7c-425c-8ed4-a079dcf80989.png">

2021-12-16 00:57 UTC, WanderingHogan commented
@stavares843 multi file upload  will be addressed in (AP-274)

2021-12-16 00:58 UTC, stavares843 commented
ohh thanks 😂

2021-12-16 00:58 UTC, stavares843 commented
and thanks for clarifying the above points! 💥

2021-12-16 01:08 UTC, stavares843 commented
added tickets here

[AP-285](https://satellite-im.atlassian.net/browse/AP-285)
[AP-286](https://satellite-im.atlassian.net/browse/AP-286)

2021-12-16 01:08 UTC, stavares843 approved these changes

2021-12-16 01:09 UTC, merged