[Ap-65]-Emoji chat render
Satellite-im/Core-PWA pull request #623
Opened 2021-12-14 00:01 UTC by KemoPaw

**What this PR does** 📖
Have emojis not render as tiny as they were previously

**Which issue(s) this PR fixes** 🔨
https://satellite-im.atlassian.net/browse/AP-65

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-14 00:10 UTC, stavares843 reviewed
@KemoPaw the emojis are awesome! 🎉 

<img width="1487" alt="Captura de ecrã 2021-12-14, às 00 09 34" src="https://user-images.githubusercontent.com/29093946/145909080-2bdeac48-4be7-47ce-8e49-2c8345c5c28a.png">

2021-12-14 00:11 UTC, stavares843 reviewed
screenshot with a couple variations @WanderingHogan 

<img width="1194" alt="Captura de ecrã 2021-12-14, às 00 10 55" src="https://user-images.githubusercontent.com/29093946/145909189-3d952670-36e2-4a98-afdd-8b30788f21f5.png">

2021-12-14 00:26 UTC, stavares843 approved these changes

2021-12-14 06:43 UTC, WanderingHogan commented on components/tailored/core/chatbar/Chatbar.vue
> +      if (!newInput) {
don't need this if, the return statement in the if above will kick you out of the method before you get here

2021-12-14 06:44 UTC, WanderingHogan commented on components/tailored/core/chatbar/Chatbar.vue
> +          } else {
never else, use a guard clause here

2021-12-14 06:44 UTC, WanderingHogan requested changes
couple changes in comments

2021-12-14 08:36 UTC, josephmcg requested changes
https://jsfiddle.net/qu43byLn/7/
I was talking with Matt about this and he thought we should check the input string in a different way. The for loop may cause performance issues down the line. See if you can draw inspiration from the jsfiddle

You can also add regex rules to the config file at:
Core-PWA/config.ts

2021-12-15 03:19 UTC, closed without merging

2021-12-15 03:19 UTC, KemoPaw commented
https://github.com/Satellite-im/Core-PWA/pull/649