[AP-169] - fix(emojiUpdateCharCounter): char counter update on emoji
Satellite-im/Core-PWA pull request #625
Opened 2021-12-14 03:01 UTC by KemoPaw

**What this PR does** 📖

- counter for char limit updates when adding emoji(s)
- emoji(s) are counted as only one "length" instead of two

**Which issue(s) this PR fixes** 🔨
https://satellite-im.atlassian.net/browse/AP-169

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-14 03:50 UTC, stavares843 approved these changes
fixed ✅

2021-12-14 05:11 UTC, WanderingHogan commented on components/tailored/core/chatbar/footer/Footer.vue
>  import Vue, { PropType } from 'vue'
you can remove the imports for PropType, Friend

2021-12-14 05:14 UTC, WanderingHogan commented on components/tailored/core/chatbar/footer/Footer.vue
> +      return _.toArray(inputString).length
you imported the toArray method, you don't need the whole library, change `_.toArray(` to `toArray(`

2021-12-14 05:15 UTC, WanderingHogan requested changes
Couple minor updates to the Footer.vue file in the comments

2021-12-14 05:33 UTC, KemoPaw commented on components/tailored/core/chatbar/footer/Footer.vue
>  import Vue, { PropType } from 'vue'
@WanderingHogan Okay!

2021-12-14 05:35 UTC, josephmcg requested changes

2021-12-14 05:35 UTC, josephmcg commented on components/tailored/core/chatbar/footer/Footer.vue
> +    </span>
I would pull this out into a computed to keep the markup cleaner and easier to read.

```
    <span :class="['charlimit', charlimit ? 'is-error' : 'is-normal']">
      {{ lengthCount }}
    </span>
```

```

computed: {
    ...mapState(['ui']),
    lengthCount() {
      return `${toArray(this.ui.chatbarContent).length}/${this.maxChars}`
    },
  },
```

2021-12-14 23:31 UTC, Jekrimo approved these changes

2021-12-15 01:08 UTC, josephmcg approved these changes
🚀

2021-12-15 13:08 UTC, stavares843 approved these changes
neat! 🎉

2021-12-15 13:09 UTC, stavares843 commented
added missing dev review label again because hogan was requested for review

2021-12-15 23:56 UTC, WanderingHogan approved these changes

2021-12-16 00:11 UTC, merged