Ap245 Clicking Glyph in Chat to Show Pack
Satellite-im/Core-PWA pull request #626
Opened 2021-12-14 03:27 UTC by josephmcg

**What this PR does** 📖
- generic mobile modal that only goes partway up the screen
- desktop modal for glyph pack details on click
- mobile modal for glyph pack details on click
- send user to a specific glyph pack in marketplace on button click

**Which issue(s) this PR fixes** 🔨

Fixes #AP245-248 subissues

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-14 03:41 UTC, WanderingHogan commented on components/tailored/glyphs/Glyphs.html
> +    text="View Glyph Pack"
add to translations file and reference here

2021-12-14 06:02 UTC, josephmcg commented on components/tailored/glyphs/Glyphs.html
> +    text="View Glyph Pack"
fixed

2021-12-14 13:45 UTC, stavares843 approved these changes
the modal on mobile is not responsive, is it not to be handled in another ticket?

otherwise, good to go

2021-12-14 14:41 UTC, Jekrimo approved these changes

2021-12-14 15:04 UTC, josephmcg commented
I put in quite a bit of effort to make the modal responsive, could you clarify what you mean? The glyph details modals are responsive. The marketplace is not, that will be handled later

2021-12-14 16:11 UTC, stavares843 commented
correct branch

https://user-images.githubusercontent.com/29093946/146035786-d137cb1b-c375-40c2-9520-2dc6e9a98a02.mp4

but on mobile appears like this

<img width="1105" alt="Captura de ecrã 2021-12-14, às 16 09 21" src="https://user-images.githubusercontent.com/29093946/146035832-b07b869d-285d-4c5e-ac66-c68c3d02dc4f.png">


when i meant the modal i meant when clicking on the glyphs section

2021-12-15 00:26 UTC, josephmcg commented
That's not a feature that I worked on in this ticket. This was focused on clicking a glyph in a conservation after it has already been sent.

2021-12-15 02:22 UTC, josephmcg commented
@stavares843 I fixed that issue you found, also rebased off dev and fixed. Let me know if you find any issues

2021-12-15 03:31 UTC, stavares843 commented
ohhh lol thanks for clarifying! and thanks for fixing as well 🎉

2021-12-16 01:20 UTC, josephmcg commented
I didn't merge, just fixed conflict w/ github gui editor

2021-12-16 01:25 UTC, stavares843 commented
neat, thanks! 🎉

2021-12-16 01:39 UTC, stavares843 requested changes
going to a chat > glyphs > crash

<img width="1402" alt="Captura de ecrã 2021-12-16, às 01 38 31" src="https://user-images.githubusercontent.com/29093946/146292207-b17a205a-f952-43ec-8aec-ac5c23f4820d.png">

2021-12-16 01:52 UTC, josephmcg commented
thanks Sara, I must have fixed that conflict incorrectly. It should be working now

2021-12-16 03:26 UTC, josephmcg commented
@stavares843 
ok ready for testing.

2021-12-16 07:48 UTC, WanderingHogan commented on components/views/chat/message/glyph/Glyph.vue
> +<template src="./Glyph.html" />
can you add a closing tag to template

2021-12-16 07:50 UTC, WanderingHogan commented on components/views/chat/message/glyph/Glyph.vue
> +      default: '404.png',
what is 404.png?

2021-12-16 07:52 UTC, WanderingHogan commented on components/views/glyphs/Glyphs.vue
> +<template src="./Glyphs.html" />
can you close this template tag

2021-12-16 08:22 UTC, WanderingHogan approved these changes

2021-12-16 08:24 UTC, josephmcg commented on components/views/chat/message/glyph/Glyph.vue
> +      default: '404.png',
Seems to be a dummy value, I copied from another ui component. removed in favor of ''

2021-12-16 15:18 UTC, stavares843 reviewed
when you send a glyph on the chat > click on the glyph > shows the pack > click on the button to go to marketplace > opens marketplace > you cant close the marketplace - non reproducible

<img width="1431" alt="Captura de ecrã 2021-12-16, às 15 16 38" src="https://user-images.githubusercontent.com/29093946/146398170-b22bf57d-ce6a-434e-a6e4-b7850135f9e0.png">


Chrome, macOS

2021-12-16 15:19 UTC, stavares843 requested changes
some glyphs have a wider button than others

<img width="553" alt="Captura de ecrã 2021-12-16, às 15 18 37" src="https://user-images.githubusercontent.com/29093946/146398491-131a8e40-01eb-474c-b129-2d9c85b512e1.png">
<img width="619" alt="Captura de ecrã 2021-12-16, às 15 18 41" src="https://user-images.githubusercontent.com/29093946/146398497-ff1a0d66-d6e1-48af-8bdd-ed7fa77be12a.png">

2021-12-16 15:22 UTC, stavares843 commented
besides that, pretty neat! 🎉

2021-12-17 02:06 UTC, josephmcg commented
Thanks, I'll work on those. Hogan encountered the same marketplace bug yesterday but was also unable to reproduce

2021-12-17 02:08 UTC, stavares843 commented
maybe its only on the first time going to that button 💥

2021-12-17 05:03 UTC, josephmcg commented
Fixed the button size issue, css for modal size is much more robust for various screen sizes/open console.
Not sure about marketplace issue though

2021-12-17 08:43 UTC, stavares843 commented
thanks! :tada:

2021-12-17 15:42 UTC, stavares843 commented
neat! 🎉

2021-12-17 15:42 UTC, stavares843 approved these changes

2021-12-17 15:42 UTC, merged