feat(Quick Profile): Implement Quick Profile
Satellite-im/Core-PWA pull request #655
Opened 2021-12-15 12:18 UTC by genie-magic

**What this PR does** 📖
When you click a users picture in chat, and the quick profile appears, it should have their name/icon, and the ability to message them
**Which issue(s) this PR fixes** 🔨

Fixes # AP-268

**Special notes for reviewers** 🗒️
I think all functionalities are implemented except icon.
I can't test user icon on quick profile because.. updating icon on settings/profile is not fully implemented.
We can create individual ticket for that.

2021-12-15 17:39 UTC, stavares843 requested changes
when you click on your own avatar shows the option to message yourself

<img width="796" alt="Captura de ecrã 2021-12-15, às 17 38 14" src="https://user-images.githubusercontent.com/29093946/146237044-e67589b4-213b-4e3e-9e83-5ff9f82cd8d5.png">

2021-12-15 17:40 UTC, stavares843 requested changes
<img width="1437" alt="Captura de ecrã 2021-12-15, às 17 40 16" src="https://user-images.githubusercontent.com/29093946/146237281-5206a40f-f9b5-4390-9568-1e8a45ba450f.png">

when you go to the quick profile of a user > message > it doesn't have the 256 chars limit

2021-12-15 17:42 UTC, stavares843 requested changes
<img width="998" alt="Captura de ecrã 2021-12-15, às 17 41 49" src="https://user-images.githubusercontent.com/29093946/146237517-384db924-dd94-4bfc-95c6-8911c59ed653.png">

on mobile appears like this when trying to access the quick profile

iPhone X

2021-12-16 08:45 UTC, WanderingHogan commented on components/interactables/QuickProfile/QuickProfile.html
> +    :placeholder="`Message ${user.name}...`"
can you add 'Message' to the translations

2021-12-16 08:46 UTC, WanderingHogan requested changes
looks good when Sara's changes go in

2021-12-17 00:16 UTC, genie-magic commented
> 

@stavares843  you see that screen because you just inspect element and change it to mobile... please f5 and try from fresh mobile mode.. 
![image](https://user-images.githubusercontent.com/28632174/146467673-2d08b8db-fd35-4031-9916-b645079f46f8.png)

2021-12-17 00:17 UTC, genie-magic commented
> looks good when Sara's changes go in

@WanderingHogan , @stavares843  I fixed issues you mentioned and pushed. only text limit is not implemented because Nick is working on there and I want to avoid conflict. After he implemented I can re work.

2021-12-17 00:19 UTC, stavares843 commented
when I refreshed stayed the same

will check again and check the fixes

2021-12-17 00:22 UTC, WanderingHogan approved these changes

2021-12-17 00:25 UTC, stavares843 commented
neat! 🎉

2021-12-17 00:25 UTC, stavares843 approved these changes

2021-12-17 00:28 UTC, stavares843 approved these changes

2021-12-17 00:28 UTC, merged