fix(images): fix multi upload bug
Satellite-im/Core-PWA pull request #738
Opened 2021-12-21 19:30 UTC by Jekrimo

**What this PR does** 📖
Fix multi upload bug

**Which issue(s) this PR fixes** 🔨
AP-274

**Additional comments** 🎤
Not nearly as pretty of code but is fully functional for me!

2021-12-21 19:45 UTC, stavares843 commented on components/views/files/upload/Upload.vue
> +          //   this.disabledButton = false
should we burn the commented-out code? 🔨

2021-12-21 22:49 UTC, Jekrimo commented on components/views/files/upload/Upload.vue
> +          //   this.disabledButton = false
Yup! Good catch thank you!

2021-12-21 23:50 UTC, stavares843 commented on store/textile/actions.ts
> +    // $TextileManager.bucketManager?.addToIndex(file.file, result?.root, path)
one more here 🔨

2021-12-22 05:52 UTC, stavares843 requested changes
multi-upload works ✅ 

but takes some time to send out the images, they are 100kb or so

https://user-images.githubusercontent.com/29093946/147042425-5006d0aa-b8b5-44e1-bd77-4fcd3a1d3939.mp4

and if we can fix the glitch 
https://github.com/Satellite-im/Core-PWA/pull/703#issuecomment-998264410

it was fixed on the previous PR before merging but not sure why after merge, the bug appeared

2021-12-22 14:31 UTC, Jekrimo commented
> multi-upload works ✅
> 
> but takes some time to send out the images, they are 100kb or so
> 
>  Screen.Recording.2021-12-22.at.5.50.04.AM.mp4 
> and if we can fix the glitch [#703 (comment)](https://github.com/Satellite-im/Core-PWA/pull/703#issuecomment-998264410)
> 
> it was fixed on the previous PR before merging but not sure why after merge, the bug appeared
> 
> Chrome, macOS

Hey, is this comment done? I'm not sure what the other bug is?

2021-12-22 15:44 UTC, Jekrimo commented
> multi-upload works ✅
> 
> but takes some time to send out the images, they are 100kb or so
> 
>  Screen.Recording.2021-12-22.at.5.50.04.AM.mp4 
> and if we can fix the glitch [#703 (comment)](https://github.com/Satellite-im/Core-PWA/pull/703#issuecomment-998264410)
> 
> it was fixed on the previous PR before merging but not sure why after merge, the bug appeared
> 
> Chrome, macOS

Should be good now!

2021-12-22 16:22 UTC, stavares843 commented
The glitch is fixed, thanks! 🎉 

do you know if we can improve the speed when sending out the images?

2021-12-22 16:23 UTC, stavares843 commented
<img width="982" alt="Captura de ecrã 2021-12-22, às 16 22 45" src="https://user-images.githubusercontent.com/29093946/147123576-f5a7ffe7-715b-4452-ba49-393bdc3f446b.png">


seems is no longer sending all now, but the glitch is fixed 🔨

2021-12-22 16:52 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
>      handleDrop(e: any) {
I know you didn't add this but can you change this from 'any' to DragEvent, and put the handleUpload into an if, like `if(e.dataTransfer){`

2021-12-22 16:53 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
>        e.stopPropagation()
Can you change the handlePaste from any to ClipboardEvent, same 'if' change as above

2021-12-22 16:53 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
> +    handleUpload(items: Array<object>, e: any) {
I think this would just be 'Event'? But I am not sure

2021-12-22 19:08 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/147142874-302367d5-2f79-4c23-b36c-c8c0886832e9.mp4

neat! 🎉

2021-12-22 19:08 UTC, stavares843 approved these changes

2021-12-22 19:10 UTC, stavares843 commented
to be done later - [AP-339](https://satellite-im.atlassian.net/browse/AP-339)

thanks for adding the ticket @Jekrimo 🎉

2021-12-22 19:11 UTC, stavares843 commented on libraries/Textile/BucketManager.ts
> +  // }
commented-out code 🔨

2021-12-22 19:12 UTC, stavares843 commented on components/views/chat/chatbar/Chatbar.vue
> +      // if (messageBox.)
commented-out code 🔨

2021-12-22 20:35 UTC, WanderingHogan approved these changes

2021-12-22 20:36 UTC, merged

2021-12-22 20:37 UTC, stavares843 commented
@Jekrimo feel free to burn the commented out code on a next PR 🔨