AP-288 Remove custom swipe controls, implement swiper
Satellite-im/Core-PWA pull request #739
Opened 2021-12-21 19:48 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-21 22:39 UTC, Jekrimo submitted a review, later dismissed

2021-12-21 22:39 UTC, Jekrimo commented on layouts/server.vue
> +      console.log('toggleMenu')
console.log here

2021-12-22 05:41 UTC, WanderingHogan requested changes
Great job! Can you make the following small changes:

1. Remove the console.log messages @Jekrimo mentioned, throughout. If you want to leave logging in please use `this.$Logger`
2. In the layout files where you load in Swiper/SwiperSlide, can you remove the imports (js/css), and remove them from the components block. Can you:

- Create a file at `plugins/thirdparty/swiper.ts`, something like
```
import Vue from 'vue'
import { Swiper, SwiperSlide } from 'vue-awesome-swiper'
import 'swiper/css/swiper.css'

Vue.component('Swiper', Swiper)
Vue.component('SwiperSlide', SwiperSlide)
```

and import it into the nuxt.config.js plugins?

2021-12-22 15:57 UTC, RetroPronghorn requested changes

2021-12-22 15:57 UTC, RetroPronghorn commented on components/views/navigation/sidebar/Sidebar.vue
> +      // this.$props.toggle()
let's delete commented out code in this file.

2021-12-22 15:57 UTC, RetroPronghorn commented on components/views/navigation/sidebar/Sidebar.vue
> +      // this.$props.toggle()
delete

2021-12-22 15:57 UTC, RetroPronghorn commented on components/views/navigation/sidebar/Sidebar.vue
> +      // this.$props.toggle()
delete

2021-12-22 15:57 UTC, RetroPronghorn commented on components/views/settings/modal/Modal.less
> +  // flex-basis: 18rem;
delete

2021-12-22 15:57 UTC, RetroPronghorn commented on components/views/settings/modal/Modal.less
> +  // .is-collapsed {
delete

2021-12-22 15:57 UTC, RetroPronghorn commented on layouts/Layout.less
> +  //   #sidebar,
delete

2021-12-22 15:57 UTC, RetroPronghorn commented on libraries/Textile/TextileManager.ts
> +    // await this.bucketManager.init().catch((e) => console.log(e))
Please un comment. @stavares843 note this must me commented out to test on mobile devices.

2021-12-22 15:57 UTC, RetroPronghorn commented on libraries/Textile/TextileManager.ts
> +    // await this.bucketManager.init().catch((e) => console.log(e))
Please un comment. @stavares843 note this must me commented out to test on mobile devices.

2021-12-22 16:13 UTC, RetroPronghorn approved these changes

2021-12-22 16:31 UTC, stavares843 commented on libraries/Textile/TextileManager.ts
> +    // await this.bucketManager.init().catch((e) => console.log(e))
noted, thanks! 💥

2021-12-22 22:09 UTC, WanderingHogan approved these changes

2021-12-22 22:10 UTC, WanderingHogan commented
/rebase

2021-12-23 02:56 UTC, WanderingHogan commented
This is good to go outside of the conflict. Thank you for making the changes.

2021-12-23 02:56 UTC, WanderingHogan commented
* if it passes QA

2021-12-23 16:35 UTC, stavares843 approved these changes

2021-12-23 16:35 UTC, stavares843 commented
this needs to be improved performance-wise but will add a ticket for that to be improved

2021-12-23 16:37 UTC, merged