feat(editChat): improve messages edit
Satellite-im/Core-PWA pull request #762
Opened 2021-12-22 18:40 UTC by nickjjang

2021-12-23 17:53 UTC, Jekrimo commented on components/views/chat/message/edit/Edit.vue
> +        case 'a':
Will you make Enums for all of these strings, Some may exist already too

2021-12-23 17:56 UTC, Jekrimo requested changes
Will you make Enums for all of these strings, Some may exist already too

2021-12-23 17:56 UTC, Jekrimo commented on components/views/chat/message/edit/Edit.vue
> +        case 'Shift':
Will you make Enums for all of these strings, Some may exist already too

2021-12-23 20:42 UTC, nickjjang commented on components/views/chat/message/edit/Edit.vue
> +        case 'Shift':
Hi @Jekrimo , thanks for letting me know.
I'll put all variable into keybindings.ts

2021-12-23 20:57 UTC, Jekrimo commented on components/views/chat/message/edit/Edit.vue
> +        case 'Shift':
Perfect, thank you!

2021-12-24 00:52 UTC, nickjjang commented on components/views/chat/message/edit/Edit.vue
> +        case 'Shift':
Hi @Jekrimo I have fixed keybinding enums.

2021-12-24 19:05 UTC, WanderingHogan approved these changes

2021-12-24 19:15 UTC, merged