feat(glyphs): recently used glyphs functionality AP-341
Satellite-im/Core-PWA pull request #769
Opened 2021-12-23 08:48 UTC by josephmcg

**What this PR does** 📖

AP-341
- added state for recently used glyphs including a counter
- removed global style that was hiding typographyText on xs devices
- limit recently used glyph array size on mobile devices
- introduce mq xs breakpoint

AP-318
- add padding to bottom of enhancers glyph list to show all

AP-264
- add small img to reply rather than string of glyph url

**Which issue(s) this PR fixes** 🔨
AP-314, AP-318, AP-264

**Special notes for reviewers** 🗒️
- I'm not a good copywriter, nor do I claim to be. If anyone has something better than 'Try using some glyphs', go for it

**Additional comments** 🎤
- in regards to UX, do we want to close the enhancers menu after sending a glyph?

2021-12-23 14:04 UTC, Jekrimo approved these changes

2021-12-23 16:54 UTC, stavares843 commented
AP-314, AP-318, AP-264 - fixed ✅

2021-12-23 16:55 UTC, stavares843 approved these changes

2021-12-23 18:28 UTC, stavares843 commented
do you want to add this one as well? 😂  [AP-359](https://satellite-im.atlassian.net/browse/AP-359)

2021-12-24 20:04 UTC, WanderingHogan commented on components/ui/Chat/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue
> +              link.split('?')[0],
weird place to put a comma

2021-12-24 20:04 UTC, WanderingHogan commented on components/ui/Chat/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue
> +        /(\b(https?):\/\/[-A-Z0-9+&@#/%?=~_|!:,.;]*[-A-Z0-9+&@#/%=~_|])/gi,
can you move this to the config

2021-12-24 20:05 UTC, WanderingHogan commented on components/ui/Chat/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue
> +              /^https?:\/\/([a-z0-9-]+[.])spotify[.]com\/(playlist|embed)?/g,
add to config so regex are all in one place

2021-12-24 20:09 UTC, WanderingHogan commented on store/ui/types.ts
> +  code: String
use lower case primitives

2021-12-24 20:10 UTC, WanderingHogan requested changes
Good, couple minor changes though when you get a chance next week

2021-12-27 02:04 UTC, josephmcg commented on components/ui/Chat/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue
> +              link.split('?')[0],
yeah, bad prettier

2021-12-27 02:28 UTC, josephmcg commented
> AP-359

lol I'll do that one separately since this is already tackling a bunch of issues. I think it was introduced with the swiper stuff

2021-12-27 16:07 UTC, stavares843 commented
neat! 🎉

2021-12-27 16:07 UTC, stavares843 commented
just added the missing dev review label because of @WanderingHogan review

2021-12-27 20:12 UTC, WanderingHogan approved these changes

2021-12-27 20:20 UTC, merged