feat(chat): improve UX when user tries to copy paste images
Satellite-im/Core-PWA pull request #791
Opened 2021-12-24 00:29 UTC by nickjjang

AP-93

2021-12-24 19:45 UTC, WanderingHogan requested changes
This works very well. Can you make one change though:

In Upload.vue, can you add the `declare module 'vue/types/vue' {` snippet back in, and then add the things to it/remove the ts-ignores?

I think it will look something like 
```
declare module 'vue/types/vue' {
  interface Vue {
    loadPicture: (item: UploadDropItemType) => void,
    cancelUpload: () => void,
    finishUploads: () => void,
    dispatchFile: (file: FileType) => void,
  }
}
```

2021-12-24 23:27 UTC, nickjjang commented
> **WanderingHogan ** requested changes

I have  fixed it.

2021-12-27 20:35 UTC, stavares843 commented on components/views/chat/chatbar/Chatbar.vue
> +      // else wrap.style.borderRadius = '41px'
commented-out code 🔨

2021-12-27 20:36 UTC, stavares843 commented on components/views/files/upload/Upload.html
> +      </div> -->
commented-out code 🔨

2021-12-27 20:36 UTC, stavares843 approved these changes
pretty neat! 🎉

2021-12-27 20:49 UTC, WanderingHogan approved these changes

2021-12-27 21:19 UTC, merged