AP-361 Fix activeCall issue
Satellite-im/Core-PWA pull request #796
Opened 2021-12-24 05:05 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-24 05:16 UTC, RetroPronghorn approved these changes

2021-12-24 19:56 UTC, WanderingHogan requested changes
This fixes the issue where when a user:
goes into a DM > clicks the call button > full screens call > clicks hangup button = chat input bar goes way up high/compresses the chat window

but has the introduces the following problem:
When you hangup following the same process again, the chatbar is either hidden or goes off screen, and you have to start a call again to bring it back

2021-12-27 22:54 UTC, WanderingHogan commented
https://user-images.githubusercontent.com/2993032/147512202-ae919fe0-be54-4011-b147-d1f070701d48.mp4

When you fullscreen from a video call and hangup I am still seeing the chatbar go missing until you start another call

2021-12-28 06:41 UTC, WanderingHogan approved these changes

2021-12-28 18:22 UTC, merged