feat(indexeddb): Added dexie to support indexeddb storage AP-366 wip
Satellite-im/Core-PWA pull request #814
Opened 2021-12-28 06:49 UTC by josephmcg

**What this PR does** 📖
- uses dexie for better indexeddb api. I researched other options (idb,localforage) too, but dexie seems like the best
- 

**Which issue(s) this PR fixes** 🔨
#AP-366

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-12-28 18:35 UTC, stavares843 commented
@josephmcg is this still a WIP or its ready? 🔨

2021-12-28 20:18 UTC, Jekrimo approved these changes

2021-12-29 01:20 UTC, josephmcg commented
@stavares843 WIP -  I'm thinking of adding some additional functionality to it first. Right now, it's just storing conversation info every time its fetched

2022-01-03 21:45 UTC, stavares843 commented
@josephmcg just checking, is this ready to review/test? 🔨

2022-01-04 01:37 UTC, josephmcg commented
not yet, I'm taking a couple vacation days. I'm hoping to finish it up tomorrow

2022-01-04 02:24 UTC, stavares843 commented
neat, thanks 🎉

2022-01-05 20:05 UTC, iltumio requested changes
the most important part is to move the indexedDb async logic from the mutation to an action or into a  store plugin. See comments

2022-01-05 20:05 UTC, iltumio commented on store/textile/mutations.ts
> +      db.conversations.get(address).then((convo) => {
I know that technically is not the mutation to be async, but it's side effect in this case. Anyway we should not put any async logic inside mutations in my opinion.
https://vuex.vuejs.org/guide/mutations.html#mutations-must-be-synchronous

Can we move this inside the action or eventually in a store plugin?
https://vuex.vuejs.org/guide/plugins.html#plugins

2022-01-11 21:36 UTC, WanderingHogan approved these changes
this is neat

2022-01-12 00:11 UTC, josephmcg commented
Manuel gave me some good feedback regarding the data structure. I'm going to finish refactoring within a day or two

2022-01-12 14:47 UTC, iltumio approved these changes

2022-01-12 14:48 UTC, merged