Ap 285
Satellite-im/Core-PWA pull request #840
Opened 2021-12-29 20:10 UTC by Jekrimo

**What this PR does** 📖
Blocks sending images deemed nsfw and shows an alert notifying user that file/s were not sent that were nsfw

**Which issue(s) this PR fixes** 🔨
AP-285

**Special notes for reviewers** 🗒️
Alert should pop up on it's own and auto close after 5ish seconds, the user can also click the close on the alert to close before then.

2021-12-29 21:23 UTC, phillsatellite commented
Tested and never had a alert pop up, the image would be blured when uploading and send button was disabled 

<img width="1728" alt="testnsfw" src="https://user-images.githubusercontent.com/93608357/147704427-5e67138f-afe7-4a0b-be6b-db9ad180d0e6.png">

2021-12-29 21:47 UTC, Jekrimo commented
> Tested and never had a alert pop up, the image would be blured when uploading and send button was disabled
> 
> <img alt="testnsfw" width="1728" src="https://user-images.githubusercontent.com/93608357/147704427-5e67138f-afe7-4a0b-be6b-db9ad180d0e6.png">

Fixed! I'm a big dummy and was always uploading multiple files to run the check and totally didn't account for a singular nsfw file lol

2021-12-29 23:22 UTC, phillsatellite approved these changes
Boom alert message is showing up now!

2021-12-30 16:35 UTC, stavares843 requested changes

2021-12-30 16:35 UTC, stavares843 commented on components/views/files/upload/Upload.html
> +      <TypographyError :text="$t('errors.chat.contains_nsfw')" />
<img width="602" alt="Captura de ecrã 2021-12-30, às 16 34 07" src="https://user-images.githubusercontent.com/29093946/147770704-17ef4f24-286e-4d13-974f-ba5b742b36c1.png">

we need to add the string into the locales

2021-12-30 17:17 UTC, stavares843 approved these changes

2022-01-05 17:10 UTC, WanderingHogan approved these changes

2022-01-05 17:38 UTC, merged