feat(notificationSounds): add notification sounds settings
Satellite-im/Core-PWA pull request #846
Opened 2021-12-30 18:15 UTC by nickjjang

2021-12-30 19:33 UTC, stavares843 commented
https://github.com/Satellite-im/locales/pull/20

2021-12-30 19:40 UTC, stavares843 approved these changes
neat! 🎉

2022-01-01 16:05 UTC, Jekrimo requested changes

2022-01-01 16:05 UTC, Jekrimo commented on components/views/settings/pages/notifications/sounds/Sounds.vue
> +import { SoundsTypes } from '../../../../../../store/sounds/types'
can we simplify the import from?  '~/whatever' if possible

2022-01-03 15:09 UTC, WanderingHogan requested changes
couple small things in the comments

2022-01-03 15:09 UTC, WanderingHogan commented on components/views/settings/pages/notifications/sounds/Sounds.vue
> +    message: {
do we need to make these unique, or can we make one generic computed property? Like

toggleSound: {
  get(soundName: string) {
    return this.sounds[soundName]
  }
  ...
}

2022-01-03 15:09 UTC, WanderingHogan commented on store/sounds/types.ts
> +  message: Boolean,
can you use the primitive 'boolean' here instead of the object 'Boolean'

2022-01-03 21:26 UTC, nickjjang commented on components/views/settings/pages/notifications/sounds/Sounds.vue
> +import { SoundsTypes } from '../../../../../../store/sounds/types'
Fixed it.

2022-01-03 21:26 UTC, nickjjang commented on components/views/settings/pages/notifications/sounds/Sounds.vue
> +    message: {
Fixed it

2022-01-03 21:26 UTC, nickjjang commented on store/sounds/types.ts
> +  message: Boolean,
Fixed

2022-01-05 17:13 UTC, WanderingHogan approved these changes
great

2022-01-05 19:35 UTC, WanderingHogan approved these changes
This looks good

2022-01-05 19:40 UTC, Jekrimo approved these changes

2022-01-05 19:51 UTC, merged