Disabled buttons and made to show not available tooltip
Satellite-im/Core-PWA pull request #870
Opened 2022-01-03 15:42 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-01-03 16:32 UTC, Jekrimo approved these changes

2022-01-04 02:52 UTC, WanderingHogan commented
@davidchan1219 please fill out the PR template, and use the correct commit messaging format.

pr template: https://github.com/Satellite-im/Core-PWA/blob/dev/PULL_REQUEST_TEMPLATE.md
commit message format: https://github.com/Satellite-im/Core-PWA/blob/dev/commit-guide.md

For example this commit message could be: fix(components): disabling items not yet implemented, translations text

2022-01-04 02:52 UTC, WanderingHogan requested changes
Code is good, need to update commit message and fill out PR template

2022-01-04 21:25 UTC, WanderingHogan approved these changes

2022-01-04 21:39 UTC, stavares843 approved these changes

2022-01-04 21:39 UTC, merged