fix(addFriends): click Add Friends to swipe into friends page
Satellite-im/Core-PWA pull request #886
Opened 2022-01-05 18:32 UTC by nickjjang

AP-371

2022-01-05 18:47 UTC, stavares843 commented on components/views/navigation/sidebar/Sidebar.vue
> +    // }
commented-out code 🔨

2022-01-06 00:35 UTC, WanderingHogan requested changes
couple small changes,

does the sidebar state update make the other sidebar state settings obsolete? or are they still used somewhere?

2022-01-06 00:35 UTC, WanderingHogan commented on layouts/chat.vue
> +    } else {
can you do a guard clause here

2022-01-06 00:35 UTC, WanderingHogan commented on layouts/files.vue
> +    } else {
guard clause instead of else

2022-01-06 00:35 UTC, WanderingHogan commented on layouts/friends.vue
> +    } else {
guard

2022-01-07 10:13 UTC, nickjjang commented on layouts/files.vue
> +    } else {
Oh, I got guard clause thanks. and I've fixed.

2022-01-07 16:53 UTC, nickjjang commented on components/views/navigation/sidebar/Sidebar.vue
> +    // }
Resolved

2022-01-07 16:53 UTC, nickjjang commented on layouts/chat.vue
> +    } else {
Resolved

2022-01-07 16:53 UTC, nickjjang commented on layouts/files.vue
> +    } else {
Resolved

2022-01-07 16:53 UTC, nickjjang commented on layouts/friends.vue
> +    } else {
Resolved

2022-01-07 19:57 UTC, WanderingHogan approved these changes

2022-01-07 20:15 UTC, stavares843 commented
<img width="489" alt="Captura de ecrã 2022-01-07, às 20 14 08" src="https://user-images.githubusercontent.com/29093946/148601656-64f2708a-bb89-4704-8368-699b26b63af8.png">

fixed

added a separate ticket for the side menu overlap icon - [AP-426](https://satellite-im.atlassian.net/browse/AP-426)

2022-01-07 20:15 UTC, stavares843 approved these changes

2022-01-07 20:15 UTC, merged