update(settings): update keybinds functionality
Satellite-im/Core-PWA pull request #899
Opened 2022-01-06 13:39 UTC by davidchan1219

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-01-06 18:28 UTC, Jekrimo requested changes

2022-01-06 18:28 UTC, Jekrimo commented on components/views/settings/pages/keybinds/index.vue
> +        this.$data.editingKeybind.errorMessage = 'That is browser/system shortcut. Please input other keys.'
Will you add this to our translations file?

2022-01-06 18:28 UTC, Jekrimo commented on components/views/settings/pages/keybinds/index.vue
>          this.$data.editingKeybind.errorMessage = 'Key already bound'
Here too

2022-01-06 18:28 UTC, Jekrimo commented on components/views/settings/pages/keybinds/index.vue
>        const modifiers = ['shift', 'control', 'alt', 'meta', 'tab', 'capslock']
I know you didn't write these but will you make enum for these and the blockedChars as well? located in libraries/Enums/types then export through the enums.ts file

2022-01-07 15:20 UTC, Jekrimo approved these changes

2022-01-07 15:21 UTC, Jekrimo commented
> 

Approved, thank you! Will you do one last thing and fill out the pr template for us?

2022-01-07 23:07 UTC, WanderingHogan commented on components/views/settings/pages/keybinds/index.vue
> +        this.$data.editingKeybind.errorMessage = this.$t('pages.settings.keybinds.editHotkeyError')
thank you for also adding translations!

2022-01-07 23:21 UTC, WanderingHogan approved these changes
this is great, thank you @davidchan1219

2022-01-08 00:06 UTC, stavares843 commented
<img width="1286" alt="Captura de ecrã 2022-01-08, às 00 05 57" src="https://user-images.githubusercontent.com/29093946/148622207-b9dc4d74-e98b-446c-8274-f9f8f965d51f.png">

im using macOS, should this say ''optionKey'' instead of ''alt''?

2022-01-08 00:07 UTC, stavares843 commented
<img width="773" alt="Captura de ecrã 2022-01-08, às 00 04 33" src="https://user-images.githubusercontent.com/29093946/148622222-9fce3982-7d85-4c47-bdc9-eb11a3fcd10f.png">

we could add a bit more padding between the error and the field above

also, should the error be red as the rest of the error messages?

2022-01-08 00:07 UTC, stavares843 commented
![image](https://user-images.githubusercontent.com/29093946/148622260-3bf57ed2-24be-4da3-827d-0ddf34698ae8.png)

when I go to the chat and I do optionKey (same as alt for macOS) + s, doesn't open the settings

2022-01-08 00:09 UTC, stavares843 requested changes
added couple comments

2022-01-08 01:06 UTC, WanderingHogan commented
Good ideas, @stavares843 :

option instead of alt if you detect it's a mac is a good idea. Can you make:
meta = 'Command'
alt = 'Option'

More spacing and an error color are also good.

I think the third thing you mentioned might be kind of a big thing and I broke it out into another ticket: AP-427

2022-01-08 01:07 UTC, stavares843 commented
thanks for checking! 🎉

2022-01-11 08:39 UTC, WanderingHogan commented
@davidchan1219 please check https://github.com/Satellite-im/Core-PWA/pull/976 when you get a chance, and make sure it has everything you want for this PR, then close this if it does

2022-01-11 09:11 UTC, davidchan1219 commented
> @davidchan1219 please check #976 when you get a chance, and make sure it has everything you want for this PR, then close this if it does

In the new branch, everything works fine.

2022-01-11 09:12 UTC, closed without merging