fix(lastVisited): handles last visited to get existing route
Satellite-im/Core-PWA pull request #912
Opened 2022-01-07 20:34 UTC by nickjjang

AP-372

2022-01-10 14:12 UTC, Jekrimo approved these changes

2022-01-11 03:33 UTC, RetroPronghorn requested changes

2022-01-11 03:33 UTC, RetroPronghorn commented on pages/chat/direct/_address.vue
> +      const friend = friends.find((fr) => fr.address === address)
Can we add this to houndDog?

2022-01-13 04:15 UTC, nickjjang commented on pages/chat/direct/_address.vue
> +      const friend = friends.find((fr) => fr.address === address)
Added it

2022-01-17 19:51 UTC, WanderingHogan approved these changes

2022-01-17 20:46 UTC, stavares843 requested changes
still getting the same error as the one on the ticket - AP-372

<img width="1114" alt="Captura de ecrã 2022-01-17, às 20 45 24" src="https://user-images.githubusercontent.com/29093946/149835102-6176fadc-3d65-4451-ab87-98c478b1f00e.png">

how to reproduce
- click on the satellite icon on the top left corner
<img width="881" alt="Captura de ecrã 2022-01-17, às 20 44 30" src="https://user-images.githubusercontent.com/29093946/149835151-c8b0cfe9-0a56-478b-a133-5a5810ed9e40.png">
- returns the error above

2022-01-20 18:25 UTC, stavares843 commented
https://user-images.githubusercontent.com/29093946/150398956-5701d5e1-784b-4383-b77c-1ff463364f2c.mov

retested and im getting the above error

2022-01-20 20:49 UTC, nickjjang commented
Hi @stavares843 I've fixed it.

2022-01-20 20:56 UTC, stavares843 commented
thanks! 🔨 checking

2022-01-21 14:12 UTC, stavares843 commented
fixed ✅

2022-01-21 14:13 UTC, stavares843 approved these changes

2022-01-21 14:17 UTC, merged