Ap 300.2
Satellite-im/Core-PWA pull request #922
Opened 2022-01-10 18:49 UTC by Jekrimo

**What this PR does** 📖
Fixes attaching reaction messages to files and image messages

**Which issue(s) this PR fixes** 🔨
AP-300

2022-01-11 02:01 UTC, josephmcg requested changes
I fixed this issue in a separate PR without forcing a new group. I like what you did with the Enums though :D

2022-01-11 02:01 UTC, josephmcg commented on utilities/Messaging.ts
> +      currentMessage.type === MessagingTypesEnum.FILE
I think I fixed this issue in my PR without forcing a new group. You should probably remove the File type check on 104.
<https://github.com/Satellite-im/Core-PWA/pull/918>

2022-01-11 02:01 UTC, josephmcg commented on utilities/Messaging.ts
> +            },
more concise before

2022-01-11 02:05 UTC, josephmcg commented on utilities/Messaging.ts
> +        isSameGroup = currentAt.diff(prevAt, MeasurementUnitsEnum.MINUTES) < 15
Jeff after this fix

![image](https://user-images.githubusercontent.com/33670767/148868604-57e18379-6767-428a-8b8e-6db77288908a.png)

2022-01-11 03:48 UTC, phillsatellite approved these changes

2022-01-11 05:04 UTC, RetroPronghorn commented on utilities/Messaging.ts
> +        isSameGroup = currentAt.diff(prevAt, MeasurementUnitsEnum.MINUTES) < 15
😂

2022-01-11 15:15 UTC, Jekrimo commented on store/ui/mutations.ts
> +          })
Ide auto format my bad

2022-01-12 00:10 UTC, josephmcg approved these changes
🚀

2022-01-12 05:07 UTC, WanderingHogan approved these changes

2022-01-12 22:35 UTC, stavares843 commented on libraries/Textile/ThreadManager.ts
> +    // }
commented out code 🔨

2022-01-12 22:35 UTC, stavares843 commented on libraries/Textile/ThreadManager.ts
> +    // const threadID = ThreadID.fromString(thread.id)
commented out code 🔨

2022-01-12 22:35 UTC, stavares843 commented on libraries/Textile/ThreadManager.ts
> +   * @argument storageMethod preffered storage method of thread assignment (LocalStorage)
typo - preferred 🔨

2022-01-12 22:36 UTC, Jekrimo commented on libraries/Textile/ThreadManager.ts
> +    // }
This should not be in here, I gotta figure out how to roll this back

2022-01-12 23:36 UTC, merged