fix(chatbar): fix emoji sending issue
Satellite-im/Core-PWA pull request #987
Opened 2022-01-12 04:15 UTC by davidchan1219

**What this PR does** 📖

fixed for not inputting emojis in chatbar.

**Which issue(s) this PR fixes** 🔨

AP-474

2022-01-12 06:08 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
> +      sel?.collapseToEnd()
I think this is forcing the cursor to the end of the input any time you move the cursor back in the text and input anything

2022-01-12 06:09 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
> +        this.updateText()
do we need this and the watch below?

2022-01-12 06:09 UTC, WanderingHogan requested changes
A question and an issue int he comments

2022-01-12 10:48 UTC, davidchan1219 commented on components/views/chat/chatbar/Chatbar.vue
> +        this.updateText()
yes

2022-01-12 10:49 UTC, davidchan1219 commented on components/views/chat/chatbar/Chatbar.vue
> +      sel?.collapseToEnd()
yes, this code was written by the old developer.

2022-01-12 14:43 UTC, WanderingHogan commented on components/views/chat/chatbar/Chatbar.vue
> +      sel?.collapseToEnd()
I get that, but we are all growing and evolving this thing together. In this particular case, removing if(collapseEnd)  means that every character added will force the cursor to the end and we can't accept this pull request that fixes one bug and introduces another

2022-01-12 15:19 UTC, davidchan1219 commented on components/views/chat/chatbar/Chatbar.vue
> +      sel?.collapseToEnd()
got it, let me find the other solution

2022-01-12 16:05 UTC, phillsatellite approved these changes

2022-01-15 00:39 UTC, stavares843 commented
@davidchan1219 thanks for taking a look! @molimauro is gonna fix this on a PR is working on 🔨 

so we are closing this one

2022-01-15 00:39 UTC, closed without merging