fix(call): fixed timer not reseting, toggle video button, and user feedback for muting
Satellite-im/Core-PWA pull request #989
Opened 2022-01-12 05:47 UTC by jpanay

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2022-01-12 14:24 UTC, Jekrimo requested changes

2022-01-12 14:24 UTC, Jekrimo commented on components/views/navigation/sidebar/controls/Controls.vue
> +        peer?.call.unmute('audio')
Hey! Will you make an enum for the 'audio' and 'video' strings in libraries/Enums? I feel like maybe they could go in messaging-types but idk, I'll let you make that call

2022-01-12 21:18 UTC, jpanay commented on components/views/navigation/sidebar/controls/Controls.vue
> +        peer?.call.unmute('audio')
Sure thing

2022-01-12 22:27 UTC, RetroPronghorn approved these changes

2022-01-12 22:35 UTC, Jekrimo approved these changes

2022-01-12 22:45 UTC, WanderingHogan commented
@jpanay which tickets is this tied to

2022-01-12 22:47 UTC, jpanay commented
> @jpanay which tickets is this tied to
AP-344, AP-345, AP-350, AP-353

2022-01-12 23:02 UTC, stavares843 commented
AP-344 - fixed ✅

2022-01-12 23:03 UTC, stavares843 commented
AP-345 - doesn't have any indication when the user is muted 


example

user A
<img width="1315" alt="Captura de ecrã 2022-01-12, às 23 01 14" src="https://user-images.githubusercontent.com/29093946/149236844-bc571f9b-b265-4e08-bf1f-8a912d43b505.png">

user B
<img width="1384" alt="Captura de ecrã 2022-01-12, às 23 01 07" src="https://user-images.githubusercontent.com/29093946/149236862-d251e33b-123d-4916-97a4-447c7c1e2147.png">


one of the user is muted but doesn't appear on the other user side

2022-01-12 23:07 UTC, stavares843 commented
AP-353 after ending the call still has the red dot that something is transmitting

<img width="533" alt="Captura de ecrã 2022-01-12, às 23 06 25" src="https://user-images.githubusercontent.com/29093946/149237261-4750bfae-3721-4070-98a6-e6b9a8786d6c.png">

2022-01-12 23:07 UTC, stavares843 requested changes
couple comments

the first ticket was fixed, but the other ones weren't fix, let me know

2022-01-12 23:09 UTC, jpanay commented
> AP-345 - doesn't have any indication when the user is muted ❌ 
> 
> 
> 
> 
> 
> example
> 
> 
> 
> user A
> 
> <img width="1315" alt="Captura de ecrã 2022-01-12, às 23 01 14" src="https://user-images.githubusercontent.com/29093946/149236844-bc571f9b-b265-4e08-bf1f-8a912d43b505.png">
> 
> 
> 
> user B
> 
> <img width="1384" alt="Captura de ecrã 2022-01-12, às 23 01 07" src="https://user-images.githubusercontent.com/29093946/149236862-d251e33b-123d-4916-97a4-447c7c1e2147.png">
> 
> 
> 
> 
> 
> one of the user is muted but doesn't appear on the other user side
> 
> 

It should just give an audible so that when a user toggles their mic or camera the other user hears it

2022-01-12 23:12 UTC, stavares843 commented
ohh 

i thought would be something visible, @WanderingHogan do we have design for this?

2022-01-12 23:13 UTC, jpanay commented
> AP-350 - still seeing discrepancies on the call time between each user
> 
> 
> 
> <img width="617" alt="Captura de ecrã 2022-01-12, às 23 04 22" src="https://user-images.githubusercontent.com/29093946/149237077-cde530b7-f443-4905-93ee-020bfa88e150.png">
> 
> 
> 
> It's the same call but one says 12 seconds, other says 17 seconds

I think the ticket was just to reset the timer, the current time represents how long each user has been on the call. We could sync them up from when the call was first initialized but if we're going to do that we should create a separate ticket because it's going to require a lot more refactoring

2022-01-12 23:16 UTC, jpanay commented
> ohh 
> 
> 
> 
> i thought would be something visible, @WanderingHogan do we have design for this?

Sorry I was unclear about that, a visual does make sense though

2022-01-12 23:20 UTC, jpanay commented
> AP-353 after ending the call still has the red dot that something is transmitting
> 
> 
> 
> <img width="533" alt="Captura de ecrã 2022-01-12, às 23 06 25" src="https://user-images.githubusercontent.com/29093946/149237261-4750bfae-3721-4070-98a6-e6b9a8786d6c.png">
> 
> 
> 
> 
> 
> 
> 
> 

That's odd I'm not getting this, I'll do some investigation

2022-01-12 23:42 UTC, stavares843 commented
thanks for checking 🎉

2022-01-13 02:03 UTC, WanderingHogan commented on components/views/navigation/sidebar/controls/Controls.vue
> +      return this.$store.state.webrtc.localTracks.audio.muted
since you need the entire webrtc state object later, can you move mapState up above these computed items, add webrtc, and then change all the `this.$store.state.webrtc` to `this.webrtc`. If it was just these two items i'd skip mapping the entire thing

2022-01-13 02:04 UTC, WanderingHogan commented on components/views/navigation/sidebar/controls/Controls.vue
> +      } else {
can you do a guard clause here instead of else

2022-01-13 02:04 UTC, WanderingHogan commented on components/views/navigation/sidebar/controls/Controls.vue
> +      const { activeCall } = this.$store.state.webrtc
this.webrtc is you add webrtc to mapstate

2022-01-13 02:06 UTC, WanderingHogan commented on components/views/navigation/sidebar/controls/Controls.vue
> +      } else {
guard

2022-01-13 02:09 UTC, WanderingHogan commented on components/views/navigation/toolbar/Toolbar.html
> +      :class="`has-tooltip has-tooltip-bottom has-tooltip-primary ${!webrtc.connectedPeer || webrtc.activeCall ? 'disabled' : ''}`"
personal preference, but can you split this into two lines since it's so long, something like
class="has-tooltip has-tooltip-bottom has-tooltip-primary"
:class="!webrtc.connectedPeer || webrtc.activeCall ? 'disabled' : '' "

or something

2022-01-13 02:16 UTC, WanderingHogan commented on libraries/WebRTC/Call.ts
> +        console.error(err)
can you use $Logger for this so it will be suppressed in the built version

2022-01-13 02:20 UTC, WanderingHogan commented on libraries/WebRTC/Call.ts
> +   * @param kind Kinds of tracks (video or audio) to disable
😍 inline documentation

2022-01-13 02:20 UTC, WanderingHogan commented on libraries/WebRTC/Call.ts
> +        console.error(err)
$Logger

2022-01-13 02:35 UTC, WanderingHogan commented on libraries/WebRTC/Call.ts
> +      // @ts-ignore
you can get rid of this ts-ignore by doing something like

```
    const localTracks = this.getLocalTracks()
    type trackType = typeof localTracks

    for (const key in localTracks) {
      const track = localTracks[key as keyof trackType]
      ```

2022-01-13 02:35 UTC, WanderingHogan requested changes
couple small changes

2022-01-14 06:08 UTC, jpanay commented on libraries/WebRTC/Call.ts
> +   * @param kind Kinds of tracks (video or audio) to disable
![But_It's_Honest_Work](https://user-images.githubusercontent.com/70326429/149460086-a663d973-1db8-4080-bf72-7a8a2dfcfe20.jpg)

2022-01-14 23:50 UTC, jpanay commented on components/views/navigation/toolbar/Toolbar.vue
> +        if (!this.webrtc.connectedPeer) { return }
It's an attempt to reconnect the peer if connectedPeer is false, and then if the second attempt fails just return out of the function

2022-01-15 00:27 UTC, stavares843 commented
@jpanay when you merged dev, you added a bunch of commits not related to this PR and that was adding 36 files

<img width="1053" alt="Captura de ecrã 2022-01-14, às 23 59 12" src="https://user-images.githubusercontent.com/29093946/149601090-6d91d5a4-cc88-453b-ac6c-f1eb9265500f.png">

I reverted those, so now only has the content that really is from this PR

<img width="1035" alt="Captura de ecrã 2022-01-15, às 00 26 11" src="https://user-images.githubusercontent.com/29093946/149601113-3211dbc3-f8c3-47c6-9195-bf23e3d9f8f4.png">

please, follow hogan's instructions on how to properly merge the dev branch into the PR branch 💥

2022-01-17 01:03 UTC, jpanay commented
> @jpanay when you merged dev, you added a bunch of commits not related to this PR and that was adding 36 changed files
> 
> <img alt="Captura de ecrã 2022-01-14, às 23 59 12" width="1053" src="https://user-images.githubusercontent.com/29093946/149601090-6d91d5a4-cc88-453b-ac6c-f1eb9265500f.png">
> 
> I reverted those, so now only has the content that really is from this PR
> 
> <img alt="Captura de ecrã 2022-01-15, às 00 26 11" width="1035" src="https://user-images.githubusercontent.com/29093946/149601113-3211dbc3-f8c3-47c6-9195-bf23e3d9f8f4.png">
> 
> please, follow hogan's instructions on how to properly merge the dev branch into the PR branch for future PR's 💥

Thank you so much for fixing this, I'll be careful to make sure I do it properly next time

2022-01-17 01:11 UTC, jpanay commented
> AP-353 after ending the call still has the red dot that something is transmitting
> 
> <img alt="Captura de ecrã 2022-01-12, às 23 06 25" width="533" src="https://user-images.githubusercontent.com/29093946/149237261-4750bfae-3721-4070-98a6-e6b9a8786d6c.png">

Can you test this again or have some other people test it, I haven't been able to replicate the problem

2022-01-17 15:33 UTC, stavares843 commented
will do, thanks! 🎉

2022-01-18 01:02 UTC, phillsatellite approved these changes

2022-01-18 04:19 UTC, stavares843 approved these changes

2022-01-18 12:59 UTC, WanderingHogan approved these changes

2022-01-18 16:06 UTC, merged